/* ============ topics/aws-hardening/bank.js -- topic 4 cross-pane BANK ============
   The mock-run / mixed-fire / frame bank for topic 4. mockBeats + curveballs +
   frames are aws-hardening-specific; cards/speak alias the LOCAL AWSHARD_CARDS /
   AWSHARD_SPEAK (defined in drill.js, loaded before this in the bundle). publishBanks()
   seeds the registry-owned globals from this object on switch. 7-bit ASCII (entities). */
var TOPIC_AWSHARD_BANK = (function () {
  var mockBeats=[
   { tag:"FRAME", cue:"&ldquo;Design the storage layer that holds signed firmware for a fleet of terminals &mdash; start wherever you like.&rdquo;",
     task:"Frame the scope in one line, then give your one-sentence version.",
     model:"<b>Frame:</b> the bucket holds signed firmware for tens of thousands of terminals and the tenant data around it, so it&rsquo;s the highest-value target in the system; hardening is what stops one mistake from exposing the fleet. <b>One-liner:</b> nothing is public (Block Public Access), every credential is least-privilege (scoped IAM, never <code>s3:*</code>), everything is encrypted at rest and in transit (SSE-KMS + deny-non-TLS), and devices download by expiring presigned URL &mdash; defense in depth, so no single slip breaches.",
     int:{q:"It&rsquo;s just an S3 bucket. Isn&rsquo;t &lsquo;make it private and encrypt it&rsquo; the whole answer?",a:"Those are two of the layers, but &lsquo;private and encrypted&rsquo; skips the ones that actually contain a breach. <b>Private</b> stops public exposure, but a stolen credential with <code>s3:*</code> still reads the fleet &mdash; that&rsquo;s least privilege. <b>Encrypted</b> protects bytes at rest, but without SSE-KMS you have no audit trail and no crypto-shred, and without a deny-non-TLS policy the bytes still travel plaintext. And neither addresses <b>delivery</b> (how credential-less devices download) or <b>exfiltration</b> (stopping a compromised role from copying data out). The answer is the <i>set</i> of controls, each bounding a different failure."},int2:{q:"What&rsquo;s the actual threat you&rsquo;re defending against &mdash; who&rsquo;s the attacker?",a:"Three of them. The <b>opportunist</b> scanning for public buckets &mdash; defended by Block Public Access. The <b>credential thief</b> who phishes or exploits a service and gets its role &mdash; defended by least privilege (the policy bounds what they get) and per-tenant keys (the blast radius is one tenant). And the <b>insider or compromised dependency</b> trying to exfiltrate &mdash; defended by the VPC endpoint perimeter and audit. Naming the attacker is what turns each control into a <i>decision</i> instead of a checklist item &mdash; you can say exactly which threat each one stops."} },
   { tag:"STRUCTURE", cue:"&ldquo;Walk me through it.&rdquo;",
     task:"Talk the whole flow, stored to delivered &mdash; no config, just the spine.",
     model:"The pipeline <b>PutObjects the signed package into a private bucket</b> &rarr; <b>Block Public Access</b>, account and bucket, so nothing can be public &rarr; a <b>least-privilege write role</b> (one prefix) put it there, and a least-privilege read role fetches it &rarr; it&rsquo;s <b>SSE-KMS encrypted with a per-tenant key</b>, and the bucket policy <b>denies unencrypted PUTs and non-TLS requests</b> &rarr; a device needs it, so the delivery service mints a <b>presigned URL</b> &mdash; one object, short expiry &mdash; and puts it in the <b>IoT Job document</b> &rarr; the device downloads with just the URL, no credential &rarr; internal reads go through a <b>VPC endpoint with PrincipalOrgID</b> so nothing exfiltrates, and <b>CloudTrail data events</b> audit every access.",
     int:{q:"50,000 devices can&rsquo;t hold AWS credentials. How do they actually download the firmware?",a:"By <b>presigned URL</b> &mdash; the delivery service, which <i>does</i> have a scoped role, generates a Signature V4 URL for one object with a short expiry, and the device downloads with nothing but that URL. The URL goes <b>inside the IoT Job document</b>, never the firmware bytes, so the job stays small and the bucket stays private. The device holds no AWS credential at any point; it holds a temporary, single-object link that&rsquo;s dead in minutes. And because the URL is signed with the delivery role&rsquo;s least-privilege permissions, it can only do what that role can &mdash; <code>GetObject</code> on one prefix."} },
   { tag:"SCALE", cue:"&ldquo;A rollout fires and 50,000 devices pull firmware in the same few minutes. What breaks first?&rdquo;",
     task:"Name the first ceiling, then the fix &mdash; don&rsquo;t hand-wave &lsquo;S3 scales.&rsquo;",
     model:"S3 itself absorbs the object reads, so the first real ceiling is <b>KMS</b>: with SSE-KMS, every <code>GetObject</code> triggers a <code>Decrypt</code>, and KMS has a <b>per-key requests-per-second quota</b> &mdash; 50,000 near-simultaneous pulls can throttle it. The fix is <b>S3 Bucket Keys</b>, which use a short-lived bucket-level key so S3 stops calling KMS per object, collapsing the call volume. Beyond that, <b>CloudFront in front</b> caches the firmware at the edge so 50,000 devices hit the cache, not the bucket &mdash; one origin fetch, many edge hits &mdash; plus a quota increase for headroom.",
     int:{q:"Why does per-object KMS throttle when S3 itself doesn&rsquo;t?",a:"Because they scale differently. S3 partitions by key prefix and handles enormous request rates on object reads. But SSE-KMS means each read also does a <b>cryptographic operation against the KMS key</b>, and KMS enforces a per-key ops-per-second quota far lower than S3&rsquo;s object-read ceiling. So at high fan-out the bottleneck moves from &lsquo;can S3 serve the object&rsquo; to &lsquo;can KMS decrypt fast enough.&rsquo; <b>S3 Bucket Keys</b> break that coupling: S3 derives a short-lived data key once and reuses it, so the per-object KMS calls largely disappear &mdash; the encryption stays, the KMS request rate drops by orders of magnitude."},int2:{q:"When do you put CloudFront in front vs just raising the KMS quota?",a:"CloudFront when the <b>same object is pulled by many devices</b> &mdash; a firmware file 50,000 devices download is the ideal cache candidate, and edge caching cuts both the KMS load and the S3 request cost while adding a WAF surface and revocable signed URLs. You raise the KMS quota (and add Bucket Keys) when the reads are <b>diverse objects</b> that don&rsquo;t cache well, or when you need presigned-URL simplicity without a distribution. For a fleet pulling one firmware version, CloudFront is the stronger answer; for scattered per-tenant objects, Bucket Keys plus quota headroom. The access pattern picks it."} },
   { tag:"FAILURE", cue:"&ldquo;GuardDuty alerts: a role is listing and reading objects it never normally touches. Walk the incident.&rdquo;",
     task:"Walk the incident &mdash; contain, scope, prove, close the class.",
     model:"<b>Contain, scope, prove, close.</b> First, <b>rotate the role&rsquo;s credentials</b> (or disable the role) to stop active access &mdash; if it&rsquo;s a role with short-lived creds the window&rsquo;s already small. Then <b>scope from CloudTrail data events</b>: exactly which objects were read, when, from where. Diagnose how the credential leaked &mdash; an exposed key, an SSRF, a compromised dependency. <b>Prove the blast radius</b>: per-tenant keys mean the role could only decrypt what its KMS grants allowed, and the VPC endpoint&rsquo;s PrincipalOrgID means nothing was copied to an outside bucket &mdash; both verifiable in the logs. Then close the <b>class</b>: tighten the role on Access Analyzer&rsquo;s evidence, add a Config rule for the drift, confirm the SCP that should have capped it.",
     int:{q:"The alert says objects were read. How do you know <i>which</i> ones &mdash; and prove it to a regulator?",a:"<b>CloudTrail data events</b> &mdash; which is exactly why they&rsquo;re enabled on sensitive buckets, and why &lsquo;CloudTrail is on&rsquo; isn&rsquo;t enough (management events don&rsquo;t log object reads). The data-event log gives you the precise list: object key, timestamp, source IP, principal. That specificity is the difference between &lsquo;a role was compromised, scope unknown&rsquo; and &lsquo;these 40 objects for one tenant were read over eleven minutes, here&rsquo;s the list, and here are the tenants that were <i>not</i> touched.&rsquo; The audit trail is what lets you bound the incident honestly &mdash; which is what a regulator and the affected customers demand."},int2:{q:"How do you prove the attacker didn&rsquo;t exfiltrate the firmware to their own account?",a:"The <b>VPC endpoint policy with <code>aws:PrincipalOrgID</code></b> is the proof, not just the defense. Every S3 request from the VPC leaves through that endpoint, and the policy restricts destinations to your org&rsquo;s resources &mdash; so a <code>CopyObject</code> or <code>PutObject</code> to an outside bucket is <i>denied at the endpoint</i>, and the denial is in the logs. So you can show the attempted exfiltration paths (if any) were blocked, and reads were confined to your own buckets. It&rsquo;s the difference between &lsquo;we think nothing left&rsquo; and &lsquo;the perimeter denied every non-org destination, here are the denies.&rsquo; Defense in depth pays off twice &mdash; it stops the exfil <i>and</i> gives you the evidence."} },
   { tag:"CURVEBALL", theme:"Public bucket", cue:"&ldquo;Your firmware bucket is suddenly public. You have Block Public Access on. Explain how that&rsquo;s even possible, then make sure it can never happen again.&rdquo;",
     task:"Reframe the premise out loud, then give the real mechanism.",
     model:"The premise to test aloud: <b>with account-level BPA on, all four settings, it should be impossible</b> &mdash; so either BPA isn&rsquo;t actually on at the account (only the bucket, and someone recreated it), or the &lsquo;public&rsquo; is a <b>path BPA doesn&rsquo;t cover</b> &mdash; a presigned URL (not public, just a bearer token) or access via a <b>VPC endpoint or another account</b>. If a policy genuinely made it public, BPA at the account was off. The durable fix is a layer <i>above</i> the account: an <b>SCP</b> that denies weakening <code>PutBucketPublicAccessBlock</code> and denies public bucket policies org-wide &mdash; un-overridable, even by an account&rsquo;s root &mdash; plus a <b>Config rule</b> that alarms the instant any bucket&rsquo;s public-access posture drifts.",
     int:{q:"So bucket-level BPA wasn&rsquo;t enough. Why does account-level plus an SCP matter so much?",a:"Because <b>bucket-level BPA protects only that bucket</b>, and it can be turned off by anyone with the permission, or sidestepped by creating a <i>new</i> bucket without it. <b>Account-level</b> BPA makes every bucket private by default, including ones created tomorrow. And the <b>SCP</b> is the ceiling above even that: it removes the <i>ability</i> to disable BPA or write a public policy from every principal in every account &mdash; because SCP denies can&rsquo;t be granted around, not even by root. It&rsquo;s defense in depth on the control itself: the bucket setting, the account setting, and the org guardrail, so no single toggle or new bucket can reopen the hole."} },
   { tag:"CLOSE", cue:"&ldquo;Sum it up &mdash; and what would you watch in prod?&rdquo;",
     task:"Two-sentence close, then the one thing you&rsquo;d alarm on.",
     model:"It&rsquo;s a storage boundary: nothing public, every credential least-privilege, SSE-KMS with a deny-unencrypted policy, credential-free expiring presigned URLs for delivery, an org-locked egress path, and audit on every access &mdash; defense in depth, so no single misconfiguration breaches the fleet. In prod I&rsquo;d alarm on the <b>shape of a credential compromise or a config drift</b> &mdash; a role reading objects it never normally touches, or any bucket&rsquo;s public-access or encryption posture changing &mdash; because those are the earliest signals, and CloudTrail data events plus Config already make them visible.",
     int:{q:"You&rsquo;ve got a week, not a month. Cut one thing to ship &mdash; what goes?",a:"The <b>sophistication</b> goes, never the controls that bound a breach. I&rsquo;d ship <b>SSE-KMS without per-tenant keys</b> (one CMK, add per-tenant later), <b>presigned URLs without CloudFront</b> (skip the edge and revocation until I need it), and <b>single-account with tight IAM</b> (defer the multi-account SCP layout) &mdash; all addable later without a rewrite. What I would <b>not</b> cut is <b>Block Public Access, least-privilege IAM, encryption with a deny-unencrypted policy, and HTTPS-only</b> &mdash; those are the boundary, and a leaked-firmware MVP is an incident, not an MVP. Knowing which parts are the boundary and which are the hardening-on-top is the answer."} }
  ];
  var mockCurveIdx=0; for(var _ci=0;_ci<mockBeats.length;_ci++){ if(mockBeats[_ci].tag==="CURVEBALL") mockCurveIdx=_ci; }
  var curveballs=[ mockBeats[mockCurveIdx],
    { tag:"CURVEBALL", theme:"Credential exfiltration", cue:"&ldquo;An attacker has your delivery service&rsquo;s role and starts copying firmware to a bucket in their own AWS account. Your IAM let them read. Stop the copy-out.&rdquo;",
      task:"Name why read-access doesn&rsquo;t imply exfil-ability, then the perimeter.",
      model:"Reading the object and <b>copying it to an outside bucket are different actions</b>, and the second can be blocked even when the first is allowed. The <b>VPC endpoint policy with <code>aws:PrincipalOrgID</code></b> is the stop: every S3 request from the VPC leaves through that endpoint, and the policy restricts destinations to your org&rsquo;s resources &mdash; so a <code>PutObject</code>/<code>CopyObject</code> to the attacker&rsquo;s bucket is <b>denied at the egress</b>, regardless of what the stolen role&rsquo;s IAM allows. Pair it with an <b>SCP</b> denying the same org-wide. The role got compromised, so you put the control on the <b>choke point the role can&rsquo;t modify</b>, not on the role.",
      int:{q:"Why not just make sure the role can&rsquo;t write anywhere &mdash; scope its IAM tighter?",a:"You should &mdash; a read-only role shouldn&rsquo;t have <code>PutObject</code> to arbitrary buckets &mdash; but that&rsquo;s the <i>same</i> layer that got compromised, so you can&rsquo;t rely on it alone. The attacker has whatever the role was granted, and if the policy was even slightly too broad, the write path is open. The <b>data perimeter</b> is an <i>independent</i> layer: even a role that <i>can</i> write is stopped from writing <i>outside the org</i> by the endpoint policy, because the restriction lives on the network egress, not the identity. Defense in depth means the tight IAM is the first line and the perimeter is the line that holds when the first was too generous."} },
    { tag:"CURVEBALL", theme:"Presigned URL leak", cue:"&ldquo;A firmware presigned URL ends up in a device log that gets shipped to a third party. The URL still works. Contain it and prevent the class.&rdquo;",
      task:"Name the bearer-token limit honestly, then the structural mitigations.",
      model:"The honest part first: a presigned URL is a <b>bearer token you can&rsquo;t revoke early</b> &mdash; whoever has it can download that one object until it expires, full stop. So containment is <b>time</b>: if the expiry is short (minutes), the exposure is already nearly closed; if it was long, that&rsquo;s the bug. Preventing the class: <b>short expiry</b> as the default, <b>single-object</b> scope so a leak is one file, and <b>don&rsquo;t log the URL</b> &mdash; treat it as a secret in logging. Where you need true revocability, front S3 with <b>CloudFront signed URLs</b>, which you <i>can</i> invalidate, or pin the URL to the device&rsquo;s source IP.",
      int:{q:"The device team wants long-lived URLs so retries don&rsquo;t fail. How do you give them that safely?",a:"You give them <b>re-issuance, not longevity</b> &mdash; the device requests a fresh presigned URL on retry rather than holding one for hours. The URL stays short-lived, and a retry just mints a new one from the delivery service, so a leaked URL is always near expiry. If the device genuinely can&rsquo;t re-request &mdash; a constrained OTA flow &mdash; then <b>CloudFront signed URLs or cookies</b> give a longer, <i>revocable</i> credential you can cut if it leaks, which a raw presigned URL can&rsquo;t. The principle: solve &lsquo;retries fail&rsquo; with cheap re-issuance of short tokens, and reach for revocable CloudFront credentials only when re-issuance isn&rsquo;t possible &mdash; never a multi-hour bearer token you can&rsquo;t take back."} },
    { tag:"CURVEBALL", theme:"KMS key compromise", cue:"&ldquo;You suspect a KMS key that encrypts one tenant&rsquo;s firmware may be compromised. Rotate it. Oh &mdash; and the old data is in immutable backups. Go.&rdquo;",
      task:"Separate key rotation from key destruction, then handle the backups.",
      model:"Two different operations, and the question conflates them. <b>Rotation</b> &mdash; new key material going forward &mdash; protects <i>future</i> writes but doesn&rsquo;t make already-encrypted data unreadable; with a KMS CMK, automatic rotation keeps old material accessible so existing ciphertext still decrypts. If the key is <b>compromised</b> and you need old data to become <i>unreadable</i>, that&rsquo;s <b>destruction</b> (schedule key deletion), and because it&rsquo;s per-tenant, deleting it <b>crypto-shreds every copy including the immutable backups</b> &mdash; ciphertext without the key is noise. The catch: destruction is <b>irreversible</b> with a mandatory waiting period, so you must be certain the key protects <i>only</i> that tenant&rsquo;s data before you pull it.",
      int:{q:"If rotation doesn&rsquo;t make old ciphertext unreadable, what does rotating a compromised key actually buy you?",a:"It bounds the <b>forward</b> exposure: after rotation, new firmware is encrypted under key material the attacker doesn&rsquo;t have, so a leaked <i>old</i> key can&rsquo;t decrypt anything written after the rotation. What rotation does <i>not</i> do is retroactively protect data already encrypted with the old material &mdash; for that you re-encrypt the live objects under the new key, and for copies you can&rsquo;t rewrite like backups, you <b>destroy the key and crypto-shred</b>. So the real answer to a compromised key is three steps: rotate to stop the bleeding forward, re-encrypt the live objects, destroy the old key to shred what you can&rsquo;t rewrite &mdash; because &lsquo;rotate&rsquo; alone is a common half-answer that leaves old ciphertext exposed."} },
    { tag:"CURVEBALL", theme:"Confused deputy", cue:"&ldquo;You let a logging service write access logs to your bucket. A researcher shows they can make that same service write <i>their</i> account&rsquo;s logs into your bucket. Explain, and close it.&rdquo;",
      task:"Name the confused-deputy attack, then the source conditions.",
      model:"Classic <b>confused deputy</b>: you granted the <i>service principal</i> (say <code>logging.s3.amazonaws.com</code>) permission to write, but that principal is <b>shared across all AWS customers</b> &mdash; so with no scoping condition, anyone who can make the service target your bucket (from their own account) becomes a &lsquo;confused deputy&rsquo; writing to you. The fix is <b><code>aws:SourceAccount</code> and <code>aws:SourceArn</code></b> conditions on the bucket policy: pin the grant to <i>your</i> account and the <i>specific</i> source resource, so the service acts on your bucket <b>only for the exact caller you intended</b>, not for any customer who names it.",
      int:{q:"Why isn&rsquo;t it enough that the bucket policy names the service principal &mdash; isn&rsquo;t that already scoped?",a:"Naming the service principal scopes it to <i>that service</i>, but not to <i>your use</i> of it &mdash; and the service principal is the same identity for every AWS account. So <code>Allow logging.s3.amazonaws.com to PutObject</code> means &lsquo;the logging service, acting for <b>anyone</b>, may write here.&rsquo; The <code>aws:SourceAccount</code>/<code>aws:SourceArn</code> conditions add the missing dimension: &lsquo;the logging service, acting <b>for my account, from this specific log source</b>.&rsquo; Without them the deputy is confused about <i>whose behalf</i> it&rsquo;s acting; with them it can only act for the exact source you specified. It&rsquo;s a subtle multi-tenant-of-AWS-itself problem, which is why it&rsquo;s a favorite senior probe."} },
    { tag:"CURVEBALL", theme:"Cost blowout", cue:"&ldquo;Your AWS bill spikes. It&rsquo;s KMS and CloudTrail, and you changed nothing &mdash; a rollout to 50,000 devices did. Cut the cost without weakening security.&rdquo;",
      task:"Name what scaled the cost, then reduce it without removing controls.",
      model:"Two culprits, both from per-operation charges at fleet scale. <b>KMS</b>: with SSE-KMS every device&rsquo;s <code>GetObject</code> was a billed <code>Decrypt</code> &mdash; 50,000 pulls, 50,000 KMS calls. <b>CloudTrail data events</b>: logging every object read is billed per event, and a fleet rollout is millions of reads. Fix without weakening: <b>S3 Bucket Keys</b> collapse the per-object KMS calls (encryption unchanged), and <b>CloudFront</b> serves the firmware from the edge so most devices never hit the bucket &mdash; cutting both KMS <i>and</i> data-event volume. For CloudTrail, <b>scope data events to the sensitive prefixes</b> rather than the whole account. Same posture, a fraction of the per-operation cost.",
      int:{q:"Couldn&rsquo;t you just turn off CloudTrail data events on the firmware bucket to save money?",a:"No &mdash; that trades the <b>audit trail that scopes a breach</b> for a cost saving, and the firmware bucket is exactly where you need it most. Without data events you&rsquo;d know a credential was compromised but not <i>which objects it read</i>, turning a bounded incident into &lsquo;scope unknown.&rsquo; The right move is to cut the <b>volume</b>, not the <b>coverage</b>: CloudFront means most reads are edge hits that never generate a bucket data event, so you keep full auditing of actual bucket access at a fraction of the events. And if cost is still an issue, scope data events to the sensitive prefixes and skip the low-value ones &mdash; targeting the audit where the blast radius is high, rather than blinding yourself on the crown-jewel bucket."} },
    { tag:"CURVEBALL", theme:"Cross-region replication", cue:"&ldquo;For DR you replicate the firmware bucket to another region. Security asks: did you just double your attack surface and break your per-tenant key story? Answer them.&rdquo;",
      task:"Name the two risks replication introduces, then how you keep the posture.",
      model:"Two real risks. <b>Attack surface</b>: the replica is a second bucket that needs the <i>same</i> hardening &mdash; Block Public Access, least-privilege access, deny-non-TLS &mdash; or it&rsquo;s a softer copy of your crown jewels. <b>Keys</b>: KMS keys are <b>regional</b>, so the replica can&rsquo;t use the source region&rsquo;s key &mdash; you replicate with a <b>destination-region CMK</b> (S3 replication supports re-encrypting to a key in the target region), or the per-tenant crypto-shred story breaks because destroying the source key wouldn&rsquo;t cover the replica. The fix: apply the identical bucket controls to the replica <i>as code</i>, and set up <b>per-tenant keys in the destination region</b> so crypto-shred still means &lsquo;destroy the key, all copies unreadable&rsquo; &mdash; in both regions.",
      int:{q:"So to crypto-shred a tenant now you have to destroy keys in two regions?",a:"Yes &mdash; and that&rsquo;s the point to say out loud, because it&rsquo;s the part people miss. Once data is replicated cross-region under a <b>region-local key</b>, erasing that tenant means <b>destroying their key in every region the data lives in</b>; a single-region key destruction leaves readable ciphertext in the replica. So the erasure procedure has to enumerate <i>all</i> regions and shred the tenant&rsquo;s key in each. This is exactly why per-tenant, per-region key management has to be deliberate: replication is a compliance decision, not just a durability one, because it multiplies both the buckets you harden and the keys you must destroy to honor an erasure request."} },
    { tag:"CURVEBALL", theme:"Silent drift", cue:"&ldquo;Six months after you hardened everything, an audit finds a role with <code>s3:*</code> and a bucket with encryption off. Nobody remembers doing it. How did &lsquo;hardened&rsquo; rot, and how do you make it not?&rdquo;",
      task:"Name why hardening drifts, then the continuous controls that catch it.",
      model:"Hardening rots because it&rsquo;s a <b>point-in-time state</b> and the system keeps changing: a role gets &lsquo;just one more permission&rsquo; for a deadline and it&rsquo;s never removed, a new bucket is created without the encryption default, an incident &lsquo;temporarily&rsquo; loosens a policy. None of it is malicious; it&rsquo;s entropy. The fix is to make the desired state <b>continuously enforced and observed</b>: <b>AWS Config rules</b> that alarm the instant encryption or BPA drifts, <b>IAM Access Analyzer</b> flagging over-broad and unused permissions, and the whole posture defined as <b>infrastructure as code</b> so the intended state is reviewable and drift is a diff. Detection catches it; <b>SCPs</b> make the worst drifts (public, unencrypted) <i>impossible</i> in the first place.",
      int:{q:"Config and Access Analyzer generate findings. How do you keep those from becoming ignored noise?",a:"By making them <b>actionable and gated</b>, not just a dashboard. High-severity findings &mdash; a public bucket, encryption off, an externally-reachable role &mdash; should <b>page or block</b>, ideally auto-remediate (a Config rule that re-enables BPA, a pipeline check that fails the deploy). Lower-severity drift (an unused permission) becomes a <b>tracked backlog item</b> with an owner, reviewed on a cadence, so it&rsquo;s tightened on evidence rather than accumulating. The failure mode is a wall of findings nobody reads; you avoid it by tiering &mdash; the dangerous few auto-remediate or block, the rest are triaged &mdash; and by defining the posture as code so &lsquo;fixing&rsquo; a finding means a reviewable change, not a console click that itself drifts. Continuous enforcement only works if the findings drive action."} }
  ];
  var mockFrameIdx=0; for(var _fi=0;_fi<mockBeats.length;_fi++){ if(mockBeats[_fi].tag==="FRAME") mockFrameIdx=_fi; }
  var frames=[ mockBeats[mockFrameIdx].cue,
    "&ldquo;Harden an S3 bucket that stores sensitive customer data &mdash; walk me through every control that keeps one mistake from exposing it.&rdquo;",
    "&ldquo;How would you deliver files to devices that can&rsquo;t hold cloud credentials, without ever making anything public?&rdquo;",
    "&ldquo;A bucket holds your crown-jewel artifacts. Walk me through the layers, from public-access to exfiltration, that bound the blast radius of a single misconfiguration.&rdquo;"
  ];
  return { cards: AWSHARD_CARDS, speak: AWSHARD_SPEAK, curveballs: curveballs, mockBeats: mockBeats, frames: frames };
})();
