/* topics/aws-hardening/walk.js -- topic 4 walkthrough. steps[] is the hardening flow
   (bucket -> Block Public Access -> least-priv IAM -> SSE-KMS -> HTTPS-only ->
   presigned delivery -> the bearer-token limit -> VPC endpoint -> versioning/Object
   Lock/audit); modelScript[] is the spoken model answer (plain beats, the interviewer
   .mq line, then the .mbeat.ans -- which MUST be LAST, the last-child CSS depends on
   it). Code strings use single-backslash \n / \'. Offline-safe; 7-bit ASCII. */
var TOPIC_AWSHARD_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"The bucket the pipeline writes to",
      flow:'<span class="fb n">pipeline</span><span class="arr">&rarr;</span><span class="fb p">PutObject</span><span class="arr">&rarr;</span><span class="fb t">private bucket</span><span class="arr">&middot;</span><span class="fb a">holds the fleet&rsquo;s firmware</span>',
      ins:'The pipeline writes the signed package here. This one bucket holds firmware for <b>50,000+ terminals</b> and tenant data &mdash; so it&rsquo;s the crown jewels, and a single misconfiguration exposes the fleet.',
      deep:'The whole topic hangs on that framing: the storage layer is the highest-value target in the system, because it holds every tenant&rsquo;s signed firmware and the data behind it. So the design goal isn&rsquo;t &ldquo;secure the bucket&rdquo; in the abstract &mdash; it&rsquo;s <b>least privilege plus defense in depth</b>, arranged so that no <i>single</i> mistake &mdash; one public setting, one over-broad role, one leaked URL &mdash; turns into a breach. Every step that follows is one layer of that.' },
    { k:"Step 2 / 9", t:"Block Public Access &mdash; the non-negotiable",
      flow:'<span class="fb n">account BPA</span><span class="arr">&rarr;</span><span class="fb p">bucket BPA</span><span class="arr">&rarr;</span><span class="fb t">all four on</span><span class="arr">&middot;</span><span class="fb a">no ACL/policy can make it public</span>',
      ins:'The first control, and it&rsquo;s not optional: <b>Block Public Access</b> at the account <i>and</i> the bucket, all four settings, so no ACL and no bucket policy can <i>ever</i> make an object public. This is the switch whose absence is behind every public-S3 breach headline.',
      code:'<span class="c">// account-level AND bucket-level -- all four true</span>\n{\n  <span class="s">"BlockPublicAcls"</span>: <span class="k">true</span>,        <span class="c">// reject PUTs carrying a public ACL</span>\n  <span class="s">"IgnorePublicAcls"</span>: <span class="k">true</span>,       <span class="c">// ignore any public ACL already set</span>\n  <span class="s">"BlockPublicPolicy"</span>: <span class="k">true</span>,      <span class="c">// reject a public bucket policy</span>\n  <span class="s">"RestrictPublicBuckets"</span>: <span class="k">true</span>  <span class="c">// same-account / service access only</span>\n}',
      cap:'BPA is the belt to least-privilege&rsquo;s suspenders &mdash; even if someone writes a public ACL or policy by mistake, the four switches make it a no-op. Set it at the <b>account</b> so every new bucket is private by default, not just this one.' },
    { k:"Step 3 / 9", t:"Least-privilege IAM &mdash; who can touch it",
      flow:'<span class="fb n">pipeline role: PutObject, one prefix</span><span class="arr">&rarr;</span><span class="fb p">delivery role: GetObject</span><span class="arr">/</span><span class="fb r">nothing gets s3:*</span>',
      ins:'Then IAM. The pipeline role can <code>PutObject</code> on <b>one prefix</b>; the delivery service can <code>GetObject</code>; neither can <code>s3:*</code>, delete the bucket, or read another prefix. <b>Deny-by-default</b> &mdash; a role does exactly what it needs, no more.',
      code:'<span class="c">// the delivery service role -- exactly one action, one prefix</span>\n{\n  <span class="s">"Effect"</span>: <span class="s">"Allow"</span>,\n  <span class="s">"Action"</span>: [<span class="s">"s3:GetObject"</span>],           <span class="c">// not s3:*, not List, not Delete</span>\n  <span class="s">"Resource"</span>: <span class="s">"arn:aws:s3:::fw-prod/signed/*"</span>  <span class="c">// one prefix, not the whole bucket</span>\n}',
      cap:'The tell is the blast radius of a <i>stolen</i> credential: <code>s3:*</code> on the bucket hands an attacker every tenant&rsquo;s firmware <i>and</i> the power to replace it; <code>GetObject</code> on one prefix hands them read of one path. Scope the <b>action</b> and the <b>resource</b>, not just one.' },
    { k:"Step 4 / 9", t:"Encryption at rest &mdash; SSE-KMS",
      flow:'<span class="fb n">default encryption</span><span class="arr">&rarr;</span><span class="fb p">SSE-KMS, per-tenant key</span><span class="arr">&rarr;</span><span class="fb t">deny unencrypted PUT</span><span class="arr">&middot;</span><span class="fb a">CloudTrail every Decrypt</span>',
      ins:'Default bucket encryption with <b>SSE-KMS</b> on a <b>per-tenant customer-managed key</b>, a bucket policy that <b>denies any PUT that isn&rsquo;t KMS-encrypted</b>, and CloudTrail logging every <code>Decrypt</code>. Per-tenant keys buy crypto-shredding and a bounded blast radius.',
      deep:'SSE-S3 (AES-256, AWS-managed) is free and fine for at-rest integrity &mdash; but <b>SSE-KMS</b> buys three things SSE-S3 can&rsquo;t: an <b>audit trail</b> (every <code>Decrypt</code> is a CloudTrail event, so you see who read what), <b>access control on the key itself</b> (the key policy is a second, independent gate), and <b>per-tenant crypto-shredding</b> (destroy that tenant&rsquo;s key and their data is unreadable everywhere &mdash; including backups). The cost is a KMS request per operation and a per-key throughput ceiling, which is real at high fan-out and is the thing you&rsquo;d actually have to engineer around.' },
    { k:"Step 5 / 9", t:"Encryption in transit &mdash; HTTPS-only",
      flow:'<span class="fb n">bucket policy</span><span class="arr">&rarr;</span><span class="fb r">deny aws:SecureTransport=false</span><span class="arr">&rarr;</span><span class="fb t">TLS only</span><span class="arr">&middot;</span><span class="fb a">no plaintext firmware</span>',
      ins:'A bucket policy that <b>denies any request where <code>aws:SecureTransport</code> is false</b>, so firmware never travels as plaintext. One statement &mdash; and the first checkbox a PCI or HIPAA auditor looks for.',
      code:'<span class="c">// deny anything not over TLS -- the compliance baseline</span>\n{\n  <span class="s">"Effect"</span>: <span class="s">"Deny"</span>,\n  <span class="s">"Principal"</span>: <span class="s">"*"</span>,\n  <span class="s">"Action"</span>: <span class="s">"s3:*"</span>,\n  <span class="s">"Resource"</span>: <span class="s">"arn:aws:s3:::fw-prod/*"</span>,\n  <span class="s">"Condition"</span>: { <span class="s">"Bool"</span>: { <span class="s">"aws:SecureTransport"</span>: <span class="s">"false"</span> } }\n}',
      cap:'A <code>Deny</code> gated on <code>SecureTransport:false</code> is the cheapest control in the whole topic &mdash; one statement that makes plaintext impossible. Its <i>absence</i> is an instant audit finding, which is why you volunteer it unprompted.' },
    { k:"Step 6 / 9", t:"Presigned URLs &mdash; delivery without credentials",
      flow:'<span class="fb n">device asks for firmware</span><span class="arr">&rarr;</span><span class="fb p">service signs a URL</span><span class="arr">&rarr;</span><span class="fb t">one object, short expiry</span><span class="arr">&middot;</span><span class="fb a">device downloads, no creds</span>',
      ins:'50,000 terminals can&rsquo;t hold AWS credentials, so the delivery service mints a <b>presigned URL</b> &mdash; a Signature V4 URL scoped to <b>one object</b> with a short expiry. The device downloads with just the URL; the IoT Job document carries the <i>URL</i>, never the firmware bytes.',
      code:'<span class="c">// the delivery service mints a short-lived, single-object URL</span>\n<span class="k">const</span> url = <span class="k">await</span> getSignedUrl(s3, <span class="k">new</span> GetObjectCommand({\n  Bucket: <span class="s">\'fw-prod\'</span>, Key: <span class="s">`signed/${tenant}/${pkg}`</span>\n}), { expiresIn: <span class="hl">300</span> });   <span class="c">// 5 min -- as short as the download needs</span>\n<span class="c">// this URL goes into the IoT Job document; the firmware never does</span>',
      cap:'The device never sees an AWS credential &mdash; only a URL that works for <b>one object for five minutes</b>. The URL is signed with the delivery role&rsquo;s permissions, so it can do exactly what that role can, and nothing more.' },
    { k:"Step 7 / 9", t:"The presigned-URL limit &mdash; it&rsquo;s a bearer token",
      flow:'<span class="fb r">URL leaks</span><span class="arr">&rarr;</span><span class="fb r">anyone can download until expiry</span><span class="arr">&middot;</span><span class="fb a">can&rsquo;t revoke early</span><span class="arr">/</span><span class="fb t">bound by expiry + scope</span>',
      ins:'The honest trade-off people miss: a presigned URL is a <b>bearer token</b> &mdash; whoever holds it can download until it expires, and you <b>can&rsquo;t revoke it early</b>. So the mitigations are structural: short expiry, one object, and the URL is bounded by the signer&rsquo;s least-privilege permissions.',
      deep:'You cannot invalidate a presigned URL before its expiry &mdash; short of rotating the signer&rsquo;s credentials, which nukes <i>every</i> outstanding URL. So the defense is to make the window small and the scope tight: a five-minute URL for one firmware file is a small thing to leak, and it&rsquo;s useless the moment it expires. Where you genuinely need revocability, you front S3 with <b>CloudFront signed URLs / cookies</b> (which you can invalidate) or add a <b>condition pinning the URL to the device&rsquo;s source IP</b> &mdash; trading a little simplicity for the ability to cut access mid-flight.' },
    { k:"Step 8 / 9", t:"VPC endpoints &mdash; private access, no egress",
      flow:'<span class="fb n">service</span><span class="arr">&rarr;</span><span class="fb p">Gateway VPC endpoint</span><span class="arr">&rarr;</span><span class="fb t">S3 over AWS backbone</span><span class="arr">&middot;</span><span class="fb a">endpoint policy: aws:PrincipalOrgID</span>',
      ins:'Internal services reach S3 through a <b>Gateway VPC endpoint</b> (free), so traffic never touches the public internet &mdash; and the endpoint policy adds <code>aws:PrincipalOrgID</code> to block exfiltration to any bucket <i>outside</i> the org, even from a compromised role.',
      deep:'Two wins. <b>Network:</b> traffic stays on the AWS backbone &mdash; the &ldquo;no internet egress&rdquo; box a HIPAA or FedRAMP auditor wants ticked. <b>Security:</b> the endpoint policy is a choke point &mdash; <code>aws:PrincipalOrgID</code> on it means a stolen credential <i>cannot</i> copy your firmware to an attacker&rsquo;s personal bucket, because every request leaving through that endpoint is restricted to your org&rsquo;s resources. It&rsquo;s the SCP-plus-endpoint-policy defense-in-depth pattern against data exfiltration, which is exactly the follow-up a senior interviewer reaches for.' },
    { k:"Step 9 / 9", t:"Versioning + Object Lock + audit &mdash; the backstop",
      flow:'<span class="fb n">versioning</span><span class="arr">&rarr;</span><span class="fb p">Object Lock (WORM)</span><span class="arr">&rarr;</span><span class="fb t">access logs + CloudTrail data events</span><span class="arr">&middot;</span><span class="fb a">blast radius bounded</span>',
      ins:'The &ldquo;assume something still goes wrong&rdquo; layer: <b>versioning</b> so an overwrite is recoverable, <b>Object Lock</b> (WORM) so a signed package can&rsquo;t be altered or deleted for its retention period, and <b>access logging + CloudTrail data events</b> so every <code>GetObject</code> is audited.',
      deep:'Versioning turns a destructive overwrite into a recoverable event. Object Lock in <b>compliance mode</b> means not even an admin can delete the firmware before retention expires &mdash; which matters because it&rsquo;s a signed artifact you may need to <i>prove</i> you shipped. And CloudTrail data events (<code>GetObject</code>/<code>PutObject</code>) give you the same audit trail authz relies on: who accessed which object, when &mdash; so a breach can be scoped precisely. No single control is trusted; each one bounds what a failure of the others can cost. That&rsquo;s the whole thesis, made concrete.' }
  ],
  modelScript: [
    { ml:'Frame the stakes', t:'"This bucket holds signed firmware for fifty thousand terminals and the data behind it &mdash; so the whole game is that no single misconfiguration can expose it. Least privilege plus defense in depth."' },
    { ml:'Nothing public', t:'"First control, non-negotiable: Block Public Access at the account and the bucket, all four settings, so no ACL or policy can ever make an object public. That&rsquo;s the switch whose absence is behind every public-S3 breach headline."' },
    { ml:'Least privilege', t:'"Then IAM: the pipeline role can PutObject on one prefix, the delivery service can GetObject, and nothing gets s3-star. A role does exactly what it needs, so a stolen credential reads one path, not the fleet."' },
    { ml:'Encrypt everything', t:'"Encrypted at rest with SSE-KMS on a per-tenant key &mdash; which buys an audit trail and crypto-shredding &mdash; and a bucket policy that denies unencrypted PUTs and anything not over TLS. Plaintext firmware is impossible."' },
    { ml:'Deliver without credentials', t:'"Devices can&rsquo;t hold AWS creds, so the service mints a presigned URL &mdash; one object, five-minute expiry &mdash; and puts it in the Job document. The device downloads with just the URL, and the URL can only do what the delivery role can."' },
    { mq:'Interviewer: "A presigned URL leaks. Now what?"' },
    { ml:'Name the limit honestly', t:'"That&rsquo;s the real trade-off &mdash; a presigned URL is a bearer token you can&rsquo;t revoke before it expires. So the defense is structural: short window, one object, least-privilege signer. A five-minute URL for one firmware file is a small thing to leak. If I needed to cut access mid-flight, I&rsquo;d front S3 with CloudFront signed URLs or pin the URL to the device&rsquo;s IP."' },
    { ml:'Land on blast radius', t:'"And underneath it all &mdash; a VPC endpoint so nothing egresses to the internet, an endpoint policy with PrincipalOrgID so a stolen credential can&rsquo;t exfiltrate to an outside bucket, versioning and Object Lock so firmware can&rsquo;t be tampered, CloudTrail data events so every access is audited. The point isn&rsquo;t any one control &mdash; it&rsquo;s that no single slip breaches, because the blast radius is bounded at every layer."', ans:true }
  ]
};
