<!--@build:include scripts/app/base-styles.js-->
<!--@build:include scripts/app/content-sheet.js-->
<!--@build:include scripts/app/shared-sheets.js-->
<!--@build:include scripts/app/red-flags.js-->
<!--@build:include scripts/app/trade-offs.js-->
<!--@build:include scripts/app/walkthrough.js-->
<!--@build:include scripts/app/drill.js-->
<!--@build:include scripts/app/whiteboard.js-->
<!--@build:include scripts/app/opener-altitude.js-->
<!--@build:include scripts/app/mock-run.js-->
<!--@build:include scripts/app/mixed-fire.js-->
<!--@build:include scripts/app/cram-sheet.js-->
<!--@build:include scripts/app/keyboard-overlay.js-->
<!--@build:include scripts/app/scope-overlay.js-->
<!--@build:include scripts/app/gameplan-overlay.js-->
<!--@build:include scripts/app/cram-overlay.js-->
<!--@build:include scripts/app/session-progress.js-->
<!--@build:include scripts/app/system-map.js-->
<!--@build:include scripts/app/model-answers.js-->
<!--@build:include scripts/app/numbers-nalsd.js-->
<!--@build:include scripts/app/router.js-->
<!--@build:include scripts/app/view-manager.js-->
<!--@build:include scripts/app/tour-guide.js-->
<!--@build:include scripts/app/search-overlay.js-->
<!--@build:include scripts/app/dynamic-features.js-->
<!--@build:include scripts/app/session-timer.js-->
<!--@build:include scripts/app/scroll-progress.js-->
<!--@build:include scripts/app/copy-code.js-->
<!--@build:include scripts/app/touch-swipe.js-->
<!--@build:include scripts/app/state-persistence.js-->
<!--@build:include scripts/app/completion-celebration.js-->
<!--@build:include scripts/app/scroll-to-top.js-->
<!--@build:include scripts/app/reading-time.js-->
<!--@build:include scripts/app/focus-mode.js-->
<!--@build:include scripts/app/share-url.js-->
<!--@build:include scripts/app/font-size.js-->
<!--@build:include scripts/app/bookmark-system.js-->
<!--@build:include scripts/app/offline-indicator.js-->
<!--@build:include scripts/app/page-visibility.js-->
<!--@build:include scripts/app/progress-ring.js-->
<!--@build:include scripts/app/typing-intro.js-->
<!--@build:include scripts/app/audio-feedback.js-->
<!--@build:include scripts/app/zoom-diagrams.js-->
<!--@build:include scripts/app/animation-speed.js-->
<!--@build:include scripts/app/welcome-banner.js-->
<!--@build:include scripts/app/pomodoro-timer.js-->
<!--@build:include scripts/app/sticky-footer.js-->
<!--@build:include scripts/app/perf-overlay.js-->
<!--@build:include scripts/app/web-share.js-->
<!--@build:include scripts/app/virtual-keyboard.js-->
<!--@build:include scripts/app/night-schedule.js-->
<!--@build:include scripts/app/double-tap.js-->
<!--@build:include scripts/app/easter-egg.js-->
<!--@build:include scripts/app/edge-swipe.js-->
<!--@build:include scripts/app/network-indicator.js-->
<!--@build:include scripts/app/prefetch-hover.js-->
<!--@build:include scripts/app/session-logger.js-->
<!--@build:include scripts/app/scroll-direction.js-->
<!--@build:include scripts/app/undo-toast.js-->
<!--@build:include scripts/app/loading-button.js-->
<!--@build:include scripts/app/badge-counter.js-->
<!--@build:include scripts/app/battery-indicator.js-->
<!--@build:include scripts/app/haptic-feedback.js-->
<!--@build:include scripts/app/resize-observer.js-->
<!--@build:include scripts/app/selection-api.js-->
<!--@build:include scripts/app/notification-system.js-->
<!--@build:include scripts/app/media-query-listener.js-->
<!--@build:include scripts/app/pointer-events.js-->