/* topics/iac/bank.js -- topic 8 working-set bank (IIFE). Builds mockBeats (6, tagged
   FRAME/STRUCTURE/SCALE/FAILURE/CURVEBALL/CLOSE), derives curveballs (8, curve[0] === the
   CURVEBALL mockBeat, 8 distinct themes) and frames (4, frame[0] === the FRAME mockBeat cue),
   and aliases the LOCAL IAC_CARDS / IAC_SPEAK so a switch reseeds the globals without clobbering
   topic 1. Entities only. 7-bit ASCII. */
var TOPIC_IAC_BANK = (function(){
  var mockBeats = [
    { tag:'FRAME',
      cue:'Design how a team manages its cloud infrastructure reproducibly and safely.',
      task:'Frame the boundary and the model before mechanics &mdash; move from &lsquo;we need to create AWS resources&rsquo; to &lsquo;declare desired infrastructure and converge reality to it,&rsquo; not straight to Terraform syntax.',
      model:'I&rsquo;d frame it as the boundary between declared infrastructure and provisioned reality, managed with infrastructure as code: you declare the desired estate as a dependency graph, the tool diffs it against a locked, remote state file, and applies a reviewed plan. State is the source of truth mapping config to real resources; plan-before-apply is the review gate; the same diff against reality detects drift. It&rsquo;s the deploy-time, human-run cousin of a reconciler &mdash; declare a goal, converge to it, reviewably.',
      int:{ q:'Why is this better than just clicking through the console?', a:'Because clicking is unrecorded, unreviewable, and unrepeatable &mdash; no audit trail, no diff to review before a risky change, no way to reproduce an environment, and no way to detect drift. IaC turns each into a solved problem: git history is the audit log, the PR is the review, the config is the reproducible definition, and plan is the drift check. The console is fine for reading and emergencies; it&rsquo;s a terrible system of record for a team.' },
      int2:{ q:'What&rsquo;s the single biggest risk in this setup?', a:'State &mdash; it&rsquo;s a fragile, sensitive single source of truth. Concurrent applies corrupt it (and corrupt state poisons every future plan), a lost state file makes the tool want to recreate everything, and it holds plaintext secrets. So most of operating IaC safely is protecting this one artifact: remote, locked, encrypted, versioned. The second biggest is destructive changes &mdash; a config edit that forces a destroy-and-recreate on a stateful resource, which the plan will show but only if you read it.' } },
    { tag:'STRUCTURE',
      cue:'Walk me through plan and apply &mdash; config change to real change.',
      task:'Narrate the two-phase loop &mdash; plan (diff) then apply (execute) &mdash; and show where state, the lock, and review sit.',
      model:'You edit config; then plan diffs it against state and shows exactly what would change &mdash; create, update, destroy &mdash; without touching anything. Someone reviews that diff, hunting for destroys and replacements, especially on stateful resources; in CI it&rsquo;s posted to the PR. If approved, apply acquires the state lock, executes the plan in dependency order (parallel where safe), and writes each real resource ID back into state. Recording IDs makes apply idempotent and crash-recoverable. The separation is the safety story: you see the consequences before they&rsquo;re real.',
      int:{ q:'Where do state and the lock come into that loop?', a:'State is what plan diffs against &mdash; it&rsquo;s the tool&rsquo;s record of what exists, so plan compares desired config to state (and refreshes actual state from the cloud) to compute the diff. The lock comes in at apply: before apply mutates state, it acquires a lock (a DynamoDB item for an S3 backend) so two applies can&rsquo;t interleave and corrupt the shared state file. So state is read during plan and written during apply, and the lock guards that write &mdash; one apply at a time, per state.' } },
    { tag:'SCALE',
      cue:'You have dev, staging, and prod across multiple AWS accounts. Structure the IaC so they&rsquo;re consistent but isolated.',
      task:'Locate the two levers &mdash; shared versioned modules for consistency, per-account isolated state for isolation &mdash; plus version-promotion.',
      model:'Two levers. For consistency, put the actual infrastructure in versioned modules, so every environment builds from the same definitions, instantiated per environment with different inputs. For isolation, separate state per environment and separate AWS accounts &mdash; so a prod apply can&rsquo;t reach dev, and each account has independent credentials, quotas, and blast radius. Promote changes by version: bump the module in dev, verify, then staging, then prod, each a reviewed plan &mdash; so the change that ran in dev is literally the same code in prod, and environments differ only in inputs and module version, never in hand-drift.',
      int:{ q:'Why separate accounts, not just separate state files?', a:'Because accounts give hard isolation state boundaries can&rsquo;t. Separate state stops an apply from touching another environment&rsquo;s resources, but everything still shares one account&rsquo;s blast radius, quotas, IAM, and billing &mdash; a compromised credential or a security misconfiguration affects the whole account regardless of state layout. Separate accounts give a real security boundary, independent quotas, clean cost attribution, and incident containment. State isolation is tooling correctness; account isolation is security and operational containment. Serious setups use both.' },
      int2:{ q:'How do you promote a change through environments safely?', a:'By version, not by copy. The infra lives in versioned modules; an environment references a specific version. To promote: land the change as a new module version, point dev at it and apply, verify (tests, the plan diff, smoke checks), then advance staging, verify, then prod &mdash; each a reviewed plan you approve. Because environments differ only in inputs and version, the change that ran in dev is the same versioned artifact in prod, not a re-implementation, so you&rsquo;re not hoping prod matches dev. Staged rollout with a checkpoint per environment and an audit trail of which version is where.' } },
    { tag:'FAILURE',
      cue:'Your state file got corrupted &mdash; two applies ran at once. Walk the incident.',
      task:'Diagnose corrupt state, contain it (restore from a version), and prevent recurrence (locking).',
      model:'First, stop applies &mdash; corrupt state poisons every plan, so I don&rsquo;t want anyone acting on a false map of reality. Diagnose: two concurrent applies interleaved writes, so state now matches neither reality nor either intent. Contain by restoring state from a known-good version (why remote, versioned state matters) &mdash; roll back to before the corruption, then carefully re-plan against reality to confirm state and cloud agree, importing or fixing any resource that diverged. Prevent recurrence: enable state locking (a DynamoDB lock table for the S3 backend) so two applies can never interleave again, and move applies into CI so they&rsquo;re serialized through the pipeline. The root cause was unlocked shared state; the fix is the lock.',
      int:{ q:'Why is restoring a version better than deleting state and starting over?', a:'Because deleting state makes the tool forget every resource it manages &mdash; the next plan wants to create everything from scratch, colliding with or duplicating your live infrastructure. State isn&rsquo;t a regenerable cache; it&rsquo;s the only record of which real resource each config address owns. Restoring a version brings back a correct mapping you then reconcile against reality; deleting throws the mapping away and risks recreating or orphaning production. Restore-and-reconcile is recovery; delete-and-rerun is a second, bigger outage.' },
      int2:{ q:'How do you know the restored state actually matches reality?', a:'Run plan against the restored state and read the diff. If plan shows no changes, state, config, and reality agree &mdash; you&rsquo;re clean. If it shows a diff, state disagrees with the real cloud somewhere (a resource created during the corruption window, or one changed), so you reconcile: import resources missing from state, or adjust so plan goes empty, before any apply. The empty-plan check is the proof of a correct mapping &mdash; you&rsquo;re not done restoring until the tool agrees its state matches the actual infrastructure.' } },
    { tag:'CURVEBALL',
      theme:'Deleted state file',
      cue:'Someone deleted the state file to &lsquo;clean up,&rsquo; and now a plan wants to create your entire production estate from scratch. What happened, and what do you do?',
      task:'Diagnose state-as-source-of-truth (not a cache) and recover via restore-or-import, not apply.',
      model:'State was the tool&rsquo;s only record of which real resource each config address owns, so deleting it made the tool forget everything it manages &mdash; with empty state, plan sees your config, finds nothing in state, and concludes it must create it all, even though it&rsquo;s already running. Do NOT apply that plan: it would collide with live resources on name conflicts or create duplicates alongside production. Recover by restoring state from a version if the backend is versioned (the easy path, which is why remote versioned state matters), or if it&rsquo;s truly gone, import each existing resource back into a fresh state by ID and iterate until plan shows no changes. The lesson: state is the source of truth, backed up and restored, never a disposable cache.',
      int:{ q:'What would have made this a non-event?', a:'Remote, versioned state. A versioned S3 backend means a deleted or corrupted state file is a one-command restore to the previous revision, not a crisis. Access controls that make state hard to casually delete help too, as does treating state like a credential rather than a scratch file someone can &lsquo;clean up.&rsquo; The whole class of state-loss incidents shrinks from &lsquo;catastrophic recovery&rsquo; to &lsquo;restore a version&rsquo; the moment state lives in a versioned, access-controlled remote backend &mdash; which is exactly why that&rsquo;s the first thing you set up.' } },
    { tag:'CLOSE',
      cue:'Two sentences &mdash; sell me the setup.',
      task:'Compress the whole IaC practice to its spine and governing discipline, no hedging.',
      model:'Infrastructure as code: declare the estate as a dependency graph, keep state remote-locked-encrypted and split by blast radius, plan-and-review every change in CI before a gated apply, detect drift on a schedule, and compose with versioned modules across isolated per-account states &mdash; so provisioning is reproducible, reviewable, and drift-detectable instead of clicked. The discipline that makes it safe is two rules and a habit: plan before apply (review the diff, catch every destroy), lock your state (never corrupt the shared source of truth), and treat state as precious and secret.',
      int:{ q:'If you had to cut one thing to ship, what goes?', a:'The tool-comparison and provider internals go first, and I&rsquo;d start with a single environment and one remote-locked state rather than the full multi-account module structure. What I&rsquo;d never cut is the three essentials: a declared diffable graph, remote-locked-encrypted state, and plan-review-before-apply. Those are a working, safe practice &mdash; modules, state-splitting, drift scheduling, and multi-account isolation are the layers that make it scale, but the spine is declare-graph, protect-state, review-before-apply.' } }
  ];
  var mockCurveIdx = mockBeats.findIndex(function(b){ return b.tag === 'CURVEBALL'; });
  var curveballs = [
    mockBeats[mockCurveIdx],
    { tag:'CURVEBALL', theme:'Concurrent-apply corruption',
      cue:'Two engineers applied at the same time and now every plan shows bizarre diffs. What happened?',
      task:'Diagnose unlocked concurrent applies corrupting shared state, and fix with locking.',
      model:'Unlocked shared state got corrupted by concurrent applies: both read the same state, each made changes, and the second write clobbered the first &mdash; so state now records a mix that matches neither reality nor either intent, and every subsequent plan diffs against that garbage, producing bizarre results. This is different from a failed apply (a retry) &mdash; corrupt state is a forensic cleanup because it poisons all future plans. Fix: restore state from a version, re-plan against reality to reconcile, and &mdash; the actual root-cause fix &mdash; enable state locking (a DynamoDB lock table for the S3 backend) so two applies can never interleave again. Ideally also move applies into CI where they&rsquo;re serialized through the pipeline.',
      int:{ q:'Why doesn&rsquo;t a failed apply cause this, but concurrent applies do?', a:'A failed apply leaves your infrastructure possibly-partial but your state intact and consistent &mdash; you re-run and converge, because state still correctly reflects what the tool knows. Concurrent applies corrupt state itself: two writers racing on the same file produce a state that&rsquo;s internally inconsistent, so the tool&rsquo;s map of reality is now wrong, and every plan built on it is wrong. One is a retryable operation on good records; the other poisons the records. That asymmetry &mdash; failed apply is a retry, corrupt state is a cleanup &mdash; is exactly why locking shared state is non-negotiable while a single-writer failed apply needs no special machinery.' } },
    { tag:'CURVEBALL', theme:'Plan destroys the prod DB',
      cue:'A routine config change&rsquo;s plan says it will destroy and recreate your production database. You didn&rsquo;t intend that. What&rsquo;s going on?',
      task:'Diagnose forced replacement from an immutable attribute; stop, don&rsquo;t apply; migrate if genuinely needed.',
      model:'You changed an immutable attribute &mdash; something the cloud can&rsquo;t alter in place, like a DynamoDB key schema, an RDS engine setting, or a resource name &mdash; so the tool must replace the resource: -/+ destroy then create. The plan is warning you, usually with &lsquo;forces replacement&rsquo; next to the offending field. On a stateful resource that&rsquo;s data loss, so I do NOT apply. I find which attribute forced it and revert that change if it wasn&rsquo;t intended; if the change is genuinely required, I do a real migration &mdash; snapshot the data, create the new resource, copy data over &mdash; rather than let the tool blind-replace. And critical stateful resources should carry prevent_destroy and live in their own state so this can&rsquo;t happen by accident. The plan did its job; the point is that I read it.',
      int:{ q:'How do you make sure this can never happen by accident?', a:'Layered guards. prevent_destroy lifecycle on the database makes any plan that would destroy it fail outright &mdash; a hard stop. Isolating stateful resources in their own state shrinks blast radius so an app-infra apply can&rsquo;t reach the DB. Cloud-level deletion protection (RDS/DynamoDB) is a second line. And in CI, block auto-apply on any plan containing a destroy and require explicit human approval. So the plan surfaces it, prevent_destroy hard-stops it, isolation contains it, cloud protection backstops it, and CI policy forces a conscious approval &mdash; no single accident should be able to delete a production datastore.' } },
    { tag:'CURVEBALL', theme:'Console-change drift',
      cue:'A security group was changed in the console last week, and now your next apply wants to revert it. How should you handle this?',
      task:'Frame it as drift; decide converge-vs-adopt; and prevent recurrence with detection + restricted access.',
      model:'That&rsquo;s drift &mdash; reality diverged from code because of the manual console change, and plan is showing what it&rsquo;d do to converge reality back to declared. The decision is converge-or-adopt: if the console change was a mistake or unauthorized, apply to revert it back to the declared config; if it was a legitimate fix, update the config to adopt it so code matches reality. Either way, bring code and reality back into agreement rather than letting the divergence sit. Prevent recurrence by running scheduled drift detection so out-of-band changes surface deliberately instead of ambushing an unrelated apply, and by restricting console write access in production so changes go through code in the first place.',
      int:{ q:'Why is finding drift inside an unrelated apply a problem?', a:'Because it turns a routine change into a risky one under pressure. You set out to make change A, and the plan suddenly also wants to revert someone&rsquo;s week-old console tweak (change B) &mdash; now you have to decide, mid-deploy, whether reverting B is safe, or you accidentally apply it along with A. Drift discovered this way is a surprise coupling: unrelated changes tangled into your deploy. Scheduled drift detection separates that decision out &mdash; you triage drift calmly on its own, converge or adopt deliberately, so it&rsquo;s resolved before it ever complicates a real change. Detect drift on purpose, not by accident.' } },
    { tag:'CURVEBALL', theme:'Secrets in committed state',
      cue:'Your security team found that your Terraform state, containing database passwords, is committed to the git repo. How bad is it, and what do you do?',
      task:'Explain state-holds-plaintext-secrets, the exposure, and remediation (rotate) + prevention.',
      model:'It&rsquo;s bad: state stores resource attributes in the clear, including generated database passwords, keys, and connection strings, so a committed state file is a plaintext secret store &mdash; exposed to everyone with repo access and preserved forever in git history, even if you delete the file now. Remediate: treat those secrets as compromised and rotate them; remove state from the repo; and purge it from git history. Prevent: move state to a remote encrypted backend with tight access control, add state files to gitignore, and minimize secrets in state going forward &mdash; provision a secret container (Secrets Manager) the app reads at runtime rather than generating secrets in Terraform where they land in state. And restrict who can read state like you would any credential store.',
      int:{ q:'Why can&rsquo;t you just delete the file and move on?', a:'Because git preserves history &mdash; the secrets are in every past commit that included the file, so anyone who&rsquo;s cloned or can access the repo history still has them, and deleting the file in a new commit doesn&rsquo;t remove the old ones. That&rsquo;s why the real remediation is to rotate the exposed secrets (assume they&rsquo;re compromised), then purge the file from history &mdash; and even then, treat rotation as the primary fix because you can&rsquo;t be sure who already saw it. Deleting the file addresses the future but not the exposure that already happened; rotation is what actually closes the hole.' } },
    { tag:'CURVEBALL', theme:'Why this tool',
      cue:'Why did you pick Terraform over CloudFormation, CDK, or Pulumi?',
      task:'Justify tool choice on cloud-scope x language-model x state-ownership, not preference.',
      model:'It depends on three axes, not preference. Cloud scope: all-in on AWS, CloudFormation gives deep AWS integration with AWS-managed state (no state file to run); heterogeneous or multi-cloud, Terraform&rsquo;s huge provider ecosystem and single tool across everything wins. Language model: Terraform and CloudFormation are declarative config; CDK and Pulumi let you write infra in a real language (loops, types, tests) &mdash; better when you need real abstraction, worse when that power hides what actually gets created. State ownership: CloudFormation manages state for you; Terraform (and Pulumi) you own it. For a multi-service AWS estate where I wanted one tool, a big ecosystem, and explicit control of state, Terraform fit &mdash; but I&rsquo;d name the axes and let context decide, and note OpenTofu as the permissively-licensed Terraform-compatible option.',
      int:{ q:'When would a real language (CDK/Pulumi) beat Terraform&rsquo;s HCL?', a:'When your infrastructure genuinely needs abstraction and logic &mdash; looping over complex data structures, sharing typed constructs across teams, unit-testing infra, or reusing your team&rsquo;s existing language skills &mdash; because a general-purpose language expresses those naturally where HCL strains. The flip side is that same power invites cleverness that makes infra unreviewable: with deep inheritance and dynamic logic, you can no longer read the config and see what gets created; you have to run the program. So a real language is better when repetition and abstraction genuinely demand it, but you keep the logic thin so the synthesized infra stays legible &mdash; and the plan/diff is your safety net either way. HCL&rsquo;s constraint is a feature: it stays close to declarative, so the config is the intent.' } },
    { tag:'CURVEBALL', theme:'Why not IaC for the fleet',
      cue:'You built a custom reconciler for your device fleet. Since IaC also does desired-state and drift, why not just point Terraform at the fleet?',
      task:'Mirror the topic-7 boundary from the IaC side: same pattern, but IaC&rsquo;s execution model can&rsquo;t be a live-fleet control loop.',
      model:'Same pattern, wrong execution model. Terraform and the reconciler both declare desired state, diff against actual, and converge &mdash; but Terraform is human-triggered plan/apply against a state file it can read authoritatively, reconciling occasionally at deploy time. A device fleet needs continuous, autonomous reconciliation running constantly, against state the devices self-report (not a readable provider API), with per-device maintenance windows, hierarchical per-tenant resolution, and closed-loop reported-hash confirmation &mdash; none of which Terraform&rsquo;s model provides. Cron-ing terraform plan/apply gives coarse periodic checks, still assumes readable authoritative state, and has no windows or per-device coordination. You&rsquo;d be reimplementing a reconciler badly on top of a deploy-time tool. So: same declarative philosophy, purpose-built engine &mdash; IaC for infrastructure, a custom reconciler for the runtime fleet.',
      int:{ q:'So where&rsquo;s the clean line between the two?', a:'Cadence, autonomy, and how you observe reality. IaC is deploy-time, human-triggered, and occasional, reconciling infrastructure whose state it reads authoritatively from provider APIs, changed rarely by operators. The reconciler is runtime, autonomous, and continuous, reconciling fleet config that devices self-report and that can drift locally at any moment, with domain needs (windows, per-tenant hierarchy, reported-hash confirmation) no IaC tool has. Same converge/diff/drift philosophy on opposite operating points &mdash; which is precisely why one engine can&rsquo;t serve both well, and why building the custom reconciler was the right call rather than stretching Terraform to fit.' } },
    { tag:'CURVEBALL', theme:'Leaky abstraction wall',
      cue:'You used a high-level module for your service, and now you need a config option it doesn&rsquo;t expose. You&rsquo;re stuck. What went wrong, and what do you do?',
      task:'Diagnose a leaky high-level abstraction; use escape hatches or drop a level; choose abstraction by how-standard-the-need-is.',
      model:'You hit the leaky-abstraction wall: a high-level module (or L2/L3 construct) is a joy while its defaults match your needs, but the moment you need something it didn&rsquo;t anticipate, you&rsquo;re stuck &mdash; the abstraction hid the underlying resources and now won&rsquo;t let you reach them. Options: use the module&rsquo;s escape hatches if it exposes overrides for the underlying resource (now you must understand what it generates anyway), contribute the missing input upstream if it&rsquo;s a shared module, or drop to raw resources for this piece where you need full control. The lesson for next time: default to the highest abstraction whose opinions you agree with, but for anything unusual or where you need to control specific details, use lower-level constructs so nothing is hidden. And always let the plan confirm what the abstraction actually produced.',
      int:{ q:'How do you decide which abstraction level to reach for up front?', a:'Match the level to how standard the need is. For well-trodden, standard infrastructure (a normal bucket, a standard service), take a high-level curated construct or shared module &mdash; you get best-practice defaults for free. For anything unusual, security-sensitive, or where you need every generated resource explicit and auditable, use raw resources so nothing&rsquo;s hidden and you can&rsquo;t hit a wall. A healthy codebase mixes levels: high-level for the boring 80%, raw for the special 20%. The anti-patterns are both extremes &mdash; forcing everything through one leaky mega-abstraction, or hand-writing raw resources for things a curated construct does perfectly. And whichever level, the plan is what confirms what actually got created.' } }
  ];
  var mockFrameIdx = mockBeats.findIndex(function(b){ return b.tag === 'FRAME'; });
  var frames = [
    mockBeats[mockFrameIdx].cue,
    'Build the infrastructure-management practice for a multi-environment platform.',
    'Set up infrastructure as code for an AWS estate across dev, staging, and prod.',
    'Design provisioning so infrastructure is reviewable, reproducible, and drift-detectable.'
  ];
  return { cards:IAC_CARDS, speak:IAC_SPEAK, curveballs:curveballs, mockBeats:mockBeats, frames:frames };
})();
