/* topics/iac/drill.js -- topic 8 drill data. LOCAL arrays IAC_CARDS / IAC_SPEAK so loading this
   bundle does NOT clobber topic 1's working set. publishBanks() reseeds the globals from
   TOPIC_IAC_BANK on switch. IAC_SPEAK[i] pairs IAC_CARDS[i]. Grounded in the Invenco AWS estate
   as Terraform/CDK (remote+locked+encrypted state, plan/apply, drift, modules). 7-bit ASCII. */
var IAC_CARDS = [
  { tier:'SDE2', signal:'IaC vs click-ops',
    q:"What does infrastructure as code actually give you over clicking through a cloud console?",
    a:"<b>Reproducibility, review, and drift detection.</b> You declare the desired infrastructure as code, so it&rsquo;s version-controlled, code-reviewed, and reproducible &mdash; the same config builds the same environment every time, and you can stand up a staging clone or a DR region from it. Every change goes through a <b>plan</b> you review before applying, and running plan later <b>detects drift</b> when reality diverges from the code. Clicking is fast for one thing once; it leaves no record, no review, and no way to know what changed.",
    f:[
      { q:"What&rsquo;s specifically wrong with clicking that IaC fixes?",
        a:"Clicking is <b>unrecorded, unreviewable, and unrepeatable</b>. There&rsquo;s no history of who changed what or why, no diff to review before a risky change, and no way to reproduce the environment &mdash; so staging drifts from prod, DR is a hope, and onboarding means &lsquo;click these forty screens.&rsquo; It also invites <b>drift</b> with no way to detect it: a hand-tweaked setting is invisible until it breaks. IaC turns each of those into a solved problem &mdash; git history is the audit log, the PR is the review, the config is the reproducible definition, and plan is the drift check. The console is fine for reading and emergencies; it&rsquo;s a bad system of record." },
      { q:"Is IaC declarative or imperative, and why does that matter?",
        a:"The dominant model is <b>declarative</b> &mdash; you describe the desired end state and the tool figures out how to reach it &mdash; and it matters because declarative gives you <b>idempotence and convergence</b>. You don&rsquo;t write &lsquo;create this, then that&rsquo;; you write &lsquo;this should exist,&rsquo; so applying twice is safe (no-op if already there), and the tool can diff current-vs-desired and make only the needed changes. That&rsquo;s the same converge-to-a-goal property as a reconciler. Imperative provisioning scripts (do step 1, step 2) are order-dependent and fragile to partial completion; declarative infra is robust to re-runs and to the messy reality of what already exists." }
    ],
    senior:"Framing IaC as <b>reproducible + reviewable + drift-detectable declared infrastructure</b> vs unrecorded console clicks &mdash; and tying declarative to idempotence and convergence &mdash; is the conceptual clarity an interviewer wants." },
  { tier:'SDE2', signal:'State is the source of truth',
    q:"What is the state file, and why does the tool need it?",
    a:"State is the tool&rsquo;s <b>record of what it manages</b> &mdash; it maps each config address (<code>aws_dynamodb_table.devices</code>) to a real resource ID and caches the resource&rsquo;s attributes. It&rsquo;s how the tool knows, on the next run, whether a resource in your config already exists (so it updates) or not (so it creates). Without state, the tool can&rsquo;t connect &lsquo;the table in my code&rsquo; to &lsquo;the table in AWS,&rsquo; so it can&rsquo;t compute a correct diff.",
    f:[
      { q:"What happens if you lose the state file?",
        a:"The tool <b>loses track of everything it manages</b>. With no state, it doesn&rsquo;t know your existing resources exist, so a plan wants to <b>create everything from scratch</b> &mdash; which, if you apply, either fails on name collisions or creates duplicate infrastructure alongside the real one. Recovery is painful: you either restore state from a versioned backup (why remote, versioned state matters) or laboriously <b>import</b> every existing resource back into a fresh state by ID. Losing state doesn&rsquo;t lose your infrastructure, but it loses the tool&rsquo;s <i>knowledge</i> of it, which is nearly as bad &mdash; hence state is treated as a precious, backed-up artifact." },
      { q:"Why can&rsquo;t the tool just query the cloud each time instead of keeping state?",
        a:"Partly it can (that&rsquo;s the refresh step), but state exists because <b>querying alone can&rsquo;t answer the key questions</b>. The cloud can tell you what resources exist, but not <i>which config address owns which resource</i> &mdash; there&rsquo;s no reliable link from &lsquo;the table named devices in AWS&rsquo; back to &lsquo;<code>aws_dynamodb_table.devices</code> in my code,&rsquo; especially with many similar resources. State stores that mapping explicitly. It also records <b>what the tool last set</b>, so it can distinguish drift (reality changed) from a config change (intent changed), and it avoids re-querying every attribute of every resource on every run. Pure query has no memory of ownership or intent; state is that memory." }
    ],
    senior:"Describing state as the explicit <b>config-address-to-real-resource mapping</b> that makes the diff possible (not a disposable cache) &mdash; and knowing losing it means import-or-restore &mdash; is the right mental model." },
  { tier:'SDE2', signal:'Plan before apply',
    q:"What&rsquo;s the difference between plan and apply, and why are they separate?",
    a:"<b>Plan is a dry run; apply executes.</b> Plan diffs your config against state and shows exactly what would change &mdash; <span class=\"hl\">+</span> create, <span class=\"hl\">~</span> update, <span class=\"hl\">-</span> destroy &mdash; without touching anything. Apply then executes that plan against the real cloud. The separation is the point: you <b>review the diff before it happens</b>, so a surprise destroy of a production resource is caught in review rather than discovered after. In CI, plan is posted to the PR for a human to approve.",
    f:[
      { q:"Why is the two-phase separation so valuable?",
        a:"Because it makes infrastructure change <b>reviewable before it&rsquo;s real</b> &mdash; the single biggest safety property IaC has. The plan is a precise, machine-generated statement of consequences: not &lsquo;this code looks right&rsquo; but &lsquo;this will create X, modify Y, and destroy Z.&rsquo; Reviewing the <i>plan</i> catches things reviewing the <i>code</i> misses &mdash; a small config edit that turns out to force a database replacement shows up as a destroy in the plan even if the code diff looked innocent. It also enables gated CI: plan on the PR, human approves the diff, apply only after approval. &lsquo;Look before you leap&rsquo; is built into the workflow, so destructive surprises are caught at review, not in production." },
      { q:"What should you actually be looking for when you read a plan?",
        a:"First, <b>destroys and replacements</b> &mdash; any <code>-</code> or <code>-/+</code>, especially on stateful resources (databases, buckets, volumes), because those risk data loss; that&rsquo;s the line that must be intended. Second, <b>blast radius</b> &mdash; is this change touching more than you expected (a change that cascades into recreating dependents)? Third, <b>surprises</b> &mdash; resources changing that your edit shouldn&rsquo;t have affected, which often signals drift or an unintended dependency. Fourth, the <b>summary count</b> (&lsquo;3 to add, 1 to change, 2 to destroy&rsquo;) as a sanity check against what you meant to do. You&rsquo;re reading the plan as a consequences report, hunting for anything destructive or larger than intended." }
    ],
    senior:"Explaining plan/apply as a <b>review-the-diff-before-it-happens gate</b> &mdash; and knowing to hunt the plan for destroys, replacements, and blast radius &mdash; is exactly the operational discipline a senior round checks." },
  { tier:'SDE2', signal:'The resource graph',
    q:"You declare a Lambda that reads a DynamoDB table. How does the tool know to create the table first?",
    a:"From the <b>dependency graph</b>. The reference to the table in the Lambda&rsquo;s config is an <b>edge</b>; the tool parses all such references into a graph and topologically sorts it, so the table is created before the Lambda that depends on it. You never write the order &mdash; you write the <i>relationships</i>, and the tool derives create order (forward), destroy order (reverse), and what can run in <b>parallel</b> (anything independent).",
    f:[
      { q:"How does the graph enable parallelism?",
        a:"Because the graph makes <b>independence explicit</b>. Two resources with no dependency path between them (a DynamoDB table and an unrelated S3 bucket) have no edge, so the tool knows they can be created concurrently &mdash; it walks the graph and provisions everything whose dependencies are already satisfied, in parallel, up to a concurrency limit. Only a genuine dependency (the Lambda needs the table&rsquo;s name) forces serialization. So a large estate of mostly-independent resources provisions in parallel waves rather than one slow sequence, and the parallelism is <i>derived</i> from the declared relationships &mdash; you get it for free by declaring dependencies rather than ordering steps." },
      { q:"What does the tool do with the graph on destroy?",
        a:"It walks the graph <b>in reverse</b>. Since creation goes dependencies-first (table before Lambda), destruction must go dependents-first (Lambda before table) &mdash; you can&rsquo;t delete a resource something still depends on. The same edges that gave create-order give destroy-order simply by reversing them, and the same independence gives parallel destroys. This is why you never hand-script teardown either: the graph knows that to remove the table you must first remove everything referencing it, and it sequences accordingly. Forward for create/update, reverse for destroy &mdash; one graph, both directions." }
    ],
    senior:"Explaining <b>references-as-edges &rarr; topological ordering, parallelism for independents, reverse-order destroy</b> &mdash; declaring relationships instead of steps &mdash; shows you understand why declarative provisioning works." },
  { tier:'SDE2', signal:'Providers',
    q:"How does one tool manage AWS, and also potentially GCP or a SaaS like Datadog?",
    a:"Through <b>providers</b> &mdash; plugins that abstract each target&rsquo;s API. The AWS provider knows how to create / read / update / delete AWS resources; a GCP provider does GCP; there are providers for Cloudflare, Datadog, GitHub, and hundreds more. Your declarative config describes <i>what</i> you want; the provider translates that into concrete API calls for that platform. The core tool does the graphing, planning, and state; the provider does the platform-specific CRUD.",
    f:[
      { q:"What does a provider actually implement?",
        a:"For each resource type it supports, a provider implements the <b>CRUD lifecycle plus a schema</b>: how to <i>create</i> the resource from config, <i>read</i> its current state from the API (for refresh/drift), <i>update</i> it in place when possible, <i>delete</i> it, and crucially, which attribute changes can be done in place versus which <b>force a replacement</b>. It also declares the resource&rsquo;s schema &mdash; its arguments and computed outputs &mdash; so the core tool can validate config and build the graph from references. The provider is the platform expertise; the core tool is platform-agnostic. That split is why the same plan/state/graph engine works across every cloud and SaaS that has a provider." },
      { q:"How does the provider relate to state and plan?",
        a:"The provider is what makes plan and state <i>accurate</i>. During <b>plan</b>, the core tool asks the provider to <b>read</b> each managed resource&rsquo;s real attributes (refresh), compares them to config and state, and uses the provider&rsquo;s knowledge of which changes force replacement to render the diff (<code>~</code> vs <code>-/+</code>). During <b>apply</b>, the provider executes the create/update/delete calls and returns the real IDs and attributes the core writes into <b>state</b>. So the provider supplies the platform-specific truth (what exists, what changed, what a change entails) and the core tool supplies the platform-agnostic machinery (graph, diff, state, orchestration). Neither works without the other." }
    ],
    senior:"Describing the provider as the <b>pluggable per-platform CRUD-and-schema adapter</b> under a common graph/plan/state engine &mdash; and its role in refresh and replacement detection &mdash; is the architecture insight a senior round rewards." },
  { tier:'SDE3', signal:'State locking',
    q:"Two engineers run apply on the same infrastructure at the same time. What goes wrong, and how do you prevent it?",
    a:"Without coordination, <b>they corrupt the state file</b>: both read the same state, each makes changes, and the second write clobbers the first &mdash; leaving state that matches neither reality nor either person&rsquo;s intent. You prevent it with <b>state locking</b>: the backend acquires a lock before apply (for an S3 backend, a DynamoDB lock item), so the second apply blocks until the first releases. One apply at a time, per state &mdash; the same serialize-concurrent-writers discipline as a distributed lock.",
    f:[
      { q:"Why is corrupt state so much worse than a failed apply?",
        a:"Because a failed apply leaves your <i>infrastructure</i> possibly-partial but your <i>records</i> intact &mdash; you re-run and converge. Corrupt <b>state</b> poisons the tool&rsquo;s knowledge itself: it now believes things exist that don&rsquo;t, or doesn&rsquo;t know about things that do, so <i>every subsequent plan is wrong</i> &mdash; it may try to recreate live resources or destroy ones it lost track of. You&rsquo;re no longer converging toward intent; you&rsquo;re operating on a false map of reality, and untangling it means manually reconciling state against the real cloud. A failed apply is a retry; corrupt state is a forensic cleanup. That asymmetry is exactly why locking is non-negotiable for shared state." },
      { q:"What happens if a crash leaves the lock held?",
        a:"The lock is <b>stuck</b> &mdash; the crashed apply never released it, so subsequent applies block, seeing &lsquo;state is locked.&rsquo; The escape is a deliberate <b>force-unlock</b> (with the lock ID), but it must be done carefully: you have to be sure the holding process is genuinely dead and not mid-write, or you re-open the concurrent-corruption window force-unlock was meant to close. Good backends record lock metadata (who, when, which operation) so you can judge whether it&rsquo;s safe. Some use lock leases with expiry to auto-recover; the DynamoDB-lock pattern typically requires the manual force-unlock. The discipline is: force-unlock is a break-glass action, confirmed-dead-holder only &mdash; the same care you&rsquo;d take reclaiming any crashed distributed lock." }
    ],
    senior:"Explaining state locking as <b>mutual exclusion over a shared mutable file</b>, why corrupt state is a forensic (not retry) problem, and the care around force-unlock is the distributed-coordination depth a senior round probes." },
  { tier:'SDE3', signal:'Remote state',
    q:"Why not just keep the state file on your laptop next to the code?",
    a:"Because <b>local state can&rsquo;t be shared, locked, or trusted</b> as a team artifact. The moment a second person runs apply, they have a different (or no) state file, and the two diverge &mdash; each tool thinks different things exist. Local state also isn&rsquo;t locked (concurrent corruption), isn&rsquo;t backed up (a lost laptop is a lost source of truth), and often ends up committed to git with secrets in it. <b>Remote state</b> (S3, Terraform Cloud) gives you one authoritative, versioned, lockable, access-controlled copy the whole team shares.",
    f:[
      { q:"What specifically breaks the first time a second person applies with local state?",
        a:"Their local state <b>doesn&rsquo;t know about the resources the first person created</b>, so their plan wants to create everything again &mdash; colliding with or duplicating live infrastructure &mdash; while the first person&rsquo;s state is now stale about anything the second changed. The two humans are operating from <b>divergent maps of reality</b>, and there&rsquo;s no lock to stop them applying simultaneously and corrupting even that. Infrastructure state is inherently <b>shared</b> &mdash; there&rsquo;s one real cloud &mdash; so it needs one shared record; local state assumes a single operator, which is false the instant a team touches it. That&rsquo;s the moment local state goes from &lsquo;works&rsquo; to &lsquo;actively dangerous.&rsquo;" },
      { q:"Beyond sharing, what does remote state give you?",
        a:"<b>Versioning, locking, durability, access control, and secret hygiene.</b> A versioned backend (S3 with versioning) lets you roll back a corrupted state to a known-good revision. Built-in <b>locking</b> (DynamoDB, or the backend&rsquo;s native lock) prevents concurrent corruption. <b>Durability</b> means state survives a lost laptop. <b>Access control</b> lets you treat state like the sensitive artifact it is &mdash; restrict who can read it, since it holds secrets &mdash; and keep it out of git. Some remote backends also run the apply server-side with audit logging. So remote state isn&rsquo;t just &lsquo;shared local state&rsquo;; it&rsquo;s the whole set of properties that make state safe to operate as a team&rsquo;s source of truth." }
    ],
    senior:"Arguing for remote state as the <b>single shared, versioned, locked, access-controlled source of truth</b> &mdash; and pinpointing that infra state is inherently shared so local state is single-operator-only &mdash; is the operational maturity a senior round wants." },
  { tier:'SDE3', signal:'Drift detection',
    q:"Someone changed a security group by hand in the console. How does IaC surface that, and how do you resolve it?",
    a:"As <b>drift</b>: run <code>plan</code> with no config change and a non-empty diff appears &mdash; the tool refreshes actual state from the cloud, compares it to what state and config say, and shows the manual change as a diff it would make to converge reality back to declared. You resolve it by <b>applying</b> (revert the manual change to match code) or <b>updating the config</b> to adopt it. It&rsquo;s the same declared-vs-actual diff a reconciler runs &mdash; just <b>on demand</b> at plan time, not continuously.",
    f:[
      { q:"How is this the same as a runtime reconciler, and how is it different?",
        a:"<b>Same principle:</b> declared desired state, refresh actual state, diff, converge &mdash; drift is exactly &lsquo;declared &ne; actual,&rsquo; and the fix is to re-apply toward declared, precisely the three-hash reconciler&rsquo;s job. <b>Different cadence and autonomy:</b> IaC drift detection is <b>human-triggered and occasional</b> (someone runs plan, or a scheduled job does), and correction is a human-approved apply; a runtime reconciler is <b>continuous and autonomous</b>, detecting and correcting drift on its own loop against device-reported state. IaC is deploy-time convergence for infrastructure changed rarely by operators; a reconciler is runtime convergence for a fleet changing constantly. Same converge/diff/drift pattern, tuned for opposite cadences &mdash; which is why you&rsquo;d build a custom reconciler rather than cron-ing terraform plan for a live fleet." },
      { q:"How do you catch drift proactively instead of stumbling on it during an unrelated change?",
        a:"Run <b>scheduled drift detection</b> &mdash; a periodic job (or a feature of your IaC platform) that runs plan/refresh against production and alerts if the diff is non-empty, so drift is surfaced on its own rather than discovered mid-deploy when it complicates a real change. Pair that with <b>guardrails that reduce drift at the source</b>: restrict console write access in production (so changes go through code), and use policy to detect out-of-band changes. Proactive detection turns drift from &lsquo;a nasty surprise inside my next apply&rsquo; into &lsquo;an alert I triage deliberately&rsquo; &mdash; and the response is the same converge-or-adopt decision, just made calmly instead of under deploy pressure." }
    ],
    senior:"Placing IaC drift as the <b>plan-time, human-run form of the same declared-vs-actual convergence</b> a reconciler does continuously &mdash; plus scheduled detection and reducing drift at the source &mdash; is the systems-connection a senior round rewards." },
  { tier:'SDE3', signal:'Resource replacement and destroy safety',
    q:"A config change is going to destroy and recreate your production database. Why, and what do you do?",
    a:"Because you changed an <b>immutable attribute</b> &mdash; something the cloud can&rsquo;t alter in place (a DynamoDB key schema, an EC2 AMI, a resource name) &mdash; so the tool must <b>replace</b> the resource: <code>-/+</code> destroy then create. On a stateful resource that&rsquo;s data loss. You <b>catch it in the plan review</b> and don&rsquo;t apply: revert the change if it wasn&rsquo;t intended, or if it&rsquo;s genuinely needed, do a real migration (snapshot, new resource, data copy) instead of a blind replace. Guard critical resources with <code>prevent_destroy</code> and isolate them in their own state.",
    f:[
      { q:"How do you tell a replacement apart from an in-place update in a plan?",
        a:"By the change symbol and the annotation. An in-place update is <code>~</code> (the resource stays, an attribute changes); a <b>replacement</b> is <code>-/+</code> (or &lsquo;must be replaced&rsquo;), and the plan usually names the <b>attribute forcing it</b> &mdash; &lsquo;forces replacement&rsquo; next to the offending field. That annotation is the tell: it&rsquo;s pointing at an immutable attribute you changed. So when you read a plan, a <code>~</code> on a database is usually fine, but a <code>-/+</code> with &lsquo;forces replacement&rsquo; on that same database is the stop-everything line &mdash; the tool is telling you this field can only be changed by destroying and recreating, which on stateful infra means you need a migration, not an apply." },
      { q:"What guards prevent an accidental destroy from ever applying?",
        a:"Layered ones. <code>prevent_destroy</code> lifecycle on critical resources makes any plan that would destroy them <b>fail outright</b> &mdash; a hard stop. <b>State isolation</b> (stateful resources in their own state/module) shrinks blast radius so an apply on app infra can&rsquo;t reach the database. <b>Deletion protection</b> at the cloud level (RDS/DynamoDB deletion protection) is a second line the provider must contend with. And in CI, <b>require explicit approval for any plan containing a destroy</b>, or block auto-apply when destroys are present. Defense in depth: the plan surfaces it, prevent_destroy hard-stops it, isolation contains it, cloud protection backstops it, and CI policy forces a human to consciously approve it. No single accident should be able to delete a production datastore." }
    ],
    senior:"Recognizing forced replacement from an <b>immutable attribute</b>, reading <code>-/+</code> &lsquo;forces replacement&rsquo; in the plan, and layering prevent_destroy + state isolation + deletion protection + CI approval is exactly the production-safety judgment a senior round wants." },
  { tier:'SDE3', signal:'Modules and composition',
    q:"Three environments each need the same VPC-plus-database-plus-cluster setup. How do you avoid copy-pasting it three times?",
    a:"<b>Modules.</b> Package the reusable infrastructure &mdash; the VPC, database, cluster and their wiring &mdash; into a parameterized module, then instantiate it three times with different inputs (CIDR, sizes, environment name). One definition, many instances; a fix or improvement lands everywhere at once. Modules are the composition unit of IaC: they give you DRY, encapsulation (callers use inputs/outputs, not internals), and versioning (pin a module version so environments upgrade deliberately).",
    f:[
      { q:"What&rsquo;s the risk of over-modularizing?",
        a:"You can trade copy-paste for <b>hidden coupling and lost clarity</b>. Too many tiny modules, or deeply nested ones, make the real infrastructure hard to follow &mdash; you chase inputs through five layers to learn what actually gets created &mdash; and a &lsquo;shared&rsquo; module that tries to serve every case grows a thicket of conditional inputs that&rsquo;s worse than duplication. Over-abstraction also creates <b>blast radius</b>: a change to a heavily-reused base module can unexpectedly alter many environments at once. The balance is to modularize at <b>meaningful, stable boundaries</b> (a &lsquo;service&rsquo; or &lsquo;network&rsquo; unit that genuinely repeats), keep module interfaces small and purposeful, and accept a little duplication over a wrong abstraction. DRY is a means, not the goal; clarity and safe change are." },
      { q:"How do you version and share modules safely?",
        a:"Treat modules like <b>versioned libraries</b>: publish them to a registry (or a git repo), tag <b>semantic versions</b>, and have callers <b>pin</b> a version rather than tracking a moving branch &mdash; so an environment upgrades a module deliberately, reviewing the plan diff that upgrade produces, not silently on the next apply. Breaking changes to a module&rsquo;s interface get a major-version bump. This gives you controlled, staged rollout of infrastructure changes across environments (bump dev, verify, then prod) and an audit trail of which environment runs which module version. Unpinned shared modules are how one person&rsquo;s module edit accidentally re-plans everyone&rsquo;s prod &mdash; pinning plus semver makes module upgrades explicit, reviewable events." }
    ],
    senior:"Treating modules as <b>parameterized, versioned, encapsulated composition units</b> &mdash; modularizing at stable boundaries, pinning versions, and preferring a little duplication over a wrong abstraction &mdash; is the design maturity a senior round rewards." },
  { tier:'SDE3', signal:'Secrets in state',
    q:"Is there anything sensitive in the state file, and what do you do about it?",
    a:"Yes &mdash; state stores resource attributes <b>in the clear</b>, and some are secrets: a generated database password, an access key, a private key, a connection string. So an unencrypted state file is effectively a <b>plaintext secret store</b>. The mitigations: <b>encrypt the backend</b> at rest and in transit, lock down access to state like a credential (not everyone who can read code should read state), never commit state to git, and keep genuine secrets in a dedicated secret manager referenced at runtime rather than baked into state where avoidable.",
    f:[
      { q:"Why does a secret end up in state at all?",
        a:"Because state <b>caches every attribute</b> of every managed resource, including the sensitive ones the provider returns. If Terraform creates a database with a generated password, or a resource exposes a private key or a connection string as an attribute, that value is stored in state so the tool can diff it next run. Even &lsquo;input&rsquo; secrets you pass to a resource are recorded. It&rsquo;s inherent to how state works &mdash; it&rsquo;s a full snapshot of resource attributes, and it can&rsquo;t selectively forget the secret ones without losing its ability to detect changes to them. So the secret isn&rsquo;t a leak you can code away; it&rsquo;s a structural property of state that you have to <i>protect</i>." },
      { q:"How do you keep secrets out of state where possible?",
        a:"Prefer <b>indirection over embedding</b>: rather than generating a password in Terraform (which lands in state), store it in a <b>secret manager</b> (AWS Secrets Manager, Vault) and have the application fetch it at <i>runtime</i>, so IaC provisions the <i>secret container</i> and access policy, not the secret value. Where a resource must reference a secret, reference it by <b>ARN/handle</b> rather than value. Use write-only or ephemeral mechanisms the provider offers so sensitive inputs aren&rsquo;t persisted. You can&rsquo;t make state hold <i>zero</i> secrets, but you can minimize which secrets it holds &mdash; and for the rest, encryption plus tight access control is the backstop. Minimize what&rsquo;s in state; protect what has to be." }
    ],
    senior:"Treating state as <b>sensitive-by-default</b> (plaintext secrets) &mdash; encrypt, access-control, keep it out of git, and prefer runtime secret-manager references over embedding &mdash; is the security hygiene a senior round expects." },
  { tier:'SDE3', signal:'Idempotence and apply safety',
    q:"You run apply, it succeeds. You run apply again immediately with no changes. What happens?",
    a:"<b>Nothing &mdash; it&rsquo;s a no-op.</b> Apply is idempotent: it computes the plan, sees state already matches config (empty diff), and makes no changes. That&rsquo;s the declarative property &mdash; you declared a desired state, so re-converging to it when you&rsquo;re already there does nothing. It&rsquo;s also why apply is <b>safe to retry</b>: a partial apply that failed halfway recorded what succeeded in state, so re-running converges from the actual current state rather than redoing completed work or double-creating.",
    f:[
      { q:"How does idempotence make a failed apply recoverable?",
        a:"Because apply <b>records each success in state as it goes</b> and then <b>re-derives the plan from actual state</b> on the next run. If an apply creates 6 of 10 resources and then fails, those 6 are in state; re-running plans against that state, sees 6 already exist (no-op for them) and 4 still missing, and creates just the 4. There&rsquo;s no double-creation of the 6 and no need to manually figure out where it stopped &mdash; the declarative model means &lsquo;make reality match config&rsquo; works from <i>any</i> partial state. Recovery is just &lsquo;run apply again,&rsquo; exactly like a reconciler converging from wherever it currently is. That&rsquo;s the practical payoff of idempotence: partial failure isn&rsquo;t a special case, it&rsquo;s just a starting point to converge from." },
      { q:"What could break idempotence?",
        a:"Non-declarative escape hatches. <b>Provisioners</b> that run imperative scripts on create (a shell command, a local exec) aren&rsquo;t automatically idempotent &mdash; re-running after a partial failure may re-execute or skip them wrongly &mdash; which is why they&rsquo;re a last resort. <b>Non-deterministic config</b> (a value derived from a timestamp or random source without being pinned into state) can make plans perpetually show a diff. And resources whose real state the provider reads <b>inaccurately</b> can produce phantom diffs. The rule is to keep everything as declarative resource definitions the provider can faithfully read and diff, and avoid imperative side effects in the apply path; where you must use a provisioner, make it idempotent yourself. Idempotence is inherent to declarative resources and forfeited by imperative additions." }
    ],
    senior:"Grounding idempotence in <b>declarative diff-and-converge (empty plan when already there, re-derive from partial state)</b> &mdash; and naming imperative provisioners as what forfeits it &mdash; is the correctness reasoning a senior round checks." },
  { tier:'SDE3', signal:'Importing existing resources',
    q:"You have infrastructure that was created by hand, and you want to bring it under IaC. How?",
    a:"<b>Import it into state.</b> Write the config for the existing resource, then use import (a CLI command or an import block) to bind that config address to the <b>real resource&rsquo;s ID</b> &mdash; which records the resource in state without recreating it. After import, a plan should show <b>no changes</b> (config matches reality); if it shows a diff, your config doesn&rsquo;t yet match the real resource, and you adjust config until plan is clean. Import is how you adopt existing infrastructure, or recover after losing state, without destroying and rebuilding.",
    f:[
      { q:"How do you know your imported config is actually correct?",
        a:"A <b>clean plan</b> is the proof. Right after import, run plan: if it reports <b>no changes</b>, your config faithfully describes the real resource &mdash; state, config, and reality all agree. If plan wants to change or replace anything, your config differs from the actual resource (you guessed an attribute wrong, or omitted one the resource actually has), so you refine the config and re-plan until the diff is empty. This iterate-to-empty-plan loop is the whole discipline of import: you&rsquo;re not done when the resource is <i>in</i> state, you&rsquo;re done when the tool agrees your code matches the imported reality &mdash; otherwise your next apply would &lsquo;fix&rsquo; the resource to match your imperfect config, possibly destructively." },
      { q:"Why is import the recovery path when you lose state?",
        a:"Because your <b>infrastructure still exists</b> &mdash; only the tool&rsquo;s <i>record</i> of it is gone &mdash; so recovery means rebuilding that record, not the infrastructure. Import binds each real resource back to its config address in a fresh state, one resource at a time, by ID. It&rsquo;s tedious for a large estate (hence remote, versioned state so you restore a backup instead), but it&rsquo;s the mechanism that lets you reattach code to running resources without the catastrophic alternative &mdash; letting the tool think nothing exists and recreating everything. So import serves two jobs from the same primitive: <b>adopting</b> hand-made resources and <b>reattaching</b> after state loss. Both are &lsquo;this real resource is managed by this config address,&rsquo; recorded in state." }
    ],
    senior:"Explaining import as <b>binding a config address to a real resource ID in state, validated by a clean plan</b> &mdash; serving both adoption and lost-state recovery &mdash; is the operational depth a senior round rewards." },
  { tier:'SDE3', signal:'State layout and blast radius',
    q:"Should all your infrastructure live in one state file? How do you decide?",
    a:"No &mdash; you <b>split state to bound blast radius and contention</b>. One giant state means every apply plans the entire estate (slow), locks everyone out of everything (contention), and a mistake can touch anything (huge blast radius). Split along <b>boundaries of change and risk</b>: separate stateful/critical resources (databases) from churny app infra, separate environments (dev/staging/prod), and separate independently-owned services. Each state is a unit of locking, planning, and blast radius. You wire them together by referencing one state&rsquo;s outputs from another.",
    f:[
      { q:"What are the downsides of splitting into too many state files?",
        a:"<b>Coordination overhead and cross-state coupling.</b> Every split adds a boundary you must wire across &mdash; one state consumes another&rsquo;s outputs (a remote-state data source), so a change to shared foundational infra (the VPC ID, a shared IAM role) ripples through every dependent state, and you have to apply them in the right order. Too many states also fragments the picture: no single plan shows the whole system, and a change spanning several states needs several coordinated applies. So it&rsquo;s a balance &mdash; split enough to bound blast radius and let teams work independently, but not so much that you&rsquo;re orchestrating a dozen interdependent applies for one logical change. Split at <b>real seams</b> (environment, ownership, risk, change-rate), not arbitrarily." },
      { q:"How do split states reference each other?",
        a:"Through <b>published outputs and remote-state data sources</b>. A foundational state (say, networking) declares <b>outputs</b> &mdash; the VPC ID, subnet IDs &mdash; and a dependent state (an application) reads them via a <b>remote state data source</b> pointing at the foundational state&rsquo;s backend. So the application state doesn&rsquo;t hardcode the VPC ID; it looks it up from the network state&rsquo;s outputs at plan time. This creates an explicit, one-directional dependency (app depends on network) and an implied apply order (network first). The cleaner alternative for some values is a shared data source or a registry (SSM Parameter Store) that both states read. Either way, the contract between states is a small set of published outputs, keeping them loosely coupled rather than reaching into each other&rsquo;s internals." }
    ],
    senior:"Treating <b>state as the unit of blast-radius, locking, and plan-time</b> &mdash; splitting by environment/risk/ownership/change-rate and wiring via published outputs &mdash; is the architecture judgment a senior round wants." },
  { tier:'SDE3', signal:'CI/CD for IaC',
    q:"How should infrastructure changes flow through CI/CD?",
    a:"<b>Plan on the PR, apply after approval, from CI &mdash; not from laptops.</b> A change opens a pull request; CI runs <code>plan</code> and posts the diff to the PR, so reviewers approve the <i>plan</i> (actual consequences), not just the code. After merge, CI runs <code>apply</code> &mdash; using CI&rsquo;s credentials and the remote locked state &mdash; so applies are audited, serialized, and consistent, and no one is applying from a personal machine with ad-hoc credentials. Guardrails: block auto-apply on plans containing destroys, require explicit approval, and run policy checks in the pipeline.",
    f:[
      { q:"Why apply from CI rather than a developer&rsquo;s machine?",
        a:"For <b>auditability, consistency, and controlled credentials</b>. A CI-run apply has a clear record &mdash; which commit, approved by whom, produced what &mdash; whereas laptop applies are invisible and unreproducible. CI uses <b>one consistent tool version and one set of scoped credentials</b>, so you don&rsquo;t get &lsquo;works on my machine&rsquo; from version skew or someone&rsquo;s over-broad personal admin keys. It naturally <b>serializes</b> applies through the pipeline (with the state lock as backstop) instead of two engineers racing. And it keeps <b>production credentials out of human hands</b> &mdash; developers propose changes via PR; only the pipeline holds apply rights. Laptop applies undermine every one of those: no audit trail, drifting tool versions, scattered credentials, and no gate. The pipeline is the single, governed path to prod." },
      { q:"What policy checks belong in the pipeline?",
        a:"<b>Policy-as-code</b> gates that run against the plan before apply: guardrails like &lsquo;no publicly-open security groups,&rsquo; &lsquo;all S3 buckets encrypted,&rsquo; &lsquo;instances only from approved types/regions,&rsquo; &lsquo;required tags present,&rsquo; and &lsquo;no destroys of resources tagged critical.&rsquo; Tools like OPA/Conftest or Sentinel evaluate the plan JSON and fail the pipeline on violation, so non-compliant infrastructure can&rsquo;t merge. You&rsquo;d also run <b>static checks</b> (format, validate, a linter like tfsec/checkov for security smells) and <b>cost estimation</b> (flag a change that balloons spend) on the PR. The point is to move compliance and security <b>left</b> &mdash; caught automatically at plan time in review &mdash; rather than discovered in an audit later. Policy-as-code turns &lsquo;we have a rule&rsquo; into &lsquo;the pipeline enforces the rule.&rsquo;" }
    ],
    senior:"Specifying <b>plan-in-PR, gated apply-from-CI on locked remote state, with policy-as-code checks</b> &mdash; audited, serialized, credential-controlled &mdash; is exactly the delivery discipline a senior round rewards." },
  { tier:'SDE3', signal:'Immutable infrastructure',
    q:"What does &lsquo;immutable infrastructure&rsquo; mean, and how does it relate to IaC?",
    a:"<b>Replace, don&rsquo;t mutate.</b> Instead of changing a running server in place (patching and config-editing it over time, which accumulates drift and snowflakes), you build a <b>new</b> artifact (a fresh AMI/image) and replace the old instance wholesale. IaC makes this natural: you change the image reference, plan shows a replacement, and you roll the fleet to the new version &mdash; often blue-green (stand up new, shift traffic, tear down old). Every instance is then identical and reproducible from code, with no in-place history to diverge; the cost is you must handle state and rollout deliberately.",
    f:[
      { q:"Why is immutable better than in-place mutation?",
        a:"Because in-place mutation <b>accumulates hidden state and drift</b> &mdash; each server gets patched, tweaked, and hotfixed on its own timeline, so no two are quite alike (&lsquo;snowflakes&rsquo;), and you can&rsquo;t reliably reproduce or reason about any of them. Immutable replacement makes every instance a <b>fresh build from a versioned artifact</b>: identical, reproducible, and disposable, so &lsquo;what&rsquo;s running&rsquo; is exactly &lsquo;what&rsquo;s in the image,&rsquo; with no local history. That gives clean rollbacks (redeploy the previous image), trivial horizontal scaling (every new instance is identical), and no configuration drift on the box. The trade is you rebuild rather than patch, which is more upfront machinery but eliminates the entire class of &lsquo;works on that server but not this one&rsquo; problems. It&rsquo;s the same &lsquo;converge to a declared artifact&rsquo; philosophy applied to compute." },
      { q:"How does immutable infrastructure interact with stateful resources?",
        a:"You <b>separate the immutable compute from the persistent state</b>. Immutable replacement works cleanly for stateless things (app servers, containers) &mdash; kill and replace freely. But data (databases, volumes, object storage) can&rsquo;t be casually destroyed and recreated, so you keep it in <b>separate, long-lived, non-immutable resources</b> that the disposable compute attaches to. So an immutable app tier reads/writes a stable database tier; you replace app instances at will while the data persists. This is also why state isolation matters (databases in their own state with prevent_destroy): the immutable-replace pattern must never accidentally sweep the stateful layer along with the compute. Immutable for the stateless, carefully-managed persistence for the stateful &mdash; the two coexist by being kept apart." }
    ],
    senior:"Framing immutable as <b>replace-with-a-versioned-artifact (no in-place drift) via IaC + blue-green, with persistent state kept separate</b> is the infrastructure-philosophy depth a senior round rewards." },
  { tier:'Staff', signal:'Tool choice',
    q:"Terraform vs CloudFormation vs CDK vs Pulumi &mdash; how do you choose?",
    a:"By <b>cloud scope, language model, and state ownership</b>. <b>CloudFormation</b>: AWS-only, state managed by AWS (no state file to run), deep AWS integration &mdash; good if you&rsquo;re all-in on AWS. <b>Terraform</b> (and OpenTofu): multi-cloud, huge provider ecosystem, declarative HCL, you own state &mdash; the default for heterogeneous estates. <b>CDK</b>: write infra in a real language (TypeScript/Python) that synthesizes to CloudFormation &mdash; loops, abstractions, types, but AWS-centric. <b>Pulumi</b>: real languages like CDK but multi-cloud with its own engine and state. The axes: single-cloud vs multi, config-DSL vs general-purpose language, and managed vs self-owned state.",
    f:[
      { q:"When is a general-purpose language (CDK/Pulumi) better than a DSL (Terraform HCL), and when worse?",
        a:"<b>Better</b> when your infrastructure needs real <b>abstraction and logic</b> &mdash; loops over complex data, conditionals, shared typed constructs, unit tests, reuse of your team&rsquo;s existing language skills &mdash; because a general-purpose language expresses those naturally where a DSL strains (HCL&rsquo;s loops and conditionals are famously awkward at the edges). <b>Worse</b> when that same power invites <b>too much cleverness</b>: infra code with deep inheritance and dynamic logic becomes hard to review because you can no longer read the config and see what gets created &mdash; you have to <i>run</i> the program to know. A DSL&rsquo;s constraint is a feature: it stays close to declarative, so the plan is legible and the config <i>is</i> the intent. The rule of thumb: reach for a general-purpose language when repetition and abstraction genuinely demand it, but keep the logic thin so the synthesized infrastructure stays reviewable &mdash; the plan/diff is still your safety net either way." },
      { q:"What does OpenTofu change about this decision?",
        a:"OpenTofu is the <b>open-source fork of Terraform</b> created after Terraform&rsquo;s license moved to BSL, and it matters mainly for <b>governance and licensing risk</b> rather than day-to-day mechanics. It&rsquo;s largely compatible (same HCL, same provider model, same state concepts), so choosing it over Terraform is a bet on a community-governed, permissively-licensed tool &mdash; relevant if the BSL terms conflict with how you build or ship, or if you want to avoid single-vendor control. For most teams the technical decision (multi-cloud, HCL, self-owned state) is the same as &lsquo;Terraform,&rsquo; and OpenTofu vs Terraform is a downstream choice about licensing, governance, and which ecosystem you trust long-term. It doesn&rsquo;t change the axes; it adds a permissively-licensed option on the Terraform-compatible side of them." }
    ],
    senior:"Choosing on <b>cloud-scope &times; language-model &times; state-ownership</b> &mdash; and articulating the DSL-vs-general-purpose-language trade (power vs reviewability) plus what OpenTofu&rsquo;s licensing fork changes &mdash; is the breadth a Staff round expects." },
  { tier:'Staff', signal:'Abstraction levels',
    q:"CDK has L1, L2, and L3 constructs. What are they, and what&rsquo;s the trade-off in choosing an abstraction level?",
    a:"<b>L1</b> is raw &mdash; a 1:1 mapping to the underlying CloudFormation resource, full control, no opinions. <b>L2</b> is <b>curated</b> &mdash; a higher-level construct with sensible defaults and convenience methods (an S3 bucket that wires up encryption and policies for you). <b>L3</b> is a <b>pattern</b> &mdash; a whole solution composed of many resources (a load-balanced Fargate service). The trade is <b>convenience vs control</b>: higher levels are faster and encode best practices but hide details and can be <b>leaky</b> (when the default isn&rsquo;t what you need, you fight the abstraction). Same spectrum as Terraform raw-resources vs a curated module vs a full-stack module.",
    f:[
      { q:"What&rsquo;s the danger of a leaky high-level abstraction?",
        a:"That it&rsquo;s <b>easy until it isn&rsquo;t</b> &mdash; a high-level construct is a joy while its defaults match your needs, but the moment you need something it didn&rsquo;t anticipate (a specific network config, a policy tweak, a parameter it doesn&rsquo;t surface), you&rsquo;re stuck: you either accept the opinionated default you didn&rsquo;t want, drop down to escape hatches that partially override its internals (now you must understand what it generates anyway), or abandon it. The abstraction &lsquo;leaks&rsquo; its underlying complexity exactly when you can least afford the surprise. The cost is also <b>hidden magnitude</b>: an L3 pattern might create dozens of resources you didn&rsquo;t explicitly ask for (and pay for), which the plan reveals but the code obscures. High-level constructs trade upfront speed for a risk of a hard wall later &mdash; great for the common case, painful at the edges." },
      { q:"How do you decide which level to reach for?",
        a:"Default to the <b>highest level whose opinions you agree with</b>, and drop lower only where you need control. For standard, well-trodden infrastructure (a bucket, a standard service), an L2/L3 construct or a curated module gives you best-practice defaults for free &mdash; take it. For anything <b>unusual, security-sensitive, or where you need to understand every generated resource</b>, use L1/raw resources so nothing is hidden. A healthy codebase mixes levels: high-level for the boring 80%, raw for the 20% that&rsquo;s special or must be auditable. The anti-patterns are both extremes &mdash; forcing everything through a leaky mega-abstraction, or hand-writing raw resources for things a curated construct does perfectly. Match the abstraction to how standard the need is, and always let the <b>plan</b> confirm what the abstraction actually produced." }
    ],
    senior:"Placing L1/L2/L3 as <b>raw/curated/pattern on a convenience-vs-control axis</b>, naming the leaky-abstraction wall and hidden magnitude, and matching the level to how standard the need is &mdash; that&rsquo;s the abstraction judgment a Staff round rewards." },
  { tier:'Staff', signal:'Multi-environment at scale',
    q:"You have dev, staging, and prod across multiple AWS accounts. How do you structure IaC so they&rsquo;re consistent but isolated?",
    a:"<b>Shared versioned modules, per-environment state and credentials, layered composition.</b> Put the actual infrastructure in <b>versioned modules</b> so all environments build from the same definitions (consistency), and instantiate them per environment with different inputs and <b>separate state per environment/account</b> (isolation &mdash; a prod apply can&rsquo;t touch dev, and blast radius is bounded). Deploy to <b>separate accounts</b> for hard security and billing isolation. Promote changes by <b>version</b>: bump the module in dev, verify, then staging, then prod &mdash; so environments differ only in inputs and module version, never in hand-drift. Layer foundational infra (network, IAM) separately from application infra.",
    f:[
      { q:"Why separate accounts, not just separate state files?",
        a:"Because accounts give <b>hard isolation that state boundaries can&rsquo;t</b>. Separate state prevents an apply from touching another environment&rsquo;s resources, but everything still shares one account&rsquo;s <b>blast radius, quotas, IAM, and billing</b> &mdash; a compromised credential, a runaway resource, or a security misconfiguration can affect the whole account regardless of state layout. Separate <b>accounts</b> give you a real security boundary (prod credentials can&rsquo;t reach dev, and vice versa), independent service quotas (dev can&rsquo;t exhaust prod&rsquo;s limits), clean per-environment cost attribution, and blast-radius containment for security incidents. State isolation is about <i>tooling correctness</i>; account isolation is about <i>security and operational containment</i>. Serious multi-environment setups use both &mdash; separate accounts <i>and</i> separate state within them." },
      { q:"How do you promote a change through environments safely?",
        a:"By <b>version, not by copy</b>. The infrastructure lives in versioned modules; an environment references a specific module version. To promote a change: land it as a new module version, point <b>dev</b> at it and apply, <b>verify</b> (tests, the plan diff, smoke checks), then advance <b>staging</b> to that version, verify again, then <b>prod</b> &mdash; each step a reviewed plan you approve. Because environments differ only in inputs and module version, the change that ran in dev is <i>literally the same code</i> in prod, not a re-implementation &mdash; so you&rsquo;re not hoping prod matches dev, it&rsquo;s the same versioned artifact. This gives a staged rollout with a checkpoint at each environment and an audit trail of which version is where, and it eliminates the &lsquo;prod drifted from staging because someone edited it directly&rsquo; failure that plagues copy-paste environments." }
    ],
    senior:"Structuring scale as <b>shared versioned modules + per-environment/account isolated state + version-promotion</b> &mdash; and distinguishing account isolation (security/containment) from state isolation (tooling correctness) &mdash; is the multi-environment maturity a Staff round wants." },
  { tier:'Staff', signal:'IaC vs a runtime reconciler',
    q:"You built a custom desired-state reconciler for your device fleet. Why not just use Terraform&rsquo;s desired-state and drift for that too?",
    a:"Because Terraform&rsquo;s <b>execution model</b> doesn&rsquo;t fit a live fleet, even though the <b>pattern</b> is identical. Terraform is <b>human-triggered plan/apply against a readable state file</b>, reconciling occasionally at deploy time; a device fleet needs <b>continuous, autonomous</b> reconciliation running constantly, against state the devices <b>self-report</b> (not a readable provider API), with per-device maintenance windows, hierarchical per-tenant resolution, and closed-loop reported-hash confirmation. You&rsquo;d be fighting Terraform to make it autonomous, real-time, and device-feedback-driven. So: <b>same declarative converge/diff/drift philosophy, purpose-built engine</b> &mdash; IaC for deploy-time infrastructure, a custom reconciler for runtime fleet config.",
    f:[
      { q:"What&rsquo;s the shared idea, and what&rsquo;s the dividing line?",
        a:"The <b>shared idea</b> is declarative convergence: declare desired state, diff it against actual, and drive actual toward desired &mdash; with drift as &lsquo;declared &ne; actual&rsquo; and idempotent re-application. Both IaC and the reconciler are that pattern. The <b>dividing line</b> is cadence and autonomy plus how you observe reality. IaC is <b>deploy-time, human-triggered, occasional</b>, reconciling <b>infrastructure</b> whose state it can <b>read authoritatively</b> from provider APIs, changed rarely by operators. The reconciler is <b>runtime, autonomous, continuous</b>, reconciling <b>fleet config</b> whose state is <b>self-reported by devices</b> that can drift locally at any moment, with domain needs (windows, per-tenant hierarchy, reported-hash confirmation) no IaC tool has. Same philosophy; opposite operating points on cadence, autonomy, and observability &mdash; which is why one engine can&rsquo;t serve both well." },
      { q:"Could you just run terraform plan/apply on a cron for the fleet?",
        a:"You could <i>approximate</i> drift detection that way, but it breaks down fast for a live fleet. Cron-ing plan/apply gives you <b>periodic, coarse</b> reconciliation &mdash; not the continuous, event-driven convergence a fleet needs &mdash; and it still assumes Terraform can <b>read authoritative state</b> for each device, which it can&rsquo;t when the truth is device-<i>reported</i> and may differ from any API. It has <b>no per-device maintenance windows</b> (so it&rsquo;d try to reconfigure terminals at the wrong time), no hierarchical per-tenant resolution, no closed-loop reported-hash confirmation, and its single locked state file becomes a scaling and blast-radius problem across tens of thousands of devices. You&rsquo;d be bolting a fleet control loop onto a deploy-time tool and reimplementing everything it lacks. At that point you&rsquo;ve built a reconciler badly &mdash; better to build the purpose-fit one and keep Terraform for the infrastructure it&rsquo;s excellent at." }
    ],
    senior:"Drawing the line as <b>same converge/diff/drift pattern, but IaC = deploy-time-human-readable-infra and the reconciler = runtime-autonomous-device-reported-fleet</b> &mdash; and why cron-ing Terraform doesn&rsquo;t close the gap &mdash; is exactly the build-vs-adapt judgment a Staff round wants." },
  { tier:'SDE3', signal:'Templating and config management (Jinja2/YAML)',
    q:"You&rsquo;ve been describing Terraform-style declarative provisioning. Where do Ansible, Jinja2, and YAML fit &mdash; and how is that different?",
    a:"They&rsquo;re the <b>config-management / templating</b> side of IaC, distinct from Terraform&rsquo;s declarative <i>provisioning</i>. Terraform (HCL) declares desired <b>infrastructure</b> &mdash; VMs, networks &mdash; and reconciles to it; <b>Ansible</b> configures <i>inside</i> machines &mdash; install packages, edit files, run ordered steps &mdash; via <b>playbooks written in YAML</b>, using <b>Jinja2</b> as the templating engine to parameterize them (<code>{{ var }}</code>, <code>{% for %}</code>, conditionals) so one template renders environment-specific config. YAML is the human-readable <i>format</i>; Jinja2 is the <i>templating</i> layer that fills it in.",
    f:[
      { q:"What&rsquo;s the classic pitfall of templating YAML with Jinja2?",
        a:"<b>Jinja2 is a text templater, but YAML is whitespace-sensitive</b> &mdash; you&rsquo;re generating a structured, indentation-significant format by string substitution, so a mis-indented <code>{% for %}</code> block, or an unquoted value YAML reinterprets (the &lsquo;Norway problem&rsquo;: <code>no</code> read as boolean <code>false</code>), silently yields wrong or invalid config. The discipline: template <i>values</i> not structure where you can, quote ambiguous scalars, and validate the <b>rendered</b> YAML (lint / dry-run), not just the template source." },
      { q:"Terraform vs Ansible &mdash; when each?",
        a:"<b>Terraform to provision, Ansible to configure.</b> Terraform stands up the infrastructure (declarative, state-tracked, reconciled); Ansible configures what runs on it (an ordered play of tasks, though its modules aim to be idempotent) with no long-lived state file. Many shops use both &mdash; Terraform for cloud resources, Ansible for in-instance setup &mdash; or drop Ansible entirely for <b>immutable images</b> (bake config into the AMI/container) so there&rsquo;s nothing to configure at runtime and no config drift to manage." }
    ],
    senior:"Placing <b>Jinja2 + YAML (Ansible config-management)</b> against <b>Terraform/HCL declarative provisioning</b> &mdash; naming the template-a-whitespace-sensitive-format pitfall and the &lsquo;provision vs configure&rsquo; split, with immutable images as the way to sidestep runtime config &mdash; shows you know the whole IaC landscape, not one tool." },
  { tier:'Staff', signal:'The whole design',
    q:"Tie it together: how would you set up infrastructure as code for a real platform, and the discipline that makes it safe?",
    a:"<b>Declare infrastructure as a dependency graph; keep state remote, locked, encrypted, and split by blast radius; plan-and-review every change in CI before a gated apply; detect drift on a schedule; and compose with versioned modules across isolated per-environment/account states.</b> The discipline that makes it safe is two rules and a habit: <b>plan before apply</b> (review the diff &mdash; catch every destroy), <b>lock your state</b> (never corrupt the shared source of truth), and <b>treat state as precious and secret</b>. It&rsquo;s the same converge-to-a-declared-goal idea as a reconciler, run at deploy time with a human in the loop &mdash; and the hard parts are state management and catching destructive changes before they&rsquo;re real.",
    f:[
      { q:"If you could keep only three properties of the setup, which three?",
        a:"<b>Declared infrastructure as a diffable graph</b> (the core &mdash; you describe desired state and the tool derives ordering, parallelism, and an idempotent converge; without this it&rsquo;s just scripts). <b>Remote, locked, encrypted state</b> (the source of truth must be shared safely &mdash; locking prevents the corruption that poisons every future plan, encryption protects the secrets it holds; lose this and the tool&rsquo;s knowledge of reality becomes untrustworthy). And <b>plan-review-before-gated-apply</b> (the safety gate &mdash; reviewing the machine-generated diff is what catches a destroy before it&rsquo;s real, which is the single most consequential failure IaC exists to prevent). Those three are a working, safe IaC practice: a declarative graph, a trustworthy shared state, and a review gate on every change. Modules, drift scheduling, and multi-account isolation are the layers that make it scale &mdash; but the spine is declare-graph, protect-state, review-before-apply." }
    ],
    senior:"Compressing to <b>declared-diffable-graph + remote-locked-encrypted-state + plan-review-gated-apply</b> &mdash; naming the irreducible three &mdash; is the systems-level synthesis that lands a Staff signal." }
];
var IAC_SPEAK = [
  "Lead with what IaC buys: <b>reproducible, reviewable, drift-detectable declared infrastructure</b> vs unrecorded, unreviewable console clicks. Version control is the audit log, the PR is the review, the config is the reproducible definition, plan is the drift check. And it's declarative &mdash; you describe the end state, which gives idempotence and convergence, same as a reconciler.",
  "State is the tool's <b>record of what it manages</b> &mdash; it maps each config address to a real resource ID, so it knows on the next run whether to create or update. Without it there's no link from 'the table in my code' to 'the table in AWS,' so no correct diff. Lose it and the tool wants to recreate everything &mdash; which is why it's remote, versioned, and backed up.",
  "Plan is a <b>dry-run diff</b>; apply executes. The separation is the whole safety story &mdash; you review the machine-generated consequences (+ create, ~ update, - destroy) before anything happens, so a surprise destroy is caught in review, not after. In CI the plan goes on the PR and a human approves the diff, not just the code.",
  "The tool builds a <b>dependency graph</b> &mdash; every reference between resources is an edge &mdash; and topologically sorts it: dependencies first, independents in parallel, reverse order for destroy. You declare <i>relationships</i>, not steps, and ordering + parallelism fall out. That's exactly why declarative provisioning works, same as a reconciler converging from a declared goal.",
  "<b>Providers</b> are the pluggable per-platform adapters &mdash; each implements CRUD, a schema, and which changes force replacement, for AWS or GCP or a SaaS. The core tool does graph, plan, and state, platform-agnostic; the provider supplies the platform truth during refresh and apply. That split is why one engine spans every cloud.",
  "<b>Lock the state.</b> Two concurrent applies read the same state, each changes it, and the second clobbers the first &mdash; corrupt state that matches neither reality nor intent, poisoning every future plan. A lock (DynamoDB item for an S3 backend) serializes applies: one at a time, per state. It's the same serialize-concurrent-writers problem as any distributed lock &mdash; and corrupt state is a forensic cleanup, not a retry.",
  "Never keep <b>local state on a team</b> &mdash; the moment a second person applies, their state doesn't know your resources exist and wants to recreate them, and there's no lock to stop concurrent corruption. Remote state (S3, TF Cloud) gives one authoritative, versioned, locked, access-controlled copy. Infra state is inherently shared; local state assumes a single operator, which is false the instant a team touches it.",
  "Drift is a <b>plan-time diff with no config change</b> &mdash; someone edited a resource in the console, and plan shows what it'd do to converge reality back to declared. It's the exact same declared-vs-actual convergence a runtime reconciler runs, just human-triggered and occasional instead of continuous and autonomous. Resolve by re-applying (revert) or updating config (adopt); catch it proactively with scheduled drift detection.",
  "A change to an <b>immutable attribute forces replacement</b> &mdash; -/+ destroy then create &mdash; and on a stateful resource that's data loss. Catch it in the plan: a ~ update is usually fine, but -/+ 'forces replacement' on a database is the stop line. Guard with prevent_destroy, isolate stateful resources in their own state, and require explicit approval for any plan that destroys.",
  "<b>Modules</b> are the composition unit &mdash; parameterized, versioned, encapsulated infrastructure you instantiate many times, so a fix lands everywhere. But modularize at <b>stable, meaningful boundaries</b>, keep interfaces small, pin versions (so environments upgrade deliberately, reviewing the plan), and prefer a little duplication over a wrong abstraction. DRY is a means; clarity and safe change are the goal.",
  "State holds <b>plaintext secrets</b> &mdash; generated passwords, keys, connection strings &mdash; because it caches every resource attribute. So an unencrypted state file is a secret store: encrypt the backend, access-control it like a credential, keep it out of git. And minimize what's in it &mdash; prefer provisioning a secret <i>container</i> (Secrets Manager) that the app reads at runtime over generating the secret in Terraform where it lands in state.",
  "Apply is <b>idempotent</b> &mdash; run it again with no change and the plan is empty, so it's a no-op. That's the declarative property, and it's why apply is retry-safe: a partial apply records successes in state, so re-running converges from the actual current state rather than double-creating. What forfeits idempotence is imperative escape hatches (provisioners running scripts) &mdash; keep the apply path declarative.",
  "<b>Import</b> binds a config address to a real resource's ID in state without recreating it &mdash; how you adopt hand-made infrastructure or reattach after losing state. The proof it's correct is a <b>clean plan</b>: iterate on the config until plan shows no changes, or your next apply would 'fix' the resource to match imperfect config, possibly destructively. In-state isn't done; agree-with-reality is done.",
  "<b>State is the unit of blast radius, locking, and plan time</b> &mdash; so split it. One giant state plans the whole estate, locks everyone out, and lets a mistake touch anything. Split by environment, risk (stateful vs churny), ownership, and change-rate; wire states via published outputs (remote-state data sources). Don't over-split though &mdash; each boundary is a cross-state dependency you must apply in order.",
  "Flow infra changes as <b>plan-in-PR, gated apply-from-CI</b> on locked remote state &mdash; never from laptops. Reviewers approve the plan (real consequences), CI applies with one tool version and scoped credentials so it's audited and serialized, and prod credentials stay out of human hands. Add policy-as-code (OPA/Sentinel) and security/cost checks against the plan, moving compliance left to review time.",
  "<b>Immutable infrastructure</b> is replace-don't-mutate &mdash; build a fresh versioned artifact and swap the instance wholesale (often blue-green) instead of patching a running box that accumulates drift and snowflakes. IaC makes it natural: change the image reference, plan shows a replacement, roll the fleet. Keep <b>persistent state separate</b> from the disposable compute, so replacing app instances never sweeps the database along.",
  "Choose the IaC tool on <b>cloud-scope, language-model, and state-ownership</b>: CloudFormation (AWS-only, AWS-managed state), Terraform/OpenTofu (multi-cloud, HCL, self-owned state &mdash; the heterogeneous default), CDK (real language synthesizing to CloudFormation, AWS-centric), Pulumi (real languages, multi-cloud, own engine). A general-purpose language helps when you need real abstraction, but keep the logic thin so the synthesized infra stays reviewable.",
  "CDK's <b>L1/L2/L3 are raw / curated / pattern</b> on a convenience-vs-control axis &mdash; L1 maps 1:1 to CloudFormation, L2 adds sensible defaults, L3 is a whole solution. Higher levels are faster and encode best practices but are <b>leaky</b>: when the default doesn't fit you hit a wall, and an L3 pattern can create dozens of resources you didn't ask for. Default to the highest level you agree with; drop to raw for the special or security-sensitive.",
  "At scale, <b>shared versioned modules + per-environment/account isolated state + version-promotion</b>: same module definitions everywhere (consistency), separate state and separate accounts per environment (isolation &mdash; prod can't touch dev, hard security/billing boundary). Promote by bumping the module version through dev, staging, prod &mdash; each a reviewed plan &mdash; so environments differ only in inputs and version, never in hand-drift.",
  "Distinguish IaC from a runtime reconciler: <b>same declarative converge/diff/drift pattern, opposite operating points.</b> IaC is deploy-time, human-triggered, occasional, reconciling infrastructure it can read authoritatively; the reconciler is runtime, autonomous, continuous, reconciling fleet config that devices self-report, with windows and per-tenant resolution. Cron-ing terraform doesn't close the gap &mdash; you'd rebuild a reconciler badly. Right pattern, purpose-built engine.",
  "Distinguish the two IaC families: <b>'Terraform declaratively <i>provisions</i> infrastructure with state; Ansible <i>configures</i> inside machines via YAML playbooks templated with Jinja2.'</b> Then the pitfall &mdash; Jinja2 is a text templater but YAML is whitespace-sensitive, so template values not structure and validate the rendered output &mdash; and immutable images sidestep runtime config entirely.",
  "Land the whole thing: <b>declare infrastructure as a diffable graph; keep state remote-locked-encrypted and split by blast radius; plan-and-review every change in CI before a gated apply; detect drift on a schedule; compose with versioned modules across isolated accounts.</b> The irreducible three: a declared graph, a trustworthy shared state, and a review gate on every change &mdash; and the discipline is two rules, plan before apply and lock your state."
];
var TOPIC_IAC_DRILL = {
  cards: IAC_CARDS,
  speak: IAC_SPEAK,
  tierNotes: {
    all:'<b>All four levels, mixed</b> &mdash; the way a real provisioning discussion actually comes at you.',
    SDE2:'<b>Fundamentals under pressure</b> &mdash; IaC vs click-ops, state, plan/apply, the resource graph, providers. The bar is &ldquo;declare desired infra, diff against state, apply the reviewed plan&rdquo;: name what state is and why plan comes before apply.',
    SDE3:'<b>Depth &amp; trade-offs</b> &mdash; state locking, remote state, drift, replacement safety, modules, secrets, idempotence, import, state layout, CI/CD, immutable infra. The bar is &ldquo;plan before apply, lock your state&rdquo;: name the constraint and the failure each choice bounds.',
    Staff:'<b>Systems judgment</b> &mdash; tool choice, abstraction levels, multi-account scale, the reconciler boundary, the whole practice. The bar is &ldquo;a declarative graph, a trustworthy shared state, a review gate&rdquo;: name the model, the state discipline, and where safety under change comes from.'
  }
};
