/* topics/iac/rf.js -- topic 8 red flags. flags[] each {bad (the quoted misstep), note (null
   except the LAST), tell (why it sinks the round), fix (what to say instead)}. Entities only,
   no backslash escapes. 7-bit ASCII. */
var TOPIC_IAC_RF = {
  lead:'The moves that quietly tank an IaC round &mdash; each is a real thing candidates say, why it reads as a no-hire, and the sentence that turns it around.',
  flags:[
    { bad:'&ldquo;We keep the state file on our machines &mdash; or commit it to the repo so everyone has it.&rdquo;',
      note:null,
      tell:'Local state can&rsquo;t be shared, locked, or trusted on a team: the moment a second person applies, their state doesn&rsquo;t know your resources exist and wants to recreate them, with no lock to stop concurrent corruption. Committing it to git is worse &mdash; now the plaintext secrets in state are in version history for everyone. Infra state is inherently shared; local state assumes one operator.',
      fix:'Use a <b>remote backend</b> &mdash; S3, Terraform Cloud &mdash; so there&rsquo;s one authoritative, versioned, locked, access-controlled copy the whole team shares. Say &lsquo;remote, locked, encrypted state, never local or in git&rsquo; &mdash; it&rsquo;s the single most important early decision.' },
    { bad:'&ldquo;We just run apply &mdash; plan slows us down.&rdquo;',
      note:null,
      tell:'Skipping plan throws away IaC&rsquo;s biggest safety property: seeing the consequences before they&rsquo;re real. A small config edit can silently force a destroy-and-recreate on a production database; without reading the plan, you discover that <i>after</i> the data&rsquo;s gone. Apply-without-plan is clicking with extra steps &mdash; you&rsquo;ve given up the review the whole workflow exists to provide.',
      fix:'<b>Always plan before apply</b>, and review the diff &mdash; hunt for destroys, replacements, and blast radius larger than intended. In CI, post the plan to the PR so a human approves the actual consequences, not just the code. The plan is your last chance to catch a destroy before it happens.' },
    { bad:'&ldquo;When we need a quick change, we just tweak it in the console.&rdquo;',
      note:null,
      tell:'Every console change is <b>drift</b> &mdash; the real infrastructure now diverges from the code, invisibly, until it breaks something or complicates an unrelated apply. It&rsquo;s also unrecorded and unreviewed, so you lose the audit trail and reproducibility that were the point of IaC. &lsquo;Just a quick tweak&rsquo; is how the code stops being the source of truth.',
      fix:'<b>Make changes through code</b>, and restrict console write access in production so people can&rsquo;t. Run scheduled <b>drift detection</b> (plan against prod, alert on a diff) so any out-of-band change surfaces deliberately. If an emergency console change happens, immediately reconcile it back into code &mdash; converge or adopt &mdash; so drift never accumulates silently.' },
    { bad:'&ldquo;Whoever needs to make a change just runs apply &mdash; we don&rsquo;t coordinate.&rdquo;',
      note:null,
      tell:'Uncoordinated applies on shared state <b>corrupt it</b>: two applies read the same state, each changes it, and the second write clobbers the first, leaving state that matches neither reality nor intent. And unlike a failed apply (a retry), corrupt state is a forensic cleanup &mdash; it poisons every future plan until you manually reconcile it against the cloud.',
      fix:'<b>Lock the state.</b> A remote backend acquires a lock before apply (a DynamoDB item for S3), so a second apply blocks until the first releases &mdash; one apply at a time, per state. It&rsquo;s the same serialize-concurrent-writers discipline as any distributed lock; corrupt shared state is exactly what it prevents.' },
    { bad:'&ldquo;State&rsquo;s just infra metadata &mdash; it&rsquo;s in the repo so everyone can read it.&rdquo;',
      note:null,
      tell:'State stores every resource attribute <b>in the clear</b>, including secrets &mdash; generated database passwords, access keys, private keys, connection strings. So a state file in the repo (or unencrypted) is a <b>plaintext secret store</b> exposed to everyone with repo access and preserved forever in git history. &lsquo;Just metadata&rsquo; badly underestimates what state contains.',
      fix:'Treat state as a <b>credential</b>: encrypt the backend at rest and in transit, restrict access tightly (not everyone who reads code should read state), and never commit it to git. Minimize what&rsquo;s in it too &mdash; provision a secret <i>container</i> (Secrets Manager) the app reads at runtime rather than generating secrets in Terraform where they land in state.' },
    { bad:'&ldquo;Everything&rsquo;s in one big state file &mdash; it&rsquo;s simpler.&rdquo;',
      note:null,
      tell:'One giant state maximizes <b>blast radius, contention, and plan time</b>: every apply plans the entire estate (slow), locks everyone out of everything (contention), and a single mistake can touch anything &mdash; including production databases sitting next to churny app infra. &lsquo;Simpler&rsquo; upfront becomes &lsquo;one careless apply can take down the whole environment&rsquo; later.',
      fix:'<b>Split state by blast radius</b> &mdash; stateful/critical apart from churny app infra, per environment, per ownership &mdash; so each state is a bounded unit of locking, plan time, and damage. Wire them via published outputs (remote-state data sources). Don&rsquo;t over-split either &mdash; each boundary is a cross-state dependency &mdash; but a single monolith is a liability.' },
    { bad:'&ldquo;The plan said it would destroy and recreate the database, so we let it run.&rdquo;',
      note:null,
      tell:'That&rsquo;s the exact failure the review gate exists to catch, ignored. A <code>-/+</code> replacement on a stateful resource is <b>data loss</b> &mdash; the plan told you, in the clearest possible terms, and applying anyway is a self-inflicted outage. Usually an immutable-attribute change (a key schema, an AMI) forced the replacement, and blindly applying destroys production data to satisfy a config edit.',
      fix:'<b>Stop on any destroy of a stateful resource.</b> Find which immutable attribute forced replacement and revert it, or if the change is genuinely needed, do a real migration (snapshot, new resource, data copy), not a blind replace. Guard critical resources with <code>prevent_destroy</code>, isolate them in their own state, and require explicit approval for any plan containing a destroy.' },
    { bad:'&ldquo;We apply from our laptops with our personal admin credentials.&rdquo;',
      note:null,
      tell:'Laptop applies are <b>unaudited, inconsistent, and over-privileged</b>: no record of which commit was applied by whom, tool-version skew between machines, and everyone wielding broad admin keys directly against production. There&rsquo;s no gate, no serialization beyond the state lock, and a single compromised laptop is a path straight to prod. It undoes the governance IaC is supposed to give you.',
      fix:'<b>Apply from CI, not laptops.</b> Changes flow through PRs; CI runs plan on the PR and apply after approval, using one consistent tool version and scoped credentials &mdash; so applies are audited, serialized, and reproducible, and production credentials stay out of human hands. The pipeline is the single governed path to prod.' },
    { bad:'&ldquo;If the state gets messed up, we just delete it and re-run apply.&rdquo;',
      note:'This is the subtle one &mdash; and the most dangerous, because it treats state like a regenerable cache when it&rsquo;s actually the irreplaceable source of truth, and the mistake feels harmless right up until it destroys production.',
      tell:'Deleting state doesn&rsquo;t reset the tool &mdash; it makes the tool <b>forget every resource it manages</b>. With empty state, the next plan wants to <b>create everything from scratch</b>, colliding with or duplicating your live infrastructure, and an apply can try to recreate resources that already exist or leave you managing duplicates. State isn&rsquo;t a cache the cloud can rebuild; it&rsquo;s the only record of which real resource each config address owns.',
      fix:'<b>Treat state as precious and never disposable.</b> If it&rsquo;s corrupted, <b>restore from a version</b> (why remote, versioned state matters) rather than deleting it; if it&rsquo;s genuinely lost, <b>import</b> each real resource back into a fresh state by ID, then confirm a clean plan. The rule: state is the source of truth &mdash; you back it up and restore it, you don&rsquo;t throw it away and hope the cloud reconstructs your intent.' }
  ]
};
