/* topics/iac/walk.js -- topic 8 walkthrough. steps[] is the provision loop (declare -> init ->
   graph -> plan -> review -> lock -> apply -> state -> drift); modelScript[] is the spoken model
   answer (plain beats, the interviewer .mq line, then the .mbeat.ans -- LAST). Code strings use
   single-backslash \n / \'. 7-bit ASCII. */
var TOPIC_IAC_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"Declare the desired infrastructure",
      flow:'<span class="fb n">resources as code</span><span class="arr">&rarr;</span><span class="fb p">not console clicks</span><span class="arr">&middot;</span><span class="fb t">desired end state</span><span class="arr">&middot;</span><span class="fb a">declare</span>',
      ins:'You write the <b>desired shape</b> of your infrastructure &mdash; resources and their relationships &mdash; as code, not as a sequence of console clicks. The tool figures out how to get there; you declare where &lsquo;there&rsquo; is.',
      code:'<span class="c">// declare resources; references between them become graph edges</span>\n<span class="k">resource</span> <span class="s">"aws_dynamodb_table"</span> <span class="s">"devices"</span> {\n  name     = <span class="s">"devices"</span>\n  hash_key = <span class="s">"device_id"</span>\n}\n<span class="k">resource</span> <span class="s">"aws_lambda_function"</span> <span class="s">"api"</span> {\n  environment { variables = { TABLE = aws_dynamodb_table.devices.name } }  <span class="c">// edge: api needs the table</span>\n}',
      cap:'The reference <code>aws_dynamodb_table.devices.name</code> isn&rsquo;t just a value &mdash; it&rsquo;s a <b>dependency edge</b>. The tool reads it and knows the table must exist before the Lambda, so you never hand-order creation. You describe the resources and their links; the graph and the ordering are derived.' },
    { k:"Step 2 / 9", t:"Initialize providers and backend",
      flow:'<span class="fb n">init</span><span class="arr">&rarr;</span><span class="fb p">download provider plugins</span><span class="arr">&rarr;</span><span class="fb t">configure remote backend</span><span class="arr">&middot;</span><span class="fb a">init</span>',
      ins:'<code>init</code> sets up the working directory: it downloads the <b>provider plugins</b> (the AWS / GCP / etc. API adapters) and configures the <b>backend</b> &mdash; where state lives (a local file, or remote like S3). This is where you point at shared, remote state.',
      deep:'The two things <code>init</code> wires up are the two pluggable seams of IaC. <b>Providers</b> are the abstraction over each cloud&rsquo;s API &mdash; the AWS provider knows how to create / read / update / delete an AWS resource, the GCP provider knows GCP &mdash; so your declarative config is translated into concrete API calls by a plugin, and the same tool spans clouds. The <b>backend</b> decides where the state file lives; choosing a <i>remote</i> backend (S3, a Terraform Cloud workspace) over a local file is the single most important early decision, because it&rsquo;s what makes state shared across a team, lockable, and durable. Getting init pointed at a remote, locked backend from day one is what separates a real IaC setup from &lsquo;works on my laptop&rsquo; &mdash; the alternative, local state, is the first thing that breaks the moment a second person runs apply.' },
    { k:"Step 3 / 9", t:"Build the resource graph",
      flow:'<span class="fb n">parse config</span><span class="arr">&rarr;</span><span class="fb p">dependency graph</span><span class="arr">&rarr;</span><span class="fb t">create / update / delete order</span><span class="arr">&middot;</span><span class="fb a">graph</span>',
      ins:'The tool parses your config into a <b>dependency graph</b> &mdash; every reference between resources is an edge &mdash; and computes a valid create / update / destroy order from it. Independent resources are created in <b>parallel</b>; dependent ones wait.',
      deep:'The graph is the heart of declarative infrastructure, and it&rsquo;s what makes &lsquo;declare, don&rsquo;t script&rsquo; actually work. Because you expressed <i>relationships</i> (the Lambda references the table) rather than <i>steps</i>, the tool can topologically sort the graph: build the VPC before the subnet, the subnet before the instance, the table before the function &mdash; and build everything <i>independent</i> concurrently, so a hundred unrelated resources provision in parallel rather than one-by-one. It also means <b>destroy</b> runs the graph in reverse (tear down the function before the table it depends on), and an <b>update</b> touches only the resources whose config changed plus anything downstream. You never write the order; you write the dependencies, and the order &mdash; forward, reverse, or partial &mdash; falls out of the graph. That&rsquo;s the same reason a reconciler converges from a declared goal: the intent is the relationships, and the execution plan is derived.' },
    { k:"Step 4 / 9", t:"Plan &mdash; compute the diff",
      flow:'<span class="fb n">desired config</span><span class="arr">vs</span><span class="fb p">state</span><span class="arr">&rarr;</span><span class="fb t">+ create &middot; ~ update &middot; - destroy</span><span class="arr">&middot;</span><span class="fb a">dry run</span>',
      ins:'<code>plan</code> is a <b>dry run</b>: it diffs your desired config against the state (what the tool believes exists) and shows exactly what it <i>would</i> do &mdash; <span class="hl">+</span> create, <span class="hl">~</span> update in place, <span class="hl">-</span> destroy &mdash; without touching anything.',
      code:'<span class="c">// terraform plan -- the diff, before any change is made</span>\n  <span class="hl">+</span> aws_lambda_function.worker      <span class="c">// will be created</span>\n  <span class="hl">~</span> aws_dynamodb_table.devices      <span class="c">// billing_mode PAY_PER_REQUEST -&gt; PROVISIONED</span>\n  <span class="hl">-</span> aws_s3_bucket.old_firmware      <span class="c">// will be DESTROYED</span>\n<span class="c">// Plan: 1 to add, 1 to change, 1 to destroy</span>',
      cap:'The plan is the <b>review artifact</b> &mdash; the single most valuable thing IaC gives you over clicking. You read it before anything happens, so a surprise <span class="hl">-</span> destroy on a production table is caught in review, not discovered after. In CI the plan is posted to the pull request; a human approves the diff, not the code alone. &lsquo;What will this change&rsquo; is answered <i>before</i> you change it.' },
    { k:"Step 5 / 9", t:"Review the plan",
      flow:'<span class="fb n">read the diff</span><span class="arr">&rarr;</span><span class="fb p">approve</span><span class="arr">&middot;</span><span class="fb r">- destroy needs the most scrutiny</span><span class="arr">&middot;</span><span class="fb a">gate</span>',
      ins:'Someone <b>reviews the plan</b> before apply &mdash; and the verb that gets the scrutiny is <span class="hl">-</span> <b>destroy</b>. A create is cheap to fix; an in-place update usually is; a destroy (especially of a stateful resource) can be irreversible.',
      deep:'The review gate is where IaC&rsquo;s &lsquo;reviewable&rsquo; promise pays off, and it&rsquo;s mostly about catching <b>destructive changes</b>. Some config edits force a resource to be <b>replaced</b> &mdash; destroyed and recreated &mdash; because the underlying attribute is immutable (renaming a resource, changing an EC2 AMI, altering a DynamoDB key schema). If that resource is stateful, replacement means data loss, so the plan calling out <code>-/+ (destroy then create)</code> on a database is exactly the line a reviewer must catch. Mitigations are part of the discipline: <code>prevent_destroy</code> lifecycle guards on critical resources, a separate explicit approval for any plan that destroys, and splitting stateful resources into their own state so a careless apply elsewhere can&rsquo;t touch them. The plan tells you what will happen; the review is where a human decides whether &lsquo;this destroys the production table&rsquo; is intended or a mistake &mdash; which is the whole reason you look before you apply.' },
    { k:"Step 6 / 9", t:"Lock the state",
      flow:'<span class="fb n">acquire lock (DynamoDB)</span><span class="arr">&rarr;</span><span class="fb p">apply</span><span class="arr">&rarr;</span><span class="fb t">release</span><span class="arr">&middot;</span><span class="fb a">no two applies at once</span>',
      ins:'Before apply mutates state, the tool <b>acquires a lock</b> &mdash; for an S3 backend, a row in a DynamoDB lock table. So two people running apply at the same time can&rsquo;t interleave writes and corrupt the state file. One apply at a time, per state.',
      code:'<span class="c">// remote, locked, encrypted state -- the backend config</span>\n<span class="k">terraform</span> {\n  <span class="k">backend</span> <span class="s">"s3"</span> {\n    bucket         = <span class="s">"acme-tfstate"</span>\n    key            = <span class="s">"platform/prod.tfstate"</span>\n    encrypt        = <span class="k">true</span>              <span class="c">// state holds secrets -- encrypt at rest</span>\n    dynamodb_table = <span class="s">"tf-locks"</span>        <span class="c">// lock table: serialize applies</span>\n  }\n}',
      cap:'The lock is the same coordination problem as the reconciler&rsquo;s per-tenant lock: <b>concurrent writers corrupt shared state</b>, so you serialize them. Without it, two simultaneous applies read the same state, each makes changes, and the second write clobbers the first &mdash; leaving state that matches neither reality nor intent. The DynamoDB table holds a lock item for the duration of an apply; a second apply blocks until it&rsquo;s released (or is force-unlocked, carefully, if a crash left it held).' },
    { k:"Step 7 / 9", t:"Apply the plan",
      flow:'<span class="fb n">execute in graph order</span><span class="arr">&rarr;</span><span class="fb p">parallel where safe</span><span class="arr">&rarr;</span><span class="fb t">write real IDs to state</span><span class="arr">&middot;</span><span class="fb a">apply</span>',
      ins:'<code>apply</code> executes the reviewed plan: it makes the actual API calls in dependency order (parallel where the graph allows), and as each resource is created, it <b>records the real resource ID in state</b> &mdash; the mapping from your config to the thing that now exists.',
      deep:'Apply is where intent becomes reality, and the easy-to-miss part is that it <b>writes back to state as it goes</b>. Creating an AWS resource returns an ID (an ARN, a table name, an instance ID); the tool stores that ID in state, bound to the config address (<code>aws_dynamodb_table.devices</code>), so next time it knows <i>which</i> real resource that config manages. This is what makes apply <b>idempotent</b>: run it again with no config change and the plan is empty (state says everything already exists as declared), so nothing happens &mdash; the same declarative, converge-to-goal property as a reconciler. It&rsquo;s also why a mid-apply crash is recoverable: the resources that succeeded are recorded in state, so the next apply picks up from the actual current state rather than redoing everything. Apply isn&rsquo;t a script that must run start-to-finish; it&rsquo;s a convergence step that drives real infrastructure to match config and records what it did.' },
    { k:"Step 8 / 9", t:"State is the source of truth",
      flow:'<span class="fb n">config</span><span class="arr">&harr;</span><span class="fb p">state</span><span class="arr">&harr;</span><span class="fb t">real resources</span><span class="arr">&middot;</span><span class="fb r">state knows what exists &middot; encrypt it</span>',
      ins:'<b>State is how the tool knows what exists.</b> It maps each config address to a real resource ID and caches the resource&rsquo;s attributes. Lose it, or let it drift from reality, and the tool no longer knows what it manages &mdash; so state is remote, versioned, and <b>encrypted</b> (it holds secrets).',
      deep:'State is the most important and most dangerous artifact in IaC. It&rsquo;s the <b>single source of truth</b> for the config-to-reality mapping: without it, the tool can&rsquo;t tell whether a resource in your config already exists (and needs updating) or not (and needs creating), so a lost state file can mean the tool tries to <i>recreate</i> infrastructure that&rsquo;s already there. That&rsquo;s why it&rsquo;s remote and versioned (a team shares one authoritative copy, and you can roll back a corrupted one) and locked (no concurrent corruption). And it&rsquo;s <b>sensitive</b>: state stores resource attributes in the clear, including secrets like generated passwords and keys, so an unencrypted state file is a plaintext secret store &mdash; encrypt the backend, restrict access to it like a credential. The operational rule is simple: treat state as precious and private &mdash; remote, locked, versioned, encrypted &mdash; because everything the tool does depends on it being correct and safe.' },
    { k:"Step 9 / 9", t:"Detect drift",
      flow:'<span class="fb n">plan against reality</span><span class="arr">&rarr;</span><span class="fb p">declared vs actual</span><span class="arr">&rarr;</span><span class="fb t">someone clicked in the console</span><span class="arr">&middot;</span><span class="fb a">the reconciler tie</span>',
      ins:'Run <code>plan</code> when nothing in your config changed and a non-empty diff means <b>drift</b> &mdash; the real infrastructure no longer matches the declared state, usually because someone changed it by hand in the console. IaC detects drift the same way a reconciler does, just on demand.',
      code:'<span class="c">// terraform plan with NO config change -- yet a diff appears = drift</span>\n  <span class="hl">~</span> aws_security_group.api\n      ingress:  <span class="c">// changed outside of Terraform (a port opened in the console)</span>\n<span class="c">// apply to converge reality back to declared, OR update config to adopt the change</span>',
      cap:'This is the <b>same desired-state / converge pattern as the reconciler</b> &mdash; declared vs actual, diff, converge &mdash; but <b>deploy-time and human-run</b> rather than continuous and autonomous. Drift here is caught when someone runs plan (or a scheduled drift-detection job), and you resolve it by re-applying (converge reality back to config) or updating config to adopt the manual change. Same principle as topic 7; different cadence &mdash; which is exactly why you&rsquo;d build a custom reconciler for a live fleet instead of leaning on plan / apply.' }
  ],
  modelScript: [
    { ml:'Frame it', t:'"The problem is managing cloud infrastructure &mdash; VPCs, databases, functions, IAM &mdash; reproducibly and reviewably, not by clicking through a console. So I declare the desired infrastructure as code and let the tool converge reality to it."' },
    { ml:'Declare as a graph', t:'"You write resources and their relationships; the tool builds a dependency graph and derives the create / update / destroy order &mdash; independent resources in parallel, dependent ones ordered. You declare where, not how."' },
    { ml:'State and locking', t:'"State is the source of truth &mdash; it maps your config to real resource IDs so the tool knows what exists. It has to be remote, locked so two applies don&rsquo;t corrupt it, and encrypted because it holds secrets."' },
    { ml:'Plan before apply', t:'"Apply is two-phase: plan computes the diff &mdash; what will create, change, or destroy &mdash; and you review it before executing. In CI the plan is posted to the PR and a human approves the diff, so a surprise destroy is caught before it happens."' },
    { ml:'Drift, and the reconciler tie', t:'"And the same diff against reality detects drift &mdash; declared vs actual, when someone clicked in the console. That&rsquo;s the same converge pattern as a runtime reconciler, but deploy-time and human-run rather than continuous."' },
    { mq:'Interviewer: "A plan shows it&rsquo;s going to destroy and recreate your production database because someone edited the config. You&rsquo;re about to apply. What do you do?"' },
    { ml:'Answer the destroy', t:'"I stop &mdash; a destroy-and-recreate on a stateful resource is data loss, and catching that is exactly what the review gate is for. The plan calling out &lsquo;-/+ replace&rsquo; on the database is the line you catch before apply. Concretely: I don&rsquo;t apply; I find which config change forced replacement &mdash; usually an immutable attribute like a key schema &mdash; and either revert it, or if the change is genuinely needed, plan a real migration (snapshot, new resource, data copy), not a blind replace. And critical stateful resources should carry a prevent_destroy guard and live in their own state so a careless apply can&rsquo;t reach them. The plan told me what would happen; the whole point is that I looked before I applied."' },
    { ml:'Land it', t:'"So: declare infrastructure as a graph, keep state remote-locked-encrypted, plan-and-review before every apply, and treat drift as the same converge problem a reconciler solves. The discipline is two rules &mdash; plan before apply, lock your state &mdash; and knowing the plan is your last chance to catch a destroy before it&rsquo;s real."', ans:true }
  ]
};
