/* topics/eav/bank.js -- topic 6 working-set bank (IIFE). Builds mockBeats (6, tagged
   FRAME/STRUCTURE/SCALE/FAILURE/CURVEBALL/CLOSE), derives curveballs (8, curve[0] === the
   CURVEBALL mockBeat, 8 distinct themes) and frames (4, frame[0] === the FRAME mockBeat cue),
   and aliases the LOCAL EAV_CARDS / EAV_SPEAK so a switch reseeds the globals without
   clobbering topic 1. Entities only. 7-bit ASCII. */
var TOPIC_EAV_BANK = (function(){
  var mockBeats = [
    { tag:'FRAME',
      cue:'Design a per-device attribute store.',
      task:'Frame the boundary and the two tables before any detail &mdash; move from &lsquo;config that outgrows migrations&rsquo; to &lsquo;attributes as data,&rsquo; not straight to a schema.',
      model:'I&rsquo;d frame it as the boundary between a fixed schema and per-device config that changes faster than migrations can keep up &mdash; 50,000 devices, many types, product adding settings constantly. So attributes become data: a definition table (the shared contract &mdash; name, type, default, JSON-Schema, flags) and a value table of sparse per-entity overrides, resolved COALESCE(override, default). A new setting is a row, not a migration &mdash; and I&rsquo;d name the EAV tax as the deliberate cost.',
      int:{ q:'Why not just add columns as settings come up?', a:'Because the config surface grows constantly and varies by device type &mdash; a column per setting means a migration and deploy each time, and a devices table full of sparse nullable columns. Modeling attributes as data moves &lsquo;add a setting&rsquo; from a schema change to an insert. The cost, paid deliberately, is that the DB no longer knows a device&rsquo;s shape, so I enforce typing and reconstruct the object myself.' },
      int2:{ q:'What&rsquo;s the single biggest risk you&rsquo;re taking on with this design?', a:'The query tax &mdash; reconstructing an entity is a pivot, and multi-attribute filtering is self-joins. EAV is structurally worse at exactly what a relational schema is best at. I mitigate with fetch-all-then-pivot, opt-in searchable indexes, and caching &mdash; and I keep EAV for the sparse, variable long tail, promoting hot attributes to real columns.' } },
    { tag:'STRUCTURE',
      cue:'Walk me through it &mdash; definition to resolved value.',
      task:'Narrate the flow end to end: define an attribute, set an override, validate, resolve. A clean pipeline, not a pile of tables.',
      model:'A definition row declares the attribute &mdash; type, default, JSON-Schema, flags. Setting a device&rsquo;s value is an upsert into the value table, unique on (entity, attribute), so overrides are sparse. On write, the value is coerced to the type and JSON-Schema-validated &mdash; rejected if bad. Reading is COALESCE(override, default) over a left join; most attributes resolve straight to the default. To hand back a whole device, I fetch all its value rows in one query and pivot once.',
      int:{ q:'Where exactly does validation happen, and why there?', a:'At the write path, once &mdash; coerce to type, check the schema, reject bad values. Because the value column is generic, the DB can&rsquo;t enforce &lsquo;positive integer&rsquo; for me, and validate-on-read would push the check to every consumer and still let garbage sit in the table. Write-once, read-many: enforce once, and every reader trusts the store.' } },
    { tag:'SCALE',
      cue:'50,000 devices, 200 attributes &mdash; where does this strain, and what breaks first?',
      task:'Reason about the row explosion, the pivot, and multi-attribute queries at fleet scale. Name the number that becomes the ceiling.',
      model:'Entities &times; attributes is 10 million potential rows &mdash; but sparse overrides mean I only store deviations, so the table tracks how much devices differ from defaults, a fraction of that. What strains is querying: reconstructing one entity is fine as a single pivot, but a list view of hundreds of devices&rsquo; full configs on every page load compounds, and filtering by several attributes is self-joins. The ceiling is the pivot/query path, not storage &mdash; so I cache reconstructed configs (CDC-invalidated) and index only the searchable attributes.',
      int:{ q:'The pivot query is your hot path. How do you keep it fast?', a:'Cache the resolved config per entity, invalidated by CDC &mdash; entity-level when an override changes, definition-level (fanning out to all non-overriding entities) when a default changes, with a TTL backstop. Most check-ins then never pivot. And sparse overrides plus cached definitions keep even a miss cheap.' },
      int2:{ q:'A default change invalidates a huge number of cached entities at once. Problem?', a:'Yes &mdash; it&rsquo;s a mass-invalidation / thundering-herd risk: every non-overriding entity re-resolves on its next read. I re-warm proactively rather than waiting for misses, stagger the invalidation, and roll the default change out gradually rather than globally &mdash; which limits both the behavioral blast radius and the cache re-warm spike.' } },
    { tag:'FAILURE',
      cue:'A stringly-typed comparison silently returned the wrong devices in production. Walk the incident.',
      task:'Diagnose a real EAV failure &mdash; a value stored as a string breaking a comparison &mdash; and show the fix at the right layer.',
      model:'The symptom: a query filtering &lsquo;version &gt; 10&rsquo; returned wrong devices because the value was stored as text, so <code>&quot;9&quot; &gt; &quot;10&quot;</code> lexicographically. Root cause: values weren&rsquo;t coerced to their type on write &mdash; a generic column held string representations, so numeric comparisons were lexicographic. The fix is at the write path: coerce to the definition&rsquo;s data_type on write (store the integer, not &quot;30&quot;), backfill-migrate the existing string values to typed, and add a test that comparisons on typed attributes behave. The deeper fix is that validate-and-coerce-on-write is the invariant that would have prevented it.',
      int:{ q:'How do you clean up the values already stored as strings?', a:'A migration that coerces existing value rows to their attribute&rsquo;s type &mdash; validating the whole set first (a dry run) to find values that won&rsquo;t coerce, then migrating the coercible ones and quarantining the rest for manual fix. I can&rsquo;t silently drop or corrupt them, so the uncoercible exceptions are surfaced, not swallowed.' },
      int2:{ q:'How do you stop this class of bug from recurring?', a:'Make coercion-on-write non-optional and gate it: every write coerces to the type and rejects what can&rsquo;t, and CI carries a property test that typed attributes compare, sort, and range-filter correctly. The invariant &lsquo;the store only holds typed, valid values&rsquo; is enforced at the one write path and verified in the gate, so a stringly-typed value can&rsquo;t re-enter.' } },
    { tag:'CURVEBALL',
      theme:'Multi-attribute query explosion',
      cue:'Product wants to filter devices by three attributes at once and sort by a fourth. Show me that query &mdash; and whether EAV was right.',
      task:'Handle the hardest EAV query honestly: multiple self-joins, indexes help each leg but not the joins, and the judgment call about columns.',
      model:'That&rsquo;s the EAV tax at its sharpest. Each attribute is its own row, so three filters are three self-joins on the value table, plus a join for the sort attribute. If those attributes are searchable, each condition is an index seek, so the legs are fast &mdash; but combining them is still self-joins the planner can struggle with. It works, but honestly: if a <i>fixed</i> set of attributes is filtered and sorted this constantly, they&rsquo;ve outgrown the long tail &mdash; I&rsquo;d promote them to real columns, where multi-column filtering is a normal indexed query.',
      int:{ q:'So was EAV the wrong choice here?', a:'Not for the store as a whole &mdash; but wrong for <i>these</i> attributes. EAV is right for the sparse, variable, rarely-queried tail; these are hot, fixed query dimensions that belong in columns. The mature answer is a hybrid: keep EAV for the variable rest, promote the constantly-queried few to columns, and govern that promotion by measured usage. Forcing everything into one model &mdash; all EAV or all columns &mdash; is the mistake.' } },
    { tag:'CLOSE',
      cue:'Two sentences &mdash; sell me the design.',
      task:'Compress the whole store to its spine and its governing judgment, no hedging.',
      model:'A per-device attribute store: typed definitions plus sparse per-entity overrides, resolved COALESCE(override, default), validated on write, with secrets encrypted-and-masked and searchable attributes on a composite partial index &mdash; so product adds config without a migration while typing and querying stay under control. The hard part isn&rsquo;t the storage; it&rsquo;s knowing which attributes belong in EAV and which have earned real columns &mdash; a hybrid, governed deliberately.',
      int:{ q:'If you had to cut one property to ship, what goes?', a:'Attribute groups and the staging UI go first &mdash; real, but not core. What I&rsquo;d never cut is the definition/value split, validate-on-write, and COALESCE resolution: a typed contract, enforced values, deterministic reads. Those three are a correct attribute store; searchability, secrets, and CDC are the scale layers on that spine.' } }
  ];
  var mockCurveIdx = mockBeats.findIndex(function(b){ return b.tag === 'CURVEBALL'; });
  var curveballs = [
    mockBeats[mockCurveIdx],
    { tag:'CURVEBALL', theme:'EAV creep / over-application',
      cue:'Your team started modeling every new field as an attribute, even ones you filter on constantly. Is that a problem?',
      task:'Diagnose over-application: hot structured data hiding in attribute rows, paying the tax for unused flexibility, and the governance fix.',
      model:'Yes &mdash; that&rsquo;s EAV creep: structured, hot, queried data hiding in attribute rows, paying the full tax (pivots, self-joins, self-enforced typing) for flexibility it never uses. The symptom is reimplementing a relational database on top of EAV &mdash; indexes and caches to make rows behave like columns. The fix is governance: new fields default to real columns unless genuinely sparse and variable, and a measured promotion loop graduates hot-and-stable attributes out of EAV. EAV for the long tail, columns for the core.',
      int:{ q:'How do you decide the boundary in practice?', a:'By stability and query-frequency, measured. An attribute that&rsquo;s densely set, frequently filtered or sorted, and stable is a promotion candidate &mdash; the data says it outgrew the tail. Sparse, variable, rarely-queried attributes stay EAV. It&rsquo;s a hybrid with a feedback loop, not a one-time choice.' } },
    { tag:'CURVEBALL', theme:'Schema evolution / type change',
      cue:'You need to change an attribute from string to int, and change another&rsquo;s default. What happens?',
      task:'Show that the definition edit is trivial but existing-value migration and default blast-radius are the real work.',
      model:'The definition change is one row &mdash; trivial. The danger is the existing values: changing the type doesn&rsquo;t retroactively coerce stored value rows, and changing a default silently changes the resolved value for every non-overriding device. So the type change needs a validate-then-migrate pass on existing values (coerce the coercible, quarantine what won&rsquo;t), and the default change is a fleet-wide behavior change I&rsquo;d stage and roll out, not flip. The migration problem moved from the schema to the data &mdash; it didn&rsquo;t disappear.',
      int:{ q:'The default change affects every non-overriding device. How do you do it safely?', a:'Treat it like a config deploy: know the blast radius (every entity without an override), canary a subset, watch, expand &mdash; and create explicit overrides for devices that need the old value before moving the default. And expect it to mass-invalidate caches, so re-warm or stagger.' } },
    { tag:'CURVEBALL', theme:'Secret leak',
      cue:'A secret attribute &mdash; an API key &mdash; showed up in plaintext in an API response and a log. Walk it.',
      task:'Diagnose a secret handled like a config flag, and fix it with encrypt-at-rest plus mask-at-API at the right layers.',
      model:'The failure: a secret attribute was read through the general path, which returned the raw value, and it landed in a log. Root cause: the secret wasn&rsquo;t routed down the protected path &mdash; it was stored and read like a config flag. The fix is two controls at two layers: flag it is_secret so it&rsquo;s KMS-encrypted at rest (a dump doesn&rsquo;t leak it) and masked at the API (reads return a placeholder, write-only from outside), with decryption narrowed to the authorized systems that actually use it. Then audit logs for anywhere it may already have leaked, and rotate the key.',
      int:{ q:'Why isn&rsquo;t encrypting it at rest enough?', a:'Because encryption protects data at rest &mdash; a dump, disk access &mdash; but the leak was through a legitimate read path returning plaintext. Masking protects data in use: the read never returns the value. A secret is attacked both at rest and in transit out, and each control covers a hole the other doesn&rsquo;t &mdash; you need both.' } },
    { tag:'CURVEBALL', theme:'CSV poisoning / bad bulk import',
      cue:'An operator pasted a CSV that wrote thousands of malformed values across the fleet in one go. How was that possible, and how do you prevent it?',
      task:'Treat the CSV as an untrusted payload: bounds, per-cell validation, and an all-or-nothing failure contract.',
      model:'It was possible because the import was unbounded and unvalidated &mdash; a user-supplied file treated as trusted, written straight in. Prevention is bounds plus per-cell validation: cap the import (500 rows, 5 MB), coerce and validate every cell against its attribute&rsquo;s definition exactly like a single write, and reject the batch with located errors rather than half-applying. Large changes run as many bounded, reviewable batches. A CSV is an untrusted payload; it goes through the same validate-on-write gate as any other value.',
      int:{ q:'Row 300 of 500 is invalid. Import the valid ones, or reject all?', a:'Prefer all-or-nothing per batch with a clear report, or at minimum a precise itemized account &mdash; never a silent partial. A config import that half-applies leaves the fleet in a state nobody chose. Validate the whole batch first, reject on any bad row with row-and-column errors, and let the operator fix the source and re-run cleanly.' } },
    { tag:'CURVEBALL', theme:'Default-change blast radius',
      cue:'Someone changed a definition default and half the fleet&rsquo;s behavior shifted instantly. What went wrong?',
      task:'Show that a one-row default edit is a fleet-wide config deploy, and make the fleet-wide effect visible and gradual.',
      model:'The change was treated as a trivial one-row edit, but its effect is on every device resolving to that default &mdash; potentially the whole fleet &mdash; and it flipped globally at once. What went wrong is thinking about the write, not the blast radius. A default change is a fleet-wide config deployment: know who&rsquo;s affected (every non-overriding entity), stage and roll it out (canary, watch, expand), create explicit overrides for devices that need the old value, and expect a cache re-warm spike. The mitigation is process, not schema &mdash; treat config changes like deploys.',
      int:{ q:'How would you make this hard to do accidentally?', a:'Gate default changes behind the same staged, rolled-out path as any config change &mdash; not a direct edit &mdash; with a preview of the blast radius (how many entities resolve to this default) before applying. Make the fleet-wide effect visible and the rollout gradual by default, so &lsquo;flip a default globally and instantly&rsquo; isn&rsquo;t a one-click action.' } },
    { tag:'CURVEBALL', theme:'Concurrent override writes',
      cue:'Two operators set the same device&rsquo;s attribute at the same time. What happens, and is it correct?',
      task:'Reason about the upsert on the unique (entity, attribute) row, last-write-wins, and when optimistic locking is needed.',
      model:'Because the value table is unique on (entity, attribute) and the write is an upsert (ON CONFLICT DO UPDATE), the two writes serialize at the row &mdash; last-write-wins, no duplicate rows, no corruption. That&rsquo;s correct for a simple override, but &lsquo;last write silently wins&rsquo; can lose an update if both operators think they set it. If that matters, add optimistic concurrency &mdash; a version on the value row, and the write fails if the version moved, so the second operator sees the conflict rather than silently clobbering. And staged-then-promote helps: prepare and review a set, promote atomically, rather than racing live writes.',
      int:{ q:'When is last-write-wins not good enough?', a:'When a lost update has real consequences &mdash; two operators making different, intentional changes where silently keeping only one is wrong. Then optimistic locking (a version check) surfaces the conflict so the second write is rejected and reconciled, instead of the last writer unknowingly overwriting the first. For low-stakes flags, last-write-wins is fine; for meaningful config, make the conflict visible.' } },
    { tag:'CURVEBALL', theme:'Cross-tenant attribute bleed',
      cue:'In a multi-tenant deployment, a query returned one tenant&rsquo;s device attributes to another. How?',
      task:'Diagnose a missing tenant scope on the value query, and make the isolation structurally enforced and gated.',
      model:'Almost certainly a value query missing its tenant scope &mdash; the same class as a missing WHERE tenant_id in the authorization topic, applied to entity_value. Value rows must be tenant-scoped so one tenant can never read or write another&rsquo;s attributes, and that scope is part of every query, not an afterthought. The fix: enforce tenant scoping at the data-access layer (row-level security, or a mandatory tenant filter every query inherits), plus a cross-tenant test in CI that fires as tenant A and asserts zero visibility into tenant B. Definitions can be global or per-tenant, but values are always scoped.',
      int:{ q:'How do you make this class of bug structurally impossible, not just fixed?', a:'Push the tenant filter below where a developer writes queries &mdash; row-level security in the database, or a repository layer that injects the tenant predicate on every read and write so it can&rsquo;t be forgotten &mdash; and gate it with a cross-tenant isolation test in CI. When the scope is enforced by the framework and verified by the gate, a missing WHERE tenant_id can&rsquo;t reach production.' } }
  ];
  var mockFrameIdx = mockBeats.findIndex(function(b){ return b.tag === 'FRAME'; });
  var frames = [
    mockBeats[mockFrameIdx].cue,
    'Design a system that lets product add per-device settings without a schema migration.',
    'Model config that varies by device type and firmware across a large fleet.',
    'Store and resolve per-entity attributes where most entities use the defaults.'
  ];
  return { cards: EAV_CARDS, speak: EAV_SPEAK, curveballs: curveballs, mockBeats: mockBeats, frames: frames };
})();
