/* topics/eav/drill.js -- topic 6 drill data. LOCAL arrays EAV_CARDS / EAV_SPEAK so
   loading this bundle does NOT clobber topic 1's working set. publishBanks() reseeds the
   globals from TOPIC_EAV_BANK on switch. EAV_SPEAK[i] pairs EAV_CARDS[i]. Grounded in the
   ICS device-attribute store (definition/value EAV, COALESCE resolution). 7-bit ASCII. */
var EAV_CARDS = [
  { tier:'SDE2', signal:'Rows not columns',
    q:"Why store device config as attribute rows in an EAV table instead of columns on a devices table?",
    a:"Because the config surface <b>grows faster than schema migrations can keep up</b>. With many device types and firmwares, product adds settings constantly, and a column-per-setting means an <code>ALTER TABLE</code> and a deploy for each one. Modeling attributes as <b>data</b> (definition rows) instead of <b>schema</b> (columns) makes &lsquo;add a setting&rsquo; an insert, not a migration. You trade the schema&rsquo;s built-in guarantees for that flexibility &mdash; deliberately.",
    f:[
      { q:"Why is &lsquo;add a setting means a migration&rsquo; actually a problem &mdash; migrations are routine.",
        a:"Because it makes product velocity <b>gated on engineering and a deploy</b> for every trivial config toggle, and it doesn&rsquo;t scale with device-type diversity: a setting relevant to one firmware becomes a nullable column on <i>every</i> device, so the table accretes dozens of mostly-null columns. Routine or not, a migration-per-setting means the schema churns constantly and the devices table becomes a graveyard of sparse, type-specific columns. EAV moves that churn out of the schema and into data, where adding a setting is an insert anyone can do without a deploy." },
      { q:"What do you actually give up by leaving the fixed schema?",
        a:"The database&rsquo;s <b>built-in guarantees</b>: column typing, constraints, and cheap querying. A real column is typed, can carry a CHECK or FK, and is trivially indexed and filtered. An EAV value is a generic cell the database can&rsquo;t type or constrain, and querying by it needs joins and opt-in indexes. So you take on <b>enforcing typing yourself</b> (validate-on-write), <b>reconstructing entities</b> (the pivot), and <b>opt-in searchability</b> &mdash; all the things the schema gave you for free. That&rsquo;s the tax you pay for not migrating." }
    ],
    senior:"Framing EAV as <b>modeling attributes as data for the variable long tail</b> &mdash; and naming the deliberate trade (flexibility for the schema&rsquo;s built-in guarantees) rather than presenting it as free &mdash; is the maturity an interviewer is checking for." },
  { tier:'SDE2', signal:'Definition / value split',
    q:"Sketch the tables for an EAV attribute store.",
    a:"Two core tables. A <b>definition</b> &mdash; one row per attribute: name, data_type, default_value, a json_schema for validation, and flags (is_secret, is_searchable, a group). And a <b>value</b> table &mdash; <code>entity_value(entity_id, attribute_id, value)</code>, one row per per-entity override. The definition is the attribute&rsquo;s <b>contract</b>; the value table holds only the entities that differ from the default.",
    f:[
      { q:"Why separate the definition from the values at all?",
        a:"Because the <b>schema of an attribute is shared</b> &mdash; its type, default, validation, and flags are the same for all 50,000 devices &mdash; while the <b>value is per-entity</b>. Putting the type and default on every value row would duplicate them 50,000 times and let them drift; putting them once on the definition means one source of truth for &lsquo;what this attribute is,&rsquo; and the value rows carry only what&rsquo;s actually per-device. It&rsquo;s normalization: the attribute&rsquo;s metadata lives once, the per-entity data references it." },
      { q:"What&rsquo;s the unique key on the value table, and why does it matter?",
        a:"<code>(entity_id, attribute_id)</code> &mdash; unique, so an entity has <b>at most one</b> override per attribute. That&rsquo;s what makes resolution a single deterministic lookup (find the one override or fall to the default), rather than a &lsquo;most-recent-wins&rsquo; scan over multiple rows. It also makes the write an <b>upsert</b> (<code>ON CONFLICT DO UPDATE</code>): setting a value either inserts the override or replaces it, never accumulates duplicates." }
    ],
    senior:"Drawing the <b>definition (shared contract) / value (per-entity override) split</b> with the <code>(entity_id, attribute_id)</code> unique key &mdash; and explaining it as normalization of the attribute&rsquo;s metadata &mdash; is a clean, concrete data-modeling signal." },
  { tier:'SDE2', signal:'Resolution',
    q:"A device reads a config attribute. How do you resolve its value?",
    a:"<b>Override-over-default</b>: <code>COALESCE(entity_value.value, definition.default_value)</code> &mdash; a left join from the definition to the entity&rsquo;s value row. If the entity has an override, use it; otherwise the default. One lookup, deterministic &mdash; and because overrides are sparse, most attributes resolve straight to the default.",
    f:[
      { q:"Why store the default on the definition rather than writing a value row per entity?",
        a:"Because a default is <b>one value shared by every entity that hasn&rsquo;t overridden</b> &mdash; storing it once on the definition means changing the default is a single update, and it keeps the value table sparse (no row for the common case). If you materialized a default row for all 50,000 devices, you&rsquo;d have 50,000 rows that all say the same thing, changing the default would be a mass update, and you&rsquo;d lose the distinction between &lsquo;explicitly set to the default&rsquo; and &lsquo;just using the default.&rsquo; Default-on-definition, override-in-value is the sparse, single-source-of-truth model." },
      { q:"What if there&rsquo;s no override <i>and</i> no default?",
        a:"Then the attribute resolves to null/absent, and the definition should say whether that&rsquo;s legal. A <b>required</b> attribute with no default means every entity <i>must</i> have an override (enforced at write, or the entity is considered incomplete); an <b>optional</b> one legitimately resolves to nothing. The definition&rsquo;s JSON-Schema and a required flag express which &mdash; so &lsquo;no value&rsquo; is a defined outcome, not an accident. The resolution rule stays COALESCE; the definition decides whether the fallthrough-to-null is acceptable." }
    ],
    senior:"Stating resolution as <b><code>COALESCE(override, default)</code> over a left join</b>, and defending default-on-definition (sparse, single source of truth) over materialized default rows, is the one-line clarity that reads as senior." },
  { tier:'SDE2', signal:'Validation on write',
    q:"The value column is generic &mdash; text or JSONB. How do you keep someone from writing a string where an integer belongs?",
    a:"<b>Validate on write.</b> Every value is type-coerced to the definition&rsquo;s data_type and checked against its JSON-Schema before it lands; a bad value is rejected at the write path. The database can&rsquo;t enforce &lsquo;positive integer&rsquo; on a generic column, so you enforce it yourself, at the one place every value passes through. The store then never holds an invalid value, and every reader can trust it.",
    f:[
      { q:"Why validate on write rather than on read?",
        a:"Because <b>write happens once, read happens constantly</b>, and a bad value written once would break <i>every</i> subsequent reader. Validating on write means the store&rsquo;s invariant is &lsquo;everything in here is well-formed&rsquo; &mdash; readers do zero validation and can trust the data. Validate-on-read pushes the check to every consumer (duplicated, easy to forget) and still lets garbage sit in the table. Push the check to the single write path, once, and correctness is centralized and guaranteed rather than hoped for at every read." },
      { q:"What does the JSON-Schema catch that type coercion alone doesn&rsquo;t?",
        a:"<b>Structure and constraints</b>, not just the base type. Coercion gets you &lsquo;this is an integer&rsquo;; the JSON-Schema gets you &lsquo;an integer <i>between 1 and 300</i>,&rsquo; &lsquo;one of this enum,&rsquo; &lsquo;an object with these required fields,&rsquo; &lsquo;a string matching this pattern.&rsquo; For a <code>json</code>-typed attribute it validates the whole nested shape. So coercion handles the primitive type and the schema handles the <i>semantics</i> &mdash; range, enumeration, required structure &mdash; which is what keeps a technically-an-integer-but-nonsensical value (a timeout of -5, a status of &lsquo;banana&rsquo;) out of the store." }
    ],
    senior:"Naming <b>validate-on-write as the load-bearing discipline of schemaless storage</b> &mdash; write-once-read-many, coercion for type + JSON-Schema for constraints &mdash; is the instinct that separates a real EAV answer from &lsquo;we just store the value.&rsquo;" },
  { tier:'SDE2', signal:'The pivot',
    q:"An API needs a device&rsquo;s entire config as one object. Your attributes are rows. How do you build that &mdash; and what&rsquo;s the trap?",
    a:"You fetch <b>all</b> the device&rsquo;s value rows (plus the definitions for defaults) in <b>one</b> query and <b>pivot</b> them into a single object in memory. The trap is doing it <b>per-attribute</b> &mdash; a query per attribute is the <b>N+1</b> that kills EAV performance. The rule: never loop attributes; fetch the set, pivot once.",
    f:[
      { q:"What does the pivot actually look like &mdash; in SQL or in the app?",
        a:"Either. In SQL it&rsquo;s a <b>crosstab</b> (Postgres <code>crosstab</code>, or conditional aggregation: <code>MAX(CASE WHEN attribute_id = X THEN value END)</code> grouped by entity) that turns rows into columns. In the app it&rsquo;s simpler and often cleaner: one query returns all of the entity&rsquo;s (attribute_id, value) rows, and you fold them into a map keyed by name, filling defaults for attributes with no row. The app-side pivot avoids awkward dynamic SQL and is easy to reason about; the SQL crosstab is worth it when you need the pivoted shape <i>in the database</i> for further querying. Both are one round trip, which is the point." },
      { q:"When does even the single-query pivot get expensive?",
        a:"When you&rsquo;re reconstructing <b>many entities at once</b> &mdash; a list view of 500 devices&rsquo; full configs &mdash; or reconstructing <b>constantly</b>. Fetching all value rows for 500 entities and pivoting is a big result set and a lot of folding, done on every page load. That&rsquo;s the signal to <b>cache the reconstructed objects</b> (with CDC-driven invalidation), or to reconsider: if you always need the whole object for many entities, the row model is fighting you, and a materialized/denormalized view or real columns for the hot attributes may be the answer. The pivot is fine occasionally; constant whole-entity reconstruction is where the EAV tax compounds." }
    ],
    senior:"Insisting on <b>fetch-all-then-pivot-once (never N+1)</b> &mdash; and recognizing that constant whole-entity reconstruction is where the tax compounds and caching or columns enter &mdash; is the performance instinct a senior round rewards." },
  { tier:'SDE3', signal:'The EAV tax',
    q:"Product wants to filter devices by three attributes at once and sort by a fourth. What does that query look like, and how bad is it?",
    a:"Ugly &mdash; this is the EAV tax at its sharpest. Each attribute is its own row, so filtering by three means <b>three self-joins</b> (or subqueries) on entity_value, one per attribute, plus a join for the sort attribute. If those attributes are <b>searchable</b> (indexed), each condition is a seek, but combining them is still multiple self-joins the planner can struggle with. It works, but it&rsquo;s the moment to ask whether these attributes wanted to be real columns.",
    f:[
      { q:"How much do the searchable indexes actually help a three-attribute filter?",
        a:"They turn each individual condition from a scan into a <b>seek</b> &mdash; &lsquo;attribute_id = X AND value = Y&rsquo; hits the composite partial index &mdash; so each of the three self-joins starts from a small, indexed set rather than scanning entity_value. That&rsquo;s a big win over unindexed. What they <i>don&rsquo;t</i> fix is the <b>join complexity</b>: you&rsquo;re still intersecting three indexed sets via self-joins, and the sort attribute adds a fourth access. So indexes make each leg fast but don&rsquo;t eliminate the structural cost of reassembling a multi-attribute predicate from row-per-attribute storage. Fast legs, still a multi-join query." },
      { q:"At what point do you stop tuning the query and reach for columns?",
        a:"When a <b>fixed, known set</b> of attributes is queried and sorted <b>frequently</b>. The moment those aren&rsquo;t part of the variable long tail but are core, hot filter/sort dimensions, they&rsquo;ve outgrown EAV: promote them to <b>real columns</b> (or a denormalized projection) on an entity table, where multi-column filtering and sorting is a normal indexed query, not a pile of self-joins. EAV earns its keep for the sparse, rarely-queried attributes; the few that are constantly filtered belong in the schema. The senior move is spotting that promotion, not out-cleverer-ing the self-joins." }
    ],
    senior:"Recognizing <b>multi-attribute filtering as EAV&rsquo;s structural weakness</b> &mdash; indexes speed each leg but not the joins &mdash; and knowing the trigger to promote hot dimensions to columns is exactly the trade-off judgment a senior round probes." },
  { tier:'SDE3', signal:'Searchable index',
    q:"You can&rsquo;t index every attribute value. How do you make <i>some</i> attributes queryable across the fleet?",
    a:"Mark them <b>searchable</b> and back them with a <b>composite partial index</b> on <code>(attribute_id, value)</code> restricted to the searchable set. Then &lsquo;all devices where attribute X = Y&rsquo; is an index seek, not a full scan of entity_value. It&rsquo;s opt-in: you index only the handful of attributes people actually filter on, so the index stays small.",
    f:[
      { q:"Why a partial index rather than a full index on (attribute_id, value)?",
        a:"Because a <b>full</b> index would include every value row for every attribute &mdash; millions of entries, most for attributes nobody ever filters on &mdash; which is large, slower to maintain on every write, and mostly dead weight. The <b>partial</b> index (WHERE the attribute is searchable) contains only the entries for the queried attributes, so it&rsquo;s a fraction of the size, cheaper to write, and still a seek for the queries that matter. You&rsquo;re indexing the working set of <i>searchable</i> values, not the entire value table." },
      { q:"Why the column order (attribute_id, value) and not (value, attribute_id)?",
        a:"Because queries are always &lsquo;<b>for this attribute</b>, find this value&rsquo; &mdash; you filter <code>attribute_id = X</code> first, then match the value. Leading with <code>attribute_id</code> lets the index seek straight to that attribute&rsquo;s slice and then range/equality-match the value within it. Leading with <code>value</code> would be wrong: the same raw value (say <code>1</code>) means different things across attributes, so you&rsquo;d match values globally and then filter attribute &mdash; scanning across unrelated attributes. Attribute-first mirrors the access pattern, which is the rule for composite-index order." }
    ],
    senior:"Choosing a <b>composite partial index on (attribute_id, value), attribute-first, restricted to the searchable set</b> &mdash; and justifying both the partial-ness and the column order from the access pattern &mdash; is concrete indexing depth." },
  { tier:'SDE3', signal:'Secrets',
    q:"Some attributes are API keys and certificates. How do you store those differently from a timeout value?",
    a:"Flag them <code>is_secret</code>, which routes them down a different path: <b>KMS-encrypted at rest</b> (ideally a per-tenant key) so a database dump doesn&rsquo;t leak them, and <b>masked at the API layer</b> so reads return a placeholder, not the value &mdash; write-only from the outside. A credential has a different threat model than a config flag, so one flag on the definition sends it down the encrypted, masked path.",
    f:[
      { q:"Why encrypt <i>and</i> mask &mdash; isn&rsquo;t one enough?",
        a:"They defend different exposures. <b>Encryption at rest</b> protects the <b>data at rest</b> &mdash; a stolen backup, a dumped table, disk access &mdash; where the bytes are the risk. <b>Masking at the API</b> protects the <b>data in use</b> &mdash; the secret being returned to a client, a log, a UI, an over-broad API consumer &mdash; where the exposure is the value flowing out through a legitimate read path. Encryption alone still hands the plaintext to anyone who calls the read API; masking alone leaves the plaintext in the database for a dump to find. You need both because the secret is attacked at rest <i>and</i> in transit out, and each control covers a hole the other doesn&rsquo;t." },
      { q:"Where does the decryption actually happen, then?",
        a:"Only in the <b>systems that legitimately need the plaintext</b>, at the point of use &mdash; not in the general read API. The masked read path never decrypts (it returns the placeholder); a specific, authorized service that must <i>use</i> the credential (to call the device, to establish TLS) fetches the ciphertext and decrypts via KMS under its own permission, ideally logged. So decryption is narrow and audited, gated by KMS key policy, rather than something the store does on every read. The default path sees masked; the exception path decrypts with explicit authority &mdash; least privilege on the secret itself." }
    ],
    senior:"Routing <code>is_secret</code> to <b>encrypt-at-rest plus mask-at-API</b> &mdash; and explaining that they cover at-rest vs in-use exposures, with decryption narrowed to authorized point-of-use &mdash; is the security depth that reads as senior." },
  { tier:'SDE3', signal:'Sparse overrides',
    q:"50,000 devices and 200 attributes is 10 million potential value rows. Is your table that big?",
    a:"No &mdash; you store <b>only overrides</b>. A device running the default for an attribute has <b>no row</b> for it; only devices that differ get a value row. So table size is proportional to how much devices actually <i>deviate</i> from defaults, which for a well-defaulted fleet is a small fraction of 10 million. Defaults live once on the definition; overrides are the exception, not the norm.",
    f:[
      { q:"What if most devices <i>do</i> override a particular attribute &mdash; then it&rsquo;s not sparse.",
        a:"Then that attribute is a signal that its <b>default is wrong</b>, or that it isn&rsquo;t really an override-style attribute at all. If nearly every device sets its own value, the &lsquo;default&rsquo; carries no weight and you&rsquo;re materializing a row per device anyway &mdash; which is the dense case EAV handles worst. Two responses: fix the default so most devices fall through to it (restoring sparseness), or recognize that a universally-set attribute is really a <b>per-entity property that wants a real column</b> on the entity table, not an override. Sparse-overrides is EAV&rsquo;s efficiency assumption; an attribute that violates it is telling you something about its modeling." },
      { q:"How does sparse storage interact with the reconstruction pivot?",
        a:"It <b>helps</b>: reconstructing an entity fetches only its <i>override</i> rows (few, because sparse) and fills the rest from definition defaults &mdash; so the per-entity value fetch is small even with 200 attributes, since most resolve to the default without a row. The pivot combines &lsquo;the handful of override rows&rsquo; with &lsquo;the definitions&rsquo; defaults&rsquo; into the full object. So sparseness keeps both the table small <i>and</i> the reconstruction cheap, as long as you fetch definitions once (they&rsquo;re shared) rather than per entity." }
    ],
    senior:"Explaining <b>override-only sparse storage</b> (size tracks deviation, not the cartesian product) &mdash; and reading a non-sparse attribute as a modeling smell &mdash; is the insight that shows you understand EAV&rsquo;s efficiency assumption." },
  { tier:'SDE3', signal:'Type coercion',
    q:"A CSV import sends the value \"30\" for an integer attribute. What happens?",
    a:"It&rsquo;s <b>coerced</b> to the definition&rsquo;s data_type on write &mdash; the string <code>&quot;30&quot;</code> becomes the integer <code>30</code> &mdash; then validated against the JSON-Schema (range, enum). Coercion is necessary because inputs arrive as strings (CSV, form fields, query params), and the store should hold the <b>typed</b> value, not the string, or else <code>&quot;30&quot;</code>, <code>30</code>, and <code>&quot;30 &quot;</code> all differ and comparisons break.",
    f:[
      { q:"What if coercion fails &mdash; the CSV cell is &lsquo;thirty&rsquo;?",
        a:"<b>Reject the write</b> with a clear, located error &mdash; which row and attribute failed &mdash; rather than storing a null or the raw string. A value that can&rsquo;t coerce to the attribute&rsquo;s type is invalid by definition, and silently dropping or stringifying it is how garbage enters the store. For a bulk import that means the row (or the import) fails with a precise message so the operator can fix the source, not a partial import that half-worked. Coercion failure is a validation failure; it belongs in the same reject-at-write bucket as a schema violation." },
      { q:"Why store the typed value rather than just keep everything as strings?",
        a:"Because <b>typed values compare, sort, and index correctly</b>, and stringly-typed ones don&rsquo;t. As strings, <code>&quot;9&quot; &gt; &quot;10&quot;</code> (lexicographic), a range filter on a numeric attribute is wrong, and equality is fragile to whitespace and formatting. Storing the coerced type &mdash; integer, boolean, the parsed JSON &mdash; means <code>value &gt; 10</code>, ordering, and equality behave, and the searchable index is meaningful. Keeping everything as strings pushes the &lsquo;parse and compare correctly&rsquo; burden onto every reader and every query, reintroducing exactly the bugs coercion-on-write prevents. (Implementation may store per-type columns or a typed JSONB; the point is the value is typed, not raw text.)" }
    ],
    senior:"Treating coercion as <b>parse-to-typed-at-write, reject-what-can&rsquo;t-coerce</b> &mdash; and knowing stringly-typed values break comparison, sorting, and indexing &mdash; is the correctness instinct behind a robust attribute store." },
  { tier:'SDE3', signal:'Staging and promote',
    q:"An operator prepares a new config for a device but doesn&rsquo;t want it live until it&rsquo;s reviewed. How?",
    a:"A <b>staging workflow</b>: values are written with <code>is_staged</code>, so they exist but aren&rsquo;t resolved as live; the operator reviews the staged set and <b>promotes it atomically</b>. The device never runs a half-applied config &mdash; it sees the old values until the promote, then the whole set at once. Same principle as not deploying half a release: prepare, review, flip.",
    f:[
      { q:"Why does the promote need to be atomic?",
        a:"So the device never observes a <b>partially-applied</b> configuration. If you promoted staged values one at a time, there&rsquo;d be a window where some new values are live and some old ones still are &mdash; an inconsistent combination that might have never been reviewed and could misbehave (a new timeout with an old, incompatible mode). An atomic promote &mdash; flip all staged values to live in one transaction &mdash; means the device transitions from the fully-old config to the fully-new one with no in-between. Config, like a deploy, wants an all-or-nothing cutover, not a partial rollout of individual values." },
      { q:"How does resolution ignore staged values so they don&rsquo;t leak as live?",
        a:"Resolution filters to <b>live (non-staged) values only</b> &mdash; the COALESCE reads the entity&rsquo;s live override or the default, and staged rows are simply not considered until promotion flips their status (or moves them into the live set). So a staged value is visible in the <i>review</i> view but invisible to the <i>device&rsquo;s</i> resolution, which is what lets you prepare config without affecting the running device. The promote is the moment a staged row becomes eligible for resolution; before that, it&rsquo;s a draft the resolver ignores." }
    ],
    senior:"Designing <b>staging with an atomic promote</b> so a device never runs a partially-applied config &mdash; and having resolution ignore staged rows until the flip &mdash; is the operational-safety thinking a senior interviewer wants." },
  { tier:'SDE3', signal:'Bulk CSV import',
    q:"Operators set attributes across thousands of devices via CSV upload. What makes that safe?",
    a:"<b>Bounds and per-cell validation.</b> The import is capped (<code>MAX_ROWS 500</code>, 5 MB) so one paste can&rsquo;t be an unbounded job, and <b>every cell is coerced to its attribute&rsquo;s type and JSON-Schema-validated</b> exactly like a single write &mdash; a bad row is rejected with a located error, not silently stored. An unbounded, unvalidated CSV is how you poison the store with garbage or a runaway job in one action; the caps and validation make bulk writes as safe as single ones.",
    f:[
      { q:"Why cap the import size rather than just letting it run?",
        a:"To bound the <b>blast radius and resource cost</b> of a single action. An unbounded import can be a multi-million-row job that locks tables, exhausts memory, and &mdash; if it&rsquo;s wrong &mdash; corrupts a huge slice of the fleet before anyone notices. Caps make each import a reviewable, recoverable unit: a 500-row batch that fails is easy to diagnose and re-run, and it can&rsquo;t monopolize the database. For genuinely large changes you run <b>many bounded batches</b> (with progress and the option to stop), which is safer than one giant transaction. The cap is a guardrail against both accidental scale and malicious payloads." },
      { q:"Partial failure: 500 rows, row 300 is invalid. All-or-nothing, or import the valid ones?",
        a:"Prefer <b>all-or-nothing per batch with a clear report</b>, or at minimum a precise account of what succeeded and what didn&rsquo;t &mdash; never a silent partial. A config import that half-applies leaves the fleet in a state nobody chose: some devices updated, some not, with no record of which. Validating the <i>entire</i> batch first and rejecting it on any invalid row (with row-and-column errors) lets the operator fix the source and re-run cleanly. If the product needs valid-rows-through, it must be <b>explicit and itemized</b> so the operator knows exactly which rows to correct. The unacceptable outcome is an opaque partial import." }
    ],
    senior:"Making bulk import <b>bounded (row/size caps) with per-cell coercion + validation and a clear partial-failure contract</b> &mdash; treating a CSV as an untrusted payload &mdash; is the operational-safety instinct a senior round rewards." },
  { tier:'SDE3', signal:'Change data capture',
    q:"When an attribute value changes, caches, search indexes, and the devices themselves need to know. How, without everyone polling the table?",
    a:"<b>Change data capture.</b> The attribute store emits a change stream &mdash; a value changed for (entity, attribute) &mdash; and downstream consumers (a cache, a search index, the device-config push) subscribe. No one polls the whole table; they react to the deltas. It&rsquo;s the same fan-out-on-change idea as the notification topic: the store is the source of truth, and CDC keeps derived copies in sync.",
    f:[
      { q:"Why CDC rather than having consumers poll for changes?",
        a:"Because polling is <b>wasteful and laggy at fleet scale</b>: every consumer repeatedly scanning for &lsquo;what changed&rsquo; is load proportional to consumers &times; poll-rate, mostly finding nothing, with staleness bounded by the interval. CDC inverts it &mdash; the store <b>pushes</b> the actual change events, so consumers do work only when something changed, and propagation is near-real-time. It also gives an <b>ordered, complete</b> log of changes (nothing missed between polls), which matters for keeping a search index or cache exactly consistent. Same reasoning as poll-vs-push for notifications: push the deltas, don&rsquo;t poll the state." },
      { q:"What consistency does a CDC-fed search index or cache actually have?",
        a:"<b>Eventual</b> consistency &mdash; there&rsquo;s a lag between the write committing and the consumer applying the change &mdash; which is the right trade for derived read models. The store stays the strongly-consistent source of truth; the index and cache converge to it within the propagation delay. You design for that: reads that need the absolute latest go to the store, while the index/cache serve the (slightly stale) common case, and CDC ordering ensures they converge correctly rather than drift. Accepting bounded staleness on derived copies is what lets you have a fast search index and a cache without them being a second source of truth to keep transactionally in lockstep." }
    ],
    senior:"Using <b>CDC to push value-change deltas to derived consumers</b> (cache, search, device push) instead of polling &mdash; and being clear the derived copies are eventually consistent while the store is the source of truth &mdash; is the data-propagation maturity a senior interviewer checks." },
  { tier:'SDE3', signal:'EAV vs JSON column',
    q:"Why an EAV table at all &mdash; why not just a JSON/JSONB column on the devices table with all the config in it?",
    a:"A JSON column is a real alternative, and often simpler &mdash; but they differ on <b>shared schema and cross-entity query</b>. EAV&rsquo;s <b>definition</b> table gives every attribute a single typed, validated, documented contract shared across all entities; a JSON blob has no shared schema, so validation and defaults are ad hoc per write. And querying <b>across entities by an attribute</b> (&lsquo;all devices where X = Y&rsquo;) is EAV&rsquo;s composite partial index vs JSON&rsquo;s bolted-on functional/GIN indexes. JSON wins when config is <b>read/written whole per entity</b> and rarely queried across; EAV wins when attributes need <b>shared definitions and cross-fleet queryability</b>.",
    f:[
      { q:"So what specifically pushes you to EAV over the simpler JSON column?",
        a:"Three things. One: a <b>shared, enforced contract</b> per attribute &mdash; you want &lsquo;timeout is an int 1&ndash;300, here&rsquo;s its default and who can set it&rsquo; defined once and applied to every device, not re-asserted in each JSON write. Two: <b>cross-entity querying and reporting</b> on attributes &mdash; filtering and aggregating &lsquo;all devices with attribute X&rsquo; is first-class in EAV with the searchable index, and clumsy on nested JSON. Three: <b>per-attribute metadata</b> &mdash; is_secret, is_searchable, grouping, staging &mdash; which lives naturally on the definition and would be awkward to attach to keys inside a blob. If you need none of those &mdash; config is just a per-device bag read and written together &mdash; the JSON column is the simpler, correct choice." },
      { q:"Isn&rsquo;t a JSON column&rsquo;s write cost (rewriting the whole blob) a reason to prefer EAV?",
        a:"It&rsquo;s a real factor: updating one field in a JSON column <b>rewrites the whole document</b> and makes the entire blob the unit of MVCC contention, so hot per-field writes amplify. EAV updates a <b>single small value row</b>, so a change to one attribute touches one row, and concurrent writes to <i>different</i> attributes of the same entity don&rsquo;t contend on one document. So for <b>write-heavy, per-attribute</b> update patterns, EAV&rsquo;s row-per-value is friendlier. For read-mostly config written whole occasionally, the JSON rewrite cost is irrelevant and its simplicity wins. It&rsquo;s the same normalized-child-table-vs-JSON trade-off: granular updates and cross-row queries favor the normalized (EAV) shape; whole-aggregate read/write favors the blob." }
    ],
    senior:"Framing <b>EAV vs JSON as shared-contract + cross-entity-query + granular-writes vs whole-aggregate simplicity</b> &mdash; and picking by access pattern rather than dogma &mdash; is precisely the senior data-modeling trade-off." },
  { tier:'SDE3', signal:'Attribute groups',
    q:"You have 200 attributes across many device types. How do you keep that from being an unmanageable flat list?",
    a:"<b>Groups</b> on the definition &mdash; attributes belong to a group (network, display, security, firmware), so the UI, permissions, and bulk operations work per group rather than over a flat 200. Grouping is metadata on the definition, so it costs nothing structurally and makes the store <b>navigable</b>: an operator edits &lsquo;network settings,&rsquo; a role is granted &lsquo;security attributes,&rsquo; an import targets &lsquo;display config.&rsquo;",
    f:[
      { q:"Beyond UI tidiness, what does grouping buy you?",
        a:"<b>Authorization and bulk scoping.</b> Groups become a natural unit for <b>permissions</b> &mdash; a support role can edit &lsquo;display&rsquo; but not &lsquo;security&rsquo; attributes &mdash; which is far more manageable than per-attribute grants across 200. They also scope <b>bulk operations and staging</b> (&lsquo;stage all network attributes for these devices&rsquo;), and they let device types <b>declare which groups apply</b>, so a device only surfaces relevant attributes. So grouping is not just cosmetic: it&rsquo;s the axis for access control, bulk actions, and per-type applicability, which is what keeps 200 attributes operationally sane." }
    ],
    senior:"Using <b>groups as the axis for UI, permissions, bulk scoping, and per-type applicability</b> &mdash; not just visual tidiness &mdash; shows you&rsquo;ve thought about operating an attribute store, not just storing values." },
  { tier:'SDE3', signal:'Multi-tenant isolation',
    q:"The platform is multi-tenant. What has to be tenant-scoped in the attribute store?",
    a:"Definitions and values both. Value rows are <b>tenant-scoped</b> so one tenant can never read or write another&rsquo;s device attributes &mdash; the same per-tenant boundary the authorization topic enforces, applied to entity_value. Definitions may be <b>global</b> (platform-wide attributes) or <b>per-tenant</b> (a tenant&rsquo;s custom attributes), and resolution must respect that. And <b>secret attributes</b> use per-tenant KMS keys, so a compromise is blast-radius-bounded to one tenant.",
    f:[
      { q:"Can one tenant define custom attributes without affecting others?",
        a:"Yes &mdash; that&rsquo;s the point of allowing <b>per-tenant definitions</b> alongside global ones. A tenant-scoped definition is visible and resolvable only within that tenant, so tenant A adding a custom attribute doesn&rsquo;t change tenant B&rsquo;s schema or clutter their attribute list. Resolution for a device considers the global definitions plus <i>its</i> tenant&rsquo;s definitions, never another tenant&rsquo;s. This is a real advantage of EAV in multi-tenant: because attributes are data, a tenant can extend the model without a shared-schema migration that would affect everyone &mdash; the flexibility that motivates EAV also gives per-tenant extensibility for free, as long as definitions carry a tenant scope." }
    ],
    senior:"Scoping <b>values (and optionally definitions) per tenant, with per-tenant secret keys</b> &mdash; and recognizing EAV gives per-tenant schema extensibility without a shared migration &mdash; is the multi-tenant insight a senior interviewer wants." },
  { tier:'Staff', signal:'When EAV is wrong',
    q:"Sell me on <i>not</i> using EAV. When is reaching for an attribute store the wrong call?",
    a:"When the data is <b>well-structured, uniform, and heavily queried</b> &mdash; which is most core data. EAV pays a real tax (pivots, self-joins, opt-in indexing, self-enforced typing) to buy schema flexibility, and if you don&rsquo;t <i>need</i> the flexibility, you&rsquo;re paying for nothing. If the attributes are the same across all entities, known upfront, and frequently filtered/sorted, they want <b>real columns</b>. EAV earns its keep only for the <b>sparse, variable, per-type long tail</b> of config &mdash; and even then, the hot, queried attributes within it should graduate to columns.",
    f:[
      { q:"What&rsquo;s the classic symptom that you&rsquo;ve over-applied EAV?",
        a:"<b>Fighting the query layer constantly</b> &mdash; every report is a pile of self-joins or a crosstab, whole-entity reconstruction is on every hot path, and you&rsquo;re building ever-more indexes and caches to make EAV behave like a schema. When you find yourself <b>reimplementing a relational database on top of EAV</b> &mdash; typing, constraints, joins, indexes you had for free with columns &mdash; you&rsquo;ve modeled structured data as attributes. The tell is that the flexibility is unused (the attributes never actually vary or get added) while the tax is fully paid. That&rsquo;s the signal to move the stable, queried attributes back into real columns and reserve EAV for the genuinely variable remainder." },
      { q:"How do you decide the boundary &mdash; which attributes stay EAV and which become columns?",
        a:"By <b>stability and query-frequency</b>. An attribute that is <b>known, uniform across entities, and frequently filtered or sorted</b> is a column: it&rsquo;s core, structured, hot data. An attribute that is <b>sparse, varies by device type or firmware, added ad hoc, and rarely queried across entities</b> is EAV: it&rsquo;s the long tail flexibility exists for. So you split the config: a small set of core columns for the hot, stable dimensions, and an EAV store for the variable rest &mdash; a hybrid, not a religion. The discipline is periodically promoting attributes that have become hot-and-stable out of EAV into columns, rather than letting everything live as attributes forever." }
    ],
    senior:"Arguing <b>against EAV for uniform, queried, structured data</b> &mdash; naming the &lsquo;reimplementing a database on top of EAV&rsquo; symptom and the stability&times;query-frequency boundary for a hybrid model &mdash; is exactly the Staff-level judgment that you use EAV surgically, not as a default." },
  { tier:'Staff', signal:'Schema evolution',
    q:"You need to change an attribute&rsquo;s type from string to int, or change its default. In a fixed schema that&rsquo;s a migration. What&rsquo;s the EAV version, and where&rsquo;s the danger?",
    a:"The <b>definition</b> change is trivial &mdash; update the data_type or default_value row. The <b>danger is the existing values</b>: changing the type doesn&rsquo;t retroactively coerce the value rows already stored, and changing the default silently changes the resolved value for every entity <i>without</i> an override. So the definition edit is one row, but you must <b>migrate the existing values</b> (coerce/validate them to the new type, handling ones that can&rsquo;t) and <b>reason about who&rsquo;s affected</b> by a default change (everyone on the default).",
    f:[
      { q:"Changing the default changes behavior for every non-overriding device. How do you do that safely?",
        a:"Treat it like any <b>fleet-wide behavior change</b>, because it is one &mdash; it&rsquo;s deceptively a one-row edit but its effect is on all devices resolving to the default. Safely: know and communicate the <b>blast radius</b> (every entity without an override for this attribute), <b>stage and roll it out</b> rather than flipping globally in one instant (canary a subset, watch, expand &mdash; the same discipline as a deploy or a desired-state rollout), and consider whether devices that <i>want</i> the old value need an explicit override created before the default moves. The trap is thinking &lsquo;it&rsquo;s just data, one update&rsquo; and forgetting that the default is load-bearing for the whole fleet &mdash; a default change is a config deployment, and gets the same care." },
      { q:"For the type change, what do you do with values that can&rsquo;t coerce to the new type?",
        a:"You <b>can&rsquo;t silently drop or corrupt them</b>, so the migration must handle them explicitly: identify the value rows that won&rsquo;t coerce (a free-text string that isn&rsquo;t a number), and decide per policy &mdash; map them to a sensible value, quarantine them for manual fix, or block the type change until they&rsquo;re cleaned. Ideally you <b>validate the whole existing value set against the new type first</b> (a dry run) so you know the exceptions before committing, then migrate the coercible ones and surface the rest. This is exactly the safety a real schema migration gives you (the DB rejects incompatible data); in EAV you rebuild that safety yourself, because the definition change alone won&rsquo;t protect the stored values." }
    ],
    senior:"Recognizing that in EAV the <b>definition change is trivial but existing-value migration and default-change blast radius are the real work</b> &mdash; a default edit is a fleet-wide config deploy, a type change needs a validate-then-migrate pass &mdash; is the Staff-level insight that flexibility relocates the migration problem, it doesn&rsquo;t remove it." },
  { tier:'Staff', signal:'Read performance at scale',
    q:"Resolving a device&rsquo;s full config is on a hot path &mdash; every device check-in. How do you make that fast at fleet scale?",
    a:"<b>Cache the resolved objects</b>, invalidated by CDC. The reconstruction (fetch overrides + definitions, pivot) is deterministic from the store, so it&rsquo;s a perfect cache candidate: resolve once, cache the assembled config per entity, serve from cache on check-in, and <b>bust on change</b> via the CDC stream when a value or default moves. Most check-ins then never touch the pivot at all. Underneath, sparse overrides keep the miss cheap, and shared definitions are cached once, not per entity.",
    f:[
      { q:"What&rsquo;s your invalidation strategy &mdash; TTL, or event-based?",
        a:"<b>Event-based via CDC</b>, with a TTL as a backstop. Because the store emits change deltas, you can precisely invalidate the affected entity&rsquo;s cached config when its override changes &mdash; and, importantly, invalidate <b>all</b> entities resolving to a definition&rsquo;s default when the <i>default</i> changes (a definition-level change fans out to every non-overriding entity). That&rsquo;s exact and immediate. A modest TTL sits under it to catch any missed event and bound worst-case staleness. Pure TTL alone would be either too stale (config lags) or too churny (constant re-resolution); CDC-driven invalidation with a TTL backstop gives promptness plus safety &mdash; the same tiered pattern as caching authorization decisions." },
      { q:"A definition default change invalidates a huge number of cached entities at once. Problem?",
        a:"It can be a <b>thundering-herd / mass-invalidation</b> risk: busting every non-overriding entity&rsquo;s cache simultaneously means they all re-resolve on their next check-in, a spike of pivots. Mitigations: <b>re-warm proactively</b> (recompute and repopulate in the background rather than waiting for cache misses), <b>stagger</b> the invalidation, and lean on the fact that resolution is cheap (sparse overrides, cached definitions) so even a miss storm is bounded. And it&rsquo;s another argument for <b>rolling out default changes gradually</b> rather than globally at once &mdash; which both limits the behavioral blast radius and spreads the cache re-warm. Recognizing that a one-row default edit can trigger fleet-wide cache invalidation is the non-obvious Staff insight." }
    ],
    senior:"Caching resolved configs with <b>CDC-driven (entity- and definition-level) invalidation plus a TTL backstop</b> &mdash; and foreseeing that a default change mass-invalidates and needs re-warming or staggering &mdash; is the scale-and-caching depth that marks a Staff answer." },
  { tier:'Staff', signal:'The whole design',
    q:"Tie it together: one sentence for how you&rsquo;d design a per-entity attribute store.",
    a:"<b>Attributes as definition rows (name, type, default, JSON-Schema, flags) plus sparse per-entity override rows, resolved as <code>COALESCE(override, default)</code>, typed and validated on write, secrets encrypted and masked, searchable attributes on a composite partial index, staged-then-promoted for safe changes, and CDC to keep derived copies in sync</b> &mdash; so product adds config without a migration, while typing, querying, and reconstruction are handled deliberately. The hard part isn&rsquo;t the storage; it&rsquo;s knowing which attributes belong in EAV and which have earned real columns.",
    f:[
      { q:"If you could only keep three of those properties, which three?",
        a:"<b>The definition/value split</b> (a shared typed contract per attribute plus sparse overrides &mdash; the core model, and where defaults and validation live), <b>validate-on-write</b> (typing and JSON-Schema at the single write path &mdash; without it the flexibility becomes a garbage store), and <b>COALESCE(override, default) resolution</b> (the deterministic read rule that makes sparse storage work). Those three <i>are</i> a correct attribute store: a typed contract, enforced values, deterministic reads. Searchability, secrets, staging, CDC, and caching are essential-at-scale layers on that spine &mdash; addable without changing the model. And wrapping all of it, the judgment to promote hot attributes to columns, which keeps the tax proportional to the flexibility you actually use." }
    ],
    senior:"Compressing the store to <b>&lsquo;typed definitions + sparse overrides + validate-on-write + COALESCE resolution,&rsquo; with searchability/secrets/staging/CDC as scale layers and column-promotion as the governing judgment</b> &mdash; and naming the irreducible three &mdash; is the systems-level framing that lands a Staff signal." },
  { tier:'Staff', signal:'Governing the model',
    q:"A year in, the store has 400 attributes and the team reaches for EAV for every new field. What&rsquo;s your concern, and how do you govern it?",
    a:"The concern is <b>EAV creep</b> &mdash; treating a store built for the sparse, variable long tail as the default home for <i>every</i> new field, including uniform, hot, queried ones. Over time that&rsquo;s more self-joins, more reconstruction on hot paths, and a schema&rsquo;s worth of structured data hiding in attribute rows, paying the full EAV tax for flexibility it never uses. Governing it: make EAV a <b>deliberate choice with a bar</b> &mdash; new fields default to real columns unless genuinely sparse/variable/per-type &mdash; and <b>periodically promote</b> attributes that have become hot-and-stable into columns. A hybrid, not a religion: EAV for the tail, columns for the core.",
    f:[
      { q:"How do you actually catch the attributes that should be promoted?",
        a:"<b>Measure usage.</b> Instrument which attributes get queried, filtered, and sorted and how often, which are set on nearly every entity (non-sparse), and which sit on hot reconstruction paths. An attribute that&rsquo;s <b>frequently queried, densely set, and stable</b> is a promotion candidate &mdash; the data says it has outgrown the long tail. Promotion is then a deliberate migration: add the real column, backfill from the value rows, cut readers over, retire the attribute. Without measurement you&rsquo;re guessing; with it, promotion becomes a periodic, evidence-driven cleanup rather than a debate. The governance is a feedback loop &mdash; attributes earn their way into the schema by demonstrated hot-and-stable usage." },
      { q:"Doesn&rsquo;t constant promotion churn undercut the whole point of EAV being flexible?",
        a:"No &mdash; because the two serve <b>different lifecycle stages</b>. EAV&rsquo;s value is letting an attribute exist <i>immediately</i>, without a migration, when it&rsquo;s new, uncertain, sparse, or type-specific &mdash; that&rsquo;s where the flexibility pays off and most attributes happily stay. Promotion only touches the <b>small minority</b> that prove, over time, to be hot and stable &mdash; and those have <i>earned</i> a migration precisely because they&rsquo;re now core. So it&rsquo;s not churn; it&rsquo;s a slow graduation of the few that matured, while the long tail keeps its flexibility. The flexibility to <i>add</i> cheaply and the discipline to <i>promote</i> the proven few are complementary, not contradictory &mdash; you get fast iteration up front and a clean schema for the hot core, instead of choosing one." }
    ],
    senior:"Treating <b>EAV as a bounded, governed choice with a promotion feedback loop</b> &mdash; default to columns, reserve EAV for the measured long tail, graduate hot-and-stable attributes &mdash; is the Staff-level ownership that keeps the tax proportional to the flexibility actually used." }
];
var EAV_SPEAK = [
  "Lead with the motivation: <b>'the config surface grows faster than migrations can keep up, so I model attributes as data, not schema &mdash; a new setting is a definition row, not an ALTER TABLE.'</b> Then name the deliberate trade: flexibility for the schema&rsquo;s built-in guarantees. Presenting the tax as free is the tell you haven&rsquo;t run EAV.",
  "Draw the split: <b>'a definition table &mdash; the attribute&rsquo;s shared contract: name, type, default, JSON-Schema, flags &mdash; and a value table of per-entity overrides, unique on (entity_id, attribute_id).'</b> The definition holds what&rsquo;s shared once; the value table holds only what differs per device.",
  "State resolution in one line: <b>'COALESCE(override, default) over a left join.'</b> Defend default-on-definition over materialized default rows: sparse, single source of truth, and most attributes resolve straight to the default because overrides are the exception.",
  "Name the discipline: <b>'validate on write &mdash; coerce to the data_type, check the JSON-Schema, reject bad values at the write path.'</b> The DB can&rsquo;t type a generic column, so you enforce it once where every value passes through &mdash; write-once, read-many, so readers trust the store.",
  "Handle reconstruction right: <b>'fetch all the entity&rsquo;s value rows in one query and pivot once &mdash; never a query per attribute.'</b> Per-attribute is the N+1 that kills EAV. And note that constant whole-entity reconstruction is where the tax compounds and caching or columns enter.",
  "Own the weakness: <b>'filtering by three attributes is three self-joins &mdash; the EAV tax at its sharpest.'</b> Searchable indexes make each leg a seek but don&rsquo;t fix the joins. If a fixed set of attributes is queried and sorted constantly, they wanted real columns.",
  "Make search opt-in: <b>'mark specific attributes searchable, backed by a composite partial index on (attribute_id, value).'</b> Attribute-first mirrors the access pattern; partial keeps it small by indexing only the queried attributes, not every value row.",
  "Route secrets separately: <b>'is_secret means KMS-encrypted at rest and masked at the API &mdash; write-only from outside.'</b> Encryption covers at-rest exposure (a dump), masking covers in-use exposure (a read leaking the value); a credential has a different threat model than a timeout, so one flag sends it down the protected path.",
  "Explain the sparseness: <b>'store only overrides &mdash; a device on the default has no row, so table size tracks deviation, not entities &times; attributes.'</b> Defaults live once on the definition. An attribute that everyone overrides is a smell &mdash; its default is wrong, or it wanted a real column.",
  "Coerce at write: <b>'the CSV sends \"30\", I coerce to the integer 30 and validate; a value that can&rsquo;t coerce is rejected.'</b> Store the typed value, not the string &mdash; stringly-typed breaks comparison, sorting, and indexing (\"9\" &gt; \"10\" lexicographically).",
  "Design for safe changes: <b>'staged values with an atomic promote &mdash; the device never runs a half-applied config.'</b> Resolution ignores staged rows until the flip; same principle as not deploying half a release. Prepare, review, promote all-at-once.",
  "Treat bulk import as untrusted: <b>'capped (500 rows, 5MB), every cell coerced and validated, a clear all-or-nothing-or-itemized failure contract.'</b> An unbounded, unvalidated CSV poisons the store or runs away in one paste; the caps and validation make bulk as safe as single writes.",
  "Keep derived copies in sync: <b>'CDC emits value-change deltas; caches, search indexes, and device-config push subscribe &mdash; nobody polls the table.'</b> Same push-not-poll idea as notifications; derived copies are eventually consistent, the store stays the source of truth.",
  "Contrast with JSON: <b>'EAV wins on a shared typed contract and cross-entity querying; a JSON column wins when config is read/written whole per entity and rarely queried across.'</b> Also: JSON rewrites the whole blob per field-write; EAV updates one small row. Pick by access pattern, not dogma.",
  "Organize with groups: <b>'attributes belong to groups &mdash; network, display, security &mdash; which scope the UI, permissions, and bulk operations.'</b> Not just tidiness: groups are the axis for per-group authorization, bulk staging, and per-device-type applicability.",
  "Scope to the tenant: <b>'value rows are tenant-scoped like the authz boundary; definitions can be global or per-tenant; secrets use per-tenant keys.'</b> And EAV gives per-tenant schema extensibility for free &mdash; a tenant adds custom attributes without a shared migration.",
  "Argue against EAV: <b>'uniform, known, heavily-queried data wants real columns &mdash; EAV is for the sparse, variable, per-type long tail.'</b> The symptom of over-applying it is reimplementing a database on top of EAV: typing, joins, indexes you had for free. Use it surgically.",
  "Relocate the migration problem: <b>'the definition change is one row, but existing-value migration and default-change blast radius are the real work.'</b> A default edit is a fleet-wide config deploy (stage and roll out); a type change needs a validate-then-migrate pass for values that can&rsquo;t coerce.",
  "Make resolution fast: <b>'cache the resolved config per entity, invalidated by CDC &mdash; entity-level on an override change, definition-level (fan-out to all non-overriding entities) on a default change.'</b> TTL as a backstop. Foresee that a default change mass-invalidates and needs re-warming or staggering.",
  "Land the whole thing: <b>'typed definitions + sparse overrides + validate-on-write + COALESCE resolution,'</b> with searchability, secrets, staging, and CDC as scale layers. Under pressure, name the irreducible three: the definition/value split, validate-on-write, and COALESCE resolution &mdash; a typed contract, enforced values, deterministic reads.",
  "Govern the model: <b>'the hard part isn&rsquo;t the storage &mdash; it&rsquo;s knowing which attributes belong in EAV and which have earned real columns.'</b> A hybrid, not a religion: core columns for the hot, stable, queried dimensions; EAV for the variable rest; and the discipline to keep promoting."
];
var TOPIC_EAV_DRILL = {
  cards: EAV_CARDS,
  speak: EAV_SPEAK,
  tierNotes: {
    all:'<b>All four levels, mixed</b> &mdash; the way a real loop actually comes at you.',
    SDE2:'<b>Fundamentals under pressure</b> &mdash; rows-not-columns, the definition/value split, COALESCE resolution, validate-on-write, the reconstruction pivot. The bar is &ldquo;this is a typed, safe attribute store, not a bag of strings&rdquo;: name the contract and the write-time enforcement.',
    SDE3:'<b>Depth &amp; trade-offs</b> &mdash; the EAV tax, searchable indexing, secrets, sparseness, coercion, staging, import, CDC, EAV-vs-JSON. The bar is &ldquo;flexibility bought on purpose&rdquo;: name the constraint and the failure each choice bounds.',
    Staff:'<b>Systems judgment</b> &mdash; when EAV is wrong, schema evolution, read-path caching, the whole model. The bar is &ldquo;flexibility for the long tail, columns for the hot core&rdquo;: name the tax, the promotion boundary, and where the migration problem relocated to.'
  }
};
