/* topics/eav/walk.js -- topic 6 walkthrough. steps[] is the attribute flow (product
   need -> definition -> set override -> validate -> resolve COALESCE -> reconstruct pivot
   -> searchable index -> secrets -> staging/import/CDC); modelScript[] is the spoken
   model answer (plain beats, the interviewer .mq line, then the .mbeat.ans -- LAST).
   Code strings use single-backslash \n / \'. 7-bit ASCII. */
var TOPIC_EAV_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"Product needs a new setting",
      flow:'<span class="fb n">product</span><span class="arr">&rarr;</span><span class="fb p">new config attribute</span><span class="arr">&rarr;</span><span class="fb t">define a row, not a migration</span><span class="arr">&middot;</span><span class="fb a">no deploy</span>',
      ins:'Product wants a new per-device setting &mdash; a timeout, a feature flag, a display option. In a fixed schema that&rsquo;s an <code>ALTER TABLE</code> and a deploy for <i>every</i> setting. Here it&rsquo;s a <b>definition row</b>: <code>defineAttribute(name, type, default, schema)</code>, and the setting exists.',
      deep:'This is the whole reason the store exists. With <b>50,000 devices of many types and firmwares</b>, the config surface grows constantly &mdash; and a schema migration per setting means product waits on engineering and a deploy for every checkbox. Modeling attributes as <b>data</b> (definition rows) instead of <b>schema</b> (columns) moves &lsquo;add a setting&rsquo; from a migration to an insert. The cost, which we pay deliberately, is that the database no longer knows the shape of a device &mdash; the shape lives in the definition table, so <i>we</i> enforce typing and reconstruct the object. That trade &mdash; flexibility for the schema&rsquo;s built-in guarantees &mdash; is the entire topic.' },
    { k:"Step 2 / 9", t:"The definition table",
      flow:'<span class="fb n">definition</span><span class="arr">&rarr;</span><span class="fb p">name + type + default + JSON-Schema + flags</span><span class="arr">&middot;</span><span class="fb a">the attribute&rsquo;s contract</span>',
      ins:'The <b>definition</b> is the schema for one attribute: its <b>name</b>, <b>data type</b>, <b>default value</b>, a <b>JSON-Schema</b> for validation, and flags &mdash; <code>is_secret</code>, <code>is_searchable</code>, a <b>group</b>. It&rsquo;s the metadata that makes a schemaless value table safe.',
      code:'<span class="c">// the definition IS the attribute&#39;s contract -- one row per setting</span>\n<span class="k">CREATE TABLE</span> attribute_definition (\n  id, name, data_type,        <span class="c">// &#39;int&#39; | &#39;bool&#39; | &#39;string&#39; | &#39;json&#39;</span>\n  default_value,              <span class="c">// used when an entity has no override</span>\n  json_schema,                <span class="c">// validation applied on every write</span>\n  is_secret, is_searchable, group_id\n);',
      cap:'The definition is what keeps &lsquo;schemaless&rsquo; from meaning &lsquo;anything goes.&rsquo; Every value written for this attribute is <b>typed by</b> <code>data_type</code>, <b>validated against</b> <code>json_schema</code>, and defaulted from <code>default_value</code> &mdash; so the flexibility is in <i>which</i> attributes exist, not in whether their values are well-formed.' },
    { k:"Step 3 / 9", t:"Set a value (the override)",
      flow:'<span class="fb n">set(entity, attribute, value)</span><span class="arr">&rarr;</span><span class="fb p">validate</span><span class="arr">&rarr;</span><span class="fb t">INSERT into entity_value</span><span class="arr">&middot;</span><span class="fb a">per-entity override</span>',
      ins:'To give one device a non-default value, write a row into <b>entity_value</b>: <code>(entity_id, attribute_id, value)</code>. It&rsquo;s an <b>override</b> &mdash; only devices that differ from the default get a row, so the value table is sparse.',
      code:'<span class="c">// per-entity override -- sparse: only non-default devices get a row</span>\n<span class="k">INSERT INTO</span> entity_value (entity_id, attribute_id, value)\n<span class="k">VALUES</span> ($1, $2, $3)\n<span class="k">ON CONFLICT</span> (entity_id, attribute_id)   <span class="c">// one override per (entity, attr)</span>\n<span class="k">DO UPDATE SET</span> value = EXCLUDED.value;   <span class="c">// upsert the override</span>',
      cap:'Storing only overrides keeps the row count sane: a fleet where most devices run defaults has few value rows. The unique key <code>(entity_id, attribute_id)</code> means an entity has at most <b>one</b> override per attribute, so resolution is a single lookup, not a &lsquo;latest wins&rsquo; scan.' },
    { k:"Step 4 / 9", t:"Validate on write",
      flow:'<span class="fb n">incoming value</span><span class="arr">&rarr;</span><span class="fb p">coerce to data_type</span><span class="arr">&rarr;</span><span class="fb t">check JSON-Schema</span><span class="arr">/</span><span class="fb r">reject if bad</span>',
      ins:'Before the value lands, it&rsquo;s <b>type-coerced</b> to the definition&rsquo;s <code>data_type</code> and checked against its <b>JSON-Schema</b>. A bad value is rejected <i>at write</i> &mdash; the store never holds an invalid attribute, so readers can trust what they get.',
      deep:'Validate-on-write is the load-bearing discipline of a schemaless store. The database can&rsquo;t enforce &lsquo;this column is a positive integer&rsquo; anymore &mdash; the value column is generic (text or JSONB) &mdash; so <i>we</i> enforce it, at the one place every value passes through: the write path. Type coercion catches the string-vs-int class (a CSV import sends <code>&quot;30&quot;</code>, we coerce to <code>30</code>); the JSON-Schema catches structure and range (an enum, a min/max, a required shape). The alternative &mdash; validate on read, or not at all &mdash; means every reader re-validates or trusts garbage, and a bad value written once breaks readers forever. Push the check to the write, once, and the store&rsquo;s contents are always well-formed.' },
    { k:"Step 5 / 9", t:"Resolve a value",
      flow:'<span class="fb n">get(entity, attribute)</span><span class="arr">&rarr;</span><span class="fb p">override? use it : default</span><span class="arr">&rarr;</span><span class="fb t">COALESCE(value, default)</span><span class="arr">&middot;</span><span class="fb a">one lookup</span>',
      ins:'Reading a device&rsquo;s value is <b>override-over-default</b>: if the entity has a row in entity_value, use it; otherwise fall back to the definition&rsquo;s <code>default_value</code>. It&rsquo;s a <code>COALESCE</code> across a left join &mdash; one lookup, deterministic.',
      code:'<span class="c">// override-over-default: COALESCE(the entity&#39;s value, the definition&#39;s default)</span>\n<span class="k">SELECT</span> d.name,\n       <span class="hl">COALESCE</span>(ev.value, d.default_value) <span class="k">AS</span> value\n<span class="k">FROM</span> attribute_definition d\n<span class="k">LEFT JOIN</span> entity_value ev\n  <span class="k">ON</span> ev.attribute_id = d.id <span class="k">AND</span> ev.entity_id = $1;',
      cap:'<code>COALESCE(override, default)</code> is the resolution rule in one line: the left join finds an override if it exists, and <code>COALESCE</code> falls through to the default when it doesn&rsquo;t. Because overrides are sparse, most attributes resolve straight to the default &mdash; correct, and cheap.' },
    { k:"Step 6 / 9", t:"Reconstruct the whole entity",
      flow:'<span class="fb n">all attributes for entity</span><span class="arr">&rarr;</span><span class="fb p">N value rows</span><span class="arr">&rarr;</span><span class="fb t">pivot back to one object</span><span class="arr">&middot;</span><span class="fb r">the EAV tax</span>',
      ins:'To hand an API a device&rsquo;s <i>full</i> config, you gather <b>all its attribute rows</b> and <b>pivot</b> them back into one row-shaped object. This is the <b>EAV tax</b>: what a fixed schema returns as one row, EAV returns as N rows you reassemble.',
      deep:'The reconstruction is where you feel the cost of the flexibility. A normal table gives you a device in one row read; EAV stores each attribute as its own row, so &lsquo;give me device X&rsquo;s whole config&rsquo; is <b>N rows &rarr; one object</b> &mdash; a pivot (a <code>crosstab</code>, or grouping in the app). Done naively, per-attribute, that&rsquo;s the <b>N+1 query</b> that kills EAV performance; done right, it&rsquo;s <i>one</i> query fetching all of an entity&rsquo;s value rows (plus the definitions for defaults) and a single pivot in memory. The senior instinct is to never loop attributes: fetch the set, pivot once. And to recognize that if you&rsquo;re reconstructing whole entities constantly <i>and</i> querying across attributes, you may be paying the EAV tax for something that wanted a real schema.' },
    { k:"Step 7 / 9", t:"Make an attribute searchable",
      flow:'<span class="fb n">is_searchable attribute</span><span class="arr">&rarr;</span><span class="fb p">composite partial index (attribute_id, value)</span><span class="arr">&rarr;</span><span class="fb t">query across devices</span><span class="arr">&middot;</span><span class="fb a">not every value</span>',
      ins:'You can&rsquo;t cheaply index <i>every</i> value, so specific attributes are marked <b>searchable</b> &mdash; backed by a <b>composite partial index</b> on <code>(attribute_id, value)</code> where <code>is_searchable</code>. Now &lsquo;all devices where attribute X = Y&rsquo; is a seek, not a full scan.',
      code:'<span class="c">// index only the attributes flagged searchable -- keeps the index small</span>\n<span class="k">CREATE INDEX</span> idx_searchable\n  <span class="k">ON</span> entity_value (attribute_id, value)\n  <span class="k">WHERE</span> attribute_id <span class="k">IN</span> (<span class="c">/* the searchable set */</span>);\n<span class="c">// query: WHERE attribute_id = X AND value = Y  ->  index seek across devices</span>',
      cap:'The <b>partial</b> index is the point: indexing every value row would be huge and mostly useless, so you index only the handful of attributes people actually filter on. It&rsquo;s the EAV answer to &lsquo;how do I query by an attribute&rsquo; without giving every attribute a column &mdash; searchability is <b>opt-in</b>, and the index stays small.' },
    { k:"Step 8 / 9", t:"Secrets get special handling",
      flow:'<span class="fb n">is_secret attribute</span><span class="arr">&rarr;</span><span class="fb p">KMS-encrypted at rest</span><span class="arr">+</span><span class="fb t">masked at API</span><span class="arr">&middot;</span><span class="fb a">never plaintext out</span>',
      ins:'Some attributes are <b>secrets</b> &mdash; an API key, a certificate. Those are <b>KMS-encrypted at rest</b> and <b>masked at the API layer</b> so they&rsquo;re never returned in plaintext (you see <code>****</code>, or write-only). A config flag and a credential can&rsquo;t be stored the same way.',
      deep:'Treating every attribute identically is the trap; a secret has a different threat model than a timeout. Two controls, at two layers. At <b>rest</b>, an <code>is_secret</code> value is encrypted with a KMS key (ideally per-tenant, so it inherits the crypto-shred and blast-radius story from the hardening topic) &mdash; a database dump doesn&rsquo;t leak it. At the <b>API</b>, it&rsquo;s masked: reads return a placeholder, not the value, so the secret is write-only from the outside and only the systems that need it decrypt it. The reason this lives in the attribute store at all is that secrets <i>are</i> per-device config &mdash; but flagging them <code>is_secret</code> routes them down the encrypted, masked path instead of the plaintext one. Same store, different handling, driven by one flag on the definition.' },
    { k:"Step 9 / 9", t:"Staging, bulk import, and change capture",
      flow:'<span class="fb n">is_staged write</span><span class="arr">&rarr;</span><span class="fb p">promote to live</span><span class="arr">&middot;</span><span class="fb t">CSV import (coerce per definition)</span><span class="arr">&middot;</span><span class="fb a">CDC &rarr; downstream</span>',
      ins:'Values can be written <b>staged</b> (<code>is_staged</code>) and <b>promoted to live</b> atomically &mdash; so you prepare a device&rsquo;s config and flip it on in one step. Bulk changes come via <b>CSV import</b> (bounded &mdash; <code>MAX_ROWS 500</code>, 5 MB &mdash; each cell coerced to its attribute&rsquo;s type), and changes stream out via <b>CDC</b>.',
      deep:'The last mile is operating the store safely at fleet scale. <b>Staging</b> decouples &lsquo;write the config&rsquo; from &lsquo;make it live&rsquo;: you stage a set of overrides, review them, and promote atomically, so a device never runs a half-applied config &mdash; the same reason you don&rsquo;t deploy half a release. <b>Bulk import</b> is how operators set attributes across many devices at once, and it&rsquo;s <b>bounded on purpose</b> (row and size caps) with <b>per-attribute type coercion</b> and validation, because an unbounded, unvalidated CSV is how you poison the store with garbage in one paste. And <b>CDC</b> means the store isn&rsquo;t a silo: when a value changes, the change is captured and streamed, so caches, search indexes, and the devices themselves stay in sync without polling the whole table. Flexibility at the core, guardrails at the edges.' }
  ],
  modelScript: [
    { ml:'Frame the boundary', t:'"The problem is a config surface that grows faster than migrations can keep up &mdash; 50,000 devices, many types, product adding settings constantly. So I model attributes as data, not schema: a new setting is a row, not an ALTER TABLE."' },
    { ml:'The two tables', t:'"Two tables. A definition table &mdash; the attribute&rsquo;s contract: name, type, default, a JSON-Schema, and flags. And a value table &mdash; per-entity overrides, sparse, one row per entity-attribute. The definition is what keeps schemaless from meaning anything-goes."' },
    { ml:'Resolution', t:'"Reading a device&rsquo;s value is override-over-default &mdash; COALESCE the entity&rsquo;s override with the definition&rsquo;s default. One lookup. Most attributes resolve straight to the default, because overrides are sparse."' },
    { ml:'Validate on write', t:'"Every write is typed and JSON-Schema-validated &mdash; because the database can&rsquo;t enforce &lsquo;positive integer&rsquo; on a generic value column anymore, I enforce it at the write path, once. A bad value is rejected at write, so readers can trust the store."' },
    { ml:'Name the EAV tax', t:'"The cost I&rsquo;d name upfront: reconstructing a whole entity is a pivot &mdash; N rows back to one object &mdash; and querying across attributes needs a composite partial index on the searchable ones. EAV buys flexibility with query complexity; you pay it on purpose."' },
    { mq:'Interviewer: "Product wants to filter devices by three attributes at once and sort by a fourth. Walk me through that query &mdash; and whether EAV was the right call."' },
    { ml:'Answer the query reality', t:'"That&rsquo;s the EAV tax at its sharpest: filtering by multiple attributes means multiple self-joins or a pivot, and it gets ugly fast. If the searchable attributes are indexed, each filter is a seek, but combining them is still self-joins. And honestly &mdash; if I&rsquo;m constantly querying and sorting across a <i>fixed</i> set of attributes, those attributes wanted to be real columns. EAV is for the sparse, variable long tail; the hot, queried few belong in the schema."' },
    { ml:'Land it', t:'"So: attributes as rows for the flexible long tail, definition/value split with COALESCE resolution, typed and validated on write, secrets masked and encrypted, searchable ones indexed &mdash; and the judgment to promote hot attributes to real columns. The hard part isn&rsquo;t the storage; it&rsquo;s knowing what belongs in EAV and what doesn&rsquo;t."', ans:true }
  ]
};
