/* topics/content-pipeline/drill.js -- Phase 1: REAL drill data (the cross-pane BANK
   source). Seeds the working-set globals cards/speakLines (declared + owned by
   topic-protocol.js) with the real 20-probe bank, then TOPIC_CP_DRILL aliases the
   SAME arrays plus the 4 per-tier notes. Loads BEFORE bank.js + register in this
   bundle, so bank.cards captures the real array and publishBanks() seeds the globals
   at boot (mock-run + mixed-fire read them). speak[i] pairs cards[i] -- order is
   load-bearing. The old pre-bundle homes drill/cards.js + drill/speak-lines.js (and
   their app.js include lines) are deleted; this file is the single source now.
   DRILL_TIER_CLASS + dShuffle stay module-level in drill/logic.js. Offline-safe. */
cards = [
  { tier:'SDE2', signal:'Memory model under streaming',
    q:"Export a 1,000,000-row CSV without OOM. How?",
    a:"Server-side cursor (<code>pg-query-stream</code>, batch 100) piped to the response. Backpressure throttles the cursor to the client\'s drain rate, so memory is <b>constant</b> regardless of row count.",
    f:[
      { q:"What sets the batch size &mdash; why 100, not 1 or 100,000?",
        a:"It\'s fetch granularity, not the memory ceiling. <b>batch=1</b> is a round-trip per row (crawls); <b>batch=100,000</b> holds a huge fetch buffer in RAM and stalls in bursts. 100 amortizes round-trips while staying tiny." },
      { q:"The client is on slow 3G and stops reading mid-download. What is your server doing right now?",
        a:"TCP window fills &rarr; <code>res.write()</code> returns false &rarr; transform stops &rarr; cursor stops &rarr; Postgres holds the cursor <b>open and idle</b>, pinning a connection. A slow-reader can exhaust the pool (slowloris). Fix: statement timeout, or stream to S3 + presigned URL." }
    ],
    senior:"Saying memory is constant <b>because of backpressure</b> &mdash; not just \"I\'d stream it\" &mdash; is the senior tell. Bonus for naming the held-cursor connection risk before being asked." },
  { tier:'SDE3', signal:'Cross-store consistency',
    q:"Import writes to Postgres AND S3. The DB write fails. What happens?",
    a:"<b>Dual-write hole:</b> the DB transaction rolls back, but the S3 objects don\'t &mdash; they\'re orphaned. Fix: track every created key, delete them in the <code>catch</code>.",
    f:[
      { q:"Your compensating delete <i>also</i> fails &mdash; S3 is throttling. Now what?",
        a:"Don\'t block the user request on best-effort cleanup. Record orphan keys to a durable cleanup queue and retry async with backoff. The real backstop is a <b>reconciler</b> sweeping S3 keys with no DB row." },
      { q:"Make the whole import idempotent so a retry is always safe.",
        a:"Content-hash keys (same bytes = same key &rarr; re-upload is a no-op), a DB <b>upsert</b> on a deterministic key, and the ladder\'s <code>name+version</code> REMAP to block duplicate logical rows. A retried import <b>converges</b>." },
      { q:"Is there a way to make the two writes atomic instead of reconciling after the fact?",
        a:"Yes &mdash; the <b>transactional outbox</b>, and reaching for it is the senior move because it kills the race instead of healing it. The DB write and an <b>outbox-event</b> row commit in <b>one transaction</b> &mdash; either both land or neither does, so there&rsquo;s never a window where Postgres and S3 disagree. A separate <b>relay</b> reads the outbox and does the S3 work with <b>retries</b>, marking each event done. You&rsquo;ve collapsed a two-store dual-write into a <b>single atomic commit point</b> plus an idempotent relay. The catch: it needs a transactional store to anchor on &mdash; when the two stores genuinely can&rsquo;t share a transaction, the reconciler is the honest backstop. So I&rsquo;d frame it as <b>outbox to prevent, reconciler to heal</b>, and name which one the constraints allow." }
    ],
    senior:"Volunteering the <b>reconciler as the real backstop</b> &mdash; not just the catch-block delete &mdash; shows you\'ve operated this in production, not only designed it on a whiteboard." },
  { tier:'SDE2', signal:'I/O &amp; concurrency reasoning',
    q:"Why hash the file <i>while</i> uploading instead of after it\'s stored?",
    a:"A <code>PassThrough</code> forks <b>one</b> read into hash + upload. Hashing after = 2&times; disk reads; buffering-then-both = the whole file in RAM. The fork is the only option that survives a 500&nbsp;MB package.",
    f:[
      { q:"Some S3 APIs want Content-MD5 / length up front &mdash; but you don\'t know the hash until the stream ends. Tension?",
        a:"That\'s why <b>multipart</b> exists &mdash; no total length or whole-object hash needed up front; parts stream and S3 assembles. If an API truly needs the digest first, you must buffer or two-pass &mdash; the precise trade you\'re avoiding." },
      { q:"Two uploads of identical bytes race and compute the same key. What happens?",
        a:"On S3, last-write-wins on the same key &mdash; harmless, since content is identical. The contention point is the <b>DB dedup row</b>: <code>ON CONFLICT</code> on the hash so both converge to one row." }
    ],
    senior:"Surfacing the <b>Content-MD5 tension yourself</b>, before being asked, signals you know exactly where the streaming abstraction leaks." },
  { tier:'Staff', signal:'Architecture trade-offs &amp; scaling ceilings',
    q:"Why a Lambda per object instead of SQS + a worker pool?",
    a:"Zero ops and low latency at this volume. <b>Switch condition:</b> move to SQS the moment you need retries, a DLQ, or ordering. Naming the switch condition is what scores.",
    f:[
      { q:"S3 delivers the event twice (at-least-once). Walk me through preventing a double-processed file.",
        a:"Idempotent processing: a content-hash key + upsert, or a <b>processed-marker</b> (a DynamoDB conditional put on the key) the handler checks first. Never rely on exactly-once delivery." },
      { q:"10,000 objects land in one second. What breaks first, and what\'s your ceiling?",
        a:"<b>Lambda concurrency</b> throttles first &rarr; events retry / DLQ. Then the <b>DB pool</b> and <b>S3 PUT rate per prefix</b> saturate. Ceilings: concurrency (RDS Proxy / queue), connections, per-prefix rate (spread keys). At firehose scale, buffer through SQS/Kinesis." }
    ],
    senior:"Giving the <b>switch condition</b> &mdash; the exact threshold where you\'d move to SQS &mdash; instead of defending one choice is the senior move. Naming concrete ceilings seals it." },
  { tier:'SDE2', signal:'Data modeling &amp; idempotent import',
    q:"Why ship the export as a SQLite bundle instead of JSON?",
    a:"SQLite keeps <b>real foreign keys</b> and stores BLOBs at <b>1:1</b> size. JSON base64-bloats binary ~33% and loses referential integrity &mdash; you\'d rebuild the graph by hand on import.",
    f:[
      { q:"On import, ids collide with existing rows. Your algorithm?",
        a:"The 4-tier ladder: <code>id+company</code> REUSE, <code>name+version</code> REMAP, <code>id-taken</code> REGEN, else INSERT &mdash; record <code>oldId&rarr;newId</code> and rewrite child FKs before insert." },
      { q:"Why check name+version BEFORE the id-collision rule?",
        a:"So a re-import <b>de-dupes</b> (REMAP to existing) instead of forking a new uuid (REGEN). Swap the order and every re-import silently <b>doubles</b> your data." }
    ],
    senior:"Explaining <b>why</b> name+version is checked first &mdash; the de-dupe-vs-fork consequence &mdash; is what separates \"I wrote an importer\" from \"I designed one.\"" },
  { tier:'Staff', signal:'Irreversible-decision foresight',
    q:"You set the S3 trigger prefix to <code>uploads/</code>. What\'s the future risk?",
    a:"S3 notifications <b>forbid overlapping prefixes</b>, so you can\'t later split <code>uploads/</code> into <code>uploads/images/</code> without reconfiguring everything. One-way door &mdash; design the taxonomy before the first trigger ships.",
    f:[
      { q:"You\'re forced to add per-type routing later anyway. How, without re-architecting?",
        a:"Move routing out of <b>S3 config</b> (rigid) into <b>code</b>: one trigger on <code>uploads/</code>, dispatch inside the Lambda by key sub-prefix or metadata &mdash; or fan out (Lambda &rarr; an SQS queue per type). Flexibility lives in code, not the bucket." }
    ],
    senior:"Calling it a <b>one-way door</b> and pre-deciding the taxonomy shows you reason about <b>irreversibility</b> &mdash; a staff-level instinct most candidates skip." },
  { tier:'EXTEND', signal:'Design adaptability',
    q:"Product wants live video <i>transcoding</i> added (not just thumbnails). How does your pipeline change?",
    a:"Transcoding is long-running and CPU/GPU-heavy &mdash; it doesn\'t belong on Lambda (15-min cap, no GPU). Keep the <b>strategy-dispatch pattern</b>: add a video handler, but instead of processing inline it <b>enqueues a job</b> to ECS / MediaConvert. The S3 event still triggers; the handler fans out and the status flow gains a PROCESSING &rarr; TRANSCODED state.",
    f:[
      { q:"Now a live-preview feature needs that content processed in under 2 seconds. What changes?",
        a:"The async S3-event path is eventual &mdash; too slow. Add a <b>synchronous fast-path</b>: small previews process inline in the request and skip the queue; heavy/bulk stays async. Two-tier by interactivity. Cache by content hash so repeat previews are instant." },
      { q:"How do you keep ONE codebase serving both the fast sync path and the heavy async path?",
        a:"The dispatch map stays the single entry point; the handler branches on a <b>size/mode flag</b> &mdash; inline for small+interactive, enqueue for large+bulk. Same contract, same handlers; only the execution venue differs. The strategy pattern earning its keep." }
    ],
    senior:"Extending the design <b>along its grain</b> &mdash; preserving the dispatch pattern while moving heavy work to the right compute, rather than bolting on a parallel system &mdash; plus naming the sync/async two-tier split, is the senior instinct." },
  { tier:'SDE3', signal:'Security boundary &amp; least-privilege',
    q:"A client\'s upload credential leaks. What can an attacker do, and how do you shrink the blast radius?",
    a:"A broad credential reads the whole bucket and overwrites anything. Shrink it with a <b>presigned URL</b> scoped to one key + a short TTL (minutes) &mdash; a leaked URL is then one upload, not the bucket. The processing role is separate and read-only on the upload prefix.",
    f:[
      { q:"A presigned URL still lets anyone holding it upload until it expires. Tighten it further.",
        a:"Bake conditions into the policy: <code>Content-Length-Range</code> caps size, <code>Content-Type</code> pins the format, a per-user key prefix isolates tenants. The URL becomes a <b>single-purpose token</b> &mdash; one file, one size, one type, one place." },
      { q:"A malicious upload (zip bomb, polyglot) reaches a processor. Stop it taking down the fleet.",
        a:"Validate before processing, not at upload: cap decompressed size, check magic bytes against the claimed type, and run processing in an <b>isolated, resource-capped sandbox</b> (separate function/container with memory + time limits) so one bad object can\'t take the fleet down." }
    ],
    senior:"Turning a credential into a <b>single-purpose token</b> with size/type/prefix conditions &mdash; and sandboxing untrusted input &mdash; is the containment instinct senior interviewers probe for." },
  { tier:'SDE3', signal:'Observability &amp; operability',
    q:"It\'s 3 AM, the pipeline is \'slow,\' and you have no logs in front of you. What four signals do you wish you\'d instrumented?",
    a:"<b>Queue depth / event age</b> (is work piling up?), <b>processing latency p99</b> (are jobs individually slow?), <b>error + DLQ rate</b> (are things failing?), and <b>reconciler orphan count</b> (is the dual-write leaking?). Those four localize almost any incident to a stage.",
    f:[
      { q:"Queue depth is climbing but error rate is flat. What does that tell you?",
        a:"Not failures &mdash; <b>throughput</b>. Consumers can\'t keep up with arrival rate: either a downstream dependency slowed (raising per-job latency) or concurrency is throttled. You scale consumers or fix the slow dependency &mdash; chasing errors finds nothing." },
      { q:"What\'s the one thing you page a human for, versus just log?",
        a:"Page on <b>sustained DLQ growth</b> or <b>event age past SLA</b> &mdash; those mean work is silently not getting done. Transient spikes that self-heal via retry are log-only; paging on them is alert fatigue. Alert on <i>symptoms users feel</i>, not every internal hiccup." }
    ],
    senior:"Choosing the <b>four signals that localize an incident</b> and splitting page-worthy (SLA breach, DLQ growth) from log-only (self-healing retries) shows you\'ve carried a pager, not just shipped features." },
  { tier:'Staff', signal:'The exactly-once illusion',
    q:"A processor pulls a message, does the work, then crashes <i>before</i> deleting it. It redelivers. How do you avoid doing the work twice?",
    a:"You can\'t buy exactly-once <b>delivery</b> &mdash; you engineer idempotent <b>effects</b>. Make the write a no-op on replay: a <b>processed-marker</b> (conditional put on the content/message key) the handler checks-and-sets first, so the second delivery sees \'already done\' and acks without re-running.",
    f:[
      { q:"The side effect can\'t be made idempotent &mdash; it charges a card / sends an email. Now what?",
        a:"Put it behind an <b>idempotency key</b> the downstream honors (Stripe-style): same key, same charge, executed once. If the downstream can\'t dedupe, use a <b>transactional outbox</b> &mdash; record intent atomically with the state change, then a relay delivers with dedup downstream." },
      { q:"Where do you store the marker so the check and the work don\'t themselves race?",
        a:"They must commit <b>atomically</b> or the check is a TOCTOU bug. Either the marker lives in the same DB transaction as the write (one commit), or the conditional put <i>is</i> the lock &mdash; first writer wins the key, losers back off. The marker can never be a separate best-effort call." },
      { q:"The marker table grows forever &mdash; one row per message ever processed. You want to expire old markers, but won&rsquo;t that let a late redelivery slip through and double-process?",
        a:"Yes &mdash; and that&rsquo;s the real tradeoff, not a detail. I TTL the markers to a window <b>longer than the maximum redelivery horizon</b> &mdash; the queue&rsquo;s retention plus its visibility-timeout ceiling &mdash; so anything that could still redeliver still finds its marker. Past that horizon a redelivery is effectively impossible, so expiring is safe. For effects that are <b>catastrophic to repeat</b> &mdash; a charge &mdash; I don&rsquo;t TTL at all: keep the key permanently, and if storage is the worry, age cold keys into a cheaper tier or a bloom filter for the &lsquo;definitely seen&rsquo; check. The point: marker retention is a <b>correctness</b> parameter, not a cleanup job &mdash; you size it against the redelivery window, never shorter." }
    ],
    senior:"Naming that exactly-once <b>delivery</b> is impossible and you build idempotent <b>effects</b> instead &mdash; plus the atomic check-and-set so the marker doesn\'t itself race &mdash; is the distributed-systems maturity Staff rounds dig for." },
  { tier:'SDE3', signal:'Large-object transfer mechanics',
    q:"A 500&nbsp;MB upload fails at 80% over flaky mobile. Does the user restart from zero?",
    a:"Not with <b>multipart upload</b>: the file is split into parts (e.g. 8&nbsp;MB), each uploaded and ack\'d independently, so a failed part retries alone. The client resumes by re-sending only the missing parts; S3 assembles on <code>CompleteMultipartUpload</code>.",
    f:[
      { q:"The upload is abandoned at 80% and never completed. What\'s in your bucket, and what does it cost?",
        a:"Uncompleted multipart uploads leave <b>orphaned parts</b> &mdash; they consume storage but don\'t show in normal listings, so it\'s a silent bill. Fix: an <b>S3 lifecycle rule</b> to abort incomplete multipart uploads after N days. A classic cost leak." },
      { q:"Does your S3 trigger fire per part or once &mdash; and why does it matter?",
        a:"Once &mdash; <code>s3:ObjectCreated:CompleteMultipartUpload</code> fires on assembly, not per part, so the handler sees one complete object, not 60 fragments. Subscribe to the complete event or you\'ll process partial garbage." }
    ],
    senior:"Knowing multipart resumes <b>per part</b>, that abandoned uploads silently bill via orphaned parts (lifecycle rule to abort), and that the trigger fires once on completion &mdash; these specifics separate \'used S3\' from \'operated S3 at scale.\'" },
  { tier:'Staff', signal:'Reconciler correctness under concurrency',
    q:"Your reconciler deletes S3 keys with no DB row. An upload is <i>in flight</i> &mdash; object written, row not yet committed. Walk me through the bug and the fix.",
    a:"<b>Race:</b> the reconciler sees an object with no row and deletes a perfectly good in-flight upload. First fix is a <b>grace period</b> &mdash; only reconcile objects older than, say, an hour (longer than any legitimate write window), so in-flight uploads are never eligible.",
    f:[
      { q:"A grace period is a guess. Make the reconciler correct, not just probably-correct.",
        a:"Make intent explicit: write a <b>pending marker</b> (a PENDING row, or an object tag) <i>before</i> the upload, flip to COMMITTED after. The reconciler deletes only objects with <b>no marker at all</b> &mdash; never a PENDING one. Correctness stops depending on a timing guess." },
      { q:"The reconciler itself races a writer: reads \'no row,\' writer commits, reconciler deletes. Still broken?",
        a:"Yes &mdash; a TOCTOU window. Close it with a <b>conditional delete</b> that re-checks for the row inside the delete, or have the writer claim the key first (PENDING) so the reconciler acts on an unambiguous marker, not a snapshot it may have read stale." },
      { q:"To spread load, your reconciler checks &lsquo;is there a row?&rsquo; against a <b>read replica</b>. What goes wrong?",
        a:"It deletes live data. A replica lags the primary, so &lsquo;no row&rsquo; can mean &lsquo;the row committed but hasn&rsquo;t replicated yet&rsquo; &mdash; the reconciler reads stale, sees an orphan that isn&rsquo;t one, and deletes an object whose record exists on the primary. The fix: the <i>delete decision</i> must read from the <b>primary</b>, or a read guaranteed to reflect committed writes &mdash; never a lagging replica. It can list candidate keys off a replica for cheapness, but it has to confirm against authoritative state before deleting. The rule worth saying out loud: a <b>destructive action can never be driven by an eventually-consistent read</b>." }
    ],
    senior:"Spotting that the naive reconciler <b>deletes in-flight uploads</b>, rejecting the grace-period guess for an explicit <b>PENDING marker</b>, then closing the reconciler\'s own TOCTOU window &mdash; that layered correctness reasoning is the Staff-level depth this whole pipeline is built to probe." },
  { tier:'SDE3', signal:'Cost modeling & the hidden bill',
    q:"This pipeline processes 10M files a day. Where does the AWS bill actually go &mdash; and what's the line item that surprises people?",
    a:"Not compute &mdash; <b>S3 requests and data transfer</b>. At 10M/day, PUTs alone run ~$50/day ($0.005 per 1K); GETs on every read, plus cross-AZ transfer when compute and bucket disagree on region, dwarf the Lambda-seconds. The surprise line is <b>NAT Gateway data processing</b> &mdash; a VPC Lambda reaching S3 without a gateway endpoint pays per-GB on top.",
    f:[
      { q:"Halve the cost without dropping a file. First move?",
        a:"An <b>S3 gateway VPC endpoint</b> &mdash; it's free, and it removes NAT and transfer charges for bucket traffic entirely. Then batch small files so you issue fewer PUTs, and add lifecycle rules to tier cold objects to S3-IA / Glacier. Compute is rarely the lever." },
      { q:"Lambda vs Fargate for this &mdash; when does the cost curve flip?",
        a:"Lambda wins for <b>spiky, short, sub-second</b> work &mdash; you pay nothing idle. It flips to Fargate / ECS when invocations run long or go <b>sustained and high-volume</b>: past roughly one continuous vCPU of steady load, always-on Fargate beats per-ms Lambda. Duration &times; frequency is the deciding product." }
    ],
    senior:"Naming <b>requests and transfer</b> &mdash; not compute &mdash; as the real bill, and reaching for a <b>gateway endpoint</b> before micro-optimizing code, shows you've read an actual AWS invoice. Knowing the Lambda&rarr;Fargate flip point seals it." },
  { tier:'SDE3', signal:'Format & schema evolution',
    q:"Your export is a CSV other teams' importers consume. You need to add a column. How do you ship it without breaking them?",
    a:"<b>Append-only, never reorder.</b> Add the new column at the <b>end</b>, optional with a sane default &mdash; positional importers keep working, header-based ones pick it up. Breakage comes from <b>inserting or renaming</b> columns, which shifts every downstream index.",
    f:[
      { q:"An old importer must keep running for a year, but new consumers need a nested structure CSV can't express. Now what?",
        a:"<b>Version the format &mdash; don't mutate one.</b> Emit a <code>v2</code> (JSON / Parquet) alongside the frozen <code>v1</code> CSV; a <b>version field or path</b> selects the reader. Expand-then-contract: dual-publish, migrate consumers, retire v1 once its usage hits zero." },
      { q:"How do you know when it's actually safe to retire v1?",
        a:"You don't guess &mdash; you <b>instrument it</b>. Emit a metric per format version on read, or track last-access per consumer. Retire v1 only after its read count has been zero for a full cycle. Schema retirement is a data-driven call, not a calendar one." }
    ],
    senior:"Separating a <b>backward-compatible append</b> from a breaking reorder, escalating to <b>versioned formats with expand / contract</b> instead of mutating in place, and gating retirement on <b>measured usage</b> &mdash; that's how schema changes ship safely in production." },
  { tier:'Staff', signal:'Backpressure through a forked stream',
    q:"In the handler, one read forks to hash and S3 upload. Hashing is instant; the upload is slow. What happens to the pipe &mdash; and to memory?",
    a:"The fork runs at the speed of its <b>slowest consumer</b>. The <code>PassThrough</code> feeding S3 fills to its <code>highWaterMark</code>, stops draining, and that backpressure propagates <b>back through the tee</b> to the source read &mdash; so the fast hash branch is throttled to the upload's pace. Memory stays bounded at the buffer size; unread chunks do <b>not</b> pile up.",
    f:[
      { q:"Someone 'fixes' the slowness by unpiping S3 and pushing chunks to it in a manual loop. What did they just break?",
        a:"They <b>defeated backpressure</b>. A manual <code>.write()</code> that ignores the <b>false</b> return value buffers unboundedly &mdash; the slow branch silently accumulates the whole file in RAM. The return-value contract <i>is</i> the flow control; bypassing it is how streaming OOMs come back." },
      { q:"Two branches, very different speeds. One shared highWaterMark, or different ones?",
        a:"Independent buffers, tuned per branch. The slow S3 branch may want a <b>larger</b> highWaterMark to keep the pipe full across network jitter; the instant hash branch needs almost none. One global value either starves the network branch or wastes RAM on the fast one &mdash; match the buffer to each consumer's latency." }
    ],
    senior:"Explaining that a fork runs at its <b>slowest consumer</b> and that backpressure propagates <i>back through the tee</i> to throttle the fast branch &mdash; then catching that a manual <code>.write()</code> defeats the flow-control contract &mdash; is the stream-internals depth most candidates only hand-wave." },
  { tier:'Staff', signal:'Data deletion &amp; the right to be forgotten',
    q:"A user invokes their right to be forgotten &mdash; purge everything tied to their content. Walk me through it across this pipeline.",
    a:"<b>Deletion is its own pipeline, not a single DELETE.</b> It spans the dual store &mdash; the S3 object <i>and</i> the catalog row &mdash; so it carries the same orphan risk as the dual-write, handled the same way: a tombstone, a tracked compensating delete, the reconciler as backstop. The hard part is everything <i>downstream</i> of the primary stores &mdash; replicas, caches, search indexes, and the genuinely hard one, <b>backups</b>, which you cannot surgically edit.",
    f:[
      { q:"You cannot DELETE a row out of an immutable backup. So how is the user actually 'forgotten'?",
        a:"<b>Crypto-shredding.</b> Encrypt each user's content under a per-user key; deletion drops the key, so the backed-up ciphertext is unrecoverable without ever touching the backup. The honest alternative is a bounded <b>retention window</b> &mdash; backups age out in N days, so you commit to 'gone from live systems now, gone from backups within N days.' Both are defensible; claiming you surgically delete from a backup is not." },
      { q:"Your reconciler deletes S3 keys with no DB row. Deletion removes the row first &mdash; does the reconciler fight you, or quietly do your job?",
        a:"That is exactly why deletion cannot lean on a side effect. I make it explicit: a <b>tombstone</b> the reconciler reads, so a deleted object is a coordinated state, not an accidental orphan it happens to clean up. A compliance guarantee resting on reconciler timing is how you fail an audit &mdash; the deletion path owns the delete end to end and emits a <b>proof-of-deletion</b> record." }
    ],
    senior:"The level signal is treating deletion with the <b>same rigor as the write path</b> &mdash; dual-delete with compensation, an explicit tombstone the reconciler honors, an auditable proof record &mdash; plus an honest answer for backups (crypto-shred or retention) rather than hand-waving. Most candidates say 'delete the row' and miss that deletion is a pipeline, that backups are the hard part, and that a compliance promise cannot rest on a reconciler's timing." },
  { tier:'SDE3', signal:'Multi-tenant fairness',
    q:"A shared pipeline serves many tenants, and one just queued ten million files in a single burst. Every other tenant&rsquo;s work is now stuck behind it. How do you stop one tenant from starving the others?",
    a:"The root cause is a <b>single shared FIFO</b> &mdash; a FIFO is never fair under burst, so one tenant&rsquo;s flood owns the queue. The fix is <b>fair scheduling</b>, not a bigger queue: partition the work by a <b>tenant key</b> and have workers dequeue <b>round-robin (or weighted) across tenants</b> so no one backlog blocks another, plus a <b>per-tenant rate limit</b> &mdash; a token bucket per tenant &mdash; that throttles any single tenant to a fair share and buffers the excess instead of letting it block. Fairness is a <i>scheduling</i> property you build in, not something a FIFO hands you.",
    f:[{q:"A physical queue per tenant, for thousands of tenants?",a:"No &mdash; the isolation is <i>logical</i>. One queue <b>partitioned by tenant key</b> (Kafka partitions, or a tenant attribute on the message), and the <b>consumer</b> does the fair part: it dequeues round-robin across tenant keys and caps per-tenant in-flight work. The scheduling discipline lives in the consumer, not in thousands of physical queues &mdash; that&rsquo;s fairness that scales."},{q:"And the burst that&rsquo;s already stuck right now?",a:"Triage first: lift the offending batch onto a <b>separate low-priority lane</b> so everyone else drains immediately, then let it catch up at a throttled rate. Isolate the noisy tenant now, fix the structure so it can&rsquo;t recur."}],
    senior:"The tell is naming fairness as a <b>scheduling discipline in the consumer</b> &mdash; partition by tenant key, round-robin, rate-limit each &mdash; rather than reaching for a bigger queue or a queue-per-customer. Juniors scale the queue; seniors schedule across tenants." },
  { tier:'Staff', signal:'Blast radius when down',
    q:"Your pipeline has been down for two hours and on-call is asking whether the device fleet is broken. What&rsquo;s the actual blast radius?",
    a:"The senior move is separating &lsquo;the pipeline is down&rsquo; from &lsquo;the system is broken&rsquo; &mdash; they aren&rsquo;t the same, and saying why is the answer. Downstream is a <b>pull plus desired-state</b> model: devices run on their <b>last-reconciled state</b>, so an outage never touches what&rsquo;s already deployed &mdash; the fleet keeps running on its last-known-good config. Inbound work isn&rsquo;t lost either: uploads land in <b>durable storage</b> and the queue holds the events, so changes are <b>delayed, not dropped</b>, and drain when the pipeline recovers. So the real blast radius is bounded to one thing &mdash; <i>config changes stop propagating</i>. Nothing in flight is lost, nothing already live breaks. That&rsquo;s the line between an availability blip and an outage.",
    f:[{q:"What WOULD make it a real outage, then?",a:"A device needing a <b>fresh</b> config it has never seen &mdash; a brand-new device onboarding, or an urgent <b>security rotation</b> that has to reach the fleet <i>now</i>. For those, &lsquo;delayed&rsquo; is &lsquo;broken.&rsquo; So I name the exception: steady-state is fine, but time-critical pushes are the part of the blast radius that actually hurts &mdash; and that&rsquo;s what the SLO should be written against, not the average case."},{q:"How do you stop the queue overflowing during a two-hour outage?",a:"The queue is durable and sized for backlog, so two hours of inbound buffers fine &mdash; that&rsquo;s the whole point of decoupling. The real risk is <b>recovery</b>: the pipeline comes back to a thundering backlog, so I drain at a <b>controlled rate</b> (bounded worker concurrency, not all-at-once) to keep recovery from hammering the downstream stores. Absorb during the outage, drain deliberately after."}],
    senior:"The tell is refusing the premise &mdash; &lsquo;down&rsquo; is not &lsquo;broken.&rsquo; A senior bounds the blast radius (steady-state keeps running, changes delayed not lost), names the one exception that genuinely hurts (time-critical pushes), and treats recovery as its own problem. Juniors say &lsquo;it&rsquo;s down, everything&rsquo;s broken&rsquo;; seniors scope the damage." },
  { tier:'SDE3', signal:'Testing &amp; confidence under failure',
    q:"How would you test this pipeline? Specifically &mdash; how do you gain confidence it&rsquo;s correct under <b>failure and concurrency</b>, not just the happy path?",
    a:"The happy-path tests are the easy part &mdash; the bugs live in redelivery, partial failure, and concurrency, so that&rsquo;s where the testing has to aim. I&rsquo;d layer it: <b>unit</b> on the pure logic (the extension&rarr;handler dispatch, the idempotency-key derivation, the oldId&rarr;newId FK remap); <b>integration</b> against real storage and a real DB or localstack for the full upload&rarr;record path; and a <b>contract test on the strategy map itself</b> &mdash; assert every registered extension has a handler and every handler is registered, because that map drifting is exactly how an unknown type starts silently skipping. But the part that earns confidence is testing the <i>hard</i> properties. Fire the <b>same event twice, then N times concurrently</b>, and assert exactly one record and one set of derived artifacts &mdash; that&rsquo;s the test most teams skip and the one at-least-once delivery will eventually break in production. Then <b>fault injection</b>: kill the worker mid-handler, after the hash but before the DB write, and assert the retry converges to a clean state with no orphaned object. And run the <b>reconciler concurrently with live writes</b> over a seeded-inconsistent state, asserting it converges without double-deleting. The honest part: you can&rsquo;t test &lsquo;exactly once&rsquo; into existence &mdash; so I test the guarantees that are actually real, <b>idempotency and convergence</b>, and use fault injection plus invariant assertions for the rest.",
    f:[{q:"What&rsquo;s the one test most teams skip that catches the most bugs?",a:"The <b>concurrent-duplicate</b> test &mdash; deliver the same event many times in parallel and assert a single record and a single set of side effects. Sequential redelivery is easy; the <i>race</i> &mdash; two workers on the same key at once &mdash; is where the idempotency check has a check-then-act gap, and at-least-once delivery guarantees you hit it eventually. If I write only one hard test, it&rsquo;s that one."},{q:"How do you keep the reconciler test from being flaky?",a:"Make it <b>deterministic</b>: inject the clock and the &lsquo;in-flight vs orphaned&rsquo; boundary so the decision is decidable instead of a race against wall-clock. Seed exact states &mdash; object-without-row, row-without-object &mdash; and assert convergence. For the concurrent case I drive a controlled interleaving, or run it many times under randomized scheduling and assert <b>invariants</b> (never double-delete, never drop a live object) rather than one exact trace. Test the property, not the output."}],
    senior:"The tell is aiming the tests at failure and concurrency rather than the happy path &mdash; plus the maturity to say out loud that some properties (exactly-once) can&rsquo;t be unit-tested, so you verify the weaker-but-real ones, idempotency and convergence, with fault injection and invariant assertions. Juniors recite the test pyramid; seniors name the <i>specific</i> hard test &mdash; the concurrent duplicate &mdash; and how they make non-determinism testable." },
  { tier:'Staff', signal:'Shipping a change to a live pipeline',
    q:"You need to ship a change to this pipeline &mdash; say a new field in the import format, or a change to how a handler writes records &mdash; while it&rsquo;s processing live traffic. How do you roll it out without downtime or corrupting data?",
    a:"The insight that drives everything: in a rolling deploy, <b>old and new workers run at the same time</b> against the same queue, so for a window both versions are processing the same events. That kills the naive &lsquo;just deploy v2&rsquo; &mdash; v2 can&rsquo;t emit anything v1 can&rsquo;t handle, or v1 chokes on v2&rsquo;s output mid-rollout. So I treat it as <b>expand, migrate, contract</b>: first deploy a version that <i>tolerates both</i> shapes &mdash; the reader ignores unknown fields and defaults missing ones, so it&rsquo;s backward- and forward-compatible; only once every worker can read the new shape do I flip the <b>writer</b> to emit it; and dropping the old path is a <i>third</i> deploy, after nothing produces the old shape anymore. For risk I <b>canary</b> &mdash; route one worker or a small slice of traffic to the new version, watch the error rate and the <i>derived-artifact correctness</i>, then ramp. And the change stays <b>idempotent and replay-safe</b>, so a worker picking up a half-processed event across the deploy converges instead of double-writing. The honest part is the <b>rollback asymmetry</b>: rolling back code is instant, but if v2 already <i>wrote</i> data v1 can&rsquo;t read &mdash; or wrote it wrong &mdash; a code rollback doesn&rsquo;t undo that. So the data change is forward-compatible by design, and anything destructive sits behind a <b>flag I can flip without a deploy</b>.",
    f:[{q:"Why not just deploy v2 everywhere at once?",a:"Because the queue holds in-flight events and workers don&rsquo;t cut over atomically &mdash; even a fast deploy has a window where old and new coexist, and any consumer lag widens it. If v2 writes a record shape v1 doesn&rsquo;t understand, v1 errors on &mdash; or silently mishandles &mdash; every event it picks up in that window. Expand/contract removes the assumption that there&rsquo;s ever a clean instant where only one version runs."},{q:"The canary looks clean, you ramp to 100%, and an hour later you find it was writing a subtly wrong field. Now what?",a:"Code rollback stops the bleeding but doesn&rsquo;t fix the hour of bad records &mdash; that&rsquo;s the asymmetry. So flip the writer back (or kill the flag), then run a <b>targeted backfill</b> over just the affected window, which I can scope because records are timestamped and the change is identifiable. That&rsquo;s exactly why the pipeline keeps enough provenance to ask &lsquo;everything written by v2 between T1 and T2,&rsquo; and why an irreversible write worries me more than a reversible one."}],
    senior:"The tell is knowing a rolling deploy means old and new run <i>concurrently</i>, so changes must be backward- and forward-compatible &mdash; expand, migrate, contract, never big-bang &mdash; and being honest that <b>rolling back code is not rolling back data</b>. Juniors say &lsquo;canary then ramp&rsquo;; seniors design the change so both versions coexist safely and so a bad write is <i>findable and reversible</i>, because the data is the part you can&rsquo;t just redeploy." },
  { tier:'SDE3', signal:'Compressing the export',
    q:"That 1,000,000-row CSV is ~400&nbsp;MB on the wire, and the terminals pulling it are on metered links. How do you cut the transfer?",
    a:"<b>Compress the stream, don&rsquo;t buffer-then-compress.</b> Pipe the cursor through the CSV transform, then through <code>zlib.createGzip()</code>, then to the response with <code>Content-Encoding: gzip</code> &mdash; so the gzip runs <i>inside</i> the same backpressured pipeline and memory stays constant. CSV is highly compressible (repeated delimiters, low-cardinality columns), so 400&nbsp;MB routinely drops to 30&ndash;50&nbsp;MB. The cost is server CPU; the win is bandwidth, transfer time, and &mdash; for an S3-staged export &mdash; storage and egress. You compress <i>as you stream</i>, never gzip a 400&nbsp;MB buffer you first built in RAM.",
    f:[
      { q:"Gzip is CPU. When is compressing actually the wrong call?",
        a:"When the client can&rsquo;t decompress, when the payload is small enough that the round-trip saving is noise, or when you&rsquo;re CPU-bound and bandwidth-rich &mdash; then the compression tax costs more than it saves. It&rsquo;s also wrong on <i>already-compressed</i> or high-entropy content (a column of random UUIDs, binary blobs) where gzip spends CPU for near-zero gain. The rule: compress high-volume, high-redundancy, bandwidth-constrained transfers; skip it when the data is incompressible or the link is already fast and the CPU isn&rsquo;t spare. A big low-cardinality CSV over metered mobile is squarely worth it." },
      { q:"You stage the export to S3 first, then hand out a presigned URL. Do you gzip before or after the upload?",
        a:"<b>Before</b> &mdash; store the object already-gzipped (<code>export.csv.gz</code>), so you pay compression once at write time and every download is small. Set the object&rsquo;s <code>Content-Encoding: gzip</code> so a browser client transparently inflates it, or hand the <code>.gz</code> to a device that inflates explicitly. Compressing after &mdash; letting a CDN or the client compress on the fly &mdash; re-pays CPU per download and doesn&rsquo;t shrink what&rsquo;s stored. Compress once at the source of truth, serve the small object many times: the same reason you don&rsquo;t re-render a cached artifact on every read." }
    ],
    senior:"Piping the cursor through <code>gzip</code> <i>inside</i> the backpressured stream (constant memory, <code>Content-Encoding: gzip</code>) rather than compressing a buffered blob &mdash; and knowing when compression is the wrong call (incompressible data, CPU-bound) and to compress-once at the S3 source &mdash; is the transfer-optimization depth a senior round rewards." },
  { tier:'SDE3', signal:'Resumable export',
    q:"The export streams for four minutes. At row 800,000 the terminal&rsquo;s connection drops. Does it re-download the whole file, or can it resume?",
    a:"A plain streaming response <b>restarts from zero</b> &mdash; the cursor was tied to that connection, so a drop means re-run. To make it resumable you <b>decouple the export from the delivery</b>: stage the export to S3 as an object, then hand out a presigned URL, and S3 serves it with <b>HTTP Range support</b> &mdash; the client re-requests <code>Range: bytes=N-</code> and resumes from where it stopped. For a live (non-staged) stream you&rsquo;d instead need a <b>resume token</b> &mdash; checkpoint the last-emitted primary key, and on reconnect continue <i>after</i> that key, which works precisely because the source read is an <b>ordered keyset</b>, not an OFFSET. The staged-object-plus-Range path is simpler and the one I&rsquo;d reach for.",
    f:[
      { q:"Why is the presigned-S3 path usually better than a resume token on the live stream?",
        a:"Because it makes resumption <b>S3&rsquo;s problem, not yours</b>: Range requests, retries, and partial delivery are built in and battle-tested, and the export is computed <i>once</i> into a stable object instead of re-running the query on every reconnect. A live resume token means re-issuing <code>WHERE id &gt; last_key</code> each time &mdash; correct only if the ordering is stable and nothing shifts the keyset under you &mdash; and it pins a DB connection for the whole slow download. Staging decouples &lsquo;produce the data&rsquo; from &lsquo;deliver the bytes,&rsquo; which is why it&rsquo;s the pattern for anything big and slow. You trade a little storage and latency-to-first-byte for robust, connection-independent delivery." },
      { q:"A resume token keyed on the last primary key &mdash; what breaks it, and how do you keep it correct?",
        a:"It breaks if the result set isn&rsquo;t <b>stably ordered</b>. Order by an immutable, unique key (the primary key), not a mutable column, so &lsquo;after key X&rsquo; is well-defined and can&rsquo;t skip or repeat rows. Rows inserted <i>after</i> the checkpoint with a higher key show up on resume (usually fine &mdash; the export reflects a moving table); a truly point-in-time export instead needs a <b>snapshot</b> &mdash; a repeatable-read transaction or an as-of timestamp &mdash; rather than a naive resume. The token is only as consistent as the ordering and isolation behind it, which is exactly why staging a snapshot into S3 sidesteps the whole class of problems." }
    ],
    senior:"Recognizing that a plain streamed export restarts from zero, and that resumption means <b>decoupling produce-from-deliver</b> &mdash; stage to S3 and let Range requests handle resume, or checkpoint an <i>ordered keyset</i> for a live token &mdash; plus the consistency caveat (stable ordering / snapshot isolation) is the delivery-robustness thinking that separates a senior answer from &lsquo;the user just retries.&rsquo;" }
];
speakLines = [
 "Open with the headline: <b>'I'd stream it with a server-side cursor so memory stays constant'</b> &mdash; then the backpressure, then flag the slow-reader connection risk.",
 "Lead with the failure: <b>'The risk here is a dual-write &mdash; the DB rolls back but S3 doesn't'</b> &mdash; then the compensating delete, then the reconciler as the real backstop.",
 "State the constraint first: <b>'I hash during the upload because reading twice or buffering won't survive 500MB'</b> &mdash; then describe the PassThrough fork.",
 "Don't defend a choice &mdash; give the rule: <b>'Lambda-per-object for this volume; I'd move to SQS the moment I need retries, a DLQ, or ordering.'</b>",
 "Anchor on the why: <b>'SQLite over JSON because I need real foreign keys and 1:1 BLOBs'</b> &mdash; bring out the conflict ladder only if pushed.",
 "Name the shape out loud: <b>'This is a one-way door &mdash; overlapping prefixes are forbidden, so I'd settle the taxonomy up front.'</b>",
 "Frame it as extending along the grain: <b>'I keep the dispatch pattern and move transcoding to ECS / MediaConvert'</b> &mdash; then the sync/async two-tier.",
 "Frame the blast radius first: <b>'a leaked broad credential reads the whole bucket'</b> &mdash; then scope it down: presigned URL, one key, short TTL, size/type conditions. Sandbox untrusted input.",
 "Answer in four signals, not prose: <b>'queue depth, p99 latency, DLQ rate, reconciler orphan count'</b> &mdash; then split page-worthy (SLA breach) from log-only (self-healing retries).",
 "Reframe the premise out loud: <b>'exactly-once delivery is impossible &mdash; I build idempotent effects'</b> &mdash; then the check-and-set marker, committed atomically with the work.",
 "Lead with the mechanism: <b>'multipart resumes per part, so they re-upload only what failed'</b> &mdash; then the orphaned-parts bill leak and the lifecycle abort rule.",
 "Name the bug out loud: <b>'the naive reconciler deletes in-flight uploads'</b> &mdash; reject the grace-period guess, use an explicit PENDING marker, then close the TOCTOU window.",
 "Redirect from compute to the real bill: <b>'at this scale it's S3 requests and transfer, not Lambda-seconds'</b> &mdash; then the free gateway endpoint, then the Lambda-to-Fargate flip point.",
 "Lead with the compat rule: <b>'append at the end, optional with a default &mdash; never reorder or rename'</b> &mdash; then versioned formats, expand-then-contract, retired on measured usage.",
 "Say what governs the fork: <b>'it runs at the slowest consumer &mdash; backpressure propagates back and throttles the fast branch'</b> &mdash; then that a manual .write() ignoring the false return is how OOM creeps back.",
 "Reframe it as a pipeline, not a DELETE: <b>'forgetting a user spans both stores, plus replicas, caches, and backups'</b> &mdash; dual-delete with a tombstone the reconciler honors, then the honest backups answer: crypto-shred the per-user key, or commit to a retention window.",
 "Lead with the diagnosis, not the fix: <b>&lsquo;a single shared FIFO is never fair under burst.&rsquo;</b> Then the fix in one breath &mdash; partition by tenant key, round-robin across tenants, rate-limit each &mdash; and land on the line that scores: fairness is a scheduling discipline in the consumer, not a bigger queue.",
 "Refuse the premise first: <b>&lsquo;down is not broken.&rsquo;</b> Then bound it &mdash; the fleet runs on last-reconciled state, changes are delayed not lost &mdash; name the one exception that hurts (a time-critical push to a device that needs a fresh config), and treat the recovery backlog as its own problem. Scoping the damage, instead of catastrophizing, is the senior move.",
 "Refuse the happy path first: the bugs live in redelivery, partial failure, and concurrency, so that&rsquo;s where the tests aim. Layer it &mdash; unit on the pure logic, integration on the full upload-to-record path, and a contract test on the strategy map so it can&rsquo;t silently drift. Then the test that earns confidence: fire the <b>same event N times concurrently</b> and assert exactly one record &mdash; the one most teams skip and the one at-least-once eventually breaks. Add fault injection, kill the worker mid-handler and assert the retry converges clean, and run the reconciler against live writes. Honest close: you can&rsquo;t test exactly-once into existence, so you test idempotency and convergence and assert invariants for the rest.",
 "The trap is &lsquo;just deploy v2&rsquo; &mdash; in a rolling deploy, old and new workers run at the same time on the same queue, so for a window both versions touch the same events. So go <b>expand, migrate, contract</b>: first ship a version that tolerates both shapes, then flip the writer to the new one, then remove the old path in a third deploy. Canary a small slice, watch error rate and artifact correctness, then ramp. And say the honest part out loud: rolling back code is instant, but if the bad version already wrote bad data, a code rollback doesn&rsquo;t fix it &mdash; so the data change is forward-compatible by design and destructive steps sit behind a flag. The senior move is making both versions coexist safely and making a bad write findable and reversible.",
 "Lead with the mechanism, not the idea: <b>'pipe the cursor through gzip inside the same backpressured stream, Content-Encoding: gzip'</b> &mdash; so memory stays constant and a 400&nbsp;MB CSV drops to 30&ndash;50&nbsp;MB. Then the honest boundary: skip compression on incompressible data or when you're CPU-bound, and compress <i>once</i> at the S3 source rather than per download.",
 "Refuse the naive answer first: <b>'a plain streamed export restarts from zero &mdash; the cursor died with the connection.'</b> Then the fix: stage to S3 and let presigned Range requests handle resume, or checkpoint an <i>ordered keyset</i> for a live resume token. Land on the caveat that scores &mdash; a resume token is only as correct as its ordering and isolation, which is why staging a snapshot sidesteps the problem."
];
var TOPIC_CP_DRILL = {
  cards: cards,
  speak: speakLines,
  tierNotes: {all:'<b>All four levels, mixed</b> &mdash; the way a real loop actually comes at you.',SDE2:'<b>Fundamentals under pressure</b> &mdash; memory model, I/O, idempotent writes. The bar is &ldquo;this won&rsquo;t fall over&rdquo;: show the mechanics cleanly.',SDE3:'<b>Depth &amp; trade-offs</b> &mdash; consistency, schema evolution, the hidden bill. The bar is &ldquo;it depends, here&rsquo;s the switch&rdquo;: never a one-size answer.',Staff:'<b>Systems judgment</b> &mdash; irreversibility, blast radius, the exactly-once illusion. The bar is &ldquo;I see the failure mode before it ships&rdquo;: name what breaks and name the backstop.'}
};
