/* topics/content-pipeline/walk.js -- topic-1 data for the WALKTHROUGH pane
   (TopicPane dataKey 'walk'). steps[9] is the guided trace (lifted VERBATIM from the
   former `var steps` in walkthrough/steps.js); modelScript[8] is the model-answer
   script (the 6 plain beats, the interviewer .mq line, then the .mbeat.ans -- which
   MUST stay LAST, the last-child CSS depends on it), lifted from the former baked
   blob in walkthrough/logic.js. Pure data: the div/span markup lives in renderBeat
   (logic.js), NOT here. Offline-safe; 7-bit ASCII (HTML entities). */
var TOPIC_CP_WALK = {
  steps: [
  { k:"Step 1 / 9", t:"Strategy dispatch",
    flow:'<span class="fb n">processUpload(key,bucket)</span><span class="arr">&rarr;</span><span class="fb n">extname(key)</span><span class="arr">&rarr;</span><span class="fb p">strategies[ext]</span><span class="arr">&rarr;</span><span class="fb t">handler</span><span class="arr">/</span><span class="fb a">skip</span>',
    ins:'A frozen object literal, not a switch. Lookup is <b>O(1)</b>; every handler shares one <code>(key,bucket) &rarr; Result</code> contract, so the dispatcher\'s cyclomatic complexity stays <b>1</b> forever.',
    deep:'The <code>Result</code> shape is normalized &mdash; image, video, font all return <code>{thumbnailKey, metadata, status}</code> &mdash; so the caller\'s PATCH-status logic is format-agnostic. Adding <code>.webp</code> is one map entry and zero caller changes.' },
  { k:"Step 2 / 9", t:"Single-read fork",
    flow:'<span class="fb n">createReadStream</span><span class="arr">&rarr;</span><span class="fb p">PassThrough</span><span class="arr">&rarr;</span><span class="fb t">hash.update</span><span class="arr">+</span><span class="fb r">s3.upload</span><span class="arr">&rarr;</span><span class="fb n">Promise.all</span>',
    ins:'One disk read, forked two ways. Buffer is <code>highWaterMark</code> (16&nbsp;KB) &mdash; never the file. When S3 lags, <code>write()</code> returns <b>false</b> and the source <b>pauses</b>, so RAM is flat at 500&nbsp;MB or 5&nbsp;GB.',
    code:'<span class="k">const</span> pass = <span class="k">new</span> PassThrough();\n<span class="k">const</span> hash = createHash(<span class="s">\'sha256\'</span>);\npass.on(<span class="s">\'data\'</span>, c => hash.update(c));      <span class="c">// consumer 1 (CPU)</span>\n<span class="k">const</span> up = s3.upload({ Bucket, Key, <span class="hl">Body: pass</span> }); <span class="c">// consumer 2 (net)</span>\ncreateReadStream(path).<span class="hl">pipe(pass)</span>;           <span class="c">// ONE disk read</span>\n<span class="k">await</span> up.promise();                        <span class="c">// pipe() handles backpressure</span>\n<span class="k">const</span> digest = hash.digest(<span class="s">\'hex\'</span>);',
    cap:'<code>pipe()</code> wires the pause/resume; the <code>data</code>-event hash rides the same buffer. Two consumers, one read.' },
  { k:"Step 3 / 9", t:"Cursor export",
    flow:'<span class="fb p">QueryStream(batch 100)</span><span class="arr">&rarr;</span><span class="fb n">csv-stringify</span><span class="arr">&rarr;</span><span class="fb t">res</span>',
    ins:'<code>DECLARE CURSOR</code>, 100 rows at a time, piped to the socket. A full TCP window backpressures the transform, which backpressures the cursor &mdash; Postgres fetches only as fast as the client drains. <b>Constant memory</b> at 1K or 10M rows.',
    deep:'Without the cursor, the pg driver buffers the <b>entire</b> result set in JS before your code runs &mdash; that\'s the OOM. The cursor turns one giant allocation into a stream of 100-row pages the GC reclaims between batches.' },
  { k:"Step 4 / 9", t:"Import conflict ladder",
    flow:'<span class="fb n">row</span><span class="arr">&rarr;</span><span class="fb t">id+co? REUSE</span><span class="arr">&rarr;</span><span class="fb a">name+ver? REMAP</span><span class="arr">&rarr;</span><span class="fb r">id taken? REGEN</span><span class="arr">&rarr;</span><span class="fb t">else INSERT</span>',
    ins:'Strict precedence. Checking <code>name+version</code> <b>before</b> id-collision means a re-import <b>de-dupes</b> (REMAP) instead of forking a new uuid (REGEN). Every REMAP/REGEN records <code>oldId&rarr;newId</code>, then rewrites child FKs before insert.',
    code:'<span class="k">const</span> idMap = <span class="k">new</span> Map();\n<span class="k">for</span> (<span class="k">const</span> row <span class="k">of</span> incoming) {\n  <span class="k">if</span> (<span class="k">await</span> match(row.id, row.company)) reuse(row.id);\n  <span class="k">else if</span> (<span class="k">await</span> match(row.name, row.version))\n       idMap.set(row.id, existing.id);   <span class="c">// REMAP (de-dupe)</span>\n  <span class="k">else if</span> (<span class="k">await</span> idExists(row.id))\n       idMap.set(row.id, uuid());        <span class="c">// REGEN (fork)</span>\n  <span class="k">else</span> insert(row.id);                  <span class="c">// INSERT</span>\n}\n<span class="k">for</span> (<span class="k">const</span> ch <span class="k">of</span> children)               <span class="c">// FK cascade</span>\n  ch.parent_id = idMap.get(ch.parent_id) ?? ch.parent_id;',
    cap:'<code>name+version</code> is checked before id-collision &mdash; that ordering is what makes a re-import REMAP instead of fork.' },
  { k:"Step 5 / 9", t:"Hash + multipart",
    flow:'<span class="fb t">sha256 streaming</span><span class="arr">&middot;</span><span class="fb n">&lt;5MB Put</span><span class="arr">/</span><span class="fb r">&ge;5MB multipart</span>',
    ins:'The digest is content-deterministic, so the <b>key is the hash</b> &mdash; identical bytes converge on one object (dedup). A failed multipart leaves orphan parts; an S3 lifecycle rule aborts incomplete uploads.',
    deep:'Multipart also gives retry-per-part and parallel upload: a 500&nbsp;MB blob goes as 100&times;5&nbsp;MB parts, and a transient failure retries one part &mdash; not the whole object.' },
  { k:"Step 6 / 9", t:"S3 event routing",
    flow:'<span class="fb n">ObjectCreated</span><span class="arr">&rarr;</span><span class="fb p">prefix &rarr; Lambda</span><span class="arr">&rarr;</span><span class="fb n">per-record</span><span class="arr">&rarr;</span><span class="fb t">PROCESSED</span><span class="arr">/</span><span class="fb r">ERROR</span>',
    ins:'Uploads push work; nothing polls. Delivery is <b>at-least-once</b> &rarr; processing must be idempotent (hash key). And prefixes can\'t overlap &mdash; you can\'t later split <code>uploads/</code> into <code>uploads/images/</code>.',
    deep:'The handler decodes the key first &mdash; S3 URL-encodes spaces as <code>+</code>. Skip that and <code>"my file.bin"</code> becomes <code>"my+file.bin"</code>, the DB lookup misses, and you get a silent no-match bug.' },
  { k:"Step 7 / 9", t:"Reconciler sweep",
    flow:'<span class="fb n">scheduled sweep</span><span class="arr">&rarr;</span><span class="fb p">list S3 keys</span><span class="arr">&rarr;</span><span class="fb a">no DB row?</span><span class="arr">&rarr;</span><span class="fb t">past grace?</span><span class="arr">&rarr;</span><span class="fb r">delete orphan</span>',
    ins:'The dual-write\'s real backstop. A scheduled job lists S3, finds keys with <b>no DB row</b>, and deletes the orphans &mdash; but only those past a grace window (or without a PENDING marker), so it <b>never touches an in-flight upload</b>.',
    code:'<span class="k">const</span> GRACE = 3600e3;                  <span class="c">// 1h &gt; write</span>\n<span class="k">for await</span> (<span class="k">const</span> o <span class="k">of</span> listKeys(bucket)) {\n  <span class="k">if</span> (fresh(o, GRACE)) <span class="k">continue</span>; <span class="c">// in-flight</span>\n  <span class="k">const</span> row = <span class="k">await</span> db.findByKey(o.Key);\n  <span class="k">if</span> (!row) <span class="k">await</span> s3.<span class="hl">deleteObject</span>(o.Key); <span class="c">// orphan</span>\n}',
    cap:'The grace window (or a PENDING marker) is the one line that stops the reconciler deleting in-flight uploads.' },
  { k:"Step 8 / 9", t:"Idempotent processing",
    flow:'<span class="fb n">event (&ge;1&times;)</span><span class="arr">&rarr;</span><span class="fb p">conditional put marker</span><span class="arr">&rarr;</span><span class="fb a">exists? skip</span><span class="arr">/</span><span class="fb t">else process</span>',
    ins:'S3 delivery is <b>at-least-once</b>, so the same event can arrive twice. A conditional put on a content-hash marker is a check-and-set: the first delivery wins and processes; a redelivery sees the marker and <b>no-ops</b>. The effect is idempotent even though delivery isn\'t.',
    code:'<span class="k">const</span> marker = <span class="s">"processed#"</span> + hash; <span class="c">// dedup key</span>\n<span class="k">try</span> {\n  <span class="k">await</span> ddb.<span class="hl">put</span>({ Item: { pk: marker },\n    ConditionExpression: <span class="s">"attribute_not_exists(pk)"</span> });\n} <span class="k">catch</span> (e) {\n  <span class="k">if</span> (e.name === <span class="s">"ConditionalCheckFailed..."</span>) <span class="k">return</span>; <span class="c">// done</span>\n  <span class="k">throw</span> e;\n}\n<span class="k">await</span> process(object); <span class="c">// once per event</span>',
    cap:'The conditional put <i>is</i> the lock &mdash; first writer wins the key; redeliveries fail the condition and skip.' },
  { k:"Step 9 / 9", t:"Observability hooks",
    flow:'<span class="fb n">each stage</span><span class="arr">&rarr;</span><span class="fb p">emit 4 signals</span><span class="arr">&rarr;</span><span class="fb t">page on SLA breach</span><span class="arr">/</span><span class="fb a">log the rest</span>',
    ins:'You can\'t operate what you can\'t see. Every stage emits the <b>four signals</b> that localize an incident &mdash; queue depth, p99 latency, error/DLQ rate, reconciler orphan count &mdash; and you <b>page only on what users feel</b> (SLA breach, DLQ growth), logging the self-healing rest.',
    code:'metrics.<span class="hl">gauge</span>(<span class="s">"queue.depth"</span>, <span class="k">await</span> queue.size());\nmetrics.<span class="hl">histogram</span>(<span class="s">"process.latency_ms"</span>, elapsed); <span class="c">// p99</span>\nmetrics.<span class="hl">count</span>(<span class="s">"process.error"</span>, err ? 1 : 0);\nmetrics.<span class="hl">gauge</span>(<span class="s">"reconciler.orphans"</span>, orphanCount);\n<span class="c">// page on: dlq.depth &gt; 0 sustained, or event.age &gt; SLA</span>',
    cap:'Alarm on symptoms users feel; transient spikes that self-heal via retry are log-only, or you drown in false pages.' }
  ],
  modelScript: [
    { ml: 'Frame it before diving', t: '"Before I trace it &mdash; I\'ll assume single region, files up to ~500&nbsp;MB, and that downstream consumers need the result within a few seconds. Stop me if any of that\'s off."' },
    { ml: 'Headline in one breath', t: '"At a high level: the object lands in S3, that fires a trigger, I hash and validate it <b>while it streams</b>, write the metadata transactionally, then fan it out to the processors &mdash; built so memory stays flat no matter the file size."' },
    { ml: 'Walk the path', t: '"Concretely &mdash; the upload completes to S3 and emits an event. My handler opens a read stream and forks it through a <b>PassThrough</b>: one branch computes the SHA&#8209;256, the other feeds the processor, so I never buffer the whole file or read it twice. Once I have the hash and size, I write the row &mdash; key, hash, status &mdash; to the metadata DB."' },
    { ml: 'Name the risk yourself', t: '"The thing I\'d flag without being asked is the <b>dual&#8209;write</b>: the object is already in S3, but if the DB write fails I\'ve got an orphan. The compensating delete covers the common case, but the real backstop is a <b>reconciler</b> that sweeps S3 for keys with no committed row. I wouldn\'t claim the delete alone is safe."' },
    { ml: 'Name the trade-off line', t: '"For dispatch I\'d run a Lambda per object at this volume &mdash; the simplest thing that works. The moment I need retries, ordering, or a DLQ, I\'d put <b>SQS</b> in front and make the processors consumers. That\'s the line I\'d move on, and I\'d say so before they ask."' },
    { ml: 'Be honest about the ceiling', t: '"This holds to low thousands of objects a minute. Past that the metadata DB is the bottleneck &mdash; I\'d shard by tenant or key&#8209;prefix and move fully onto SQS&#8209;fronted consumers. I\'d call that out as the next redesign rather than pretend it scales forever."' },
    { mq: 'Interviewer: "What if two uploads race on the same key?"' },
    { ml: 'Absorb the follow-up', t: '"S3 is last&#8209;writer&#8209;wins on the object, so the bytes are fine &mdash; but my metadata could interleave. I\'d make the DB write <b>idempotent on the key</b> with a conditional put, so the second writer updates cleanly or no&#8209;ops. And if ordering genuinely matters to the business, that\'s one more reason to move to a queue with a per&#8209;key partition."', ans: true }
  ]
};
