/* ============ topics/signing/bank.js -- topic 2 cross-pane BANK ============
   The mock-run / mixed-fire / frame bank for topic 2. mockBeats + curveballs +
   frames are signing-specific; cards/speak alias the LOCAL SIGN_CARDS / SIGN_SPEAK
   (defined in drill.js, loaded before this in the bundle). publishBanks() seeds the
   registry-owned globals from this object on switch. Offline-safe; 7-bit ASCII. */
var TOPIC_SIGN_BANK = (function () {
  var mockBeats=[
   { tag:"FRAME", cue:"&ldquo;Design package signing &mdash; start wherever you like.&rdquo;",
     task:"Frame the scope in one line, then give your one-sentence version.",
     model:"<b>Frame:</b> the pipeline produces a package and its hash; signing makes that package tamper-proof so a device will only run authorized code. <b>One-liner:</b> the hash goes to an HSM that returns a signature, we stamp it into the header, and the device verifies it against a burned-in public key before flashing &mdash; rejecting anything unsigned.",
     int:{q:"Why sign at all &mdash; if the download is over HTTPS, isn&rsquo;t it already secure?",a:"HTTPS secures the <b>channel</b>, not the <b>artifact</b>. It protects bytes in transit between two endpoints, but the moment the package leaves TLS &mdash; sitting in a CDN, a mirror, a compromised build server, or handed device-to-device &mdash; there&rsquo;s nothing binding those bytes to <i>us</i>. Signing binds authenticity to the artifact itself, so the device can verify origin and integrity no matter how the package reached it. Transport security and artifact trust are different problems."},int2:{q:"So why can&rsquo;t the device just trust whatever our server sends it?",a:"Because &lsquo;our server&rsquo; is not a durable trust anchor &mdash; servers get compromised, DNS gets spoofed, and a device in the field can&rsquo;t re-authenticate a backend on every boot. Trust has to live <b>on the device</b>, anchored to a public key it already holds, so it can decide <i>locally</i> whether a package is authentic. The signature moves the trust decision from &lsquo;did this come from a server I&rsquo;m talking to&rsquo; to &lsquo;is this signed by a key I trust&rsquo; &mdash; which survives a compromised server."} },
   { tag:"STRUCTURE", cue:"&ldquo;Walk me through it.&rdquo;",
     task:"Talk the whole flow, artifact to device &mdash; no code, just the spine.",
     model:"Pipeline hands over the <b>hash</b> &rarr; resolve the key via the <b>four-table lookup</b> (per tenant, per product type) &rarr; the <b>HSM signs the hash</b> with a non-exportable key &rarr; stamp <b>signature + version + key id</b> into the header, payload untouched &rarr; deploy. On the device: <b>hash the payload, verify against the burned-in public key, check the version isn&rsquo;t a downgrade</b> &rarr; write the spare A/B slot, test-boot, <b>confirm or roll back</b>. Any failure &rarr; reject, keep the current image.",
     int:{q:"A device family you&rsquo;ve never signed for lands &mdash; it only verifies PKCS#1 v1.5, but your default is PSS. What happens?",a:"Hand a v1.5-only device a PSS signature and it <b>rejects</b> a perfectly valid package &mdash; the verifier can&rsquo;t check a scheme it doesn&rsquo;t implement. So the signing service branches on <b>device family</b> and produces the padding <i>that family</i> verifies. It&rsquo;s a compatibility surface, not a preference: I sign what the fleet can check, and retire the old scheme as the fleet ages onto the new one. &lsquo;Just use the newest&rsquo; is exactly the trap."} },
   { tag:"SCALE", cue:"&ldquo;A release drops to 50,000 devices and the HSM is pegged. What breaks first?&rdquo;",
     task:"Name the first ceiling, then the fix &mdash; don&rsquo;t hand-wave &lsquo;it scales.&rsquo;",
     model:"The ceiling is <b>HSM sign-ops per second</b> &mdash; not CPU, not bandwidth, because signing is <b>size-independent</b> (you sign a 32-byte digest). Past one partition&rsquo;s throughput you <b>queue the hashes and drain at a controlled rate</b>, or <b>add HSM partitions</b> and shard signing across them. Signing tolerates a short backlog, so a burst that would throttle becomes a queue that clears.",
     int:{q:"Why doesn&rsquo;t a bigger instance or more bandwidth fix it &mdash; be specific.",a:"Because the work isn&rsquo;t in <i>your</i> process. The private-key operation happens <b>inside the HSM</b>, and you&rsquo;re rate-limited by <b>its</b> op/sec, not your app&rsquo;s. Resizing your box makes it wait on the HSM faster &mdash; same wall. The only real levers are <b>parallelism across HSM partitions</b> or <b>smoothing the burst with a queue</b>. Naming that the bottleneck is a resource you don&rsquo;t scale by resizing is the whole point."},int2:{q:"Do you even need to sign all 50,000 in real time?",a:"Almost never. You sign a package <b>once per key</b>, not once per device &mdash; 50,000 devices on one tenant&rsquo;s product type share <i>one</i> signature. So the real signing count is releases &times; keys, far below the device count. And even that tolerates a queue: buffer the sign requests, drain against the HSM, let the release complete <i>eventually</i>. The device fan-out is a <b>distribution</b> problem, not a signing one."} },
   { tag:"FAILURE", cue:"&ldquo;A signing key leaks. Now what?&rdquo;",
     task:"Walk the blast radius, then the recovery that makes a leak survivable.",
     model:"<b>Bound, recover, verify.</b> The radius is <b>one tenant&rsquo;s product type</b> &mdash; that&rsquo;s why keys are scoped that way &mdash; and it&rsquo;s bounded in time by rotation speed. Recover by <b>rotating</b>: provision a new key, sign new packages with it, <b>revoke the old at the trust anchor</b>. Devices verify against the anchor, so once it stops certifying the old key, forgeries stop being trusted &mdash; <b>no re-flash</b>. Then audit anything the leaked key signed during the window.",
     int:{q:"Before rotation finishes, the attacker signs a malicious package. How do devices not accept it?",a:"That&rsquo;s the hard window, and it&rsquo;s where the <b>downgrade defense plus monitoring</b> earn their keep: a forged package still has to beat the <b>monotonic version</b>, so it can&rsquo;t simply replace what&rsquo;s running with something older, and I&rsquo;d alarm on the signing-volume anomaly. The airtight move is to push a <b>new legitimate version</b> that supersedes anything the attacker could forge, then complete revocation. Rotation isn&rsquo;t instant &mdash; the <b>scoping</b> is what keeps &lsquo;not instant&rsquo; from being &lsquo;catastrophic.&rsquo;"},int2:{q:"What if it was the <b>root</b> key that leaked?",a:"Different, far worse incident. The root certifies signing keys, so a root leak undermines the <b>anchor itself</b> &mdash; you may have to re-establish trust on devices, which is exactly the fleet-wide pain you designed to avoid. Which is <i>why the root is offline and air-gapped</i>, used almost never, behind a human ceremony. The two-tier model is the firewall: day-to-day exposure is on cheap, rotatable, scoped leaf keys, never the anchor."} },
   { tag:"CURVEBALL", theme:"Downgrade", cue:"&ldquo;An attacker re-pushes an old firmware with a known, since-patched CVE. It&rsquo;s validly signed by your real key. Stop it.&rdquo;",
     task:"Reframe the premise out loud, then give the real mechanism.",
     model:"The premise to say aloud: a signature proves <b>authenticity, not freshness</b> &mdash; that old package really was signed by us, so the signature check passes. The defense is a <b>monotonic version</b> carried <i>inside the signed header</i>: the device refuses any version below what it&rsquo;s running. Because the version is under the signature, an attacker can&rsquo;t re-stamp the old package as &lsquo;newer&rsquo; without breaking the signature.",
     int:{q:"Why does the version have to be <i>inside</i> the signed region &mdash; why not just a header field the device reads?",a:"An unsigned header field is <b>attacker-controlled</b> &mdash; they&rsquo;d bump the number on the old, vulnerable package and it would look current, sail past the check, and downgrade the device. Binding the version <b>under the signature</b> ties freshness to authenticity: tamper with the version and the signature fails to verify. That&rsquo;s the entire trick &mdash; the version is only trustworthy because it&rsquo;s signed. And the device&rsquo;s &lsquo;current version&rsquo; floor lives in tamper-resistant storage so it, too, can&rsquo;t be rolled back."} },
   { tag:"CLOSE", cue:"&ldquo;Sum it up &mdash; and what would you watch in prod?&rdquo;",
     task:"Two-sentence close, then the one thing you&rsquo;d alarm on.",
     model:"It&rsquo;s a trust boundary: the pipeline makes the bytes, an HSM-held key signs the hash, and the <b>device</b> enforces it &mdash; verifying before it flashes and rejecting anything unsigned, downgraded, or forged. In prod I&rsquo;d watch <b>signing volume per key</b> &mdash; an anomaly there is the earliest signal of a compromised signer, the failure mode that matters most because the key is the whole design.",
     int:{q:"You&rsquo;ve got a week, not a month. Cut one thing you described to ship &mdash; what goes?",a:"The <b>offline-root ceremony and multi-tier key hierarchy</b> can wait &mdash; I&rsquo;d ship with HSM-held per-tenant keys and a documented (if manual) rotation, and add the formal air-gapped root next. What I would <b>not</b> cut is <b>device-side verify-before-flash</b> or the <b>monotonic-version downgrade defense</b> &mdash; those are load-bearing for the entire trust model, not nice-to-haves. Signing without on-device verification is theatre, and no-downgrade-defense means a signed old CVE walks right back in. Knowing which parts are the contract and which are the hardening is the answer."} }
  ];
  var mockCurveIdx=0; for(var _ci=0;_ci<mockBeats.length;_ci++){ if(mockBeats[_ci].tag==="CURVEBALL") mockCurveIdx=_ci; }
  var curveballs=[ mockBeats[mockCurveIdx],
    { tag:"CURVEBALL", theme:"Supply chain", cue:"&ldquo;How do you know the build you signed is the code your engineers actually wrote &mdash; and not something a compromised CI slipped in?&rdquo;",
      task:"Name what signing does and doesn&rsquo;t prove, then the layer that closes the gap.",
      model:"Signing proves the artifact is <b>authentic and untampered from the moment it was signed</b> &mdash; it does <b>not</b> prove that what you signed is what you <i>intended</i>. If CI is compromised, you&rsquo;ll faithfully sign malware. Closing that gap is <b>provenance</b>: sign in an <b>isolated, trusted builder</b>, produce a <b>build attestation</b> (in-toto / SLSA provenance recording the source commit, builder, and inputs), and verify that attestation before signing or before deploy. Keyless signing with a <b>transparency log</b> (Sigstore/Rekor) makes every signature publicly auditable.",
      int:{q:"So signing alone isn&rsquo;t enough &mdash; what&rsquo;s the honest one-line summary?",a:"<b>Signing answers &lsquo;is this the artifact we released?&rsquo; &mdash; provenance answers &lsquo;is the artifact we released the one we meant to build?&rsquo;</b> You need both: a signature binds trust to the bytes, and an attestation binds the bytes to a trusted build of a known source. A signature over a compromised build is a correctly-signed compromise. The senior move is naming that boundary instead of claiming the signature covers it."} },
    { tag:"CURVEBALL", theme:"Offline fleet", cue:"&ldquo;You need to rotate a signing key, but a chunk of the fleet is offline for weeks at a time. How?&rdquo;",
      task:"Rotate without assuming connectivity &mdash; and say what bounds the risk meanwhile.",
      model:"Anchor trust to the <b>root</b>, not the leaf key, so the new signing key is trusted the moment the anchor certifies it &mdash; no per-device action. For offline devices, lean on <b>supersession</b>: sign the next legitimate release with the new key and let the <b>monotonic version</b> ensure that when the device does come online, the newest authorized package is what it takes. Don&rsquo;t depend on online revocation lists a disconnected device can&rsquo;t fetch.",
      int:{q:"A device is offline for a year, misses the rotation entirely, then reconnects. What happens &mdash; and what&rsquo;s the risk?",a:"On reconnect it fetches the current release, which is signed by the <b>new</b> key the anchor certifies, verifies fine, and updates &mdash; forward, never a downgrade. The residual risk is the <b>exposure window</b>: if the old key was compromised, that device was reachable with forged-but-old packages the whole time, though the monotonic version still blocks a straight downgrade. That&rsquo;s the honest limit of offline fleets: you can guarantee they <i>catch up safely</i>, not that they were <i>never targeted</i> &mdash; which is another argument for short-lived, tightly-scoped keys."} },
    { tag:"CURVEBALL", theme:"Tenant isolation", cue:"&ldquo;Tenant A&rsquo;s key signed a package that ended up trusted on Tenant B&rsquo;s devices. How is that even possible, and how do you prevent it?&rdquo;",
      task:"Diagnose the two ways it happens, then the fix on each side.",
      model:"Two failure modes. One: a <b>key-resolution bug</b> &mdash; the four-table lookup returned the wrong key, so A&rsquo;s package got signed with a key B&rsquo;s devices also trust. Two: <b>trust anchors aren&rsquo;t tenant-scoped</b> &mdash; B&rsquo;s devices trust a key/root that also covers A. Fix on the signing side: verify the resolved key&rsquo;s scope matches the request&rsquo;s tenant <b>before</b> signing, and put the tenant/key-id in the signed header. Fix on the device side: a device only trusts packages whose <b>key id is certified for its tenant/product type</b>, not any key under a shared root.",
      int:{q:"How does the device actually enforce &lsquo;only my tenant&rsquo;s key&rsquo; &mdash; it just has a public key burned in?",a:"You don&rsquo;t give every device the same anchor. Either the device is provisioned with the <b>public key (or intermediate) scoped to its tenant/product type</b>, so a package signed by another tenant&rsquo;s key simply won&rsquo;t verify against what <i>this</i> device holds; or the signed header carries a <b>key id / tenant id</b> and the device checks it&rsquo;s the one it&rsquo;s bound to before verifying. Isolation is only real if it&rsquo;s enforced <b>at the device&rsquo;s trust anchor</b>, not just assumed at sign time &mdash; cross-tenant trust is a provisioning decision, and getting it wrong is how one tenant&rsquo;s leak becomes another&rsquo;s problem."} },
    { tag:"CURVEBALL", theme:"Cost",
      cue:"&ldquo;Finance says the signing infrastructure bill is climbing. Where&rsquo;s the money, and how do you cut it?&rdquo;",
      task:"Profile before optimizing &mdash; and know the cost isn&rsquo;t the signing itself.",
      model:"Signing is <b>nearly free per operation</b> &mdash; you sign a 32-byte digest, so the bill isn&rsquo;t compute or bandwidth. It&rsquo;s the <b>HSM/KMS infrastructure</b>: CloudHSM bills <b>per HSM-hour</b> (over-provisioned partitions burn money idle), KMS bills <b>per Sign request</b>. Levers: right-size HSM partitions to actual peak, and &mdash; the big one &mdash; sign <b>once per key, not once per device</b>, so 50,000 devices on one product type cost one signature, not fifty thousand.",
      int:{q:"Give me the single biggest lever.",a:"<b>Don&rsquo;t confuse the device count with the signing count.</b> A package is signed <b>once per key</b> and the whole tenant/product-type fleet shares that one signature. Teams that wire signing per-device pay 50,000&times; for nothing, because the signature is <i>identical</i>. Fan-out to devices is a <b>distribution</b> cost (bandwidth / CDN), not a signing cost &mdash; naming that they&rsquo;re two different bills is the lever."} },
    { tag:"CURVEBALL", theme:"Version concurrency",
      cue:"&ldquo;Two releases for the same tenant and product type get signed at the same instant, and both stamp version N+1. A device could now see two different &lsquo;N+1&rsquo; packages. What went wrong?&rdquo;",
      task:"Find the race, then make version allocation safe.",
      model:"The <b>version was allocated non-atomically</b> &mdash; both signers read current version N and each computed N+1 independently. Fix: an <b>atomic monotonic counter</b> (a DB sequence, a conditional increment) so version assignment is a single serialized step and no two packages share a version. The device&rsquo;s downgrade defense <i>assumes strictly increasing</i> versions, so a duplicate version breaks the ordering guarantee it depends on.",
      int:{q:"Does the device even care, as long as both are validly signed?",a:"It does &mdash; the <b>monotonic-version</b> rule is &lsquo;accept only a version greater than current.&rsquo; Two packages at the same version means one gets <i>rejected as not-greater</i> once the device has the other, and ordering turns ambiguous. The version must be a <b>total order</b> for downgrade protection to mean anything, and a total order needs atomic allocation. Same &lsquo;two writers, one counter&rsquo; race as anywhere &mdash; just with security consequences."} },
    { tag:"CURVEBALL", theme:"Multi-region",
      cue:"&ldquo;Your signing service and its HSM live in one region. That region goes down in the middle of a release. Now what?&rdquo;",
      task:"Separate what breaks (signing) from what doesn&rsquo;t (verifying).",
      model:"Scope it first: <b>verification is unaffected</b> &mdash; devices verify offline against a burned-in anchor, so already-signed packages and the whole deployed fleet keep working. What&rsquo;s down is the <b>ability to sign new packages</b>. Fix is key availability across regions: <b>KMS multi-region keys</b> or a replicated/HA HSM, so signing fails over. Because signing is <b>on the release path, not the request path</b>, a short outage is a delayed release, not a fleet outage.",
      int:{q:"You fail signing over to another region. What&rsquo;s the one thing you must NOT replicate carelessly?",a:"The <b>root of trust</b>. Per-tenant <b>signing keys</b> can be multi-region so signing fails over &mdash; but the <b>offline root</b> that certifies them stays air-gapped and is <i>not</i> casually replicated, because every copy is another place it can leak. Make the <b>online signing capability</b> highly available; keep the <b>root</b> rare and controlled. Conflating &lsquo;replicate for availability&rsquo; with &lsquo;replicate the root&rsquo; turns a DR plan into a compromise."} },
    { tag:"CURVEBALL", theme:"Silent failure",
      cue:"&ldquo;A library upgrade quietly changed your signatures to a format the newest device family rejects. You found out from field reports days later. What happened, and how do you catch it next time?&rdquo;",
      task:"Name the failure class, then the check that catches it pre-ship.",
      model:"A <b>scheme/format regression</b> &mdash; the signing side changed (padding, encoding, a library default) so the device verifier no longer accepts it, and nothing verified it <i>before</i> shipping. The catch is a <b>round-trip in the pipeline</b>: after signing, <b>verify with the real device-side verifier</b> for each target family and fail the release if it doesn&rsquo;t verify. Plus monitor <b>device-reported verification failures</b> as a first-class alarm.",
      int:{q:"Why isn&rsquo;t &lsquo;we unit-tested the signer&rsquo; enough here?",a:"Because the bug is at the <b>signer/verifier boundary</b>, and a unit test of the signer alone confirms it produces <i>a</i> signature &mdash; not that <i>this device</i> accepts it. The only test that catches a format regression is an <b>end-to-end round-trip</b> against the actual verifier per family, run as a release gate. Signing correctness is a property of the <b>pair</b>, so you test the pair &mdash; and watch the fleet&rsquo;s reported verify-failure rate as the backstop."} }
  ];
  var mockFrameIdx=0; for(var _fi=0;_fi<mockBeats.length;_fi++){ if(mockBeats[_fi].tag==="FRAME") mockFrameIdx=_fi; }
  var frames=[ mockBeats[mockFrameIdx].cue,
    "&ldquo;We ship firmware to devices in the field. Design how you make sure a device only ever runs code we actually authorized.&rdquo;",
    "&ldquo;Design a code-signing system for over-the-air firmware updates to a fleet of payment terminals.&rdquo;",
    "&ldquo;How do you make a software package tamper-proof from the moment it&rsquo;s built to the moment a device runs it?&rdquo;"
  ];
  return { cards: SIGN_CARDS, speak: SIGN_SPEAK, curveballs: curveballs, mockBeats: mockBeats, frames: frames };
})();
