/* topics/signing/walk.js -- topic 2 WALKTHROUGH data. steps[] is the guided trace of
   the signing flow (request -> key resolve -> HSM sign -> family algo -> header stamp
   -> validation -> device verify -> flash/reject); modelScript[] is the spoken model
   answer (plain beats, the interviewer .mq line, then the .mbeat.ans -- which MUST be
   LAST, the last-child CSS depends on it). The div/span markup lives in renderBeat;
   this is pure data. Offline-safe; 7-bit ASCII (entities + \uXXXX). */
var TOPIC_SIGN_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"Request + key resolution",
      flow:'<span class="fb n">signPackage(hash,tenant,type)</span><span class="arr">&rarr;</span><span class="fb p">four-table lookup</span><span class="arr">&rarr;</span><span class="fb t">scoped key</span><span class="arr">/</span><span class="fb r">404 no key</span>',
      ins:'The pipeline already hashed the package, so the signer takes the <b>digest</b>, not the bytes. The key is resolved <b>per tenant, per product type</b> &mdash; a leaked key blasts one company&rsquo;s one product line, never the fleet.',
      code:'<span class="c">// product_type -&gt; company_product_type -&gt; company_device_keys</span>\\n<span class="k">const</span> key = <span class="k">await</span> resolveKey(tenant, productType);\\n<span class="k">if</span> (!key)\\n  <span class="k">throw</span> <span class="k">new</span> SignError(<span class="hl">404</span>, <span class="s">\'no signing key for this product\'</span>);',
      cap:'The four-table resolution is what scopes a signature to one tenant &mdash; the same per-tenant isolation the authz topic enforces on reads.' },
    { k:"Step 2 / 9", t:"HSM signs the hash",
      flow:'<span class="fb n">hash</span><span class="arr">&rarr;</span><span class="fb p">HSM.sign(hash, keyId)</span><span class="arr">&rarr;</span><span class="fb t">signature</span><span class="arr">&middot;</span><span class="fb a">key never leaves</span>',
      ins:'The service sends the hash to the HSM and gets back a signature. The <b>private key is non-exportable</b> &mdash; it never enters the process, so a compromised signer produces signatures for a bounded window but can never <b>exfiltrate the key</b>.',
      code:'<span class="k">const</span> sig = <span class="k">await</span> hsm.<span class="hl">sign</span>({\\n  keyId: key.id,          <span class="c">// a handle, not the key</span>\\n  digest: hash,           <span class="c">// 32 bytes in</span>\\n  alg: key.alg            <span class="c">// RSA_PSS_SHA_256 / ...</span>\\n});                       <span class="c">// signature out; key stays in the HSM</span>',
      cap:'&ldquo;Send a hash, get a signature&rdquo; is the whole security property &mdash; the boundary is the HSM, and nothing on your side ever holds the private key.' },
    { k:"Step 3 / 9", t:"Algorithm by device family",
      flow:'<span class="fb n">device family</span><span class="arr">&rarr;</span><span class="fb t">G6: PKCS#1 v1.5</span><span class="arr">/</span><span class="fb p">G7: RSA-PSS</span><span class="arr">/</span><span class="fb a">SEQ5: HSM v2</span>',
      ins:'You sign with what the device&rsquo;s <b>verifier</b> implements, not what&rsquo;s newest. <b>G6</b> checks PKCS#1 v1.5, <b>G7</b> checks RSA-PSS, and older families have their own quirks &mdash; the fleet&rsquo;s trust anchor decides the scheme.',
      deep:'This is why &ldquo;just use PSS&rdquo; is wrong as a blanket answer: a G6 device that only knows v1.5 will <b>reject</b> a PSS signature as invalid. The signing service branches on family and produces the padding <i>that device</i> can verify &mdash; a compatibility surface, not a preference.' },
    { k:"Step 4 / 9", t:"Stamp the header",
      flow:'<span class="fb t">signature</span><span class="arr">+</span><span class="fb p">version + keyId</span><span class="arr">&rarr;</span><span class="fb n">package header</span><span class="arr">&middot;</span><span class="fb a">payload untouched</span>',
      ins:'The signature, a <b>monotonic version</b>, and the key id go into the package <b>header</b>; the payload bytes are never altered. Header carries <b>proof</b>, payload carries <b>content</b> &mdash; and the version rides <i>inside</i> the signed region so it can&rsquo;t be forged.',
      deep:'Putting the version under the signature is what makes the downgrade defense real: the device reads the version from the <b>signed</b> header, so an attacker can&rsquo;t re-stamp an old package as &ldquo;newer&rdquo; without breaking the signature. Proof and freshness travel together.' },
    { k:"Step 5 / 9", t:"Validate + sanitize",
      flow:'<span class="fb t">exists? 404</span><span class="arr">&rarr;</span><span class="fb a">format? 409</span><span class="arr">&rarr;</span><span class="fb r">HSM reject? 500</span><span class="arr">&rarr;</span><span class="fb n">redact key material</span>',
      ins:'A three-level ladder: the key <b>exists</b> (else 404), the input is <b>well-formed</b> (else 409, e.g. &ldquo;must be 6 characters&rdquo; for a vendor key), the HSM <b>accepts</b> it (else 500). And every error is <b>sanitized</b> &mdash; no key bytes, no key id, ever leak into a message or a log.',
      code:'<span class="k">try</span> {\\n  assertKeyFormat(vendorKey);  <span class="c">// 409 "must be 6 characters long"</span>\\n  <span class="k">return</span> <span class="k">await</span> hsm.sign(req);\\n} <span class="k">catch</span> (e) {\\n  log.error(<span class="hl">redact</span>(e));   <span class="c">// strip key material before it&#39;s logged</span>\\n  <span class="k">throw</span> sanitize(e);       <span class="c">// 500, no secrets in the response</span>\\n}',
      cap:'Sanitizing the error path is a security control, not politeness &mdash; a stack trace that echoes a key or key id is a leak, so redaction happens before anything is logged or returned.' },
    { k:"Step 6 / 9", t:"Sign a manifest, not the blob",
      flow:'<span class="fb n">N files</span><span class="arr">&rarr;</span><span class="fb p">manifest of hashes</span><span class="arr">&rarr;</span><span class="fb t">sign the manifest</span><span class="arr">&middot;</span><span class="fb a">per-file + delta</span>',
      ins:'When a package is many files, you don&rsquo;t sign the concatenated blob &mdash; you build a <b>manifest</b> listing each file&rsquo;s path and hash and sign <b>that</b>. The device verifies the manifest once, then checks each file against its listed hash &mdash; one signature transitively covers every file.',
      deep:'This is what makes <b>delta updates</b> safe: ship only the changed files, and the device re-verifies <i>every</i> file &mdash; changed and unchanged &mdash; against the signed manifest, so a partial or mismatched apply fails verification. The manifest <i>is</i> the digest of the whole file set &mdash; the trust model is unchanged, the unit of integrity is just a set instead of one blob.' },
    { k:"Step 7 / 9", t:"Device verifies before flash",
      flow:'<span class="fb n">package</span><span class="arr">&rarr;</span><span class="fb p">hash payload</span><span class="arr">&rarr;</span><span class="fb t">verify vs public key</span><span class="arr">&rarr;</span><span class="fb a">version &ge; current?</span><span class="arr">/</span><span class="fb r">reject</span>',
      ins:'The device hashes the payload, verifies the header signature against its <b>burned-in public key</b>, and checks the version is not a downgrade &mdash; <b>all before writing anything</b>. Verification gates the flash; it never follows it.',
      deep:'Three checks, any of which rejects: authenticity (does the signature verify?), freshness (is the version &ge; what&rsquo;s running?), and integrity (does the recomputed hash match what was signed?). Only a package that passes all three is allowed to touch the flash &mdash; and even then it lands in the spare A/B slot first.' },
    { k:"Step 8 / 9", t:"Flash or reject &mdash; safely",
      flow:'<span class="fb t">valid + newer</span><span class="arr">&rarr;</span><span class="fb p">write spare slot</span><span class="arr">&rarr;</span><span class="fb a">test-boot + confirm</span><span class="arr">/</span><span class="fb r">rollback</span>',
      ins:'A verified package is written to the <b>spare A/B partition</b>, boots into a test state, and must <b>confirm</b> within a watchdog window or roll back. A rejected package changes <b>nothing</b> &mdash; the device keeps its current image. Refusing an update is the <b>safe</b> path, not a brick.',
      code:'<span class="k">if</span> (!verify(pkg)) <span class="k">return</span> reject();     <span class="c">// keep current image</span>\\nwriteSlot(<span class="hl">spare</span>, pkg);                <span class="c">// never overwrite the running slot</span>\\nbootInto(spare, { test: <span class="k">true</span> });\\n<span class="k">if</span> (!confirmedWithin(watchdog))\\n  rollback(<span class="hl">active</span>);                    <span class="c">// signed-but-broken -&gt; revert</span>',
      cap:'A/B + confirm covers the case signing can&rsquo;t: a package that is perfectly signed but boots badly. Signature proves trust; the confirm window proves it actually runs.' },
    { k:"Step 9 / 9", t:"Rotate + revoke at the anchor",
      flow:'<span class="fb n">anchor certifies leaf</span><span class="arr">&rarr;</span><span class="fb p">rotate leaf key</span><span class="arr">&rarr;</span><span class="fb t">sign with new key</span><span class="arr">&middot;</span><span class="fb a">no re-flash</span>',
      ins:'Keys don&rsquo;t live forever. Because devices trust the <b>anchor</b> (the root), not the individual signing key, you can <b>rotate a leaf key</b> &mdash; provision a new one the anchor certifies, sign new packages with it, let monotonic versions supersede &mdash; <b>without re-flashing the fleet</b>.',
      deep:'Compromise recovery rides the same path: the root <b>stops certifying</b> the bad leaf, so devices no longer trust anything it signed, and packages signed by the rotated key supersede the old. The one link you <i>can&rsquo;t</i> rotate remotely is the <b>anchor itself</b> &mdash; burned in at manufacture &mdash; which is exactly why the leaf/anchor split exists: routine rotation stays on the cheap side of the line, the irreplaceable root stays rare and offline.' }
  ],
  modelScript: [
    { ml: 'Frame it before diving', t: '"Before I trace it &mdash; I&rsquo;ll assume the pipeline already gives me the package hash, the devices verify with a public key we control, and signing keys are per-tenant. Stop me if any of that&rsquo;s off."' },
    { ml: 'Headline in one breath', t: '"At a high level: the pipeline hands me a hash, I resolve the tenant&rsquo;s key, the <b>HSM signs the hash</b>, I stamp the signature into the header, and the <b>device verifies it against a burned-in key before flashing</b> &mdash; rejecting anything unsigned."' },
    { ml: 'Walk the path', t: '"Concretely &mdash; I take the SHA&#8209;256 the pipeline computed, resolve the signing key through the four-table lookup, and send <b>just the hash</b> to the HSM. It signs with a non-exportable private key and returns a signature; the key never touches my process. I stamp signature, version, and key id into the header &mdash; payload untouched."' },
    { ml: 'Name the risk yourself', t: '"The thing I&rsquo;d flag without being asked is that a signature proves <b>authenticity, not freshness</b> &mdash; so I carry a <b>monotonic version inside the signed header</b>, and the device refuses anything older. That&rsquo;s the downgrade defense people skip."' },
    { ml: 'Name the trade-off line', t: '"The algorithm isn&rsquo;t my preference &mdash; it&rsquo;s what the device verifies. <b>G6 checks PKCS#1 v1.5, G7 checks PSS.</b> I sign with what the fleet can check, and I&rsquo;d say that before they ask &lsquo;why RSA.&rsquo; Rolling my own padding would be the one thing I&rsquo;d never do."' },
    { ml: 'Be honest about the ceiling', t: '"This holds as long as the HSM keeps up. Signing is <b>size-independent</b> &mdash; I sign a 32-byte digest &mdash; so the ceiling is <b>HSM ops/sec</b>, not bandwidth. Past it I queue the hashes and batch, or add HSM partitions. And the real operational hard part isn&rsquo;t throughput &mdash; it&rsquo;s key rotation."' },
    { mq: 'Interviewer: "What if a signing key is compromised?"' },
    { ml: 'Absorb the follow-up', t: '"I <b>rotate</b>: provision a new key, sign new packages with it, revoke the old. What a leaked signing key can forge is bounded by what it was scoped to &mdash; one tenant&rsquo;s product type &mdash; and by the window before rotation. The device&rsquo;s <b>trust anchor</b> is what makes rotation enforceable: because devices verify against a public key or a root that certifies signing keys, I can retire a signing key <b>without re-flashing every device</b>, as long as the anchor still certifies the new one. So per-tenant keys plus a clean rotation path is the answer &mdash; and I&rsquo;d name which one the constraints allow rather than pretend one size fits."', ans: true }
  ]
};
