/* topics/desired-state/bank.js -- topic 7 working-set bank (IIFE). Builds mockBeats (6, tagged
   FRAME/STRUCTURE/SCALE/FAILURE/CURVEBALL/CLOSE), derives curveballs (8, curve[0] === the
   CURVEBALL mockBeat, 8 distinct themes) and frames (4, frame[0] === the FRAME mockBeat cue),
   and aliases the LOCAL DS_CARDS / DS_SPEAK so a switch reseeds the globals without clobbering
   topic 1. Entities only. 7-bit ASCII. */
var TOPIC_DS_BANK = (function(){
  var mockBeats = [
    { tag:'FRAME',
      cue:'Design a system to keep a large fleet&rsquo;s config converged to what you intend.',
      task:'Frame the boundary and the model before mechanics &mdash; move from &lsquo;keep config correct&rsquo; to &lsquo;converge toward a declared goal,&rsquo; not straight to pushing config.',
      model:'I&rsquo;d frame it as the boundary between config intent and fleet reality, and model it as desired state: three hashes per device &mdash; desired (the SHA-256 of the rendered output), deployed (what we last pushed), reported (what the device says it runs) &mdash; with drift as any mismatch and the differing pair localizing it. An event-driven resolve-render-diff-deploy-report loop converges each device, under a per-tenant lock and inside maintenance windows. The point is to converge toward a goal, not fire commands and hope.',
      int:{ q:'Why converge instead of just pushing config to devices?', a:'Because at fleet scale partial failure is the steady state &mdash; deploys fail, devices roll back, terminals go offline &mdash; and a fire-and-forget push has no feedback to catch that, so you accumulate silent divergence. A convergence loop keeps measuring each device against the goal and re-acts until they match, so failures self-correct on the next loop. Command-and-hope works for one supervised device; it doesn&rsquo;t survive a fleet.' },
      int2:{ q:'What&rsquo;s the single biggest risk in this design?', a:'That the whole model rests on two fragile foundations: deterministic rendering (or the content hash is unstable and every device looks perpetually drifted) and truthful device reporting (or the closed loop can&rsquo;t confirm convergence). Non-deterministic rendering gives you phantom drift; assuming the push worked instead of measuring reported gives you silent divergence. The drift signal&rsquo;s trustworthiness is the hard part, not the loop.' } },
    { tag:'STRUCTURE',
      cue:'Walk me through the loop &mdash; config change to running config.',
      task:'Narrate resolve, render, hash, diff, deploy, report as a control loop &mdash; and show where the gates are.',
      model:'A trigger &mdash; a config edit, a check-in, a window &mdash; kicks the loop for the affected devices. Resolve the tenant-site-tag-device hierarchy into a config, render it deterministically to output bytes, hash the output for desired, and three-way diff against deployed and reported. All that is read-only. If there&rsquo;s drift, acquire the per-tenant lock and check the maintenance window, then push and record the deployed hash. The device runs it and reports its hash; the next diff compares reported to desired. It&rsquo;s a loop because the report feeds back, so it converges until they match.',
      int:{ q:'Where in the loop are the lock and the window?', a:'Both sit just before deploy &mdash; the two gates on the one step that touches devices. Resolve, render, hash, and diff are read-only and ungated, done concurrently; only when a deploy is actually needed do you take the per-tenant lock (so no other reconciler deploys that fleet at once) and check the window (so the push lands only when safe). If the window&rsquo;s closed, you record the drift as visible-but-uncorrected and defer; detection is ungated, correction is doubly gated.' } },
    { tag:'SCALE',
      cue:'10,000 devices per tenant, many tenants, all reconciling. Where does this strain first?',
      task:'Locate the real ceiling &mdash; deploy/report I/O and lock hold-time, not the diff &mdash; and relieve it.',
      model:'Not the diff &mdash; comparing three fixed-size hashes is trivial and embarrassingly parallel, and it&rsquo;s event-scoped to affected devices. The pressure is touching reality: the rate of deploys and reported check-ins the reconciler and datastore absorb, and the per-tenant lock, whose hold-time can starve a big tenant&rsquo;s own backlog if its reconcile is slow. I relieve it by reconciling incrementally (only affected devices under the lock, not the whole tenant), keeping the locked critical section to just the deploy-and-record step, sub-partitioning the lock per-site for the largest tenants, and sharding reported-state ingestion.',
      int:{ q:'Most reconciles are the hot path. How do you keep it cheap?', a:'By making the common case a no-op: most reconciles confirm an already-converged device, which is a read-only three-hash comparison with no deploy and no lock. Only the rare drifted device does the expensive part &mdash; acquire the lock, deploy, record. So the hot path (the vast majority of reconciles) is trivial, and cost concentrates on the small fraction that actually need correction. That&rsquo;s why the diff must stay cheap and the lock must wrap only the deploy.' },
      int2:{ q:'A tenant&rsquo;s reconciles are slow and its per-tenant lock is a bottleneck. Now what?', a:'Shrink the critical section and shard within the tenant. Pull all the read-only work (resolve, render, diff) outside the lock so it runs concurrently, and hold the lock only for the exclusive deploy-and-record step. If one tenant is still too large, sub-partition its lock along a non-overlapping device boundary &mdash; per-site sub-locks &mdash; so independent slices reconcile in parallel while preserving the one invariant that matters: one device, one lock, never two reconcilers on the same device.' } },
    { tag:'FAILURE',
      cue:'A config change went out and a chunk of the fleet is misbehaving. Walk the incident.',
      task:'Diagnose a bad-config rollout and show that declarative rollback and staged convergence contain it.',
      model:'First, the visibility API tells me the blast radius &mdash; which devices took the bad config (reported == the bad desired) and which are healthy. The immediate fix is declarative: re-declare the previous desired, and the same loop converges the affected devices back &mdash; no bespoke undo, just change the goal and reconcile, in-window. Then the real lesson: this shouldn&rsquo;t have reached a chunk of the fleet, because a config change should roll out canaried &mdash; a small set first, watch their reported hashes and health, expand only if good. So: rollback now, and staged rollout so the next bad config is caught on the canaries.',
      int:{ q:'How does declarative rollback actually work here?', a:'You set desired back to the last-known-good config. Because the loop drives reality toward desired regardless of current state, re-declaring old desired makes every affected device drift (deployed/reported == bad, desired == good) and the loop converges them back to good &mdash; the exact same mechanism as rolling forward, run in reverse. There&rsquo;s no separate undo procedure to get wrong; rollback is symmetric with deploy, which is a core advantage of a declarative model over imperative compensation.' },
      int2:{ q:'How do you stop a bad config from reaching the fleet next time?', a:'Canaried, reported-hash-gated rollout: change desired for a small canary subset first, and gate expansion on those canaries actually converging (reported == new desired) and staying healthy. If the canaries go bad, halt and re-declare old desired before the other devices see the change. Combined with maintenance windows spreading updates into waves, a bad config&rsquo;s blast radius is a handful of canaries, not the fleet &mdash; the three-hash model makes &lsquo;did the canary take it and is it healthy&rsquo; a measured gate, not a guess.' } },
    { tag:'CURVEBALL',
      theme:'Template refactor = false drift',
      cue:'Someone refactored a config template &mdash; renamed variables, restructured it &mdash; with identical output, and now your whole fleet shows as drifted. What went wrong?',
      task:'Diagnose drift defined by the wrong thing (template/version, not rendered output) and fix the definition of identity.',
      model:'The system is defining a config&rsquo;s identity by the template or its version rather than the rendered output. A refactor that produces byte-identical output changed the template (and bumped its version) but changed nothing the device runs &mdash; yet the drift check saw a difference and flagged the whole fleet, triggering needless redeploys. The fix is to hash the rendered output, not the template: SHA-256 of the actual bytes. Then a refactor with identical output is not drift (same hash), and only a change that alters output is. Content, not version &mdash; which also means rendering must be deterministic so identical config always hashes the same.',
      int:{ q:'So how should drift have been defined from the start?', a:'By observable output. A device&rsquo;s desired state is the hash of what it will actually run &mdash; the rendered bytes &mdash; so &lsquo;is this drifted&rsquo; means &lsquo;do the bytes differ,&rsquo; not &lsquo;did the template or version differ.&rsquo; That definition is immune to refactors (no output change, no drift) and catches real changes (output differs, drift), which is exactly the semantics you want. Defining identity by content rather than template-version bookkeeping is the sharp idea; this incident is what happens when you get it wrong.' } },
    { tag:'CLOSE',
      cue:'Two sentences &mdash; sell me the design.',
      task:'Compress the whole reconciler to its spine and governing judgment, no hedging.',
      model:'A fleet desired-state reconciler: three hashes per device &mdash; desired (hash of the rendered output), deployed, reported &mdash; resolved through a stored tenant-site-tag-device hierarchy, driven by an event-driven resolve-render-diff-deploy-report loop under a per-tenant lock, correcting only in maintenance windows, with drift made visible &mdash; so the fleet converges toward a declared goal instead of being commanded. The judgment that makes it work: hash the output not the version, measure the device&rsquo;s reported reality rather than assuming, and separate always-on detection from safe, windowed, staged correction.',
      int:{ q:'If you had to cut one thing to ship, what goes?', a:'The maintenance-window scheduler sophistication and sweep-frequency tuning go first &mdash; real, but not core. What I&rsquo;d never cut is the three hashes over rendered output, the closed-loop confirmation on the reported hash, and gated correction: a precise content-defined drift signal, a loop that acts on measured reality, and safe correction. Those three are a working reconciler; hierarchical resolution and visibility are the layers on that spine.' } }
  ];
  var mockCurveIdx = mockBeats.findIndex(function(b){ return b.tag === 'CURVEBALL'; });
  var curveballs = [
    mockBeats[mockCurveIdx],
    { tag:'CURVEBALL', theme:'Non-deterministic render',
      cue:'Your fleet shows drifted even though nobody changed any config. What&rsquo;s your first hypothesis?',
      task:'Diagnose phantom drift from non-deterministic rendering and fix the render function.',
      model:'My first hypothesis is non-deterministic rendering &mdash; the same config rendering to different bytes each time, so the desired hash is unstable and every device perpetually looks drifted, with no config change involved. The usual culprits: a timestamp or generated-at header baked into the output, unordered map/dict keys serializing in random order, a nonce, or non-canonical serialization. The fix is to make rendering a pure function of the resolved config &mdash; strip volatile fields, sort keys canonically, pin encoding, forbid clocks and randomness in the render path &mdash; and add a CI test that renders the same input twice and asserts byte-identical output. That invariant underpins the whole hash-based model.',
      int:{ q:'How do you confirm it&rsquo;s rendering and not real drift?', a:'Render the same resolved config for the same device twice, in the same process and across processes, and diff the bytes &mdash; if they differ with identical input, it&rsquo;s non-deterministic rendering, not real drift. You can also hash the output repeatedly and watch the hash change with no input change. That immediately distinguishes &lsquo;the config is genuinely different&rsquo; from &lsquo;our render function is injecting noise,&rsquo; and it&rsquo;s exactly the test that belongs in CI to prevent the class entirely.' } },
    { tag:'CURVEBALL', theme:'Reconciler crash mid-deploy',
      cue:'The reconciler crashes after pushing to some devices but before recording the deployed hash. What state are you in?',
      task:'Show crash-idempotence &mdash; lock TTL frees the tenant, the loop converges from actual state, recovery is re-reconcile.',
      model:'A safe state, because the design is crash-idempotent. The lock auto-expires via its TTL, so the tenant isn&rsquo;t blocked. For a device where the push landed but deployed wasn&rsquo;t recorded, the next loop just re-diffs: the device reports the new hash while our deployed record shows old &mdash; a benign inconsistency the next reconcile resolves, because deployed is a cache and the durable truth is desired and reported. Worst case is a redundant re-push of config the device already runs, which is a no-op by determinism. Recovery isn&rsquo;t a special mode; it&rsquo;s the normal loop, because the loop is a function of current state, not of having completed a prior run.',
      int:{ q:'Why doesn&rsquo;t the lost &lsquo;deployed hash&rsquo; write corrupt anything?', a:'Because deployed is just a cache of &lsquo;what we last pushed,&rsquo; not a source of truth. The sources of truth &mdash; desired (intent) and reported (the device&rsquo;s measured reality) &mdash; both survive the crash. A stale deployed record only causes the next diff to see deployed != reported, which the loop handles by reconciling: recompute desired, observe reported, self-correct the record or re-push idempotently. No single hash&rsquo;s staleness can make the loop diverge &mdash; it can only cause an extra, harmless reconcile that re-establishes truth from the durable pair.' } },
    { tag:'CURVEBALL', theme:'Lock contention at scale',
      cue:'One tenant has a massive fleet and its reconciles are backing up behind the per-tenant lock. Fix it.',
      task:'Minimize the critical section and sub-partition the lock while preserving same-device exclusion.',
      model:'Two moves. First, make sure only the deploy coordination is under the lock &mdash; resolve, render, hash, and diff are read-only and should run outside it, concurrently; a common bug is holding the lock across the whole reconcile, serializing work that never needed it. Second, if that tenant is still too big for one lock, sub-partition it along a non-overlapping device boundary &mdash; per-site or a consistent hash of device ID &mdash; so disjoint slices reconcile in parallel while each device is always covered by exactly one sub-lock. The invariant to protect through all of it is one-device-one-lock: never two reconcilers deploying the same device.',
      int:{ q:'How do you partition the lock without reintroducing the race?', a:'By partitioning so no device belongs to two partitions and the mapping is stable. As long as a given device is always reconciled under the same sub-lock, the &lsquo;never two on the same device&rsquo; guarantee holds within that sub-lock while different partitions (disjoint device sets) proceed in parallel. The race only returns if partitions overlap or a device moves between sub-locks mid-flight &mdash; so keep the device-to-sublock mapping deterministic and non-overlapping. Correct sharding multiplies parallelism while preserving per-device exclusion.' } },
    { tag:'CURVEBALL', theme:'Device won&rsquo;t confirm',
      cue:'You deployed to a device but it never reports the new hash. What does the system do?',
      task:'Show the never-reports case as an explicit escalating state, not an assumed success.',
      model:'It stays in the unconverged / unconfirmed state &mdash; which is itself a signal, not a shrug. The device was deployed to (deployed set) but reported never advances to desired, so it remains visibly drifted, the reconciler keeps re-attempting on triggers within its window, and after enough missed confirmations it escalates to an alert with a health flag rather than retrying silently forever. The key discipline is that absence of a report is never treated as success &mdash; the whole point of closed-loop &mdash; so a device silent for a day surfaces as a problem to investigate, with its own age in the visibility API, not a mystery hidden behind an assumed-good deploy.',
      int:{ q:'How is &lsquo;never reports&rsquo; different from a device that reports a wrong hash?', a:'A wrong hash (deployed != reported) is a device running something, just not what we pushed &mdash; a rollback or failed apply the loop re-attempts. &lsquo;Never reports&rsquo; is a device we can&rsquo;t measure at all &mdash; possibly offline, unreachable, or its reporting is broken &mdash; which is a connectivity/health concern as much as a config one. Both are unconverged and visible, but they route differently: re-apply for the wrong-hash case, investigate reachability for the silent case. The visibility API distinguishes them by whether reported is stale-but-present versus missing.' } },
    { tag:'CURVEBALL', theme:'Fleet-wide bad config',
      cue:'A config change went out and started breaking devices before anyone noticed. How do you contain and recover?',
      task:'Contain via declarative rollback and prevent recurrence via canaried, reported-gated rollout.',
      model:'Contain: re-declare the last-known-good desired, and the loop converges the affected devices back &mdash; declarative rollback is symmetric with deploy, so there&rsquo;s no fragile undo to write; you change the goal and reconcile, in-window. Recover fully by using the visibility API to confirm the blast radius shrinks as devices report the good hash. Prevent recurrence with canaried rollout: change desired for a small subset first, gate expansion on those canaries actually converging and staying healthy, and halt-and-rollback if they don&rsquo;t &mdash; so a bad config&rsquo;s reach is a handful of canaries, not the fleet. Windows spreading updates into waves reinforce that.',
      int:{ q:'Why is rollback easier here than in an imperative deploy system?', a:'Because you just re-declare the previous desired and the same convergence loop rolls back, whereas imperative rollback needs explicit compensating actions &mdash; a reverse script undoing each forward step, which is order-dependent, error-prone, and often incomplete. Declarative rollback is &lsquo;go to state X&rsquo; regardless of current state, so it&rsquo;s uniform and reliable; imperative rollback is a separate, fragile procedure. That symmetry between roll-forward and roll-back is a major operational advantage of desired-state.' } },
    { tag:'CURVEBALL', theme:'Stuck device / blind redeploy',
      cue:'A device keeps failing to converge and your system keeps redeploying to it every loop, forever. What&rsquo;s wrong with that, and what&rsquo;s the right behavior?',
      task:'Show that infinite silent retry masks a real problem, and that localization plus escalation is the fix.',
      model:'Two things are wrong. One, redeploying on every mismatch without localizing means you might be re-pushing config to a device whose problem isn&rsquo;t delivery at all &mdash; deployed already matches desired, and it&rsquo;s the device that won&rsquo;t hold config (deployed != reported), a health issue re-pushing won&rsquo;t fix. Two, retrying silently forever masks that the device is genuinely stuck. The right behavior: use the three-hash localization to take the correct action (re-apply for a device-drift, not a blind redeploy), and bound the retries &mdash; after N failed convergence attempts across windows, flag the device unhealthy and alert rather than looping. Self-healing for the recoverable; escalation for the stuck.',
      int:{ q:'When exactly do you stop retrying and alert?', a:'When retries stop being likely to succeed and start being noise. A device that fails to converge across several maintenance windows isn&rsquo;t hitting a transient glitch &mdash; it&rsquo;s probably broken (unreachable, rejecting config, hardware), and silent infinite retry hides that behind &lsquo;the loop will get it eventually.&rsquo; So track consecutive failed attempts and, past a threshold, flag it unhealthy and alert while optionally backing off the retry cadence. The loop still owns correction, but a device that won&rsquo;t converge becomes a surfaced exception for a human, not an infinite quiet retry.' } },
    { tag:'CURVEBALL', theme:'Why not just use Terraform',
      cue:'This has desired state and drift detection &mdash; why build it instead of just using Terraform?',
      task:'Distinguish the shared declarative pattern from Terraform&rsquo;s execution model, which doesn&rsquo;t fit a live fleet.',
      model:'The pattern is identical &mdash; declare desired, diff, converge, detect drift &mdash; and I&rsquo;d steal Terraform&rsquo;s philosophy. But its execution model doesn&rsquo;t fit: Terraform is human-triggered plan/apply against a readable state file, not a loop running continuously and autonomously thousands of times a minute; it assumes providers whose state it can read authoritatively, whereas a terminal&rsquo;s true state must be self-reported and can drift locally between applies; and it has no native per-device maintenance windows, hierarchical per-tenant resolution at fleet cardinality, or closed-loop reported-hash confirmation. You&rsquo;d fight the tool to make it autonomous, real-time, and device-feedback-driven. Same principles, purpose-built engine for a live fleet.',
      int:{ q:'What do you keep from the IaC world even though you built your own?', a:'The declarative discipline: desired state as an inspectable, diffable value; a plan/diff before acting so changes are previewable; idempotent operations so re-applying is safe; and drift as a first-class comparison of declared-vs-actual. Those are exactly what this reconciler rests on, and IaC validated them at industry scale. You steal the philosophy and add what a live payment fleet needs &mdash; runtime autonomy, device-reported feedback, hierarchical multi-tenant resolution, windowed safety. Same principles, different engine, which is often right when a general tool&rsquo;s execution model doesn&rsquo;t match your domain even though its philosophy does.' } }
  ];
  var mockFrameIdx = mockBeats.findIndex(function(b){ return b.tag === 'FRAME'; });
  var frames = [
    mockBeats[mockFrameIdx].cue,
    'Design drift detection and correction for tens of thousands of devices.',
    'Keep a fleet of payment terminals running their intended config, continuously.',
    'Build a reconciler that converges device config toward a declared desired state.'
  ];
  return { cards: DS_CARDS, speak: DS_SPEAK, curveballs: curveballs, mockBeats: mockBeats, frames: frames };
})();
