/* topics/desired-state/drill.js -- topic 7 drill data. LOCAL arrays DS_CARDS / DS_SPEAK so
   loading this bundle does NOT clobber topic 1's working set. publishBanks() reseeds the
   globals from TOPIC_DS_BANK on switch. DS_SPEAK[i] pairs DS_CARDS[i]. Grounded in the ICS
   desired-state reconciler (three-hash model, rendered-output hashing). 7-bit ASCII. */
var DS_CARDS = [
  { tier:'SDE2', signal:'Converge, not command',
    q:"What&rsquo;s the difference between a desired-state system and just pushing config to devices?",
    a:"A desired-state system <b>declares a goal and drives reality toward it continuously</b>; pushing config is a one-shot imperative command that assumes success. The loop keeps comparing what a device <i>should</i> run against what it <i>reports</i> running, and re-acts until they match &mdash; so a failed push, a rollback, or a device offline during a deploy all self-correct on the next loop. Command-and-hope has no feedback; converge-to-goal is closed-loop and self-healing.",
    f:[
      { q:"Why is command-and-hope insufficient at fleet scale?",
        a:"Because at 10,000 devices, <b>something is always failing partially</b> &mdash; a deploy times out, a terminal is offline, a push half-applies &mdash; and a fire-and-forget command has no way to know or recover. You&rsquo;d accumulate silent divergence: devices running stale or wrong config with nothing detecting it. A convergence loop treats every device&rsquo;s state as continuously measured against the goal, so partial failures are just drift the next loop corrects. Command-and-hope works for one device you can eyeball; it doesn&rsquo;t survive a fleet where the steady state <i>is</i> partial failure." },
      { q:"What does &lsquo;declarative&rsquo; actually buy you operationally, beyond being a buzzword?",
        a:"<b>Idempotence and recoverability.</b> Because you declare the end state rather than the steps, running the reconcile again is always safe &mdash; it re-drives toward the same goal, whatever the current state &mdash; so retries, restarts, and crashes don&rsquo;t need bespoke recovery logic; you just reconcile again. It also makes the system <b>auditable</b> (the desired state is a value you can inspect and diff) and <b>self-correcting</b> (drift from any cause is detected and fixed uniformly). Imperative steps are order-dependent and fragile to partial completion; a declared goal plus a convergence loop is robust to exactly the messy, partial-failure reality of a fleet." }
    ],
    senior:"Framing it as <b>converge-toward-a-declared-goal (closed loop, self-healing) vs fire-an-imperative-command-and-assume</b> &mdash; and tying declarative to idempotence and recoverability &mdash; is the conceptual clarity an interviewer is listening for." },
  { tier:'SDE2', signal:'The three hashes',
    q:"What state do you track per device to know whether it&rsquo;s correctly configured?",
    a:"<b>Three hashes.</b> <b>Desired</b> &mdash; what the device should be running. <b>Deployed</b> &mdash; what we last pushed to it. <b>Reported</b> &mdash; what the device says it&rsquo;s actually running. When all three match, the device is converged. Any mismatch is drift &mdash; and which two differ tells you what kind.",
    f:[
      { q:"Why three and not just desired vs reported?",
        a:"Because <b>deployed</b> distinguishes &lsquo;we haven&rsquo;t pushed the change yet&rsquo; from &lsquo;we pushed it but the device isn&rsquo;t running it.&rsquo; With only desired vs reported, a mismatch is ambiguous &mdash; you can&rsquo;t tell whether the fix is &lsquo;deploy the new config&rsquo; or &lsquo;the deploy failed, investigate the device.&rsquo; The deployed hash is the record of <i>our</i> last action, so it splits the gap: desired-vs-deployed is about us (a deploy owed), deployed-vs-reported is about the device (it drifted or the deploy didn&rsquo;t stick). Three hashes make the state machine unambiguous; two collapse two different problems into one signal." },
      { q:"When all three match, are you done &mdash; or do you keep checking?",
        a:"You <b>keep checking</b> &mdash; convergence is a steady state to maintain, not a milestone to reach once. A device that matches now can drift later (a local change, a reboot to old config, a manual override on the device), and the only way to catch that is to keep re-measuring reported against desired every loop. So &lsquo;all three match&rsquo; means <i>converged right now</i>; the loop still re-evaluates on the next trigger, and if reported diverges, it re-acts. Desired-state is continuous reconciliation, so the check never stops &mdash; that&rsquo;s what makes it self-healing rather than a one-time deploy." }
    ],
    senior:"Naming the <b>desired / deployed / reported</b> triad &mdash; and explaining that the deployed hash is what disambiguates &lsquo;deploy owed&rsquo; from &lsquo;device drifted&rsquo; &mdash; is the model an interviewer wants to hear stated crisply." },
  { tier:'SDE2', signal:'Hash rendered, not template',
    q:"What exactly do you hash to get the &lsquo;desired&rsquo; state &mdash; the config template, or something else?",
    a:"The <b>rendered output</b> &mdash; SHA-256 of the fully-resolved config bytes the device will actually run &mdash; not the template or its version. A config&rsquo;s identity is <i>what it produces</i>, so a template refactored to render identical output is not a change (same hash, no redeploy), and a value edit that alters the output is (different hash, real drift). Content, not version, defines the desired state.",
    f:[
      { q:"What breaks if you hash the template version instead of the rendered output?",
        a:"Two symmetric failures. A <b>false positive</b>: you refactor a template &mdash; rename a variable, restructure it &mdash; with byte-identical output, the version bumps, and now the entire fleet looks drifted and gets needlessly redeployed. And a <b>false negative</b>: a change that <i>does</i> alter output but somehow doesn&rsquo;t bump the version (a shared partial, an included default) goes undetected because the version still matches. Hashing the version couples drift-detection to bookkeeping discipline that doesn&rsquo;t reflect reality. Hashing the rendered output couples it to <i>the actual thing the device runs</i>, which is the only definition of &lsquo;correct config&rsquo; that matters." },
      { q:"What property must rendering have for hashing the output to be reliable?",
        a:"<b>Determinism</b> &mdash; the same resolved config must always render to the exact same bytes. If rendering injects anything variable (a timestamp, a generation ID, unordered map keys), identical config produces different hashes and every device looks perpetually drifted. So rendering has to be a pure function of the resolved input: no clocks, no randomness, stable ordering. Given that, the output hash is a true content address &mdash; identical config anywhere hashes identically &mdash; and the whole three-hash comparison is trustworthy. Non-deterministic rendering silently poisons the entire model." }
    ],
    senior:"Content-addressing the <b>rendered output</b> (not the template version) &mdash; and immediately naming determinism as the property that makes it work, with the false-positive/false-negative framing &mdash; is a sharp, senior-level design instinct." },
  { tier:'SDE2', signal:'Hierarchical resolution',
    q:"A device&rsquo;s config comes from tenant defaults, its site, its device group, and device-specific overrides. How do you resolve the final value?",
    a:"Resolve <b>top-down, later levels overriding earlier</b>: tenant &rarr; site &rarr; tag (group) &rarr; device, each level winning over the one above. The device-specific value beats the tag, which beats the site, which beats the tenant default. And you <b>store every level</b>, not just the resolved answer &mdash; so you can explain where any value came from.",
    f:[
      { q:"Why store every level and not just the final resolved config?",
        a:"For <b>explainability and change-propagation</b>. Storing only the resolved answer loses <i>why</i> a device has a value &mdash; when an operator asks &lsquo;why is this timeout 30?&rsquo; you can&rsquo;t say &lsquo;the site overrode the tenant default of 60&rsquo; without the per-level source. It also breaks propagation: if you change a <b>site-level</b> default, you need to know which devices inherit it (no device-level override) versus which pin their own value &mdash; which requires knowing each device&rsquo;s resolution chain, not just its current answer. Storing every level makes the config <b>auditable</b> (provenance) and <b>maintainable</b> (a level change correctly re-resolves the right devices)." },
      { q:"This is basically CSS specificity or COALESCE &mdash; what&rsquo;s the risk in the override model?",
        a:"The risk is <b>surprising precedence and hidden overrides</b>. Like CSS, a device-level override silently wins over a well-intentioned site or tenant change, so an operator updates the site default and is baffled that some devices don&rsquo;t move &mdash; because they have a forgotten device-level pin. The mitigations are the same as good CSS: make precedence <b>explicit and visible</b> (the stored per-level provenance shows exactly which level set the effective value), avoid over-using the most-specific level (device overrides should be exceptions, not the norm, or you lose the leverage of hierarchy), and surface &lsquo;this value is overridden at a lower level&rsquo; when someone edits a higher one. Predictable precedence plus visible provenance keeps the hierarchy an asset rather than a debugging trap." }
    ],
    senior:"Describing <b>ordered hierarchical override (tenant&rarr;site&rarr;tag&rarr;device) with stored per-level provenance</b> &mdash; and flagging the CSS-specificity risk of hidden lower-level overrides &mdash; shows you&rsquo;ve built and operated one, not just drawn it." },
  { tier:'SDE2', signal:'The reconciliation loop',
    q:"Walk the loop &mdash; what happens from a config change to a device running the new config?",
    a:"<b>Resolve &rarr; render &rarr; hash &rarr; diff &rarr; deploy &rarr; report.</b> Resolve the hierarchy into a config, render it to output bytes, hash the output (desired), diff against deployed and reported; if there&rsquo;s drift, deploy the rendered config (recording it as deployed) inside a maintenance window under a lock. The device runs it and reports its hash; when reported == desired, it&rsquo;s converged. The loop re-runs on the next trigger.",
    f:[
      { q:"Where in that loop is the lock, and where is the maintenance-window gate?",
        a:"Both sit <b>just before deploy</b> &mdash; the two gates on the one step that touches devices. The reconciler resolves, renders, hashes, and diffs freely (all read-only, safe to do anytime), and only when a deploy is actually needed does it (1) acquire the <b>per-tenant lock</b> so no other reconciler deploys that fleet concurrently, and (2) check the <b>maintenance window</b> so the push only lands when it&rsquo;s safe. If the window is closed, it records the drift as visible-but-uncorrected and defers; if the lock is held, it defers to the next trigger. Detection is ungated; correction is doubly gated." },
      { q:"What makes it a loop rather than a one-shot pipeline?",
        a:"The <b>report step feeding back into the next diff</b>. A pipeline would end at &lsquo;deploy&rsquo; and assume success; the loop continues &mdash; the device reports its actual running hash, the next trigger re-diffs reported against desired, and if they still don&rsquo;t match, it deploys again. So the loop closes on measured reality, not on the act of pushing, and it runs continuously: every trigger re-resolves and re-diffs, correcting any new drift. It&rsquo;s a control loop (measure, compare, act, re-measure), not a deploy pipeline (do steps once and finish). That feedback is exactly what makes it converge rather than command." }
    ],
    senior:"Narrating the full <b>resolve&rarr;render&rarr;hash&rarr;diff&rarr;deploy&rarr;report</b> cycle as a continuous control loop &mdash; with lock and window gating only the deploy, and report closing the feedback &mdash; is the end-to-end fluency a senior round rewards." },
  { tier:'SDE3', signal:'Drift localization',
    q:"A device is drifted. How do you know whether the config changed upstream or the device changed under you?",
    a:"By <b>which pair of hashes differs</b>. <code>desired &ne; deployed</code> (with deployed == reported) means the intended config changed and we <b>haven&rsquo;t pushed it yet</b> &mdash; a deploy is owed. <code>deployed &ne; reported</code> means we pushed one thing but the device is <b>running another</b> &mdash; it drifted locally, rolled back, or the deploy failed. The three-way comparison turns &lsquo;something&rsquo;s wrong&rsquo; into a specific diagnosis.",
    f:[
      { q:"What does desired &ne; reported but deployed == desired mean?",
        a:"It means <b>we already pushed the correct config (deployed matches desired) but the device isn&rsquo;t running it</b> &mdash; so the device has drifted <i>after</i> a good deploy: it rolled back, someone changed it locally, or it reverted on reboot. The action isn&rsquo;t &lsquo;deploy the new config&rsquo; (we already did, and deployed is correct); it&rsquo;s <b>re-apply and investigate the device</b> &mdash; the deploy stuck once and came undone. This is exactly why the deployed hash exists: without it you&rsquo;d see desired &ne; reported and might redeploy blindly, when the real story is &lsquo;the config is right, the device won&rsquo;t hold it,&rsquo; which is a device-health problem, not a config-delivery one." },
      { q:"How does the localized diagnosis drive the next action?",
        a:"Each pattern maps to a distinct action. <b>desired &ne; deployed</b> &rarr; a deploy is owed: render and push (in-window, under lock). <b>deployed &ne; reported</b> &rarr; re-attempt the deploy and, if it keeps recurring, flag the device as unhealthy rather than retrying forever. <b>all match</b> &rarr; converged, do nothing but keep watching. So the three-way state isn&rsquo;t just a label &mdash; it&rsquo;s the input to the reconciler&rsquo;s decision: push, re-push-and-watch, or rest. That&rsquo;s what makes the loop precise: it doesn&rsquo;t blindly redeploy on any mismatch; it takes the <i>right</i> action for <i>which</i> pair diverged." }
    ],
    senior:"Reading the <b>specific differing pair</b> to separate &lsquo;deploy owed&rsquo; from &lsquo;device drifted after a good deploy&rsquo; &mdash; and mapping each to a different action (push vs re-apply-and-flag) &mdash; is the diagnostic precision that reads as senior." },
  { tier:'SDE3', signal:'The per-tenant lock',
    q:"Two reconciler instances pick up the same tenant at the same time. What stops them from fighting?",
    a:"A <b>per-tenant distributed lock</b> &mdash; the reconciler acquires <code>reconcile:{tenantId}</code> before deploying, with a bounded TTL (~30s) and acquire window (~4min). Only one reconciler holds a tenant at a time, so its fleet&rsquo;s deploys are serialized; the other defers to the next trigger. It&rsquo;s <b>per-tenant, not global</b>, so different tenants reconcile in parallel &mdash; concurrency across tenants, mutual exclusion within one.",
    f:[
      { q:"Why per-tenant rather than a global lock or a per-device lock?",
        a:"It&rsquo;s the right <b>granularity</b> for the contention. A <b>global</b> lock would serialize the entire platform &mdash; one tenant&rsquo;s reconcile blocks all others &mdash; throwing away the parallelism you need at scale. A <b>per-device</b> lock is finer than necessary and multiplies lock operations (10,000 acquire/release per sweep) while missing tenant-level coordination (two reconcilers interleaving different devices of the same tenant can still race on shared tenant state). <b>Per-tenant</b> matches the natural isolation boundary: tenants are independent (parallel is safe and desirable), and within a tenant the reconcile is a coherent unit that should run once at a time. Granularity follows the isolation boundary." },
      { q:"What does the TTL protect against, and separately, what does the acquire window protect against?",
        a:"The <b>TTL</b> (~30s) protects against a <b>crashed lock-holder</b>: if a reconciler dies mid-reconcile without releasing, the lock auto-expires so the tenant isn&rsquo;t blocked forever &mdash; it bounds the blast radius of a crash. The <b>acquire window</b> (~4min) protects the <b>waiter</b>: it bounds how long a second reconciler tries to get the lock before giving up and deferring to the next trigger, so a waiter never blocks indefinitely behind a busy tenant. One caps how long a dead holder can stall others; the other caps how long a live waiter will queue. Together they keep the lock live-lock-free and self-healing without manual intervention." }
    ],
    senior:"Choosing <b>per-tenant lock granularity</b> (parallel across tenants, serial within) and explaining the distinct jobs of the TTL (crash recovery) and acquire window (bounded waiting) is exactly the distributed-coordination depth a senior round probes." },
  { tier:'SDE3', signal:'Maintenance windows',
    q:"You detect drift on a payment terminal at 2pm during peak hours. Do you fix it immediately?",
    a:"No &mdash; <b>detect now, correct in-window</b>. Deploys are gated by <b>maintenance windows</b>, because pushing a config change to a terminal mid-transaction or at peak is unacceptable. The device is marked drifted and visible in the API, and the reconciler applies the fix when the site&rsquo;s window opens. The loop separates <b>detection</b> (continuous) from <b>correction</b> (windowed) &mdash; a device can be known-drifted for hours before it&rsquo;s safe to deploy.",
    f:[
      { q:"So drift can persist for hours by design &mdash; isn&rsquo;t that a problem?",
        a:"It&rsquo;s a <b>deliberate trade of promptness for safety</b>, and the key is that persisting drift is <b>known and bounded</b>, not silent. The alternative &mdash; deploying to a live payment terminal at peak &mdash; risks interrupting transactions, which is far worse than a config being stale for a few hours. What makes the trade acceptable is visibility: the device is in the drift API the whole time, so it&rsquo;s an <i>accounted-for</i> pending correction, not an undetected problem, and truly urgent changes (a security fix) can have an expedited or emergency window that overrides the normal schedule. Known, visible, windowed drift is a controlled state; the thing to avoid is <i>invisible</i> drift or unsafe-timed deploys." },
      { q:"How does windowed deploy interact with the visibility story?",
        a:"They&rsquo;re complementary: <b>windows gate correction, visibility covers the gap</b>. Because a device can be legitimately drifted-but-waiting, the visibility API has to show not just <i>that</i> it&rsquo;s drifted but <i>why it hasn&rsquo;t been fixed yet</i> &mdash; &lsquo;drifted, correction pending, next window at 02:00.&rsquo; That distinguishes a healthy &lsquo;waiting for its window&rsquo; device from an unhealthy &lsquo;deploy keeps failing&rsquo; one, which look identical if you only see &lsquo;drifted.&rsquo; So the window model <i>requires</i> good visibility to be operable: without it, windowed drift is indistinguishable from a stuck device. With it, an operator sees exactly which devices are safely pending versus genuinely stuck." }
    ],
    senior:"Separating <b>continuous detection from window-gated correction</b> &mdash; and recognizing that windowed drift is only acceptable <i>because</i> it&rsquo;s visible and bounded, with an emergency-window escape hatch &mdash; is the production-safety judgment a senior interviewer wants." },
  { tier:'SDE3', signal:'Convergence confirmation',
    q:"You push config to a device. How do you know it actually took?",
    a:"You <b>don&rsquo;t assume &mdash; you wait for the device to report its running hash</b>. Convergence is confirmed only when <code>reported == desired</code>; until then the device is still drifted. A push that failed, a rollback, or an offline device all leave <code>deployed &ne; reported</code>, which the next loop sees and re-acts on. Measuring the device&rsquo;s <i>actual</i> reported state &mdash; rather than trusting the deploy stuck &mdash; is what makes the system self-healing.",
    f:[
      { q:"What if the device never reports back?",
        a:"Then it stays in the <b>unconverged / unknown</b> state, and that&rsquo;s itself a signal. A device that was deployed to but never confirms is either offline, unhealthy, or unreachable &mdash; so it remains visibly drifted (deployed set, reported stale or missing), the reconciler keeps re-attempting on triggers, and after enough missed confirmations it escalates to an <b>alert</b> rather than retrying silently forever. The absence of a report is not treated as success (the whole point of closed-loop) nor ignored; it&rsquo;s an explicit &lsquo;this device hasn&rsquo;t confirmed&rsquo; state with its own age, so a terminal that&rsquo;s been silent for a day surfaces as a problem to investigate, not a mystery hidden behind an assumed-good deploy." },
      { q:"Why is &lsquo;assume the push worked&rsquo; the failure mode you&rsquo;re avoiding?",
        a:"Because a push succeeding at the <i>transport</i> level says nothing about the device <i>running</i> the config. The connection can succeed while the device rejects the config, applies it and crashes back to the old one, or reboots to a previous version &mdash; all leaving it running the wrong thing while your records say &lsquo;deployed, done.&rsquo; Assume-success turns those into <b>silent divergence</b>: your system believes the fleet is correct when it isn&rsquo;t. Closed-loop convergence refuses to mark done until the device <i>itself</i> reports the matching hash, so the source of truth for &lsquo;is it running the right config&rsquo; is the device&rsquo;s measured state, not our optimistic assumption. That&rsquo;s the difference between a system that <i>hopes</i> and one that <i>knows</i>." }
    ],
    senior:"Insisting convergence is confirmed only by the <b>device&rsquo;s reported hash</b> (never by assume-success), and treating a missing report as an explicit escalating state, is the closed-loop discipline that separates a robust reconciler from a fragile one." },
  { tier:'SDE3', signal:'Deterministic rendering',
    q:"Why does rendering the config have to be deterministic, and what goes wrong if it isn&rsquo;t?",
    a:"Because the <b>desired hash is taken over the rendered output</b> &mdash; if the same resolved config can render to different bytes (a timestamp, unordered map keys, a &lsquo;generated-at&rsquo; comment), the hash is unstable and <b>every reconcile looks like drift</b>. You&rsquo;d redeploy the fleet endlessly chasing phantom changes. Rendering must be a <b>pure function</b> of the resolved config: same input, same bytes, always &mdash; so identical config hashes identically everywhere.",
    f:[
      { q:"What are the classic sources of render nondeterminism to watch for?",
        a:"The usual suspects: <b>timestamps</b> or &lsquo;generated-at&rsquo; headers baked into output; <b>unordered iteration</b> over maps/sets/dicts so keys serialize in random order; <b>floating-point or locale-dependent formatting</b>; <b>absolute paths, hostnames, or environment values</b> leaking in; <b>random IDs or nonces</b>; and <b>non-canonical serialization</b> (JSON key order, whitespace, trailing newlines varying by library). Each makes byte-identical inputs produce different bytes. The fix is canonicalization: sort keys, strip volatile fields, pin formatting and encoding, and forbid clocks/randomness in the render path &mdash; so the output is a deterministic function of the resolved config and nothing else." },
      { q:"How do you actually test that rendering is deterministic?",
        a:"<b>Render the same input many times and assert byte-identical output</b> &mdash; ideally across processes, machines, and time, not just one run &mdash; and gate it in CI. A property test that feeds a range of resolved configs through render twice and diffs the bytes catches accidental nondeterminism the moment it&rsquo;s introduced. You can also hash the output in the test and assert the hash is stable across runs (mirroring exactly what production does). And a golden-file test pins known configs to known rendered bytes, so a change in rendering that shifts output is caught as an intentional-vs-accidental diff. The invariant &lsquo;same resolved config &rarr; same bytes&rsquo; is testable and belongs in the gate, because a regression here poisons the entire drift model silently." }
    ],
    senior:"Treating deterministic rendering as a <b>tested invariant</b> (canonical serialization, no clocks/randomness, render-twice-and-diff in CI) &mdash; and knowing the classic nondeterminism sources &mdash; is the rigor behind a content-hash-based system." },
  { tier:'SDE3', signal:'Event-driven vs sweep',
    q:"Do you reconcile the whole fleet on a timer, or something else?",
    a:"<b>Event-driven</b>, triggered by what actually changes state &mdash; a config edit, a device check-in, a window opening &mdash; not a blind timer sweep of all 10,000 devices. A full periodic sweep is either too slow (drift undetected between sweeps) or too wasteful (re-rendering everything on a cron, mostly finding no change). Triggering on real events means work is proportional to change and propagation is seconds, with a slow sweep as a backstop.",
    f:[
      { q:"If you&rsquo;re event-driven, why keep a periodic sweep at all?",
        a:"As a <b>backstop for missed events and silent drift</b>. Event-driven propagation is fast but not perfectly reliable &mdash; an event can be dropped, a trigger can fail, and some drift produces <i>no</i> event at all (a device silently reverts locally without checking in). A slow, low-frequency full sweep catches anything the event path missed: it re-resolves and re-diffs every device, so nothing stays drifted indefinitely just because its trigger never fired. It&rsquo;s the belt-and-suspenders pattern &mdash; events for fast, cheap, common-case convergence; the sweep as an eventual-consistency guarantee that the whole fleet gets reconciled regardless. Fast path plus safety net, rather than betting everything on events firing." },
      { q:"What events actually trigger a reconcile?",
        a:"Three broad classes. <b>Desired-side changes</b> &mdash; a config edit at any hierarchy level (tenant/site/tag/device), which changes desired for the affected devices. <b>Reported-side changes</b> &mdash; a device checking in with its running hash, which updates reported and may reveal drift. And <b>time/policy events</b> &mdash; a maintenance window opening (so queued corrections can now deploy) or the periodic sweep tick. Each maps to the part of the three-hash state it affects: desired-side events mean &lsquo;a deploy may now be owed,&rsquo; reported-side events mean &lsquo;the device&rsquo;s reality moved,&rsquo; window events mean &lsquo;correction is now permitted.&rsquo; The reconciler is woken by whichever fired and reconciles just the impacted devices." }
    ],
    senior:"Choosing <b>event-driven reconciliation (work proportional to change) with a periodic sweep as a missed-event backstop</b> &mdash; and mapping event classes to the three-hash state each moves &mdash; is the scale-and-reliability instinct a senior round rewards." },
  { tier:'SDE3', signal:'Drift visibility',
    q:"An operator asks &lsquo;how much of my fleet is running the right config right now?&rsquo; How do you answer?",
    a:"Through the <b>drift-visibility API</b> &mdash; a first-class output of the reconciler. It reports, per device and aggregated, which are converged vs drifted, <b>which pair of hashes differs</b> (deploy owed vs device drifted), and <b>how long</b> each has been out of sync. Because every resolution level and all three hashes are stored, it can also answer <i>why</i>: where a value came from, and whether a drifted device is safely waiting for its window or genuinely stuck.",
    f:[
      { q:"Why is visibility a first-class output rather than just logs you can grep?",
        a:"Because <b>drift is a live operational state, not a historical event</b>. Logs tell you what happened; an operator needs to know what <i>is</i> &mdash; right now, which devices are wrong, and why &mdash; to make decisions (is this rollout safe to continue? is that site&rsquo;s window working?). A queryable, current, aggregated view is what makes the fleet <b>operable</b>: you can answer &lsquo;97% converged, 300 drifted, 280 waiting for windows, 20 failing&rsquo; instantly, versus reconstructing it from log spelunking. It also makes the self-healing loop <b>trustworthy</b> &mdash; a system that silently fixes things is one you can&rsquo;t audit or debug, so surfacing exactly what it&rsquo;s doing and why is what earns the right to be autonomous. Visibility is the interface between an autonomous loop and the humans accountable for the fleet." },
      { q:"What specific fields turn &lsquo;this device is drifted&rsquo; into something actionable?",
        a:"The differentiators: <b>which pair differs</b> (desired&ne;deployed = we owe a deploy; deployed&ne;reported = the device won&rsquo;t hold config &mdash; different owners, different fixes); <b>how long</b> it&rsquo;s been drifted (a device drifted for minutes waiting for its window is fine; one drifted for days is a problem); <b>correction status</b> (pending-window vs actively-failing vs never-reported); the <b>next window</b> (so &lsquo;drifted&rsquo; reads as &lsquo;will self-correct at 02:00&rsquo; not &lsquo;stuck&rsquo;); and the <b>resolution provenance</b> (which level set the desired value, for &lsquo;why is it even trying to set this?&rsquo;). Bare &lsquo;drifted: true&rsquo; is noise; those fields let an operator triage &mdash; ignore the safely-pending, investigate the stuck, and know exactly what to look at." }
    ],
    senior:"Treating <b>drift as an observable, queryable current state</b> (which pair, how long, correction status, provenance) rather than log residue &mdash; and arguing visibility is what earns an autonomous loop the right to run &mdash; is the operability instinct a senior round values." },
  { tier:'SDE3', signal:'Deploy failure and retry',
    q:"A deploy to a device fails. What happens?",
    a:"Nothing special is needed &mdash; the <b>loop handles it structurally</b>. A failed deploy leaves <code>deployed &ne; reported</code> (or reported never advances to desired), so the device stays visibly drifted, and the <b>next trigger re-attempts</b> the deploy in the next window. Because the loop converges toward desired regardless of current state, a retry is just another reconcile &mdash; no bespoke retry queue. But repeated failures escalate: after N missed windows, it&rsquo;s an <b>alert and a health flag</b>, not infinite silent retry.",
    f:[
      { q:"Why doesn&rsquo;t a failed deploy need its own retry mechanism?",
        a:"Because <b>the convergence loop <i>is</i> the retry mechanism</b>. In an imperative system a failed step needs an explicit retry queue, backoff, and dead-lettering, because the system only acts when told to. Here, the loop already re-evaluates every device against desired on every trigger &mdash; a device whose deploy failed is simply still drifted, which the next reconcile naturally re-addresses. The &lsquo;retry&rsquo; falls out of the loop&rsquo;s continuous nature: you don&rsquo;t track failed deploys to retry them; you track desired state and re-converge, and a previously-failed device is just one that hasn&rsquo;t converged yet. This is a core benefit of declarative convergence &mdash; error recovery is the same code path as normal operation, not a separate failure-handling subsystem." },
      { q:"When do you stop retrying and alert instead of looping forever?",
        a:"When retries stop being <b>likely to succeed</b> and start being <b>noise masking a real problem</b>. A device that fails to converge across <i>several</i> maintenance windows isn&rsquo;t hitting a transient glitch &mdash; it&rsquo;s likely genuinely broken (unreachable, rejecting the config, hardware fault), and silently re-attempting forever hides that behind &lsquo;the loop will get it eventually.&rsquo; So you bound it: track consecutive failed convergence attempts, and after a threshold, <b>flag the device unhealthy and alert</b> while optionally backing off the retry cadence. The loop still owns correction, but a device that won&rsquo;t converge becomes a surfaced exception for a human, not an infinite quiet retry. Self-healing for the recoverable; escalation for the stuck." }
    ],
    senior:"Recognizing that <b>the convergence loop is itself the retry path</b> (no separate queue) &mdash; while bounding it with escalation-to-alert on repeated failure so stuck devices surface &mdash; is the declarative-systems maturity a senior interviewer checks." },
  { tier:'SDE3', signal:'Idempotent loop',
    q:"Why does it matter that a reconcile can be safely run again, and how do you guarantee it?",
    a:"Because the loop <b>will</b> run again &mdash; on the next trigger, after a crash, on the sweep &mdash; so every reconcile must be <b>idempotent</b>: running it against an already-converged device does nothing, and against a drifted one drives it to the same goal. It&rsquo;s guaranteed by <b>declaring the end state, not steps</b>: the loop computes desired and diffs; if there&rsquo;s no diff, no action. There&rsquo;s no &lsquo;apply step 3&rsquo; that breaks if repeated &mdash; just &lsquo;make reality match desired,&rsquo; which is naturally idempotent.",
    f:[
      { q:"How does declaring the end-state (vs steps) give you idempotence for free?",
        a:"Because a <b>diff-and-converge</b> operation is a no-op when there&rsquo;s nothing to converge. The loop always starts by computing desired and comparing to current (deployed/reported); if they match, it does nothing &mdash; running it once or a hundred times on a converged device has identical effect. Contrast an imperative script (&lsquo;increment the version, append this line, restart&rsquo;): re-running it double-applies &mdash; two increments, two appended lines &mdash; because each step assumes it hasn&rsquo;t run. Declarative operations are idempotent because they specify the <i>destination</i>, not the <i>journey</i>: &lsquo;be in state X&rsquo; is the same whether you&rsquo;re already there or not, whereas &lsquo;take these steps toward X&rsquo; compounds on repeat. The idempotence isn&rsquo;t added; it&rsquo;s inherent to comparing-against-a-goal." },
      { q:"What would break idempotence, and how do you avoid it?",
        a:"Any <b>non-declarative side effect in the loop</b>: a step that <i>appends</i> rather than <i>sets</i>, a counter it increments, an external call that isn&rsquo;t safe to repeat (charging something, sending a non-deduplicated notification), or state derived from &lsquo;did we do this already&rsquo; that a crash can lose. You avoid it by keeping the loop&rsquo;s effects to <b>convergent operations</b> &mdash; set the config to X (not &lsquo;change it&rsquo;), record the deployed hash as X (not &lsquo;log another deploy&rsquo;) &mdash; and by making any external effect idempotent (keyed, deduplicated) or driven off the diff so it only fires when state actually needs to change. The rule: the reconcile should be expressible as &lsquo;make it be X,&rsquo; and every effect inside it should be safe to apply when it&rsquo;s already X." }
    ],
    senior:"Grounding idempotence in <b>declarative diff-and-converge (no-op when already converged)</b> &mdash; and knowing that append/increment/non-deduplicated side effects are what break it &mdash; is the correctness reasoning behind a crash-safe, retry-safe loop." },
  { tier:'SDE3', signal:'Safe rollout',
    q:"A new config for 10,000 devices turns out to be bad. How do you avoid bricking the whole fleet?",
    a:"<b>Don&rsquo;t converge everything at once.</b> Roll the desired-state change out gradually &mdash; canary a small set, watch their reported hashes and health, then expand &mdash; and gate correction with maintenance windows so devices update in waves, not simultaneously. Because desired state is declarative, a <b>rollback is just re-declaring the old desired</b>: set desired back, and the loop converges the fleet to it. Staged, windowed convergence means a bad config is caught on the canaries before it reaches the fleet.",
    f:[
      { q:"How is rollback different in a declarative system versus an imperative one?",
        a:"In a declarative system, rollback is <b>trivial and uniform &mdash; you just re-declare the previous desired state</b>, and the same convergence loop that rolled forward now rolls back, converging every device to the old config. There&rsquo;s no separate &lsquo;undo&rsquo; logic, because &lsquo;go to state X&rsquo; works regardless of the current state. In an imperative system you need <b>explicit compensating actions</b> &mdash; a reverse script that undoes each forward step &mdash; which is error-prone, order-dependent, and often incomplete (some steps don&rsquo;t cleanly reverse). Declarative rollback is symmetric with roll-forward (change desired, let it converge); imperative rollback is a whole separate, fragile procedure. That symmetry is a major operational advantage of desired-state." },
      { q:"How do canaries fit the three-hash model concretely?",
        a:"You change desired for <b>a small canary subset first</b>, and the loop converges just those devices &mdash; then you <b>watch their reported hashes and health</b>: reported advancing to the new desired and staying healthy is your success signal. If the canaries converge cleanly and behave, you widen the desired change to the next wave; if their reported state or health goes bad, you halt the rollout and re-declare the old desired, converging the canaries back &mdash; before the other 9,900 devices ever saw the change. The three-hash model makes this measurable: &lsquo;did the canary actually take the new config and is it running it correctly&rsquo; is exactly reported==new-desired plus health, not a guess. Canaries plus reported-hash measurement give you a real, observed gate at each rollout stage." }
    ],
    senior:"Combining <b>staged/canaried convergence, reported-hash-gated waves, and declarative rollback (re-declare old desired)</b> &mdash; and contrasting that symmetric rollback with fragile imperative compensation &mdash; is the fleet-safety thinking a senior round rewards." },
  { tier:'SDE3', signal:'Multi-tenant isolation',
    q:"It&rsquo;s multi-tenant. What has to be isolated in the reconciler?",
    a:"Everything per device is <b>tenant-scoped</b> &mdash; desired/deployed/reported state, the resolution hierarchy, and the visibility API all bounded to one tenant, so a tenant can never see or affect another&rsquo;s devices. The <b>lock is per-tenant</b>, giving cross-tenant parallelism with within-tenant serialization. And the resolution hierarchy is naturally tenant-rooted (tenant &rarr; site &rarr; tag &rarr; device), so a tenant&rsquo;s config genuinely can&rsquo;t leak into another&rsquo;s resolution.",
    f:[
      { q:"Where could cross-tenant leakage realistically sneak in?",
        a:"The usual places: a <b>drift/visibility query missing its tenant filter</b> (returning another tenant&rsquo;s device states &mdash; the same missing-WHERE-tenant_id class as the authorization topic); a <b>resolution step</b> that pulls a site or tag without confirming it belongs to the device&rsquo;s tenant (so a shared or mis-keyed group bleeds config across tenants); and <b>lock keys or cache keys not namespaced by tenant</b> (so two tenants collide on a &lsquo;reconcile&rsquo; lock or read each other&rsquo;s cached resolved config). The defense is to make tenant scope <b>structural</b> &mdash; tenant-rooted hierarchy, tenant-prefixed lock/cache keys, and a data-access layer that injects the tenant predicate on every query &mdash; plus a cross-tenant isolation test in CI. Isolation that depends on every query remembering the filter is isolation you&rsquo;ll eventually lose." },
      { q:"How does per-tenant locking serve both isolation and scale at once?",
        a:"It aligns the <b>concurrency boundary with the isolation boundary</b>. For <b>scale</b>: tenants are independent, so per-tenant locks let all tenants reconcile in parallel &mdash; no global serialization &mdash; while still serializing within a tenant where coordination is actually needed. For <b>isolation</b>: a per-tenant lock (namespaced by tenant) means one tenant&rsquo;s reconcile contention never touches another&rsquo;s, and it reinforces that a reconcile operates on exactly one tenant&rsquo;s fleet at a time. The same choice that gives cross-tenant parallelism (scale) also guarantees cross-tenant non-interference (isolation), because the natural unit of both is the tenant. Picking the lock granularity to match the tenant boundary is what makes the two goals reinforce rather than conflict." }
    ],
    senior:"Scoping <b>all three-hash state, the hierarchy, and the lock/cache keys per tenant</b> &mdash; making isolation structural and noting the per-tenant lock serves parallelism and non-interference together &mdash; is the multi-tenant rigor a senior interviewer wants." },
  { tier:'Staff', signal:'Scale at fleet size',
    q:"10,000 devices per tenant, many tenants, all reconciling. Where does this design strain first?",
    a:"The <b>deploy/report throughput and the lock</b>, not the diffing. Resolving and hashing are cheap and event-scoped; the pressure is (1) the rate of reported check-ins and deploys the reconciler and datastore must absorb, and (2) the <b>per-tenant lock serializing a tenant&rsquo;s reconciles</b> &mdash; if one tenant&rsquo;s fleet is large and its reconcile is slow, lock hold-time can starve its own backlog. You relieve it by making reconcile <b>incremental</b> (only affected devices per event, not the whole tenant under the lock), keeping the lock&rsquo;s critical section to the actual deploy coordination, and sharding reported-state ingestion.",
    f:[
      { q:"Why isn&rsquo;t the three-way diff the bottleneck?",
        a:"Because the diff is a <b>cheap, embarrassingly-parallel hash comparison</b> &mdash; comparing three fixed-size hashes per device is trivial CPU, needs no coordination, and is done per-event on just the affected devices, not the whole fleet at once. What&rsquo;s expensive is <b>touching reality</b>: pushing config to thousands of devices (network, device-side apply, retries), ingesting a high rate of reported check-ins (write throughput, storage), and <i>coordinating</i> those safely (the lock). Those are I/O- and coordination-bound, which is where real systems bottleneck &mdash; not the arithmetic of comparing hashes. A classic mistake is optimizing the diff (the cheap part) while the deploy/report pipeline and lock (the expensive parts) are the actual ceiling. Profile the I/O and coordination, not the comparison." },
      { q:"How do you keep the per-tenant lock from serializing too much of a big tenant&rsquo;s work?",
        a:"By <b>doing as little as possible under the lock</b>. Resolve, render, hash, and diff are read-only &mdash; do them <i>outside</i> the lock, concurrently; acquire the lock only for the small critical section that must be exclusive: deciding to deploy a given device and recording its deployed hash, so two reconcilers can&rsquo;t deploy the same device at once. Combined with <b>incremental reconcile</b> (an event touches only its affected devices, so the locked work per event is tiny) and, if a single tenant is still too large, <b>sub-partitioning the lock</b> (per-site sub-locks so independent slices reconcile in parallel), the lock stops being a whole-tenant serialization point and becomes brief, per-slice mutual exclusion. The lock&rsquo;s job is only &lsquo;not the same device twice&rsquo; &mdash; everything not serving that can run outside it." }
    ],
    senior:"Identifying <b>deploy/report I/O and lock hold-time (not the diff) as the scale ceiling</b> &mdash; and relieving it with incremental reconcile, a minimal critical section, and per-site lock sub-partitioning &mdash; is the systems-scaling judgment that marks a Staff answer." },
  { tier:'Staff', signal:'Crash mid-deploy',
    q:"The reconciler crashes after pushing to some devices but before recording the deployed hash. What state are you in, and is it safe?",
    a:"It&rsquo;s <b>safe, because the design is crash-idempotent</b>. The lock <b>auto-expires (TTL)</b>, freeing the tenant. For a device where the push landed but deployed wasn&rsquo;t recorded, the next loop re-diffs: the device reports the new hash while our deployed record shows the old one &mdash; a benign inconsistency the next reconcile resolves (it re-derives desired, sees reported now matches, and updates records / re-pushes idempotently). No device is left half-configured in a way a retry can&rsquo;t fix, because <b>the loop converges from whatever the actual state is</b> &mdash; it never depends on having completed a previous run. Crash recovery is &lsquo;acquire the lock and reconcile again,&rsquo; not a bespoke rollback.",
    f:[
      { q:"Why doesn&rsquo;t a lost &lsquo;deployed hash&rsquo; write corrupt the model?",
        a:"Because <b>deployed is a cache of &lsquo;what we last pushed,&rsquo; not the source of truth</b> &mdash; the source of truth for reality is the device&rsquo;s <i>reported</i> hash, and for intent is <i>desired</i>, both of which survive the crash. A stale deployed record just means the next diff sees deployed&ne;reported (we think we pushed old, device reports new); the loop&rsquo;s response is to reconcile &mdash; recompute desired, observe reported already matches, and self-correct the deployed record (or, if it doesn&rsquo;t match, re-push idempotently). Worst case is a redundant re-push of config the device already runs, which is a no-op by determinism, not corruption. The three-hash model degrades gracefully because no single hash&rsquo;s staleness can make the loop <i>diverge</i> &mdash; it can only cause an extra, harmless reconcile that re-establishes truth from the durable desired/reported pair." },
      { q:"What makes &lsquo;just reconcile again&rsquo; a valid recovery rather than a hope?",
        a:"That the loop is <b>a pure function of current state, not of history</b>. Because each reconcile recomputes desired and diffs against the <i>actual</i> current deployed/reported &mdash; making no assumption that any prior run completed &mdash; running it from any partial state converges to the same goal. There&rsquo;s no step that requires &lsquo;the previous run got to step 3&rsquo;; there&rsquo;s only &lsquo;here is desired, here is reality, close the gap.&rsquo; That&rsquo;s precisely idempotent convergence: recovery isn&rsquo;t a special mode, it&rsquo;s the normal loop applied to whatever mess the crash left. The lock TTL guarantees the crashed holder can&rsquo;t block forever, and the loop&rsquo;s state-not-history design guarantees re-running is always correct &mdash; so &lsquo;reconcile again&rsquo; is a guarantee from the architecture, not optimism." }
    ],
    senior:"Explaining <b>crash-idempotence &mdash; deployed is a cache, the loop is a function of current state not history, so recovery is just re-reconcile after the lock TTL</b> &mdash; is exactly the failure-mode reasoning that separates a Staff-level answer on reconcilers." },
  { tier:'Staff', signal:'Lock contention at scale',
    q:"A huge tenant&rsquo;s reconciles are slow, and the per-tenant lock is becoming a bottleneck for that tenant. What do you do?",
    a:"<b>Shrink the critical section, then shard within the tenant.</b> First, keep the lock around only the <b>coordination that truly needs mutual exclusion</b> (the per-device deploy decision and hash record), not the read-only resolve-render-diff. If a single tenant is still too big, <b>partition its lock</b> &mdash; per-site or per-shard sub-locks &mdash; so independent slices reconcile in parallel while still serializing within a slice. The principle: make the locked region as small and as parallelizable as correctness allows, since the lock exists only to stop two reconcilers deploying the <i>same</i> device at once.",
    f:[
      { q:"What part of the loop actually needs the lock, and what doesn&rsquo;t?",
        a:"Only the <b>deploy coordination</b> needs it &mdash; the moment where you decide &lsquo;this device needs a push&rsquo; and record the deployed hash, because two reconcilers doing that concurrently for the same device is the race you&rsquo;re preventing. Everything else &mdash; resolving the hierarchy, rendering, hashing, and diffing &mdash; is <b>read-only</b> and produces the same result no matter how many reconcilers run it, so it needs no lock and can happen fully concurrently. The bug pattern is holding the lock across the <i>whole</i> reconcile (including the expensive read-only rendering of thousands of devices), which serializes work that never needed serializing. Pull all the read-only computation out of the lock; hold it only for the tiny exclusive deploy-and-record step." },
      { q:"How do you partition a tenant&rsquo;s lock without reintroducing the race it prevents?",
        a:"By partitioning along a boundary where <b>no device belongs to two partitions</b> &mdash; per-site, per-device-shard, or a consistent hash of device ID &mdash; so each device is covered by exactly one sub-lock. As long as a given device is always reconciled under the <i>same</i> sub-lock, the &lsquo;never two reconcilers on the same device&rsquo; guarantee holds within that sub-lock, while different partitions (disjoint device sets) proceed in parallel safely. The race only returns if partitions <b>overlap</b> (a device reachable under two sub-locks) or if the partition mapping isn&rsquo;t stable (a device moving between sub-locks mid-flight) &mdash; so you keep the mapping deterministic and non-overlapping. Correct sharding preserves per-device exclusion while multiplying parallelism; the invariant to protect is &lsquo;one device, one lock.&rsquo;" }
    ],
    senior:"Minimizing the critical section to the <b>deploy-and-record step</b> and <b>sub-partitioning the lock along a non-overlapping device boundary</b> (preserving one-device-one-lock) is the concurrency-scaling depth a Staff round is probing for." },
  { tier:'Staff', signal:'Desired-state vs IaC',
    q:"How is this desired-state reconciler different from infrastructure-as-code, which also has a &lsquo;desired state&rsquo; and detects drift?",
    a:"Same <i>pattern</i>, different <b>domain and cadence</b>. IaC (Terraform/CDK) declares <b>infrastructure</b> &mdash; resources and their shape &mdash; and reconciles at <b>deploy time</b> via a human-run plan/apply, with drift detection as an occasional check. This reconciler declares <b>per-device runtime config</b> across a live fleet and reconciles <b>continuously and autonomously</b>, converging thousands of devices in real time within safety windows. IaC&rsquo;s &lsquo;resources&rsquo; are cloud objects changed rarely by operators; here they&rsquo;re payment terminals whose config changes often and whose <i>reported</i> reality must be measured, not assumed. The converge-not-command idea is shared; the scale, autonomy, real-device feedback, and windowed safety make it its own system.",
    f:[
      { q:"So why not just use Terraform for the fleet?",
        a:"Because Terraform&rsquo;s model doesn&rsquo;t fit <b>continuous, autonomous, high-cardinality, measured-reality</b> reconciliation. It&rsquo;s built around a <b>human-triggered plan/apply</b> against a state file, not a loop that runs thousands of times a minute on its own; it assumes providers whose state it can <b>read authoritatively</b>, whereas a payment terminal&rsquo;s true state must be <b>reported by the device</b> and can drift locally between applies; and it has no native notion of <b>per-device maintenance windows, hierarchical per-tenant resolution at fleet scale, or the closed-loop reported-hash confirmation</b> this needs. You&rsquo;d be fighting the tool to make it autonomous, real-time, and device-feedback-driven. The <i>pattern</i> (declare desired, diff, converge) is exactly right; Terraform is the wrong <i>engine</i> for a live fleet of tens of thousands of devices reconciling continuously." },
      { q:"What&rsquo;s the shared idea worth stealing from IaC even though you built your own?",
        a:"The <b>declarative core</b>: represent desired state as an inspectable, diffable value; compute a <b>plan/diff</b> before acting so changes are previewable; make operations <b>idempotent</b> so re-applying is safe; and <b>detect drift</b> by comparing declared-vs-actual. Those are exactly the principles this reconciler rests on &mdash; and IaC validated them at industry scale. What you steal is the <i>discipline</i> (desired as data, plan before apply, idempotent converge, drift as first-class), and what you add is the runtime autonomy, the device-reported feedback loop, hierarchical multi-tenant resolution, and windowed safety that a live payment fleet demands. Same principles, purpose-built engine &mdash; which is often the right call when a general tool&rsquo;s <i>execution model</i> doesn&rsquo;t match your domain even though its <i>philosophy</i> does." }
    ],
    senior:"Placing this as the <b>same converge/diff/idempotent/drift pattern as IaC but a purpose-built engine</b> for runtime-continuous-autonomous-fleet vs deploy-time-human-infra &mdash; stealing the philosophy while rejecting the execution model &mdash; is precisely the build-vs-adapt judgment a Staff round wants." },
  { tier:'Staff', signal:'The whole design',
    q:"Tie it together: one sentence for how you&rsquo;d design a fleet desired-state system, and the judgment that makes it work.",
    a:"<b>Three hashes per device &mdash; desired (hash of the rendered output), deployed, reported &mdash; resolved through a stored tenant&rarr;site&rarr;tag&rarr;device hierarchy, driven by an event-driven resolve&rarr;render&rarr;diff&rarr;deploy&rarr;report loop under a per-tenant lock, correcting only in maintenance windows, with drift made visible</b> &mdash; a system that converges toward a declared goal rather than commanding. The judgment that makes it work: hash the <i>output</i> not the version, measure the device&rsquo;s <i>reported</i> reality rather than assuming, and separate always-on detection from safe, windowed, staged correction. The hard part isn&rsquo;t pushing config; it&rsquo;s detecting drift precisely and correcting it safely.",
    f:[
      { q:"If you could keep only three properties of the design, which three?",
        a:"<b>Three hashes over the rendered output</b> (the drift model itself &mdash; desired/deployed/reported hashing the actual bytes, which gives precise, localizable, content-defined drift and is the core the rest hangs on); <b>closed-loop convergence on the reported hash</b> (measuring the device&rsquo;s real state and re-acting until reported==desired, rather than assuming a push worked &mdash; this is what makes it self-healing instead of fire-and-hope); and <b>windowed, staged, gated correction</b> (deploy under a per-tenant lock, only in maintenance windows, rolled out in waves &mdash; because on live payment terminals, <i>correcting safely</i> matters as much as detecting). Those three are a working reconciler: a precise drift signal, a closed loop that acts on measured reality, and safe correction. Hierarchical resolution, visibility, and the sweep backstop are essential-at-scale layers on that spine &mdash; but the spine is content-hash drift, reported-measured convergence, and safe windowed correction." }
    ],
    senior:"Compressing to <b>three-hashes-over-rendered-output + closed-loop-reported-measurement + safe-windowed-staged-correction</b> &mdash; and naming the irreducible three &mdash; is the systems-level synthesis that lands a Staff signal." }
];
var DS_SPEAK = [
  "Lead with the model: <b>'declare a goal and drive reality toward it continuously,'</b> not 'push config and hope.' Command-and-hope has no feedback; converge-to-goal is closed-loop and self-healing &mdash; a failed push or a rollback just self-corrects on the next loop. Tie declarative to idempotence and recoverability.",
  "Track <b>three hashes per device: desired, deployed, reported.</b> All match = converged; any mismatch = drift. The deployed hash is the one that disambiguates &mdash; desired&ne;deployed means a deploy is owed, deployed&ne;reported means the device drifted under us. Two hashes collapse two different problems into one signal.",
  "Hash the <b>rendered output, not the template version.</b> A config's identity is the bytes it produces &mdash; a template refactor with identical output isn't drift, a value change that alters output is. And name the property it requires: deterministic rendering, or every reconcile is phantom drift.",
  "Resolve the hierarchy <b>tenant &rarr; site &rarr; tag &rarr; device, later overriding earlier,</b> and store every level. The stored provenance is what lets you explain 'why does this device have timeout 30' and correctly re-resolve when a site default changes. Watch the CSS-specificity trap: a device override silently beats a site change.",
  "Narrate the loop: <b>resolve &rarr; render &rarr; hash &rarr; diff &rarr; deploy &rarr; report</b> &mdash; a control loop, not a pipeline. Lock and window gate only the deploy; the report step feeds back into the next diff, which is what makes it converge rather than command.",
  "Localize drift by <b>which pair differs:</b> desired&ne;deployed = deploy owed (push it); deployed&ne;reported = device drifted after a good deploy (re-apply, and flag if it recurs). Map each pattern to a distinct action &mdash; the loop doesn't blindly redeploy on any mismatch.",
  "Use a <b>per-tenant distributed lock:</b> parallel across tenants, serialized within one. The TTL (~30s) bounds how long a crashed holder blocks others; the acquire window (~4min) bounds how long a waiter tries before deferring. Granularity follows the isolation boundary &mdash; not global, not per-device.",
  "Separate <b>detection (continuous) from correction (windowed).</b> You detect drift on a terminal at peak but don't deploy mid-transaction &mdash; you mark it drifted-and-visible and fix it when the site's maintenance window opens. Windowed drift is acceptable only because it's bounded and visible, with an emergency window as the escape hatch.",
  "Never assume the push worked &mdash; <b>wait for the device's reported hash.</b> Converged means reported==desired, full stop. A failed deploy, a rollback, an offline terminal all leave deployed&ne;reported for the next loop to catch. A device that never reports is an explicit escalating state, not an assumed success.",
  "Rendering must be a <b>pure function of the resolved config</b> &mdash; same input, same bytes &mdash; or the output hash is unstable and every device looks perpetually drifted. Name the nondeterminism sources (timestamps, unordered keys, nonces) and test it: render twice, assert byte-identical, gate it in CI.",
  "Reconcile <b>event-driven, not on a blind timer</b> &mdash; a config edit, a check-in, a window opening &mdash; so work is proportional to change and propagation is seconds. Keep a slow full sweep as a backstop for dropped events and silent local drift. Fast path plus safety net.",
  "Make <b>drift a first-class, queryable state</b>, not log residue: which pair differs, how long, correction status (pending-window vs failing vs never-reported), next window, and resolution provenance. That's what lets an operator triage &mdash; ignore the safely-pending, investigate the stuck &mdash; and it's what earns an autonomous loop the right to run.",
  "A failed deploy <b>needs no retry queue</b> &mdash; the convergence loop <i>is</i> the retry: the device stays drifted and the next trigger re-attempts. Error recovery is the same code path as normal operation. Bound it, though: after N missed windows, flag unhealthy and alert rather than looping forever silently.",
  "Make the loop <b>idempotent by declaring end-state, not steps:</b> diff-and-converge is a no-op when already converged, so re-running after a crash or on the sweep is always safe. What breaks it is append/increment/non-deduplicated side effects &mdash; keep every effect a convergent 'set it to X,' not 'change it.'",
  "Don't converge 10,000 devices at once &mdash; <b>canary, watch the reported hashes and health, then expand in waves.</b> A bad config is caught on the canaries. And rollback is trivial: re-declare the old desired and the same loop converges the fleet back &mdash; symmetric with roll-forward, unlike fragile imperative compensation.",
  "Scope <b>everything per tenant</b> &mdash; the three-hash state, the hierarchy, the lock and cache keys, the visibility API. Make isolation structural (tenant-rooted hierarchy, tenant-prefixed keys, an injected tenant predicate), not dependent on every query remembering the filter. The per-tenant lock serves parallelism and non-interference at once.",
  "Name the real ceiling: <b>deploy/report I/O and lock hold-time, not the diff</b> &mdash; comparing three hashes is trivial; touching thousands of devices and ingesting check-ins isn't. Relieve it with incremental reconcile (only affected devices under the lock), a minimal critical section, and sharded report ingestion.",
  "On a crash mid-deploy, you're <b>safe because the design is crash-idempotent:</b> the lock TTL frees the tenant, and the loop converges from actual state, not from history. A lost deployed-hash write can't corrupt anything &mdash; deployed is a cache; desired and reported are the durable truth &mdash; so recovery is just 'acquire the lock and reconcile again.'",
  "When the per-tenant lock bottlenecks a big tenant, <b>shrink the critical section to the deploy-and-record step</b> (resolve/render/diff are read-only, do them outside the lock) and <b>sub-partition the lock per-site along a non-overlapping device boundary.</b> Preserve the one invariant: one device, one lock &mdash; never two reconcilers on the same device.",
  "Distinguish it from IaC: <b>same converge/diff/idempotent/drift pattern, purpose-built engine.</b> Terraform is human-triggered plan/apply against a readable state file; this is continuous, autonomous, high-cardinality, and reconciles against device-<i>reported</i> reality within maintenance windows. Steal the declarative philosophy; reject the execution model for a live fleet.",
  "Land the whole thing: <b>three hashes over the rendered output, hierarchical resolution stored for explainability, an event-driven loop under a per-tenant lock, correction only in windows, drift made visible.</b> Under pressure, the irreducible three: content-hash drift, closed-loop convergence on the reported hash, and safe windowed correction &mdash; a precise signal, a loop acting on measured reality, and safe correction."
];
var TOPIC_DS_DRILL = {
  cards: DS_CARDS,
  speak: DS_SPEAK,
  tierNotes: {
    all:'<b>All four levels, mixed</b> &mdash; the way a real loop actually comes at you.',
    SDE2:'<b>Fundamentals under pressure</b> &mdash; converge-not-command, the three hashes, hashing rendered output, hierarchical resolution, the reconcile loop. The bar is &ldquo;a closed loop that measures reality, not a config push&rdquo;: name the three hashes and what confirms convergence.',
    SDE3:'<b>Depth &amp; trade-offs</b> &mdash; drift localization, the per-tenant lock, maintenance windows, determinism, event-driven reconcile, visibility, safe rollout. The bar is &ldquo;detect always, correct safely&rdquo;: name the constraint and the failure each choice bounds.',
    Staff:'<b>Systems judgment</b> &mdash; scale ceilings, crash-idempotence, lock partitioning, the IaC boundary, the whole model. The bar is &ldquo;converge toward a declared goal, safely, at fleet scale&rdquo;: name the drift model, the closed loop, and where correctness under failure comes from.'
  }
};
