/* topics/desired-state/rf.js -- topic 7 red flags. flags[] each {bad (the quoted misstep),
   note (null except the LAST), tell (why it sinks the round), fix (what to say instead)}.
   Entities only, no backslash escapes. 7-bit ASCII. */
var TOPIC_DS_RF = {
  lead:'The moves that quietly tank a desired-state round &mdash; each is a real thing candidates say, why it reads as a no-hire, and the sentence that turns it around.',
  flags:[
    { bad:'&ldquo;We detect drift by comparing the config template&rsquo;s version number.&rdquo;',
      note:null,
      tell:'Hashing the version instead of the rendered output gives you both false positives and false negatives. A template refactor with identical output bumps the version and looks like fleet-wide drift &mdash; so you needlessly redeploy everything; and a change that alters output without bumping the version goes undetected. Version is bookkeeping, not reality.',
      fix:'Hash the <b>rendered output</b> &mdash; SHA-256 of the actual bytes the device will run. A config&rsquo;s identity is what it produces, so drift tracks real output changes, immune to refactors. Say &lsquo;content, not version&rsquo; &mdash; and note it requires deterministic rendering.' },
    { bad:'&ldquo;We push the config to the device and mark it deployed &mdash; done.&rdquo;',
      note:null,
      tell:'That&rsquo;s commanding, not converging &mdash; a one-shot imperative push with no feedback. At fleet scale, deploys fail, devices roll back, terminals go offline; &lsquo;marked done&rsquo; accumulates silent divergence where your records say correct while the fleet runs the wrong thing. There&rsquo;s no loop to catch it.',
      fix:'<b>Converge, don&rsquo;t command.</b> Keep comparing what the device <i>should</i> run against what it <i>reports</i> running, and re-act until they match. &lsquo;Done&rsquo; is when the device reports the desired hash &mdash; not when you pushed. The loop makes it self-healing; the command makes it hope.' },
    { bad:'&ldquo;Once the deploy call succeeds, the device has the new config.&rdquo;',
      note:null,
      tell:'A deploy succeeding at the transport level says nothing about the device <i>running</i> the config &mdash; it can reject it, apply it and crash back, or reboot to the old version, all while your deploy call returned success. Assuming the push worked turns those into silent divergence you can&rsquo;t see.',
      fix:'<b>Measure the device&rsquo;s reported hash.</b> Converged means the device <i>itself</i> reports the matching hash, not that the push returned OK. A device that never confirms stays visibly drifted and re-attempts &mdash; the source of truth for &lsquo;is it running the right config&rsquo; is measured reality, not an optimistic assumption.' },
    { bad:'&ldquo;Any worker can reconcile any device &mdash; we just run several in parallel.&rdquo;',
      note:null,
      tell:'With no coordination, two reconcilers can deploy to the same device at once and fight over its state &mdash; interleaving pushes, racing on the deployed record, leaving it in a config nobody chose. Uncoordinated parallel writes to the same device is a classic distributed-systems race.',
      fix:'Take a <b>per-tenant distributed lock</b> before deploying &mdash; parallel across tenants, serialized within one, so two reconcilers never deploy the same device concurrently. A TTL frees a crashed holder. The lock&rsquo;s one job is &lsquo;never two on the same device&rsquo;; keep its critical section tiny.' },
    { bad:'&ldquo;We render the config with a generated-at timestamp at the top.&rdquo;',
      note:null,
      tell:'A timestamp (or unordered keys, or a nonce) makes rendering non-deterministic &mdash; the same config renders to different bytes each time, so the desired hash is unstable and <i>every device looks perpetually drifted</i>. You&rsquo;d redeploy the whole fleet forever, chasing phantom changes that are just render noise.',
      fix:'Make rendering a <b>pure function</b> of the resolved config: no timestamps, no randomness, canonical key ordering, stable encoding. Then identical config hashes identically everywhere. And test it &mdash; render twice, assert byte-identical, gate in CI &mdash; because this invariant underpins the entire drift model.' },
    { bad:'&ldquo;When we detect drift on a terminal, we fix it immediately.&rdquo;',
      note:null,
      tell:'Immediately reconfiguring a live payment terminal &mdash; mid-transaction, at peak &mdash; risks interrupting payments, which is far worse than a config being briefly stale. Correcting the instant you detect ignores that these are production devices where <i>when</i> you change them matters as much as <i>what</i>.',
      fix:'<b>Detect always, correct in-window.</b> Gate deploys behind maintenance windows: the device is marked drifted-and-visible now, and the fix lands when the site&rsquo;s window opens. An emergency window covers genuinely urgent changes. Windowed drift is safe because it&rsquo;s bounded and visible, not because it&rsquo;s invisible.' },
    { bad:'&ldquo;Every few minutes we re-render and re-diff all 10,000 devices per tenant.&rdquo;',
      note:null,
      tell:'A full periodic sweep is either too slow (drift sits undetected between sweeps) or too wasteful (re-rendering the entire fleet on a timer, mostly finding no change) &mdash; and it doesn&rsquo;t scale as fleets and tenants grow. You&rsquo;re doing fleet-sized work to catch a handful of changes.',
      fix:'Reconcile <b>event-driven</b> &mdash; on a config edit, a check-in, a window &mdash; so work is proportional to change and propagation is seconds. Keep a <i>slow</i> full sweep only as a backstop for dropped events and silent local drift. Events for the common case; the sweep as a safety net, not the primary path.' },
    { bad:'&ldquo;The loop fixes drift automatically, so operators don&rsquo;t really need to see it.&rdquo;',
      note:null,
      tell:'A reconciler that silently self-heals is one you can&rsquo;t trust, audit, or debug. When something is stuck &mdash; a device failing every window, a bad rollout &mdash; there&rsquo;s no way to see it, and &lsquo;the loop will handle it&rsquo; hides real problems behind assumed autonomy. Invisible automation is unaccountable automation.',
      fix:'Make <b>drift a first-class, queryable state</b>: which devices are drifted, which pair of hashes differs, how long, and correction status (pending-window vs failing vs never-reported). Visibility is what lets operators triage the stuck from the safely-pending &mdash; and it&rsquo;s what earns an autonomous loop the right to run.' },
    { bad:'&ldquo;We compare desired against reported &mdash; if they differ, we just redeploy.&rdquo;',
      note:'This is the subtle one &mdash; and the deepest, because two-hash thinking looks sufficient but silently throws away the diagnosis: you can detect drift but not <b>localize</b> it, so you take the wrong action.',
      tell:'With only desired vs reported, a mismatch is ambiguous &mdash; you can&rsquo;t tell &lsquo;we haven&rsquo;t pushed the change yet&rsquo; from &lsquo;we pushed it but the device won&rsquo;t hold it.&rsquo; So you blindly redeploy on any mismatch &mdash; re-pushing config to a device that&rsquo;s actually a health problem, and never distinguishing a delivery task from a device fault.',
      fix:'Track <b>three</b> hashes &mdash; desired, deployed, reported. desired&ne;deployed means a deploy is owed (push it); deployed&ne;reported means the device drifted after a good deploy (re-apply, and flag if it recurs). The deployed hash is what disambiguates, so the reconciler takes the <i>right</i> action for which pair diverged instead of redeploying blindly.' }
  ]
};
