/* topics/desired-state/walk.js -- topic 7 walkthrough. steps[] is the reconciliation loop
   (trigger -> resolve hierarchy -> render -> hash rendered -> three-way diff -> acquire lock
   -> deploy in-window -> report/converge -> visibility); modelScript[] is the spoken model
   answer (plain beats, the interviewer .mq line, then the .mbeat.ans -- LAST). Code strings
   use single-backslash \n / \'. 7-bit ASCII. */
var TOPIC_DS_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"A trigger kicks the loop",
      flow:'<span class="fb n">config change / check-in / schedule</span><span class="arr">&rarr;</span><span class="fb p">reconcile event</span><span class="arr">&middot;</span><span class="fb t">not a cron sweep</span><span class="arr">&middot;</span><span class="fb a">event-driven</span>',
      ins:'The loop runs on a <b>trigger</b> &mdash; a config change, a device check-in, a scheduled window &mdash; not a blind cron sweep of the whole fleet. Each event reconciles the affected devices, so work is proportional to what changed.',
      deep:'Event-driven is the first design choice, and it&rsquo;s about scale and freshness. With <b>10,000 devices per tenant</b>, a periodic full sweep is either too slow (drift sits undetected between sweeps) or too expensive (re-rendering and diffing every device on a timer, mostly finding nothing). Triggering on the events that <i>actually change state</i> &mdash; a config edit upstream, a device checking in with its reported state, a maintenance window opening &mdash; means the reconciler works when there&rsquo;s a reason to, and a change propagates in seconds, not on the next sweep. The loop is the same calculate-render-diff-deploy-report every time; what varies is what triggered it and which devices it touches.' },
    { k:"Step 2 / 9", t:"Resolve the hierarchy",
      flow:'<span class="fb n">tenant</span><span class="arr">&rarr;</span><span class="fb p">site</span><span class="arr">&rarr;</span><span class="fb t">tag</span><span class="arr">&rarr;</span><span class="fb a">device</span><span class="arr">&middot;</span><span class="fb r">each overrides &middot; store every level</span>',
      ins:'Desired config is <b>resolved through a hierarchy</b>: start at the tenant defaults, override with site, then tag (device group), then the individual device. Each level wins over the one above it, and you <b>store every level</b> &mdash; not just the final answer.',
      code:'<span class="c">// resolve tenant -&gt; site -&gt; tag -&gt; device; later levels override earlier</span>\n<span class="k">function</span> resolve(device) {\n  <span class="k">const</span> levels = [tenant, site(device), tag(device), device];\n  <span class="k">const</span> resolved = {};\n  <span class="k">for</span> (<span class="k">const</span> lvl <span class="k">of</span> levels)\n    Object.assign(resolved, lvl.config);   <span class="c">// last write wins</span>\n  <span class="k">return</span> resolved;   <span class="c">// plus: keep each level&#39;s source for explainability</span>\n}',
      cap:'Storing every level is what makes desired state <b>explainable</b>: when someone asks &lsquo;why does this device have timeout = 30?&rsquo; you can answer &lsquo;the site set it; the tenant default was 60.&rsquo; The final resolved config is what gets rendered, but the per-level provenance is what lets you debug and audit it.' },
    { k:"Step 3 / 9", t:"Render the output",
      flow:'<span class="fb n">resolved config + template</span><span class="arr">&rarr;</span><span class="fb p">rendered bytes</span><span class="arr">&rarr;</span><span class="fb t">the exact artifact the device runs</span><span class="arr">&middot;</span><span class="fb a">deterministic</span>',
      ins:'The resolved config is <b>rendered</b> into the actual output the device will run &mdash; the config file, the manifest, the bytes. Rendering is deterministic: the same resolved input always produces the same output artifact.',
      deep:'Rendering turns <i>intent</i> into <i>artifact</i>, and its determinism is load-bearing for everything downstream. The desired hash (next step) is taken over this rendered output, so rendering has to be a pure function of the resolved config &mdash; same input, same bytes, every time &mdash; or the hash would be unstable and every reconcile would look like drift. That means no timestamps, no map-ordering nondeterminism, no &lsquo;rendered-at&rsquo; noise baked into the output. The payoff is that the rendered artifact is <b>content-addressable</b>: identical config anywhere in the fleet renders to identical bytes and hashes to the same value, so you can compare, dedupe, and cache by hash. Get rendering deterministic and the whole three-hash model rests on solid ground; let it be sloppy and you get phantom drift forever.' },
    { k:"Step 4 / 9", t:"Hash the rendered output",
      flow:'<span class="fb n">SHA-256(rendered bytes)</span><span class="arr">&rarr;</span><span class="fb p">desired hash</span><span class="arr">&middot;</span><span class="fb r">NOT the template version</span><span class="arr">&middot;</span><span class="fb a">content-addressed</span>',
      ins:'The <b>desired hash</b> is <code>SHA-256</code> of the <b>rendered output</b> &mdash; the bytes, not the template version number. A config&rsquo;s identity is what it actually produces, so a template refactor that renders identical output is <i>not</i> a change, and a value edit that alters output <i>is</i>.',
      code:'<span class="c">// identity of a config = hash of what it RENDERS, not its template version</span>\n<span class="k">const</span> desiredHash = sha256(render(resolve(device)));\n<span class="c">// template v4 -&gt; v5 but identical output? same hash, NOT drift</span>\n<span class="c">// one value changes the output?           different hash, IS drift</span>',
      cap:'Hashing the rendered output instead of a template version is the design&rsquo;s sharpest idea. Drift is defined by <b>observable output</b>, not version bookkeeping: you never redeploy a whole fleet because a template was refactored with no output change, and you never miss a real change because the version happened to match. Content, not version, is the source of truth for &lsquo;is this the config we want.&rsquo;' },
    { k:"Step 5 / 9", t:"The three hashes, diffed",
      flow:'<span class="fb n">desired</span><span class="arr">vs</span><span class="fb p">deployed</span><span class="arr">vs</span><span class="fb t">reported</span><span class="arr">&rarr;</span><span class="fb r">any mismatch = drift</span><span class="arr">&middot;</span><span class="fb a">which pair localizes it</span>',
      ins:'Three hashes per device: <b>desired</b> (what it should run), <b>deployed</b> (what we last pushed), <b>reported</b> (what the device says it&rsquo;s running). Drift is <i>any</i> mismatch &mdash; and <b>which pair</b> differs tells you what happened.',
      code:'<span class="c">// three-way compare -- which pair differs localizes the fault</span>\n<span class="k">if</span> (desired === deployed &amp;&amp; deployed === reported) converged();\n<span class="k">else if</span> (desired !== deployed)  needsDeploy();     <span class="c">// config changed upstream</span>\n<span class="k">else if</span> (deployed !== reported) deviceDrifted();    <span class="c">// device changed under us</span>',
      cap:'The three-way comparison makes drift <b>diagnosable</b>, not just detectable. <code>desired &ne; deployed</code> means the intended config changed and we haven&rsquo;t pushed it &mdash; a deploy is owed. <code>deployed &ne; reported</code> means we pushed one thing but the device runs another &mdash; it drifted locally, or the deploy failed. One hash tells you &lsquo;something&rsquo;s wrong&rsquo;; three tell you <i>where</i>.' },
    { k:"Step 6 / 9", t:"Acquire the lock",
      flow:'<span class="fb n">before deploy</span><span class="arr">&rarr;</span><span class="fb p">per-tenant distributed lock</span><span class="arr">&middot;</span><span class="fb t">30s hold, 4min acquire</span><span class="arr">&middot;</span><span class="fb a">no two reconcilers</span>',
      ins:'Before pushing anything, the reconciler takes a <b>per-tenant distributed lock</b> &mdash; roughly a 30-second hold with a bounded acquire window &mdash; so two reconcilers can never deploy to the same tenant&rsquo;s fleet at once and fight over device state.',
      code:'<span class="c">// per-tenant lock: serialize reconciles for a tenant, bounded hold + wait</span>\n<span class="k">const</span> lock = <span class="k">await</span> acquire(<span class="s">`reconcile:${tenantId}`</span>, { ttl: 30000, wait: 240000 });\n<span class="k">if</span> (!lock) <span class="k">return</span> deferToNextTrigger();   <span class="c">// someone else holds it</span>\n<span class="k">try</span> { <span class="k">await</span> reconcileTenant(tenantId); }\n<span class="k">finally</span> { <span class="k">await</span> lock.release(); }',
      cap:'The lock is <b>per-tenant</b>, not global, on purpose: tenants are independent, so their reconciles run in parallel, but within one tenant the loop is serialized. The TTL (30s) bounds how long a crashed reconciler blocks others before the lock auto-expires; the acquire window (4min) bounds how long a waiter tries before deferring to the next trigger. Two loops deploying the same device concurrently is the failure this prevents.' },
    { k:"Step 7 / 9", t:"Deploy within a window",
      flow:'<span class="fb n">push rendered config</span><span class="arr">&rarr;</span><span class="fb p">record deployed hash</span><span class="arr">&middot;</span><span class="fb t">only inside a maintenance window</span><span class="arr">&middot;</span><span class="fb a">gated deploy</span>',
      ins:'The reconciler <b>pushes the rendered config</b> to the device and records it as the new <b>deployed hash</b> &mdash; but only inside an allowed <b>maintenance window</b>. Outside the window, drift is detected and queued, not applied.',
      deep:'Deploying is where a reconciler touches the real world, so it&rsquo;s gated twice: by the lock (no concurrent deploys) and by <b>maintenance windows</b> (deploys land only when allowed). The window matters because these are <b>payment terminals</b> &mdash; you don&rsquo;t push a config change mid-transaction or during peak hours; you wait for the site&rsquo;s window. So the loop separates <b>detecting</b> drift (always, continuously) from <b>correcting</b> it (only in-window): a device can be known-drifted for hours, visible in the API, and the deploy fires when the window opens. Recording the deployed hash the moment we push is what lets the next loop distinguish &lsquo;we pushed X, device confirms X&rsquo; (converged) from &lsquo;we pushed X, device still reports Y&rsquo; (deploy failed or device drifted). Deploy is deliberate, gated, and recorded &mdash; not fire-and-forget.' },
    { k:"Step 8 / 9", t:"Report and confirm convergence",
      flow:'<span class="fb n">device runs config</span><span class="arr">&rarr;</span><span class="fb p">reports its actual hash</span><span class="arr">&rarr;</span><span class="fb t">reported == desired? converged</span><span class="arr">&middot;</span><span class="fb a">closed loop</span>',
      ins:'The device runs the pushed config and <b>reports back the hash it&rsquo;s actually running</b>. When <b>reported == desired</b>, the loop has converged for that device. Until then, it&rsquo;s still drifted &mdash; and the next trigger will act.',
      deep:'The reported hash closes the loop from open-loop &lsquo;we sent it&rsquo; to closed-loop &lsquo;it&rsquo;s confirmed running.&rsquo; This is the difference between <b>commanding</b> and <b>converging</b>: a command-based system pushes config and assumes success; a convergence-based system keeps checking reported against desired until they match, and re-acts if they don&rsquo;t. A failed deploy, a device that rolled back, a terminal offline during its window &mdash; all show up as <code>reported &ne; desired</code> on the next loop, and the reconciler tries again. The device reporting its <i>own</i> running state (rather than us assuming the deploy stuck) is what makes the system <b>self-healing</b>: reality is measured, not presumed, and the loop runs until measurement matches intent. That&rsquo;s the core of desired-state &mdash; you declare the goal and the system drives toward it continuously, rather than firing imperative steps and hoping.' },
    { k:"Step 9 / 9", t:"Make drift visible",
      flow:'<span class="fb n">mismatch-visibility API</span><span class="arr">&rarr;</span><span class="fb p">which devices drifted, and why</span><span class="arr">&rarr;</span><span class="fb t">drift is observable</span><span class="arr">&middot;</span><span class="fb a">then re-loop</span>',
      ins:'Every mismatch is surfaced through a <b>drift-visibility API</b> &mdash; which devices are drifted, which pair of hashes differs, how long they&rsquo;ve been out of sync. Drift is <b>observable</b>, not silent; and the loop re-runs on the next trigger to close it.',
      deep:'A reconciler that silently fixes things is one you can&rsquo;t trust or debug, so <b>visibility</b> is a first-class output, not an afterthought. The API answers the operational questions: how much of the fleet is converged right now, which devices are stuck drifted (and for how long), and &mdash; because you stored every resolution level and all three hashes &mdash; <i>why</i>: which pair differs (a deploy owed vs a device that drifted), and where the desired value came from. That turns the loop from a black box into an operable system: an operator sees a terminal drifted for six hours because it missed its window, not a mystery. And the loop is <b>continuous</b> &mdash; each trigger re-resolves, re-diffs, and re-converges, so visible drift shrinks as devices come back into their windows and confirm. Detect always, correct in-window, and show your work.' }
  ],
  modelScript: [
    { ml:'Frame it', t:'"The problem is keeping a fleet of 10,000-plus terminals per tenant running the config we intend, continuously &mdash; not pushing config once and hoping. So I model it as desired state: declare the goal, and a loop drives reality toward it."' },
    { ml:'The three hashes', t:'"The core is three hashes per device &mdash; desired (what it should run), deployed (what we last pushed), reported (what it says it&rsquo;s running). Drift is any mismatch, and which pair differs localizes the fault: desired &ne; deployed means a deploy is owed; deployed &ne; reported means the device drifted under us."' },
    { ml:'Hash the rendered output', t:'"Crucially, the hash is of the rendered output, not the template version &mdash; a config&rsquo;s identity is the bytes it produces. So a template refactor with identical output isn&rsquo;t drift, and a value change that alters output is. Content, not version."' },
    { ml:'Hierarchical resolution', t:'"Desired config resolves through a hierarchy &mdash; tenant, site, tag, device, each overriding the last &mdash; and I store every level, so I can always explain where a value came from. That&rsquo;s what makes it auditable."' },
    { ml:'The loop under a lock', t:'"Convergence is an event-driven loop &mdash; resolve, render, hash, diff, deploy, report &mdash; guarded by a per-tenant distributed lock so two reconcilers never deploy the same fleet at once, and gated by maintenance windows so deploys land only when they&rsquo;re allowed to."' },
    { mq:'Interviewer: "A device has reported the wrong hash for six hours &mdash; deployed says X, reported says Y. What&rsquo;s happening, and what does your system do about it?"' },
    { ml:'Answer the drift', t:'"Deployed &ne; reported means we pushed X but the device runs Y &mdash; the deploy failed, the device rolled back, or it was offline during its window. My system doesn&rsquo;t assume the push worked: it measures reported against desired every loop, so this device shows as drifted in the visibility API, with how long and which pair. The reconciler re-attempts the deploy on the next trigger inside the device&rsquo;s maintenance window &mdash; it keeps converging until reported matches desired. If it&rsquo;s stuck across many windows, that&rsquo;s an alert, not silent retry forever."' },
    { ml:'Land it', t:'"So: three hashes over rendered output, hierarchical resolution stored for explainability, an event-driven loop under a per-tenant lock, deploys gated by windows, and drift made visible &mdash; a system that converges toward a declared goal instead of firing commands. The hard part isn&rsquo;t pushing config; it&rsquo;s detecting drift precisely and correcting it safely."', ans:true }
  ]
};
