/* ============ topics/notifications/bank.js -- topic 5 cross-pane BANK ============
   The mock-run / mixed-fire / frame bank for topic 5. mockBeats + curveballs + frames
   are notifications-specific; cards/speak alias the LOCAL NOTIF_CARDS / NOTIF_SPEAK
   (defined in drill.js, loaded before this in the bundle). publishBanks() seeds the
   registry-owned globals from this object on switch. 7-bit ASCII (entities). */
var TOPIC_NOTIF_BANK = (function () {
  var mockBeats=[
   { tag:"FRAME", cue:"&ldquo;Design a multi-channel notification system &mdash; email, in-app, maybe push. Start wherever you like.&rdquo;",
     task:"Frame the scope in one line, then give your one-sentence version.",
     model:"<b>Frame:</b> producers across the system need to reach users when something happens, across channels, once, honoring preferences &mdash; and the notification system is the boundary that owns all of that so producers don&rsquo;t. <b>One-liner:</b> producers emit a domain event, the system resolves recipients and fans out on their preferences, delivers effectively-once via a content-derived idempotency key, uses in-app as the polled default and email as reach-with-fallback.",
     int:{q:"Why a separate notification system &mdash; why not have each service send its own emails?",a:"Because channel logic <b>scatters</b> if every service does it: preferences, retry, throttling, and fallback get reimplemented, inconsistently, in every producer, and &lsquo;add a channel&rsquo; becomes a change to all of them. A notification boundary centralizes it &mdash; producers emit an event and stay <b>channel-ignorant</b>, and everything about <i>how</i> and <i>where</i> to deliver lives in one place. It&rsquo;s the same reason you don&rsquo;t scatter auth checks across every endpoint: cross-cutting concerns belong at a boundary, not copy-pasted."},int2:{q:"What&rsquo;s the very first thing you&rsquo;d build, before any channel?",a:"<b>Idempotency.</b> Before I write a single channel, I&rsquo;d establish that every send goes through a deterministic id &mdash; hash of user, event, channel &mdash; checked against a dedup store. It&rsquo;s first, not last, because delivery is at-least-once and retries are guaranteed, so without the key <i>every</i> channel I add will double-send on the first blip. Idempotency isn&rsquo;t a channel feature; it&rsquo;s the property that makes the whole thing correct, so it&rsquo;s the foundation, not a patch. At-least-once plus idempotency is effectively exactly-once."} },
   { tag:"STRUCTURE", cue:"&ldquo;Walk me through it &mdash; event to the user seeing it.&rdquo;",
     task:"Talk the whole flow, producer to seen &mdash; no code, just the spine.",
     model:"A producer <b>emits an event</b> &mdash; <code>notify(user, event)</code> &rarr; the system computes a <b>content-derived idempotency key</b> and checks a dedup store, so a retry sends nothing &rarr; it <b>resolves recipients</b> from the event&rsquo;s role against current membership, tenant-scoped &rarr; reads each recipient&rsquo;s <b>preferences</b> and <b>fans out</b> to their enabled channels &rarr; in-app is a <b>row per recipient</b> in Postgres with a partial index on unread, which the client <b>polls</b> every ~60s &rarr; email goes through <b>SES</b>, batched with allSettled under the tenant&rsquo;s sender, throttled &rarr; a failed send is <b>classified and retried</b> (backoff/jitter) or dead-lettered &rarr; and a <b>smart fallback</b> escalates in-app to email only if unseen, canceling the pending email if opened.",
     int:{q:"A producer three services deep needs to notify someone. Does it call your system directly, synchronously?",a:"It <b>emits an event</b>, asynchronously &mdash; it doesn&rsquo;t call the notification system inline and wait. The producer fires &lsquo;notify this user of this thing&rsquo; and returns immediately; the notification system consumes the event and does the work on its own path. Sending synchronously would couple the producer&rsquo;s latency and availability to the email provider &mdash; a slow SES would slow the producer&rsquo;s request. So the boundary is an <b>event</b>, not a synchronous call: the producer&rsquo;s job ends at &lsquo;something happened,&rsquo; and delivery is the notification system&rsquo;s job, with its own retries and DLQ."} },
   { tag:"SCALE", cue:"&ldquo;A rollout fires and 50,000 devices report in within minutes &mdash; a burst of &lsquo;rollout done&rsquo; and &lsquo;device offline&rsquo; events, each notifying operators. What breaks?&rdquo;",
     task:"Name the first ceiling, then the fix &mdash; don&rsquo;t hand-wave &lsquo;it scales.&rsquo;",
     model:"The burst hits two places. First, if operators are notified per-device, that&rsquo;s a <b>notification storm</b> &mdash; one operator gets 50,000 notifications, which is unusable; the fix is <b>aggregation/digest</b> (&lsquo;50,000 devices completed&rsquo; as one summary) and <b>per-user rate limiting</b>. Second, the <b>send throughput</b> &mdash; a spike of emails against SES&rsquo;s rate limit; the fix is a <b>token-bucket per channel</b> pacing to the provider&rsquo;s ceiling, with the queue absorbing the burst. The in-app writes are cheap (a row each); the storm is about <b>not drowning the human</b> and <b>not tripping the provider</b>, not about the database.",
     int:{q:"The per-user digest helps the human. What protects SES from the raw send burst?",a:"A <b>token-bucket rate limiter per channel</b>, sized to SES&rsquo;s sending rate &mdash; it lets you burst up to the limit and then paces the rest, so you never exceed the provider&rsquo;s ceiling and trip throttling or reputation penalties. The <b>queue</b> is what makes that safe: the burst of events lands in the queue instantly, and the worker drains it at the rate-limited pace, so the spike becomes a smooth send stream rather than a wall of simultaneous API calls. You decouple &lsquo;events arrived&rsquo; from &lsquo;emails sent&rsquo; &mdash; the queue holds the burst, the rate limiter meters the drain."},int2:{q:"When does aggregation stop being enough and you need to rethink the notification itself?",a:"When the <b>aggregate itself is still noise</b> &mdash; if an operator gets a &lsquo;50,000 devices completed&rsquo; digest every rollout and there are rollouts hourly, even the summaries pile up. At that point the fix isn&rsquo;t more batching, it&rsquo;s <b>rethinking what deserves a notification</b>: maybe individual completions aren&rsquo;t notification-worthy at all, and only <i>exceptions</i> (devices that <b>failed</b>) should notify, with the successes visible in a dashboard on demand. The senior move is recognizing when the answer is &lsquo;notify less,&rsquo; not &lsquo;batch more&rsquo; &mdash; the best notification for a routine success is often none, with the information available when the operator wants it."} },
   { tag:"FAILURE", cue:"&ldquo;Users report getting the same notification twice. Walk the incident.&rdquo;",
     task:"Walk the incident &mdash; contain, diagnose, close the class.",
     model:"<b>Diagnose, fix, close the class.</b> A double-send is the <b>idempotency key failing</b>, in one of three ways, and the logs tell me which: the <b>same id sent twice</b> means the dedup check isn&rsquo;t running on that path (a new channel, a direct provider call); <b>two different ids for one notification</b> means the id is random, not content-derived, so the retry didn&rsquo;t collide; a <b>batch pattern</b> means Promise.all short-circuited and the handler re-sent the whole batch. I fix the specific cause, then <b>close the class</b>: route every send through one dedup gate so a new path can&rsquo;t skip it, make the id a deterministic hash of user/event/channel, and use allSettled so a batch retries only its failures.",
     int:{q:"You added the dedup check to the path that was double-sending. Why isn&rsquo;t that the end of it?",a:"Because the double-send is a <b>class</b>, not one path &mdash; the same gap exists anywhere a send bypasses the check, and patching one path is whack-a-mole. The durable fix is <b>structural</b>: make the idempotency check something <i>every</i> send goes through unavoidably &mdash; a single deliver function that owns the dedup, so a new channel or a new call site physically can&rsquo;t send without it &mdash; plus a test that fires a duplicate on every path. You close the class by making the mistake <b>unwritable</b>, not by remembering the check each time, the same principle as enforcing a query filter at the data layer rather than per-query."},int2:{q:"A channel is fully down &mdash; say SES is having an outage. What should users experience?",a:"<b>Degraded, not broken.</b> The in-app channel is independent of SES, so notifications still land in the unread index and the badge still works &mdash; users see their notifications in-app even with email down. The email sends <b>fail, get classified as retryable (5xx), and back off</b>, accumulating in the retry path / DLQ rather than being lost; when SES recovers, they drain. And the <b>fallback</b> shouldn&rsquo;t cascade <i>to</i> a dead channel &mdash; ideally a circuit-breaker on SES pauses email attempts so you&rsquo;re not hammering a downed provider. So: in-app keeps working, email is delayed not dropped, and nothing double-sends on recovery because every retry rides the idempotency key. A channel outage degrades one channel, not the system."} },
   { tag:"CURVEBALL", theme:"Double-send / retry", cue:"&ldquo;Your queue guarantees at-least-once delivery. A consumer sends the email, then crashes before acking. The message redelivers. The user gets two emails. Your queue is &lsquo;working.&rsquo; Fix it.&rdquo;",
     task:"Reframe the premise out loud, then give the real mechanism.",
     model:"The premise to say aloud: the queue <b>is</b> working &mdash; at-least-once <i>means</i> &lsquo;redeliver if not acked,&rsquo; and a crash between send and ack is exactly the case it&rsquo;s designed for. What&rsquo;s missing is <b>idempotent processing</b> on my side. The fix: a <b>content-derived idempotency key</b> &mdash; hash of user, event, channel &mdash; recorded in a dedup store with a conditional write as part of sending, so the redelivery finds the key already there and sends nothing. At-least-once delivery plus idempotent handling is effectively exactly-once; the queue guarantees no <i>loss</i>, and the key guarantees no <i>duplicate</i>.",
     int:{q:"There&rsquo;s a race: the crash is between sending the email and recording the key. Now the redelivery doesn&rsquo;t see the key and sends again. How do you close that window?",a:"That&rsquo;s the crux &mdash; you want the &lsquo;have I sent this&rsquo; record as close to atomic with the send as possible. The standard approach: <b>record the key first</b> with a conditional write, and only send if that write won; on redelivery the conditional write fails and you skip. That closes the common window &mdash; a crash <i>after</i> the send but before an ack now finds the key already recorded and doesn&rsquo;t resend. The residual edge is a crash <i>between</i> recording and sending, which yields a rare <b>missed</b> send rather than a duplicate &mdash; and you&rsquo;d rather occasionally miss-and-reconcile than double-send. The honest framing is that exactly-once is impossible; you order the key-write ahead of the side effect to make duplicates rare, and accept a tiny reconcilable edge. At-least-once plus this idempotency is effectively exactly-once."} },
   { tag:"CLOSE", cue:"&ldquo;Sum it up &mdash; and what would you watch in prod?&rdquo;",
     task:"Two-sentence close, then the one thing you&rsquo;d alarm on.",
     model:"It&rsquo;s a delivery boundary: producers emit events, the system fans out on preferences, delivers effectively-once via a content-derived idempotency key, uses in-app as the polled default and email as reach-with-fallback, and retries per-channel with a DLQ &mdash; so a user gets each notification once, on the channel that worked. In prod I&rsquo;d alarm on the <b>bounce/complaint rate</b> and <b>DLQ depth</b> &mdash; a rising bounce rate is the earliest sign of a deliverability problem that will filter <i>all</i> my mail, and a DLQ spike is the earliest sign a channel or provider is failing &mdash; both catch silent failures before users report them.",
     int:{q:"You&rsquo;ve got a week, not a month. Cut one thing you described to ship &mdash; what goes?",a:"The <b>sophistication</b> goes, never the correctness. I&rsquo;d ship <b>in-app only</b> (skip email until the polled default works), or in-app plus <b>fire-both</b> email (skip the smart fallback and cancel logic &mdash; addable later), <b>no digests</b>, <b>preferences as on/off only</b>, and the <b>main Postgres</b> (no dedicated store). All of that layers on later without a rewrite. What I would <b>not</b> cut is <b>idempotency</b> and the <b>fan-out boundary</b> &mdash; those are the correctness and the maintainability, and a notification MVP that double-sends or scatters channel logic is an incident, not an MVP. Knowing which parts are the boundary and which are the polish is the answer."} }
  ];
  var mockCurveIdx=0; for(var _ci=0;_ci<mockBeats.length;_ci++){ if(mockBeats[_ci].tag==="CURVEBALL") mockCurveIdx=_ci; }
  var curveballs=[ mockBeats[mockCurveIdx],
    { tag:"CURVEBALL", theme:"Polling meltdown", cue:"&ldquo;Your in-app notifications work great in the demo. In prod, the database falls over every afternoon at peak &mdash; the notifications table is the hottest thing in the system. Fix it without dropping in-app notifications.&rdquo;",
      task:"Find why polling scales badly, then fix it without abandoning the feature.",
      model:"It&rsquo;s the <b>poll read load</b>: every active user polling the notifications table on an interval is a fixed read rate that scales with your user count &mdash; and at peak, that&rsquo;s the hottest query, especially if it&rsquo;s <b>scanning</b> rather than seeking. Fixes, without dropping in-app: <b>a partial index on unread</b> so the badge query is a tiny seek not a scan; <b>cache the unread count</b> in Redis (invalidated on new-notification and mark-read) so most polls never touch Postgres; and a <b>sane interval</b> (60s, not 2s). If a surface genuinely needs faster, that&rsquo;s <b>push</b>, because faster polling is the wall, not the fix.",
      int:{q:"The partial index and cache help, but the poll traffic still grows linearly with users. Is polling just fundamentally doomed at scale?",a:"Not doomed, but <b>bounded</b> &mdash; and knowing the bound is the point. Polling load is users-over-interval, a fixed cost you can drive way down (a cached count is a Redis GET, not a Postgres query) but can&rsquo;t eliminate: it&rsquo;s work proportional to users whether or not anything changed. That&rsquo;s <i>fine</i> up to a large scale when each poll is a ~1ms cache hit &mdash; millions of cheap polls are cheap. It stops being fine when you need <b>low latency</b>, because shortening the interval multiplies the load. So the honest framing: polling is the right, simple default for a badge and scales further than people think <i>if</i> each poll is cheap; you switch to push when the <b>latency requirement</b>, not the user count, demands it &mdash; push does work only on actual change, which is what real-time needs."} },
    { tag:"CURVEBALL", theme:"Offline user", cue:"&ldquo;You add WebSocket push for instant in-app delivery. A user is offline when the notification fires, and comes back an hour later. Walk me through what they see &mdash; and what a naive push-only design gets wrong.&rdquo;",
      task:"Name the persist-first principle, then the reconnect flow.",
      model:"The naive mistake is treating <b>push as the source of truth</b> &mdash; if you only push over the socket and the user&rsquo;s offline, the notification is <b>lost</b>, because there was no connection to receive it. The fix is <b>persist first, push second</b>: every notification is written to the durable store (the row-per-recipient) <i>regardless</i> of connection state, and the WebSocket push is a best-effort <b>accelerator</b> on top. So the offline user&rsquo;s notification is sitting in their unread index the whole time; when they reconnect, the client <b>fetches unread on connect</b> and shows it. Push gains latency when they&rsquo;re online; it never owns delivery. A dropped connection loses <i>speed</i>, not the notification.",
      int:{q:"On reconnect the client fetches unread &mdash; but what about a notification that fires <i>during</i> the reconnect, after the fetch but before the socket is live? Does it fall through?",a:"It can, if you get the <b>order of subscribe-then-fetch</b> wrong. The safe pattern is to <b>subscribe to the push stream first, then fetch the backlog</b>: establish the socket (so any notification from now on is delivered live), and <i>then</i> query unread for everything before that point. A notification firing mid-reconnect is either caught by the now-live subscription or included in the backlog fetch &mdash; and if it&rsquo;s caught by both, the client dedupes by notification id. The bug is fetch-then-subscribe, which leaves a gap between the fetch and the subscription where a notification lands nowhere. Subscribe-first, fetch-second, dedupe on id, closes it &mdash; the same at-least-once-plus-idempotent thinking, now on the client."} },
    { tag:"CURVEBALL", theme:"Notification storm", cue:"&ldquo;A bug upstream emits the same event 10,000 times in a minute. Your system faithfully tries to send 10,000 notifications to one user. The idempotency key is per-event, and these are 10,000 <i>different</i> events. Now what?&rdquo;",
      task:"Distinguish dedup from rate-limiting, then defend the user.",
      model:"The key insight: <b>idempotency and rate-limiting solve different problems</b>, and this is the rate-limiting one. Idempotency stops the <i>same</i> notification twice; it can&rsquo;t help here because these are 10,000 <i>distinct</i> events, so 10,000 distinct keys, all &lsquo;first-time.&rsquo; What protects the user is a <b>per-user rate limit</b> &mdash; a sliding window (say, max N per user per hour) that collapses the storm into a bounded number, aggregating or dropping the rest. Ideally a <b>digest</b> catches the overflow (&lsquo;10,000 updates&rsquo; as one summary) rather than silently dropping. The user is defended by the rate limit, not the idempotency key &mdash; two different mechanisms for two different failures.",
      int:{q:"Rate-limiting the user stops the spam, but the upstream bug is still emitting 10,000 events. Is throttling at the notification layer really the right place to fix this?",a:"It&rsquo;s the right place to <b>protect the user</b>, but not the root cause &mdash; and I&rsquo;d be clear about the distinction. The per-user rate limit is a <b>defensive backstop</b>: the notification system shouldn&rsquo;t trust its inputs to be sane, so it caps what any single user can receive regardless of how buggy the producer is &mdash; defense in depth, and it stays even after the bug is fixed. But the <b>actual fix</b> is upstream: the producer shouldn&rsquo;t emit the same logical event 10,000 times, which points at <i>its</i> idempotency or a retry loop gone wrong. So two things: the rate limit protects users now and permanently (never rely on upstream sanity), and the incident follow-up fixes the emitting service. The senior move is doing both &mdash; the backstop <i>and</i> the root cause &mdash; not only throttling (user protected, bug festering) or only fixing upstream (this bug fixed, the next still floods users)."} },
    { tag:"CURVEBALL", theme:"Ordering anomaly", cue:"&ldquo;A user gets &lsquo;Your order has shipped&rsquo; &mdash; and thirty seconds later, &lsquo;Your order is confirmed.&rsquo; Both are correct events. The user is confused. Is this a bug, and how do you fix it?&rdquo;",
      task:"Diagnose it as a per-user ordering problem, then the scoped fix.",
      model:"It&rsquo;s a real bug, but a <b>per-user causal-ordering</b> one, not a call for global ordering. The events were produced in order (confirmed, then shipped) but delivered out of order &mdash; because they were processed in <b>parallel</b> with no per-user sequencing, and &lsquo;shipped&rsquo; happened to win. The fix is to order <b>per recipient</b>: partition the notification stream by <code>user_id</code> so one user&rsquo;s notifications are processed in sequence, while different users stay parallel. You get the causal order exactly where it&rsquo;s observable &mdash; one user&rsquo;s timeline &mdash; without a global bottleneck. Global ordering across all users would be unnecessary and would kill throughput.",
      int:{q:"Partitioning by user_id orders them &mdash; but what if &lsquo;shipped&rsquo; and &lsquo;confirmed&rsquo; genuinely arrive at your system out of order from two different upstream services?",a:"Right &mdash; if the <b>events themselves arrive out of causal order</b>, sequencing the delivery queue can&rsquo;t reconstruct an order that wasn&rsquo;t there on input. Then you need ordering information <i>in the events</i>: a <b>timestamp or sequence number</b> from the source, so the system (or the client) orders by the event&rsquo;s logical time rather than arrival time &mdash; or briefly holds a notification if a causally-earlier one is expected. In practice, for order state, the cleaner fix is often <b>upstream</b>: the order service owns the state machine and should emit changes in order, or the notification should reflect <i>current state</i> (&lsquo;shipped&rsquo; implies confirmed) rather than a raw event stream. So: partition-by-user handles same-source reordering; genuine cross-source causality needs event timestamps or a rethink of what the notification represents. Knowing which case you&rsquo;re in is the answer."} },
    { tag:"CURVEBALL", theme:"Bounce / reputation", cue:"&ldquo;Your transactional emails &mdash; password resets, receipts &mdash; suddenly start landing in spam. Nothing changed in that code. Marketing just launched a big campaign from the same domain. Connect the dots.&rdquo;",
      task:"Explain shared reputation, then the isolation fix.",
      model:"The dots: <b>sender reputation is per-domain (and per-IP), and it&rsquo;s shared</b>. Marketing&rsquo;s campaign generated <b>spam complaints and bounces</b> &mdash; people marking it spam, dead addresses bouncing &mdash; which tanked the <i>domain&rsquo;s</i> reputation, and mailbox providers then started filtering <b>everything</b> from that domain, including your untouched transactional mail. Your code didn&rsquo;t change; the domain&rsquo;s standing did. The fix is <b>isolation</b>: send transactional and promotional from <b>separate domains/subdomains (and separate IPs)</b>, so marketing&rsquo;s reputation can&rsquo;t sink password resets. Plus the hygiene that protects both: authenticate with SPF/DKIM/DMARC, and honor bounces/complaints into a suppression list so you stop mailing dead or hostile addresses.",
      int:{q:"So separating the domains protects transactional. But how do you keep the <i>marketing</i> domain from just repeatedly destroying its own reputation?",a:"With <b>list hygiene and engagement discipline</b>, because promotional reputation is earned by not annoying people. Concretely: <b>honor unsubscribes and complaints immediately</b> (re-mailing someone who complained is the fastest way to get flagged), <b>remove bouncing addresses</b> (a dead-address-heavy list signals poor management), <b>warm up the domain gradually</b> rather than blasting from zero, and ideally <b>send to engaged users</b> &mdash; stop mailing people who never open, because low engagement itself hurts placement. Mailbox providers are scoring whether recipients <i>want</i> your mail; you protect the marketing domain by only sending wanted mail and pruning the rest. Separating domains stops marketing from hurting transactional; disciplined list management stops marketing from hurting <i>itself</i> &mdash; and you need both, because one domain&rsquo;s bad practices shouldn&rsquo;t take down mail people actually asked for."} },
    { tag:"CURVEBALL", theme:"Fallback race", cue:"&ldquo;Your smart fallback sends in-app first, then email if unseen after 5 minutes. A user opens the in-app at 4 minutes 59 seconds &mdash; and gets the email anyway. Both fired. Explain the race and close it.&rdquo;",
      task:"Name the check-then-act race, then make the cancel reliable.",
      model:"It&rsquo;s a <b>check-then-act race</b> between the &lsquo;open&rsquo; event and the scheduled email firing. At ~5 minutes the email job wakes, checks &lsquo;was it opened?&rsquo;, and sends &mdash; but the open at 4:59 and the email&rsquo;s check are concurrent, so the job can read &lsquo;not opened&rsquo; (stale) and send just as the open lands. Closing it: make the <b>decision atomic</b>. The open and the send must agree on one source of truth &mdash; the open <b>atomically cancels the scheduled job</b> (deletes the delayed message / flips a status with a conditional write), and the email job, before sending, does an atomic <b>check-and-claim</b> on that same status. Only one of &lsquo;opened&rsquo; and &lsquo;email-sent&rsquo; can win the compare-and-set; the loser no-ops. The race is real; you close it by funneling both through one atomic state transition, not two independent reads.",
      int:{q:"Even with an atomic check-and-claim, the email might have <i>already</i> been handed to SES when the open arrives. You can&rsquo;t un-send an email. Is a small double-notify rate just unavoidable?",a:"Honestly, yes &mdash; and saying so is the mature answer. Once an email is handed to SES it&rsquo;s <b>gone</b>; there&rsquo;s no recall. So the atomic check-and-claim shrinks the window to &lsquo;the few milliseconds between claiming the send and actually calling SES,&rsquo; but it can&rsquo;t make it zero &mdash; an open landing in that sliver still gets a redundant email. The judgment is that this is a <b>rare, low-harm</b> outcome: the cost of a duplicate here is one extra email, not a correctness or security violation, so you drive the probability down with the atomic transition and <b>accept the residual</b> rather than over-engineering (a distributed lock on every send) for a harmless edge. Contrast the double-<i>charge</i> case, where you&rsquo;d pay real complexity to close it fully. Matching the rigor to the blast radius &mdash; tight where a duplicate hurts, &lsquo;good enough&rsquo; where it&rsquo;s a stray email &mdash; is the senior call."} },
    { tag:"CURVEBALL", theme:"Cross-tenant leak", cue:"&ldquo;A multi-tenant SaaS. An admin at tenant A receives a notification meant for an admin at tenant B &mdash; with B&rsquo;s data in it. Your auth is fine; users log into the right tenant. Where did the notification system leak?&rdquo;",
      task:"Locate the leak in resolution or fan-out, then the boundary fix.",
      model:"The leak is in <b>recipient resolution</b>, not authentication &mdash; auth confirms who&rsquo;s logged in, but the notification system independently decided <i>who to send to</i>, and that decision crossed the tenant boundary. Usual suspects: a resolution query that <b>wasn&rsquo;t tenant-scoped</b> (&lsquo;all admins&rsquo; instead of &lsquo;admins <i>of tenant B</i>&rsquo;), a <b>cached recipient list</b> keyed without the tenant, or an event carrying a raw user list resolved in the wrong tenant context. The fix is the same boundary the authorization layer uses: <b>every resolution is tenant-scoped</b> &mdash; the tenant is part of the query, not an afterthought &mdash; and it&rsquo;s the same class of bug as a missing <code>WHERE tenant_id</code> filter. Plus the <b>per-tenant sender</b> so even the from-address can&rsquo;t impersonate B.",
      int:{q:"How would you have caught this <i>before</i> it shipped &mdash; what test makes a cross-tenant notification leak impossible to introduce?",a:"The same way you&rsquo;d guard any tenant boundary: an <b>adversarial test that fires a notification and asserts every recipient is within the intended tenant</b>, run on every resolution path. Concretely, set up two tenants, trigger a notification for tenant B, and assert <b>zero</b> tenant-A users receive it &mdash; for each event type and each resolution route, including the cached path. Better, make the leak <b>structurally hard</b>: resolution goes through one helper that <i>requires</i> a tenant context and scopes every query to it, so a developer can&rsquo;t write an unscoped recipient query &mdash; the tenant filter is injected, not remembered, exactly like the authz topic&rsquo;s data layer. Then the test is a backstop confirming the structure holds. Cross-tenant isolation can&rsquo;t rely on every resolution query being written correctly by hand; you make the scoped path the <i>only</i> path and gate CI with an adversarial cross-tenant assertion."} }
  ];
  var mockFrameIdx=0; for(var _fi=0;_fi<mockBeats.length;_fi++){ if(mockBeats[_fi].tag==="FRAME") mockFrameIdx=_fi; }
  var frames=[ mockBeats[mockFrameIdx].cue,
    "&ldquo;Design the system that sends a million notifications a day to email, SMS, and push, with per-user preferences, idempotency, and retries.&rdquo;",
    "&ldquo;A user should get notified when something happens &mdash; but only once, on the right channel, even if they&rsquo;re offline. Build it.&rdquo;",
    "&ldquo;Fan an event out to millions of users across channels, honoring their preferences and guaranteeing you don&rsquo;t double-send. Walk me through it.&rdquo;"
  ];
  return { cards: NOTIF_CARDS, speak: NOTIF_SPEAK, curveballs: curveballs, mockBeats: mockBeats, frames: frames };
})();
