/* topics/notifications/drill.js -- topic 5 drill data. LOCAL arrays NOTIF_CARDS /
   NOTIF_SPEAK so loading this bundle does NOT clobber topic 1's working set.
   publishBanks() reseeds the globals from TOPIC_NOTIF_BANK on switch. NOTIF_SPEAK[i]
   pairs NOTIF_CARDS[i]. Grounded in the ICS dual-channel notification system
   (in-app Postgres polling + SES email, idempotent fan-out). 7-bit ASCII. */
var NOTIF_CARDS = [
  { tier:'SDE2', signal:'Idempotency',
    q:"You send notifications through an at-least-once queue. What&rsquo;s the first thing you build so a retry doesn&rsquo;t double-notify?",
    a:"A <b>deterministic idempotency key</b> &mdash; <code>hash(user_id, event_id, channel)</code> &mdash; checked against a dedup store with a conditional write before every send. A retry of the same notification computes the <i>same</i> id, finds it already recorded, and acknowledges without re-sending. It&rsquo;s the mechanism that turns at-least-once machinery into effectively exactly-once delivery.",
    f:[
      { q:"Why must the id be content-derived rather than a random UUID?",
        a:"Because a random id is <i>different</i> on the retry &mdash; so the dedup store sees a new key and sends again, which is exactly the double-send you were trying to prevent. The id has to be a deterministic function of the notification&rsquo;s identity (user + event + channel) so that the retry of the <i>same</i> logical notification collides with the original. Random ids deduplicate nothing; content-derived ids deduplicate the retry." },
      { q:"How long do you keep the idempotency keys, and why does that matter?",
        a:"Long enough to cover the <b>maximum retry and replay window</b> &mdash; a TTL of a few days to a week is typical. Too short and a late retry (a message stuck in a queue, a delayed redrive) arrives after the key expired and re-sends. Too long and the store grows unbounded. You size the TTL to the longest plausible delay between the original and a retry, then let it expire &mdash; the key only needs to outlive the duplicate, not live forever." }
    ],
    senior:"Naming a <b>content-derived idempotency key plus a conditional-write dedup store</b> as the <i>first</i> thing &mdash; and knowing why random ids fail and how to size the TTL &mdash; is the reflex that separates someone who&rsquo;s run at-least-once delivery from someone who&rsquo;s only drawn the happy path." },
  { tier:'SDE2', signal:'Fan-out pattern',
    q:"An order service, a billing service, and a rollout job all need to notify users. How do you structure it so each one isn&rsquo;t calling SES directly?",
    a:"A <b>fan-out boundary</b>: each producer emits a domain event &mdash; <code>notify(user, event)</code> &mdash; and the notification system owns everything after: channel selection, preferences, batching, fallback. Producers stay <b>channel-ignorant</b>. The single event fans out to the channels each recipient has enabled, so &lsquo;add SMS&rsquo; is one change in the notification system, not a change in every producer.",
    f:[
      { q:"What specifically goes wrong if each producer calls SES itself?",
        a:"Channel logic <b>scatters across every service</b>: preferences, retry, throttling, and fallback get reimplemented (inconsistently) in the order service, the billing service, the rollout job. Adding a channel means touching all of them; changing a throttle means finding all of them. And there&rsquo;s no single place to enforce &lsquo;don&rsquo;t send this user both an email and an in-app for the same event.&rsquo; Centralizing at a fan-out boundary makes all of that one system&rsquo;s job." },
      { q:"If every producer now depends on the notification system, haven&rsquo;t you just created a single point of failure?",
        a:"You&rsquo;ve centralized, but you decouple with a <b>queue at the boundary</b>, not a synchronous call. Producers emit the event to a durable queue/topic and return immediately &mdash; they don&rsquo;t block on the notification system being up or fast. If it&rsquo;s down, events buffer in the queue and drain when it recovers, so a notification outage never becomes an order-service outage. The boundary is a place events <i>land</i>, not a service the producer waits on &mdash; which is exactly what keeps a central notification system from being a synchronous SPOF for every producer." }
    ],
    senior:"Framing it as a <b>producer/notification boundary where producers emit events and stay channel-ignorant</b> &mdash; so channel logic lives in one place and new channels are additive &mdash; is the architectural instinct an interviewer is checking for." },
  { tier:'SDE2', signal:'In-app storage model',
    q:"How do you store in-app notifications so a user&rsquo;s unread badge is cheap to compute even with millions of notifications in the table?",
    a:"<b>One row per recipient</b> (~100 bytes: user_id, event_id, body, <code>read_at</code>, created_at), with a <b>partial index on unread</b> &mdash; <code>WHERE read_at IS NULL</code>. The badge query is a seek into that small index, not a scan of the full table. A million notifications is ~100 MB, and read history can grow unbounded without slowing the unread count.",
    f:[
      { q:"Why a partial index rather than a plain index on read_at?",
        a:"Because a <b>partial index only contains the unread rows</b> &mdash; the ones the badge query actually needs &mdash; so it stays tiny even as the table fills with millions of <i>read</i> rows you never query on. A full index on <code>read_at</code> would index every row, read and unread, and grow with total history. The partial index is sized to the working set (unread), which is small per user, so the hot query stays a cheap seek forever." },
      { q:"That table grows forever as read history piles up. Does that ever become a problem?",
        a:"The <b>unread badge</b> never degrades &mdash; the partial index is sized to unread, not total &mdash; but the <i>table</i> and the full-history queries (the notification <i>list</i>, not the count) do grow. You handle it the usual way for append-heavy history: <b>partition or archive by age</b>, since users rarely scroll back far, so notifications older than N months move to a partitioned older table or cold storage. The hot path (badge + recent list) stays on a small, indexed working set, and old read rows age out of the primary table rather than accumulating forever. Growth is bounded by retention policy, not left unbounded." }
    ],
    senior:"Reaching for a <b>row-per-recipient model with a partial index on <code>read_at IS NULL</code></b> &mdash; and articulating that it indexes only the working set so the badge query never degrades &mdash; is a concrete storage-design signal." },
  { tier:'SDE2', signal:'The read-heavy badge',
    q:"The unread-count query runs on every page load for every user. It&rsquo;s becoming your hottest query. What do you do?",
    a:"First, make sure it&rsquo;s already a <b>seek into the partial unread index</b>, not a scan &mdash; that alone keeps it cheap. If the read <i>volume</i> is the problem (every page, every user), <b>cache the count</b> in Redis with invalidation on read/new-notification, so most page loads never touch Postgres. The count is derived data with a clear invalidation trigger, which makes it a good cache candidate.",
    f:[
      { q:"How do you keep the cached count correct when a notification is read or arrives?",
        a:"Invalidate or adjust on the events that change it: a <b>new notification</b> increments (or busts) the cached count for that user; <b>marking read</b> decrements (or busts) it. Because both are explicit events, the cache has precise invalidation triggers rather than a blind TTL &mdash; though a short TTL as a backstop catches any missed event. The count is eventually consistent by at most that TTL, which is fine for a badge &mdash; a slightly stale unread number for a few seconds is acceptable, unlike, say, a balance." },
      { q:"What happens on the first page load after the cache is cold, or if Redis is down entirely?",
        a:"You <b>fall back to the source of truth</b> &mdash; the partial-index seek on Postgres &mdash; which is <i>already</i> cheap, so a cache miss or a Redis outage degrades to &lsquo;a fast query,&rsquo; not an error. That&rsquo;s the key property: the cache is an <b>optimization for read volume, not a correctness dependency</b>. On a cold cache you compute the count once from the index and populate it; if Redis is unavailable, every request just hits the index directly (higher DB load, still correct). Because the fallback is a seek and not a scan, losing the cache is a performance event, not an outage &mdash; which is exactly why the partial index still has to exist even <i>with</i> the cache in front of it." }
    ],
    senior:"Distinguishing the two failure modes &mdash; <b>a slow query (fix with the partial index) vs high read volume (fix with a cached, event-invalidated count)</b> &mdash; rather than jumping straight to a cache, is the diagnostic instinct that reads as senior." },
  { tier:'SDE2', signal:'Delivery guarantees',
    q:"What delivery guarantee does your notification system provide &mdash; at-most-once, at-least-once, or exactly-once?",
    a:"<b>At-least-once delivery plus idempotent processing</b>, which together give <b>effectively exactly-once</b>. True exactly-once end-to-end is a distributed-systems unicorn; what you actually build is at-least-once (retry until acked, so nothing is lost) and dedupe on a content-derived key (so the inevitable duplicates don&rsquo;t reach the user twice). At-most-once (send and pray) risks losing a notification, which for a transactional one is unacceptable.",
    f:[
      { q:"Why not just aim for exactly-once delivery directly?",
        a:"Because <b>exactly-once <i>delivery</i> across a network is effectively impossible</b> &mdash; you can&rsquo;t distinguish &lsquo;the send succeeded but the ack was lost&rsquo; from &lsquo;the send failed,&rsquo; so any system that guarantees no loss must risk a duplicate. The honest, achievable target is exactly-once <i>effect</i>: at-least-once delivery (never lose) combined with idempotent handling (dedupe the duplicate). Claiming exactly-once delivery is a red flag; claiming at-least-once-plus-idempotency is the correct, buildable guarantee." },
      { q:"&lsquo;Never lose a notification&rsquo; assumes the event reliably gets from the producer into the queue. How do you guarantee that hand-off?",
        a:"That&rsquo;s the <b>dual-write problem</b> &mdash; a producer that commits its business transaction and <i>then</i> publishes the event can crash in between, silently losing the notification. The fix is the <b>transactional outbox</b>: the producer writes the event to an outbox table <i>in the same database transaction</i> as its business change, so they commit atomically, and a separate relay reliably publishes outbox rows to the queue. Now the event can&rsquo;t be lost even if the producer dies right after commit &mdash; it&rsquo;s durably recorded with the change that caused it. At-least-once is only truly no-loss if the <i>entry</i> into the pipeline is atomic with the triggering event; the outbox is how you get that." }
    ],
    senior:"Answering &lsquo;at-least-once plus idempotency equals effectively exactly-once&rsquo; &mdash; and knowing that exactly-once <i>delivery</i> is unachievable while exactly-once <i>effect</i> is &mdash; is the distributed-systems literacy that separates a real answer from a buzzword." },
  { tier:'SDE3', signal:'Polling vs push',
    q:"In-app notifications: do you poll or push? Defend the choice.",
    a:"For a <b>notification badge</b>, <b>poll</b> &mdash; the client queries the unread index every ~60 seconds. It&rsquo;s simple, stateless, needs no persistent connection, and a minute of latency is fine for a badge. You switch to <b>push</b> (WebSocket/SSE) only when the product needs <b>sub-second</b> delivery &mdash; a chat, a live feed &mdash; and you accept the cost of maintaining a connection per active user and the server-side delivery-on-write plumbing.",
    f:[
      { q:"What&rsquo;s the scaling cost of driving the poll interval toward real-time?",
        a:"Polling load is <b>users &times; (1 / interval)</b> &mdash; a fixed read rate that grows as you shorten the interval. At 60s it&rsquo;s trivial; at 1s it&rsquo;s 60&times; the query load, most of it returning &lsquo;nothing new.&rsquo; That&rsquo;s the wall: polling wastes work proportional to how &lsquo;instant&rsquo; you make it, because most polls find no change. Push inverts that &mdash; the server does work only when there&rsquo;s <i>actually</i> something to deliver &mdash; which is why real-time features move to push rather than fast polling." },
      { q:"With push, how do you handle a user who&rsquo;s offline when the notification fires?",
        a:"You <b>persist first, deliver second</b>: the notification is written to the store (the row-per-recipient) regardless of connection state, and the WebSocket/SSE push is a <i>best-effort accelerator</i> on top. If the user is connected, they get it instantly; if not, it&rsquo;s waiting in the unread index when they reconnect and the client fetches on connect. Push is never the source of truth &mdash; the store is &mdash; so a dropped connection loses latency, not the notification." }
    ],
    senior:"Defending <b>poll for a badge, push for sub-second</b> &mdash; with the scaling math (polling load grows as you shorten the interval) and &lsquo;persist first, push as accelerator&rsquo; for offline &mdash; is the trade-off fluency a senior round wants." },
  { tier:'SDE3', signal:'Preferences',
    q:"Users want control over what notifications they get. How do you model and store preferences?",
    a:"Multi-dimensional: <b>global on/off</b>, <b>per-channel</b> (email yes, push no), <b>per-category</b> (transactional vs promotional vs system), <b>frequency</b> (instant vs hourly/daily digest), and <b>quiet hours</b> with timezone. Store them in a durable backing store (DynamoDB/Postgres) but <b>cache in Redis for ~1ms reads</b>, because fan-out reads preferences on every notification &mdash; and invalidate the cache on preference update.",
    f:[
      { q:"Fan-out hits preferences on every single notification. How do you keep that from becoming a bottleneck?",
        a:"Cache them: preferences change rarely and are read constantly, which is the ideal cache profile. A <b>Redis read (~1ms) per fan-out</b> with the durable store behind it means the hot path never waits on the primary database, and you <b>invalidate on update</b> so a preference change takes effect promptly. Without the cache, every notification does a preference lookup against the primary store, which at fan-out volume is exactly the read amplification you want to avoid. Read-heavy, write-rare data belongs in a cache with event-based invalidation." },
      { q:"A user turns off email notifications. How fast does that take effect, and what if fan-out reads a stale cached preference?",
        a:"You <b>invalidate the cache entry on the preference write</b>, so the next fan-out reads the new value &mdash; effect is near-immediate, bounded by the invalidation. The stale-read window is the only risk: a notification fanning out at the exact moment the preference flips might use the old value and send one more email. For preferences that&rsquo;s <b>acceptable</b> &mdash; one extra email just after opting out is an annoyance, not a correctness violation &mdash; so you invalidate promptly and tolerate a sub-second stale window rather than pay for strong consistency on every read. The one place you&rsquo;d tighten it is a legally-significant unsubscribe, where you might read through to the source of truth on the send path to be certain." }
    ],
    senior:"Modeling preferences across <b>channel / category / frequency / quiet-hours</b> and putting them in a <b>Redis cache with invalidation</b> because fan-out reads them constantly &mdash; is the completeness and performance-awareness a senior answer shows." },
  { tier:'SDE3', signal:'Retry and DLQ',
    q:"A send fails. Walk me through your retry strategy.",
    a:"<b>Classify first.</b> Retryable errors (429, 5xx, network timeout) get <b>exponential backoff with full jitter</b> &mdash; a few attempts &mdash; then, if still failing, a <b>dead-letter queue</b>. Non-retryable errors (400, invalid address, 403) go <b>straight to the DLQ</b>; retrying a malformed request just burns quota. And the policy is <b>per channel</b>: email a few retries, SMS once then DLQ (duplicates cost money), push fire-and-forget. Every retry rides the same idempotency key, so it can&rsquo;t double-send.",
    f:[
      { q:"Why full jitter on the backoff rather than plain exponential?",
        a:"To break up <b>synchronized retries</b>. If a downstream (SES, a provider) has a blip and a thousand sends fail at once, plain exponential backoff has them <i>all</i> retry at exactly the same later moments &mdash; a thundering herd that re-hammers the recovering service. <b>Full jitter</b> randomizes each retry within the backoff window, spreading them out so the load is smooth. It&rsquo;s the difference between a thousand retries landing in the same millisecond and a thousand retries spread across the window &mdash; the recovering service gets a ramp, not a spike." },
      { q:"What happens to a message once it&rsquo;s in the DLQ?",
        a:"It&rsquo;s <b>out of the hot path but not lost</b>: the DLQ is a holding area with its own retention and alarming (DLQ depth &gt; N pages someone). From there it&rsquo;s either <b>auto-redriven</b> after a cool-off (for transient-looking failures), or <b>manually reviewed</b> (for the ones that need a human &mdash; a persistently bad address, a bug). The point is that a failed send never silently vanishes and never blocks the queue behind it &mdash; it&rsquo;s parked, visible, and recoverable, which is exactly what you want for the small fraction that exhausts retries." }
    ],
    senior:"Splitting <b>retryable (backoff + jitter) from non-retryable (straight to DLQ)</b>, using <b>full jitter</b> to avoid thundering herds, and setting <b>per-channel policies</b> by cost &mdash; is the reliability depth that marks a strong answer." },
  { tier:'SDE3', signal:'Recipient resolution',
    q:"An event says &lsquo;notify the tenant&rsquo;s admins.&rsquo; How do you turn that into actual sends, and why not just store a recipient list?",
    a:"<b>Role-based resolution at send time</b>: the event carries a target (&lsquo;admins of tenant T&rsquo;), and resolution expands it against <b>current membership</b> to concrete users, each with their channel preferences, scoped to the tenant. A stored list would go stale &mdash; a new admin wouldn&rsquo;t get notified, a removed one still would. Resolving against live membership means the target stays correct as the org changes, with no code change.",
    f:[
      { q:"Where does tenant isolation come into recipient resolution?",
        a:"Resolution is <b>scoped to the tenant</b> &mdash; the same per-tenant boundary the authorization layer enforces &mdash; so &lsquo;admins of tenant T&rsquo; can only ever resolve to users <i>within</i> T, never leak across tenants. And the email goes out under the <b>tenant&rsquo;s own sender identity</b>, so one tenant&rsquo;s notifications can&rsquo;t address or appear to come from another&rsquo;s. A bug that resolved cross-tenant would be the same class of leak as a missing authorization filter, so resolution inherits the tenant scope rather than trusting the event to be well-formed." },
      { q:"&lsquo;Notify all members of a 50,000-person tenant&rsquo; &mdash; do you resolve that to 50,000 sends up front, and when?",
        a:"You resolve at <b>send-time but fan the expansion out asynchronously</b>, not as one synchronous blast. The event carries the <i>target</i> (&lsquo;all members of T&rsquo;); a resolution step expands it against current membership and enqueues per-recipient send tasks, which fan-out workers drain in parallel under the per-channel rate limits. You don&rsquo;t block the producer while 50,000 rows materialize, and you don&rsquo;t pre-store the list (it&rsquo;d go stale). For very large targets you expand in <b>batches</b>, paging through membership, so a huge tenant doesn&rsquo;t become one massive unit of work. So resolution is late (against live membership) and streamed (batched into the queue), keeping a big broadcast from being either a stale list or a synchronous stall." }
    ],
    senior:"Resolving recipients from a <b>role against current membership at send time</b> (not a stale stored list) &mdash; and scoping resolution to the tenant with a per-tenant sender &mdash; is the correctness-and-isolation thinking a senior round rewards." },
  { tier:'SDE3', signal:'Topic design',
    q:"Building fan-out on a pub/sub system: one topic per channel, or one topic with routing? Which and why?",
    a:"<b>One topic per event domain, with channel selection at the subscriber via filter policies</b> &mdash; not one topic per channel. Publishers emit &lsquo;notification N for user U&rsquo; with attributes, and each channel worker&rsquo;s subscription filters for the channel it handles. This keeps <b>publishers ignorant of channels</b>: a new channel is a new subscription with zero publisher change. Per-channel topics would push routing knowledge back to publishers, which is exactly the coupling you&rsquo;re trying to avoid.",
    f:[
      { q:"When would you switch from filter policies to actually separate topics or queues?",
        a:"When you need <b>per-channel SLA or scaling differentiation</b> &mdash; transactional SMS at p99 under 5s vs marketing email at p99 under 5 minutes &mdash; you give each channel its own <b>queue</b> with different visibility timeouts and worker concurrency, fed from the one topic. And you split <i>topics</i> when filter policies get unmaintainable or you exceed the routing-dimension limits (e.g. the 5-key filter-policy cap on SNS). The heuristic: filter policies while routing is simple; separate queues for SLA isolation; separate topics only when the policy layer stops scaling." },
      { q:"A channel worker (a subscriber) is down for an hour. Do those notifications just disappear?",
        a:"No &mdash; that&rsquo;s why each channel worker consumes from its <b>own durable queue subscribed to the topic</b>, not directly off a fire-and-forget fan-out. The topic delivers into each subscription&rsquo;s queue, so if the email worker is down, its messages <b>accumulate in its queue</b> and process on recovery, while the SMS and push workers on their own queues are unaffected. This is the SNS-to-SQS fan-out pattern: the topic is the fan-out, but a queue per subscriber gives each channel independent durability, retry, and back-pressure. Without the per-subscriber queue a down consumer would drop its notifications; with it, a channel outage is a <i>delay</i> for that channel only, isolated from the rest." }
    ],
    senior:"Choosing <b>one topic per event domain with subscriber-side filter policies</b> (publishers stay channel-ignorant) &mdash; and knowing the switch points to per-channel queues (SLA) and separate topics (policy limits) &mdash; is the pub/sub design maturity an interviewer probes." },
  { tier:'SDE3', signal:'Rate limiting',
    q:"How do you stop a burst of events from spamming a user &mdash; or blowing past your email provider&rsquo;s limits?",
    a:"Two layers. <b>Per-user throttling</b> &mdash; a sliding window (e.g. one email per 20s per recipient, max N per hour) so a storm of events collapses into a bounded number of notifications. And <b>per-channel rate limiting</b> &mdash; a token bucket against the provider&rsquo;s ceiling (SES ~14 emails/sec, SMS per-number limits) so you burst up to the limit without tripping it. The per-user limit protects the human; the per-channel limit protects the integration.",
    f:[
      { q:"Why sliding window for the per-user limit but token bucket for the per-channel one?",
        a:"Different goals. <b>Per-user</b>, you want an <i>accurate</i> &lsquo;no more than N in the last hour&rsquo; with no burst allowance &mdash; a sliding window gives precise boundary behavior so a user never gets a flood. <b>Per-channel</b>, you <i>want</i> to allow controlled bursts up to the provider&rsquo;s ceiling &mdash; a token bucket refills at the sustainable rate but lets you spend accumulated tokens on a spike, maximizing throughput without exceeding the limit. Sliding window = accurate suppression for the human; token bucket = burst-friendly pacing for the provider." },
      { q:"You have ten fan-out workers. How do they share one per-channel limit without each thinking it has the full budget?",
        a:"The limiter state has to be <b>shared and atomic</b>, not per-worker &mdash; ten workers each enforcing &lsquo;14/sec&rsquo; locally would allow 140/sec and trip SES. You keep the token bucket (or window counter) in a <b>shared store like Redis</b> and decrement it <b>atomically</b> (a Lua script or atomic op), so every worker draws from one global budget. When the bucket is empty a worker doesn&rsquo;t drop the send &mdash; it <b>re-queues with a small delay</b>, so the notification is paced, not lost. The two requirements are one shared, atomically-updated limiter across all workers, and delay-and-retry rather than drop when throttled &mdash; which turns a fleet of workers into a single coordinated rate against the provider." }
    ],
    senior:"Separating <b>per-user throttling (sliding window, suppress the flood) from per-channel rate limiting (token bucket, pace to the provider)</b> &mdash; and knowing why each algorithm fits its job &mdash; is the rate-limiting depth that reads as senior." },
  { tier:'SDE3', signal:'Batching and partial failure',
    q:"You send a batch of 50 emails through SES and one address is malformed. What happens to the other 49?",
    a:"They should all send. Use <code>Promise.allSettled</code>, not <code>Promise.all</code> &mdash; <code>allSettled</code> waits for every send and reports each independently, so one rejected send doesn&rsquo;t abort the batch. You then retry <b>only the failures</b>. With <code>Promise.all</code>, the first rejection short-circuits and you&rsquo;d lose (or blindly retry) the whole batch, risking duplicates on the 49 that already succeeded.",
    f:[
      { q:"Why does using Promise.all here specifically create a duplicate-send risk?",
        a:"Because <code>Promise.all</code> rejects as soon as <i>one</i> promise rejects, but the other 49 sends may have <b>already gone out</b> &mdash; they&rsquo;re in flight or complete. If your error handling then retries &lsquo;the batch,&rsquo; you re-send those 49, duplicating them. <code>allSettled</code> gives you a per-send result, so you retry exactly the one that failed and leave the 49 alone. The idempotency key would still catch the duplicates, but relying on it to clean up a batch you needlessly re-sent is sloppy &mdash; <code>allSettled</code> avoids creating the duplicates in the first place." },
      { q:"After allSettled you retry the one failed address. Doesn&rsquo;t the idempotency key make the whole batch-vs-individual distinction moot anyway?",
        a:"The idempotency key is the <b>safety net, not the plan</b> &mdash; it guarantees a duplicate <i>attempt</i> won&rsquo;t reach the user twice, but you still shouldn&rsquo;t <i>generate</i> needless duplicates and lean on dedup to clean up. <code>allSettled</code> + retry-only-the-failure means you make exactly the sends you need; the key then protects the <i>separate</i> case where the retry of that one failure itself gets retried. So they work at different layers: <code>allSettled</code> keeps the batch from re-sending the 49 that succeeded, and the key protects any individual send from its own retries. Relying on the key alone would work but wastes provider quota and muddies delivery metrics with duplicates &mdash; correct plumbing plus the key is belt <i>and</i> suspenders." }
    ],
    senior:"Knowing <b><code>Promise.allSettled</code> tolerates partial failure so only the bad send retries</b> &mdash; and that <code>Promise.all</code>&rsquo;s short-circuit creates a duplicate-send risk on the already-sent members &mdash; is a concrete correctness detail that signals real batch-processing experience." },
  { tier:'SDE3', signal:'Push channel specifics',
    q:"You add mobile push. What do APNs and FCM force you to handle that email doesn&rsquo;t?",
    a:"<b>Token lifecycle and payload caps.</b> Push targets a <b>device token</b> that goes stale &mdash; you must clean up on <code>410 Gone</code> (APNs) or <code>NotRegistered</code> (FCM), or you keep sending to dead devices. Payloads are <b>tiny</b> (APNs ~4 KB, FCM 4 KB data / 2 KB notification), so you send a summary and a deep link, not content. And the platforms differ: APNs stores only 1 notification per app when offline; FCM stores up to 100.",
    f:[
      { q:"Why is cleaning up invalid tokens on 410/NotRegistered important, not just tidy?",
        a:"Because <b>dead tokens accumulate and degrade the channel</b>: you waste sends on devices that will never receive them, your delivery metrics rot (a rising &lsquo;failed&rsquo; rate that&rsquo;s really just stale tokens), and some providers penalize senders who repeatedly push to invalid tokens. The <code>410</code>/<code>NotRegistered</code> response <i>is</i> the provider telling you &lsquo;this token is gone, stop&rsquo; &mdash; so you remove it from the user&rsquo;s device set. Ignoring it means an ever-growing fraction of your push volume is aimed at nothing, and your reputation and metrics both suffer." },
      { q:"The same user has your app on a phone and a tablet. How does &lsquo;notify the user&rsquo; map to devices?",
        a:"&lsquo;User&rsquo; maps to a <b>set of device tokens</b>, not one &mdash; you keep a device registry per user (each token with its platform, APNs vs FCM, and last-seen), and a push fans out to all <i>active</i> tokens for that user. So one logical notification becomes N device pushes, deduped at the human level by the in-app/badge state, not by the push layer. Two consequences: token cleanup (from <code>410</code>/<code>NotRegistered</code>) prunes that per-user set so you don&rsquo;t push to an uninstalled device, and &lsquo;mark read on one device clears the badge everywhere&rsquo; is driven by the server-side read state (the row-per-recipient), not the push. Push is per-device; &lsquo;the user has seen it&rsquo; lives in the store above the devices." }
    ],
    senior:"Knowing push forces <b>token cleanup on 410/NotRegistered and tiny payloads (summary + deep link, not content)</b> &mdash; plus the APNs/FCM offline-storage difference &mdash; is the channel-specific depth that shows you&rsquo;ve shipped mobile push, not just read about it." },
  { tier:'SDE3', signal:'Digest and aggregation',
    q:"A user follows a busy project and gets 200 notifications an hour. How do you keep that from being unusable?",
    a:"<b>Frequency preferences with digest aggregation.</b> Instead of 200 instant notifications, the user opts into an <b>hourly or daily digest</b>: the system buffers their notifications and, on the schedule, collapses them into <i>one</i> summary (&lsquo;42 updates on Project X&rsquo;) with the details linked. Instant stays the default for transactional/urgent categories; digest is for high-volume, low-urgency streams. It&rsquo;s a preference (per category), so the user chooses the cadence.",
    f:[
      { q:"How do you implement the buffering &mdash; where do the pending digest items live?",
        a:"You <b>still write each in-app notification immediately</b> (so the badge and the list are current), but you <b>suppress the per-item email/push</b> and instead accumulate the items for that user+category in a pending-digest bucket keyed by the digest window. A scheduled job fires per window, reads the bucket, renders one summary email, sends it, and clears the bucket. So the in-app channel is always instant and complete; only the <i>push/email</i> side is batched into the digest. The buffer is just &lsquo;the unsent items since the last digest,&rsquo; which the schedule drains." },
      { q:"A digest is hourly, but a security alert fires mid-window. Does it wait for the digest?",
        a:"No &mdash; <b>urgency overrides frequency</b>. Digest is a per-<i>category</i> preference, so transactional/urgent categories (a security alert, a password reset) are <b>always instant regardless of the digest setting</b>; only the high-volume, low-urgency categories the user chose to digest get buffered. So the security alert skips the bucket and sends immediately, while &lsquo;42 project updates&rsquo; wait for the hourly summary. This is why frequency is scoped per category rather than global &mdash; a single &lsquo;digest everything&rsquo; switch would dangerously delay the notifications that must be instant. The category&rsquo;s urgency, not the schedule, decides whether something waits; the digest only ever holds things it&rsquo;s safe to delay." }
    ],
    senior:"Offering <b>per-category digest frequency (instant for transactional, hourly/daily for high-volume)</b> &mdash; and keeping in-app instant while only batching email/push into the summary &mdash; is the product-and-systems judgment a senior answer brings." },
  { tier:'SDE3', signal:'Delivery tracking',
    q:"How do you know whether a notification was actually delivered and seen &mdash; and what do you do with that?",
    a:"Track a <b>lifecycle of events</b> per notification: SENT, DELIVERED, OPENED, CLICKED, BOUNCED, FAILED. Model it as an <b>observer/event stream</b> &mdash; each delivery emits events that subscribers consume (analytics, a delivery-rate monitor, and the fallback trigger). Use <code>Promise.allSettled</code> across observers so one failing consumer doesn&rsquo;t block the others. This gives you ground truth for the smart fallback and for deliverability metrics.",
    f:[
      { q:"Which of those lifecycle events actually drives system behavior, versus just analytics?",
        a:"<b>OPENED</b> (on the in-app) drives the <b>fallback</b> &mdash; it&rsquo;s what tells you whether to cancel the pending email or cascade to it. <b>BOUNCED</b> and <b>FAILED</b> drive <b>suppression and retry</b> &mdash; a hard bounce adds the address to a suppression list, a soft failure schedules a retry. The rest (DELIVERED, CLICKED) are mostly <b>analytics and deliverability monitoring</b>. So the events aren&rsquo;t just a dashboard: OPENED and BOUNCED close real control loops (fallback, suppression), which is why you capture them as first-class events rather than just logging." },
      { q:"How do you actually capture OPENED and BOUNCED &mdash; and can you trust those signals?",
        a:"They come from <b>different sources with different reliability</b>. <b>BOUNCED</b> and DELIVERED come from the <b>provider&rsquo;s webhooks</b> (SES publishes bounce and delivery events to an SNS topic you consume) &mdash; authoritative, which is why they can safely drive suppression. <b>OPENED</b> for email is a <b>tracking pixel</b>, which is <i>lossy</i> &mdash; image-proxying clients block it, and Apple Mail Privacy Protection pre-fetches and inflates opens &mdash; so email-open is a soft signal. That&rsquo;s why the fallback keys on the <b>in-app OPENED</b> (a real, server-observed read) rather than the email pixel: the in-app read is trustworthy, the email open isn&rsquo;t. So you trust provider webhooks for delivery/bounce and treat email-open as best-effort analytics, driving control loops only off signals you can believe." }
    ],
    senior:"Modeling delivery as a <b>lifecycle event stream (SENT/DELIVERED/OPENED/BOUNCED) with allSettled observers</b> &mdash; and knowing which events drive behavior (OPENED &rarr; fallback, BOUNCED &rarr; suppression) vs analytics &mdash; is the observability-and-control depth a senior round wants." },
  { tier:'SDE3', signal:'Multi-tenant isolation',
    q:"Your platform is multi-tenant. What has to be tenant-scoped in the notification system?",
    a:"Nearly everything on the send path: <b>recipient resolution</b> (a role resolves only within the tenant), the <b>sender identity</b> (email goes out under the tenant&rsquo;s own verified domain/sender, so it can&rsquo;t impersonate another), <b>templates and branding</b>, <b>preferences</b>, and <b>rate limits</b> (one tenant&rsquo;s burst can&rsquo;t consume another&rsquo;s send capacity). A cross-tenant leak here &mdash; notifying the wrong tenant&rsquo;s users, or sending under the wrong sender &mdash; is the same severity as an authorization leak.",
    f:[
      { q:"Why is the per-tenant <i>sender</i> identity a security concern, not just cosmetics?",
        a:"Because sending under a shared or wrong sender lets one tenant&rsquo;s notifications <b>appear to come from another tenant</b> &mdash; or from your platform generically &mdash; which is an impersonation and a phishing vector, and it also <b>pools deliverability reputation</b> so one tenant&rsquo;s spam complaints tank everyone&rsquo;s inbox placement. A per-tenant verified sender means each tenant&rsquo;s mail is authenticated as theirs (SPF/DKIM/DMARC on their domain), reputation is isolated, and a recipient can trust the from-address. It&rsquo;s the email-layer expression of the same tenant boundary the authz topic enforces on data." },
      { q:"One tenant fires a million-recipient campaign. How do you keep that from delaying every other tenant&rsquo;s notifications?",
        a:"You <b>isolate send capacity per tenant</b> so one tenant&rsquo;s burst can&rsquo;t monopolize the shared pipeline &mdash; the noisy-neighbor problem. Concretely: per-tenant rate limits (a tenant draws from its own budget, not the global one), and ideally <b>fair scheduling</b> across tenants at fan-out (round-robin or weighted queues) so a huge tenant&rsquo;s million sends interleave with a small tenant&rsquo;s two rather than the small tenant waiting behind the whole campaign. Transactional traffic should also outrank bulk, so a password-reset never queues behind a marketing blast. Without this the system is technically multi-tenant but operationally single-tenant &mdash; the biggest sender sets everyone&rsquo;s latency &mdash; the same fairness concern the platform enforces wherever a resource is shared." }
    ],
    senior:"Recognizing that <b>resolution, sender identity, templates, preferences, and rate limits all need tenant scoping</b> &mdash; and that a per-tenant sender is a security and deliverability control, not branding &mdash; is the multi-tenant awareness a senior interviewer checks." },
  { tier:'Staff', signal:'Smart fallback',
    q:"You have in-app and email. A naive system sends both, every time. Design something better.",
    a:"A <b>smart fallback / cascade</b> (LinkedIn&rsquo;s &lsquo;air traffic controller&rsquo; pattern): send the cheap <b>in-app first</b>, wait a window, and escalate to <b>email only if the in-app went unseen</b>. If the user <b>opens the in-app within the window, cancel the pending email</b>. You reach the user once, on the channel that worked, instead of double-notifying on every channel. It needs delivery tracking (an OPENED event) and a scheduled, cancelable email send.",
    f:[
      { q:"What does the cancel-the-pending-email step actually require in the implementation?",
        a:"A <b>scheduled send you can revoke</b>: when the in-app goes out, you enqueue the email with a <i>delay</i> equal to the fallback window (a delayed queue message, a scheduled job, or a &lsquo;send_after&rsquo; timestamp). If an OPENED event for the in-app arrives before the delay elapses, you <b>cancel that scheduled send</b> (delete the delayed message / mark the job canceled). So it&rsquo;s two pieces: delivery tracking that emits OPENED, and a delayed-send mechanism that&rsquo;s cancelable. If your email path is fire-immediately with no delay, you can&rsquo;t implement cancel &mdash; the escalation has to be <i>scheduled</i>, not instant, for the cancel to have a window to act in." },
      { q:"How do you choose the fallback window &mdash; too short spams, too long delays the email?",
        a:"By the <b>notification&rsquo;s urgency and the channel&rsquo;s realistic check cadence</b>. For something time-sensitive (a security alert), a short window (minutes) &mdash; you&rsquo;d rather send both than delay the email. For routine updates, a longer window (a few hours, like ATC&rsquo;s default) because most active users will see the in-app soon and the email is pure backup. You can make it <b>per-category</b>: urgent categories skip or shorten the fallback, low-urgency ones use a long window. The window is a tuning knob trading &lsquo;risk of a redundant email&rsquo; against &lsquo;risk of a delayed one,&rsquo; set by how much the specific notification&rsquo;s latency matters." }
    ],
    senior:"Designing the <b>cascade (in-app first, email on unseen, cancel-on-open) with a scheduled cancelable send and a per-category window</b> &mdash; rather than firing every channel &mdash; is exactly the multi-channel sophistication that lands a Staff signal." },
  { tier:'Staff', signal:'Ordering',
    q:"Do notifications need to be delivered in order? A user gets &lsquo;order shipped&rsquo; before &lsquo;order confirmed.&rsquo; Is that a bug?",
    a:"<b>Usually you don&rsquo;t need global ordering, but per-user causal ordering can matter</b> &mdash; and &lsquo;shipped before confirmed&rsquo; is the case where it does. The answer is to order <b>per recipient</b>, not globally: partition the notification stream by <code>user_id</code> so one user&rsquo;s notifications are processed in sequence, while different users stay parallel. Global ordering across all users is unnecessary and would kill throughput; per-user ordering is cheap and fixes the visible anomaly.",
    f:[
      { q:"How does partitioning by user_id give you per-user ordering without serializing everything?",
        a:"Because a <b>partitioned consumer</b> (the Kafka model) guarantees ordering <i>within</i> a partition but processes partitions in parallel. If you partition by <code>user_id</code>, every notification for a given user lands in the same partition and is consumed in order, so that user never sees &lsquo;shipped before confirmed.&rsquo; But user A&rsquo;s partition and user B&rsquo;s partition are handled by different consumers concurrently, so total throughput scales with partition count. You get ordering exactly where it&rsquo;s observable (one user&rsquo;s timeline) and parallelism everywhere else &mdash; the standard way to buy causal order without a global serialization bottleneck." },
      { q:"Partitioning by user_id means one slow message blocks that user&rsquo;s whole partition. Is ordering always worth that?",
        a:"No &mdash; ordering has a real cost (head-of-line blocking within the partition), so you impose it <b>only where the anomaly is observable and harmful</b>. &lsquo;Shipped before confirmed&rsquo; matters; &lsquo;two unrelated updates arrived out of order&rsquo; doesn&rsquo;t. So often the better answer is <b>not</b> to serialize at all and instead make notifications <b>order-independent</b> &mdash; each carries enough context to stand alone (&lsquo;Order #123 shipped&rsquo; is meaningful even if &lsquo;confirmed&rsquo; is late), or the <i>display</i> orders by the event&rsquo;s business timestamp rather than delivery order. Reserve per-user partitioning for genuine causal chains and let everything else be unordered and parallel. The senior move is recognizing most notifications don&rsquo;t need ordering, so you pay the blocking cost surgically, not everywhere." }
    ],
    senior:"Scoping ordering to <b>per-user (partition by user_id) rather than global</b> &mdash; recognizing that &lsquo;shipped before confirmed&rsquo; is a per-user causal-order bug, not a call for global ordering &mdash; is the distributed-systems judgment that separates Staff from &lsquo;add a queue.&rsquo;" },
  { tier:'Staff', signal:'Bounces and sender reputation',
    q:"Emails are landing in spam and your bounce rate is climbing. What&rsquo;s happening and how do you protect deliverability?",
    a:"You&rsquo;re damaging <b>sender reputation</b>. Fixes: <b>authenticate</b> (SPF, DKIM, DMARC on the sending domain), <b>honor bounces and complaints</b> &mdash; a hard bounce or spam complaint must add the address to a <b>suppression list</b> so you never send to it again (repeated sends to bad addresses are what tank reputation), <b>warm up</b> new sending domains gradually, and <b>separate transactional from promotional</b> streams (ideally different domains/IPs) so marketing complaints don&rsquo;t sink transactional deliverability.",
    f:[
      { q:"Why does continuing to send to bounced addresses hurt <i>other</i> users&rsquo; deliverability?",
        a:"Because mailbox providers judge you by your <b>aggregate sender reputation</b>, and a high bounce/complaint rate signals &lsquo;this sender doesn&rsquo;t manage their list&rsquo; &mdash; so they start filtering <i>all</i> your mail, including to perfectly good addresses. One sender, one reputation: the bad addresses drag down the good. That&rsquo;s why honoring bounces (suppression) isn&rsquo;t optional hygiene &mdash; it&rsquo;s protecting the deliverability of every <i>other</i> recipient. And separating transactional from promotional onto different domains isolates the reputations, so a promotional campaign&rsquo;s complaints don&rsquo;t bury a password-reset email." },
      { q:"Do you treat every bounce the same &mdash; suppress on the first one?",
        a:"No &mdash; you distinguish <b>hard from soft bounces</b>. A <b>hard bounce</b> (invalid address, domain doesn&rsquo;t exist) is permanent, so you <b>suppress immediately</b> &mdash; retrying only damages reputation. A <b>soft bounce</b> (mailbox full, temporary server issue, greylisting) is transient, so you <b>retry a few times with backoff</b> before giving up and suppressing. Collapsing them would either wrongly stop mailing a valid recipient whose inbox was briefly full, or keep hammering a dead address and tank reputation. Complaints (the spam button) are their own category: treat as a hard suppression <i>and</i> a signal to review why that mail was unwanted. So bounce handling is a small classifier &mdash; permanent to suppression, transient to bounded retry, complaint to suppression-plus-review &mdash; not one blanket rule." }
    ],
    senior:"Connecting <b>bounce/complaint handling and suppression lists to aggregate sender reputation</b> &mdash; and isolating transactional from promotional streams so one can&rsquo;t sink the other &mdash; is deliverability depth most candidates don&rsquo;t have, which reads as Staff." },
  { tier:'Staff', signal:'Cost at scale',
    q:"At a billion notifications a month, where does the money actually go &mdash; and what do you optimize?",
    a:"The <b>fan-out infrastructure is nearly free relative to channel delivery</b>. The pub/sub layer, the queues, the in-app writes &mdash; rounding error. The cost is <b>per-message channel delivery</b>, and <b>SMS dominates</b> (cents per message plus carrier fees), then push/email are cheap, and in-app is essentially free (a DB row). So the cost conversation at scale is <b>which channels you enable and how you throttle them</b> &mdash; SMS provider arbitrage, 10DLC carrier-fee management, and pushing users toward in-app/push over SMS &mdash; not the messaging backbone.",
    f:[
      { q:"So what&rsquo;s the highest-leverage cost lever &mdash; optimizing the infrastructure or the channel mix?",
        a:"The <b>channel mix</b>, decisively. Halving your queue costs saves rounding error; moving 20% of SMS volume to push saves real money, because SMS is orders of magnitude more expensive per message than push or in-app. So the levers are: <b>default to the cheap channels</b> (in-app/push) and reserve SMS for genuinely SMS-worthy notifications (a login code), <b>use fallback</b> so you don&rsquo;t send SMS <i>and</i> push for the same event, and <b>manage SMS provider/carrier costs</b> directly. The engineering instinct to optimize the code path is misapplied here &mdash; at notification scale, the architecture decision <i>is</i> the channel-enablement policy, and that&rsquo;s where the spend lives." },
      { q:"At a billion a month, is it cheaper to keep buying SES/Twilio, or build your own delivery?",
        a:"You almost always <b>keep buying delivery</b> and build only the <i>orchestration</i>. The expensive, hard part of email/SMS is <b>deliverability and carrier relationships</b> &mdash; IP reputation, SPF/DKIM/DMARC at scale, ISP feedback loops, SMS carrier registration (10DLC), global routing &mdash; which providers have spent years and infrastructure on. Reproducing that to run your own SMTP or connect to carriers directly rarely beats their per-message price until truly enormous, specialized volume, and it hands you reputation and compliance risk you&rsquo;re now managing alone. So the build-vs-buy line sits between <b>orchestration and transport</b>: you build fan-out, preferences, idempotency, fallback, and channel policy (your differentiation), and you buy the actual send (their scale, reputation, carrier plumbing). The cost lever stays the channel mix, not vertically integrating transport." }
    ],
    senior:"Knowing that at scale <b>SMS delivery dominates cost while the fan-out backbone is rounding error</b> &mdash; so the real lever is channel mix and fallback, not infrastructure micro-optimization &mdash; is the cost-modeling judgment that marks a Staff answer." },
  { tier:'Staff', signal:'The whole design',
    q:"Tie it together: one sentence for how you&rsquo;d design a multi-channel notification system.",
    a:"<b>Producers emit events at a fan-out boundary; the system resolves recipients by role, fans out on their preferences, delivers effectively-once via a content-derived idempotency key, uses in-app as the cheap polled default and email/push as reach with a smart fallback, retries per-channel with a DLQ, and tracks the delivery lifecycle</b> &mdash; so a user reliably gets each notification once, on the channel that works, and no producer ever knows a channel exists. The hard parts are idempotency and the fallback, not the channels.",
    f:[
      { q:"If you could only ship three of those, which three?",
        a:"<b>The fan-out boundary</b> (producers emit events, stay channel-ignorant &mdash; without it, channel logic scatters and never recovers), <b>idempotency</b> (a content-derived key + dedup store &mdash; without it, every retry double-notifies, which is the fastest way to look broken), and <b>the in-app row-per-recipient model with a partial unread index</b> (the cheap, always-correct default channel). Those three are the skeleton: a boundary so it&rsquo;s maintainable, idempotency so it&rsquo;s correct under retries, and a working default channel. Preferences, fallback, digests, and multi-channel are depth layered on that spine &mdash; addable without a rewrite." },
      { q:"You&rsquo;ve shipped the spine. What&rsquo;s the first thing that breaks as you scale, and what do you add?",
        a:"The first things to bite are <b>channel cost and user overload</b>. As volume climbs, <b>SMS spend</b> and double-notifying (email <i>and</i> push for one event) start to hurt, so the first additions are the <b>smart fallback</b> (reach the user once, on the channel that worked) and <b>digest/frequency preferences</b> (so a busy user isn&rsquo;t buried) &mdash; both directly attack the two pains a naive multi-channel system creates. Close behind is <b>deliverability</b>: as email volume grows, bounce/complaint handling and sender-reputation management become load-bearing, because ignoring them silently sinks inbox placement. So the evolution is spine &rarr; fallback + digests (cost and overload) &rarr; deliverability hygiene &mdash; each added when the scale that makes it matter actually arrives, not all up front." }
    ],
    senior:"Compressing the whole system into <b>&lsquo;fan-out boundary + idempotent delivery + polled in-app default + smart fallback&rsquo;</b> &mdash; and being able to name the irreducible three under pressure &mdash; is the systems-level framing that lands a Staff signal." }
];
var NOTIF_SPEAK = [
  "Lead with the non-negotiable: <b>'a content-derived idempotency key &mdash; hash of user, event, channel &mdash; checked before every send.'</b> Then why random ids fail (they don&rsquo;t collide on the retry) and how you size the TTL (to the longest retry delay). That&rsquo;s the &lsquo;I&rsquo;ve run at-least-once delivery&rsquo; tell.",
  "Frame the boundary: <b>'producers emit notify(user, event) and stay channel-ignorant; the notification system owns channels, preferences, fallback.'</b> The alternative &mdash; every service calling SES &mdash; scatters channel logic everywhere and makes &lsquo;add a channel&rsquo; a fleet-wide change.",
  "State the storage shape: <b>'one row per recipient, ~100 bytes, with a partial index on read_at IS NULL.'</b> The badge query is a seek into a tiny index, not a scan; a million notifications is ~100 MB. The partial index only holds the working set (unread), so it never degrades.",
  "Diagnose before caching: <b>'first make sure the badge query is a seek into the partial unread index; if the read <i>volume</i> is the problem, cache the count in Redis with event invalidation.'</b> A slow query and high read volume are different problems with different fixes.",
  "Get the guarantee right: <b>'at-least-once delivery plus idempotent processing equals effectively exactly-once.'</b> Exactly-once <i>delivery</i> across a network is impossible; exactly-once <i>effect</i> is what you build. Claiming exactly-once delivery is a red flag.",
  "Defend the default: <b>'poll the unread index every 60s for a badge; push (WebSocket/SSE) only for sub-second.'</b> Polling load grows as you shorten the interval, most polls finding nothing &mdash; that&rsquo;s the wall. With push, persist first and treat the push as an accelerator, so an offline user still gets it.",
  "Model preferences across <b>'channel, category, frequency, and quiet hours'</b> &mdash; and put them in a <b>Redis cache with invalidation</b>, because fan-out reads them on every notification. Read-heavy, write-rare data belongs in a cache, or the primary store gets hammered.",
  "Classify the failure: <b>'retryable (429, 5xx, timeout) gets exponential backoff with full jitter; non-retryable (400, bad address) goes straight to the DLQ.'</b> Full jitter breaks the thundering herd; per-channel policy reflects cost &mdash; SMS retries conservatively because a duplicate has regulatory cost.",
  "Resolve at send time: <b>'the event carries a role; resolution expands it against current membership, scoped to the tenant.'</b> A stored recipient list goes stale &mdash; a new admin wouldn&rsquo;t get notified. And resolution is tenant-scoped, so it can&rsquo;t leak across tenants.",
  "Choose the topology: <b>'one topic per event domain, channel selection at the subscriber via filter policies.'</b> Publishers stay channel-ignorant; a new channel is a new subscription. Split to per-channel queues for SLA isolation, separate topics only when filter policies stop scaling.",
  "Two rate-limit layers: <b>'per-user sliding window to suppress the flood, per-channel token bucket to pace to the provider.'</b> Sliding window is accurate suppression for the human; token bucket allows controlled bursts up to SES or the SMS ceiling without tripping it.",
  "Name the batch primitive: <b>'Promise.allSettled, not Promise.all &mdash; one bad address doesn&rsquo;t fail the batch, and you retry only the failure.'</b> Promise.all short-circuits on the first rejection, so you&rsquo;d re-send the 49 that already went out &mdash; a duplicate-send risk.",
  "Handle the push realities: <b>'clean up tokens on 410 Gone / NotRegistered, and keep payloads tiny &mdash; a summary and a deep link.'</b> Dead tokens waste sends and rot your metrics and reputation; APNs and FCM cap payloads at a few KB, so content lives behind the link.",
  "Offer digest: <b>'per-category frequency &mdash; instant for transactional, hourly or daily digest for high-volume streams.'</b> Keep in-app instant and complete; only batch the email/push into one summary. The buffer is just the unsent items since the last digest, drained on schedule.",
  "Track the lifecycle: <b>'SENT, DELIVERED, OPENED, BOUNCED &mdash; as an event stream with allSettled observers.'</b> OPENED drives the fallback (cancel or cascade), BOUNCED drives suppression; the rest is analytics. Capture the control-loop events as first-class, not just logs.",
  "Scope to the tenant: <b>'resolution, sender identity, templates, preferences, and rate limits all per-tenant.'</b> A per-tenant verified sender isn&rsquo;t branding &mdash; it stops impersonation and isolates deliverability reputation, the email-layer version of the authz tenant boundary.",
  "Design the cascade: <b>'in-app first, wait a window, email only if unseen &mdash; and cancel the pending email if they open the in-app.'</b> It needs an OPENED event and a scheduled, cancelable send. You reach the user once, on the channel that worked, instead of firing every channel.",
  "Order per user, not globally: <b>'partition the stream by user_id so one user&rsquo;s notifications are sequenced, while users stay parallel.'</b> &lsquo;Shipped before confirmed&rsquo; is a per-user causal-order bug; global ordering is unnecessary and kills throughput.",
  "Protect the reputation: <b>'authenticate with SPF/DKIM/DMARC, honor bounces into a suppression list, warm up domains, split transactional from promotional.'</b> Sending to bounced addresses tanks aggregate reputation, filtering <i>all</i> your mail &mdash; so suppression protects every other recipient.",
  "Follow the money: <b>'the fan-out backbone is rounding error; SMS delivery dominates.'</b> The lever is the channel mix &mdash; default to in-app and push, reserve SMS for login codes, use fallback so you don&rsquo;t send SMS and push for one event. The architecture decision is the channel-enablement policy.",
  "Land the whole thing: <b>'fan-out boundary, idempotent delivery, polled in-app default, smart fallback.'</b> Under pressure, name the irreducible three: the boundary (maintainable), idempotency (correct under retries), the in-app row model (a working default). The rest is depth on that spine."
];
var TOPIC_NOTIF_DRILL = {
  cards: NOTIF_CARDS,
  speak: NOTIF_SPEAK,
  tierNotes: {
    all:'<b>All four levels, mixed</b> &mdash; the way a real loop actually comes at you.',
    SDE2:'<b>Fundamentals under pressure</b> &mdash; idempotency, the fan-out boundary, the in-app row model, delivery guarantees. The bar is &ldquo;this is a real delivery system, not a for-loop over SES&rdquo;: name the guarantee and the mechanism that enforces it.',
    SDE3:'<b>Depth &amp; trade-offs</b> &mdash; poll vs push, preferences caching, retry classification, topic design, batching. The bar is &ldquo;it depends, here&rsquo;s the switch&rdquo;: name the constraint and the failure each choice bounds.',
    Staff:'<b>Systems judgment</b> &mdash; smart fallback, per-user ordering, sender reputation, cost at scale. The bar is &ldquo;reach the user once, correctly, cheaply&rdquo;: name the hard part (idempotency, fallback) and why the channels are the easy part.'
  }
};
