/* topics/notifications/walk.js -- topic 5 walkthrough. steps[] is the delivery flow
   (producer event -> idempotency key -> recipient resolution -> fan-out -> in-app row
   -> poll/push -> SES batch -> retry/DLQ -> fallback+tracking); modelScript[] is the
   spoken model answer (plain beats, the interviewer .mq line, then the .mbeat.ans --
   which MUST be LAST). Code strings use single-backslash \n / \'. 7-bit ASCII. */
var TOPIC_NOTIF_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"The producer emits an event",
      flow:'<span class="fb n">service</span><span class="arr">&rarr;</span><span class="fb p">notify(user, event)</span><span class="arr">&rarr;</span><span class="fb t">notification request</span><span class="arr">&middot;</span><span class="fb a">producer knows no channels</span>',
      ins:'A producer calls <code>notify(user, event)</code> &mdash; it emits &lsquo;this user should know about this event,&rsquo; and stops there. It never names email or in-app; the notification system owns channel selection, so adding a channel is <b>zero producer change</b>.',
      deep:'This is the boundary that makes the whole thing maintainable. A producer &mdash; an order service, a firmware-rollout job &mdash; shouldn&rsquo;t know or care whether the user gets an email, an in-app badge, or both; it emits a <b>domain event</b> and the notification system decides delivery. So preferences, channel routing, batching, and fallback all live on <i>one</i> side of the boundary, and producers stay ignorant. The alternative &mdash; each producer calling SES directly &mdash; scatters channel logic across every service and makes &lsquo;add a channel&rsquo; a fleet-wide change instead of one.' },
    { k:"Step 2 / 9", t:"Make it idempotent",
      flow:'<span class="fb n">request</span><span class="arr">&rarr;</span><span class="fb p">id = hash(user, event, channel)</span><span class="arr">&rarr;</span><span class="fb t">dedup store (SET NX)</span><span class="arr">/</span><span class="fb r">already sent &rarr; skip</span>',
      ins:'Before anything sends, compute a <b>deterministic id</b> &mdash; <code>hash(user_id, event_id, channel)</code> &mdash; and record it in a dedup store with a conditional write. If the id is already there, this is a <b>retry</b>: acknowledge and <b>don&rsquo;t re-send</b>. Non-negotiable, because at-least-once delivery and retries both duplicate.',
      code:'<span class="c">// deterministic id -- same event + user + channel always collides</span>\n<span class="k">const</span> id = sha256(`${userId}:${eventId}:${channel}`);\n<span class="k">const</span> fresh = <span class="k">await</span> dedup.<span class="hl">setNX</span>(id, <span class="hl">1</span>, { ttl: <span class="hl">7</span> * DAY });  <span class="c">// SET if Not eXists</span>\n<span class="k">if</span> (!fresh) <span class="k">return</span> ack();          <span class="c">// already sent -- ack the retry, send nothing</span>',
      cap:'The id is <i>content-derived</i>, not random &mdash; so a retry of the exact same notification computes the exact same id and collides. That collision is what turns at-least-once machinery into <b>effectively exactly-once</b> delivery, without the producer thinking about it.' },
    { k:"Step 3 / 9", t:"Resolve the recipients",
      flow:'<span class="fb n">event target</span><span class="arr">&rarr;</span><span class="fb p">role-based resolution</span><span class="arr">&rarr;</span><span class="fb t">concrete users + channels</span><span class="arr">&middot;</span><span class="fb a">per-tenant sender</span>',
      ins:'The event names a <b>target</b> &mdash; often a role (&lsquo;all admins of tenant T&rsquo;), not a person. Resolution expands that to concrete recipients, each with their channel preferences, scoped to the tenant. A <b>role, not a hard-coded list</b>, so membership changes need no code change.',
      deep:'Role-based resolution keeps the notification target <b>stable as the org changes</b>. &lsquo;Notify the tenant&rsquo;s billing admins&rsquo; resolves against <i>current</i> membership at send time, so a new admin gets it and a removed one doesn&rsquo;t &mdash; the producer never maintains a recipient list. It&rsquo;s also where <b>tenant isolation</b> lands: resolution is scoped to the tenant (the same per-tenant boundary the authz topic enforces), and the email goes out under the <b>tenant&rsquo;s own sender identity</b>, so one tenant&rsquo;s notifications can never address or impersonate another&rsquo;s.' },
    { k:"Step 4 / 9", t:"Fan out to channels",
      flow:'<span class="fb n">recipient + prefs</span><span class="arr">&rarr;</span><span class="fb p">{in-app, email}</span><span class="arr">&rarr;</span><span class="fb t">one deliver per channel</span><span class="arr">&middot;</span><span class="fb a">producer emitted once</span>',
      ins:'For each recipient, the system reads their <b>preferences</b> and fans the single event out to the channels they&rsquo;ve enabled &mdash; in-app, email, or both. The producer emitted <i>once</i>; fan-out is where one event becomes N channel deliveries.',
      code:'<span class="c">// one event -> the channels this recipient actually wants</span>\n<span class="k">const</span> prefs = <span class="k">await</span> getPrefs(userId);       <span class="c">// cached, ~1ms</span>\n<span class="k">const</span> channels = resolveChannels(prefs, event.category); <span class="c">// e.g. [in-app, email]</span>\n<span class="k">for</span> (<span class="k">const</span> ch <span class="k">of</span> channels)\n  <span class="k">await</span> deliver(ch, userId, event);      <span class="c">// each deliver() is independently idempotent</span>',
      cap:'Fan-out reads <b>preferences</b>, not a fixed channel list &mdash; so a user who muted email still gets the in-app, and a category they opted out of gets nothing. The producer stays one call; the <i>routing</i> is a property of the recipient, computed here.' },
    { k:"Step 5 / 9", t:"The in-app channel &mdash; a row per recipient",
      flow:'<span class="fb n">in-app deliver</span><span class="arr">&rarr;</span><span class="fb p">INSERT row (per recipient)</span><span class="arr">&rarr;</span><span class="fb t">partial index (unread)</span><span class="arr">&middot;</span><span class="fb a">~100 bytes</span>',
      ins:'In-app delivery is an <b>INSERT of one row per recipient</b> into Postgres &mdash; roughly 100 bytes each, with a <b>partial index on unread</b> so the badge query is a tiny seek. A million notifications is ~100 MB; the read path is the unread index, never a scan.',
      code:'<span class="c">// one row per recipient -- the read is the partial index, not a scan</span>\n<span class="k">INSERT INTO</span> notifications (user_id, event_id, body, read_at, created_at)\n<span class="k">VALUES</span> ($1, $2, $3, <span class="k">NULL</span>, now());\n<span class="c">-- CREATE INDEX ... ON notifications (user_id) WHERE read_at IS NULL;</span>\n<span class="c">-- badge: SELECT count(*) ... WHERE user_id=$1 AND read_at IS NULL; -- seek</span>',
      cap:'The <b>partial index on <code>read_at IS NULL</code></b> is the trick &mdash; it indexes only unread rows, so it stays small even as read history grows unbounded. The expensive query (unread count, shown on every page) is a seek into a tiny index, not a scan of a million-row table.' },
    { k:"Step 6 / 9", t:"Delivery to the client &mdash; poll or push",
      flow:'<span class="fb n">client</span><span class="arr">&rarr;</span><span class="fb t">poll unread every 60s</span><span class="arr">/</span><span class="fb p">WebSocket push</span><span class="arr">&middot;</span><span class="fb a">the trade-off</span>',
      ins:'The client gets the in-app notification by <b>polling the unread index every ~60 seconds</b> &mdash; simple, stateless, good enough for a badge. For sub-second delivery you&rsquo;d switch to <b>push</b> (WebSocket/SSE), trading polling&rsquo;s simplicity for a connection to maintain.',
      deep:'Polling is the honest default: a lightweight query against the partial index every 60s costs almost nothing and needs no persistent connection, which is why it&rsquo;s right for a badge where a minute of latency is fine. It <i>doesn&rsquo;t</i> scale to &lsquo;instant&rsquo; &mdash; every user polling every minute is a fixed read load, and driving the interval toward real-time multiplies it. When the product genuinely needs sub-second (a chat, a live feed), you move to <b>push</b>: a WebSocket or SSE connection the server writes to on delivery. The tell is matching the mechanism to the latency the feature <i>actually</i> needs, not defaulting to whichever is fancier.' },
    { k:"Step 7 / 9", t:"The email channel &mdash; batched through SES",
      flow:'<span class="fb n">email deliver</span><span class="arr">&rarr;</span><span class="fb p">batch (allSettled, 50)</span><span class="arr">&rarr;</span><span class="fb t">SES, per-tenant sender</span><span class="arr">&middot;</span><span class="fb a">throttle 1/20s</span>',
      ins:'Email goes through <b>SES</b>, sent in <b>batches</b> with <code>Promise.allSettled</code> so one bad address doesn&rsquo;t fail the batch, under the <b>tenant&rsquo;s own sender identity</b>, and <b>throttled</b> (roughly one per 20s per recipient) so a burst of events doesn&rsquo;t spam a user or trip SES limits.',
      code:'<span class="c">// batch, tolerate partial failure, stay under the sender&#39;s rate</span>\n<span class="k">const</span> results = <span class="k">await</span> Promise.<span class="hl">allSettled</span>(       <span class="c">// one bad address != failed batch</span>\n  batch.map(r =&gt; ses.send(buildEmail(r, tenantSender)))\n);                                          <span class="c">// MAX_BATCH_SIZE 50, SES BCC up to 50</span>\nresults.filter(isRejected).forEach(scheduleRetry);  <span class="c">// only the failures retry</span>',
      cap:'<code>allSettled</code> over <code>all</code> is deliberate &mdash; with <code>Promise.all</code>, one rejected send aborts the whole batch and you&rsquo;d retry the good ones too, risking duplicates. Settling each independently means <b>only the actual failures retry</b>, which pairs with the idempotency key to keep exactly-once intact.' },
    { k:"Step 8 / 9", t:"Retry, classify, DLQ",
      flow:'<span class="fb r">send fails</span><span class="arr">&rarr;</span><span class="fb t">retryable? backoff+jitter</span><span class="arr">/</span><span class="fb r">non-retryable? DLQ</span><span class="arr">&middot;</span><span class="fb a">per-channel policy</span>',
      ins:'A failed send is <b>classified</b>: retryable (429, 5xx, timeout) gets <b>exponential backoff with jitter</b>; non-retryable (400, bad address) goes <b>straight to a DLQ</b> &mdash; no point retrying a malformed request. And the policy is <b>per channel</b>: email retries a few times, SMS once then DLQ, push is fire-and-forget.',
      deep:'Classification is what stops a retry storm from a permanent failure. A <b>429 or 5xx</b> is transient &mdash; back off with jitter (so retries don&rsquo;t align into a thundering herd) and try again. A <b>400 or invalid address</b> is permanent &mdash; retrying just burns quota and delays the DLQ, where a human or a cleanup job handles it. Per-channel policy reflects the cost asymmetry: a missed in-app is cheap (it&rsquo;s still in the table), a missed transactional email matters, and a duplicate SMS has real regulatory cost &mdash; so SMS retries conservatively and dead-letters fast. Every retry rides the <b>same idempotency key</b>, so it can never double-send.' },
    { k:"Step 9 / 9", t:"Fallback + delivery tracking",
      flow:'<span class="fb n">in-app unseen in window</span><span class="arr">&rarr;</span><span class="fb p">cascade to email</span><span class="arr">/</span><span class="fb t">seen &rarr; cancel pending email</span><span class="arr">&middot;</span><span class="fb a">track SENT/OPENED</span>',
      ins:'The channels aren&rsquo;t independent &mdash; there&rsquo;s a <b>smart fallback</b>: if the user doesn&rsquo;t <b>open the in-app</b> within a window, cascade to email; if they <i>do</i> see it in time, <b>cancel the pending email</b>. Underneath, every delivery is <b>tracked</b> (SENT, DELIVERED, OPENED) so the fallback and the analytics both have ground truth.',
      deep:'This is the LinkedIn &lsquo;air traffic controller&rsquo; pattern, and it&rsquo;s what makes multi-channel feel considerate instead of spammy. You <b>don&rsquo;t</b> fire email and in-app simultaneously; you send the cheap in-app first, wait a window, and escalate to email only if it went unseen &mdash; and if the user opens the in-app during the window, you <b>cancel</b> the queued email so they don&rsquo;t get both. It needs the <b>delivery tracking</b> (an OPENED event on the in-app) to drive the decision, and a <b>scheduled, cancelable</b> email send. Getting this right is the difference between &lsquo;we notify on every channel every time&rsquo; (annoying) and &lsquo;we reach you once, on the channel that worked&rsquo; (good).' }
  ],
  modelScript: [
    { ml:'Frame the boundary', t:'"A producer emits an event &mdash; notify this user of this thing &mdash; and the notification system owns everything after: which channels, deliver-once, fall back if a channel is missed. So producers stay channel-ignorant and all the delivery logic lives in one place."' },
    { ml:'Idempotency first', t:'"The first thing I add is a deterministic id &mdash; hash of user, event, and channel &mdash; recorded in a dedup store with a conditional write. Because delivery is at-least-once and retries happen, that id is what stops a double-send. It&rsquo;s not optional."' },
    { ml:'Fan out on preferences', t:'"Then I resolve recipients &mdash; usually a role, so membership changes need no code &mdash; and fan the event out to each recipient&rsquo;s enabled channels: in-app, email, or both. The producer emitted once; fan-out turns that into the deliveries the user actually wants."' },
    { ml:'The cheap default', t:'"In-app is a row per recipient in Postgres &mdash; about a hundred bytes, with a partial index on unread so the badge query is a seek. A million notifications is a hundred megabytes. The client polls that index every minute, which is plenty for a badge."' },
    { ml:'Email as reach and backup', t:'"Email goes through SES, batched with allSettled so one bad address doesn&rsquo;t fail the batch, under the tenant&rsquo;s sender, throttled so a burst doesn&rsquo;t spam anyone. And it&rsquo;s the fallback: if the in-app goes unseen in a window, cascade to email; if they open the in-app in time, cancel the pending email."' },
    { mq:'Interviewer: "A retry fires and the user gets the same notification twice. How?"' },
    { ml:'Trace it to the missing key', t:'"That&rsquo;s the idempotency key not applied on the send path &mdash; or being random instead of content-derived. The fix is the deterministic id checked before every deliver, so a retry of the same event computes the same id and collides. And allSettled, not all, so a batch retry re-sends only the actual failures, not the whole batch."' },
    { ml:'Land on the guarantees', t:'"So the shape is: producers emit events, the system fans out on preferences, delivers effectively-once via a content-derived idempotency key, uses in-app as the cheap default and email as reach-and-fallback, and retries with per-channel policies and a DLQ. The hard parts aren&rsquo;t the channels &mdash; they&rsquo;re idempotency and the smart fallback."', ans:true }
  ]
};
