// tools/compiler/compile.mjs -- the driver that turns a topic SOURCE into module files, plus
// a Vite plugin so it happens at build time.
//
// Source is standard markdown (.md, the primary path) or the legacy .topic; both parse to the
// same data. Any ```mermaid step is rendered to inline SVG here (build-time) so nothing ships
// to the runtime. index/total come from the caller (the build owns the topic sequence).
//
// compileTopicsPlugin({srcDir, order, topicsDir}) compiles every <id>.md|.topic in srcDir into
// src/topics/<id>/*.js on buildStart, which the existing concat-include build then picks up --
// so a topic is authored as ONE markdown file instead of twelve hand JS files.

import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { parseTopic } from './parse.mjs';
import { parseMarkdown } from './parse_md.mjs';
import { validateTopic } from './topic-schema.mjs';
import { emit } from './emit.mjs';
import { renderMermaid, closeMermaid } from './mermaid.mjs';
import { renderShiki, closeShiki } from './shiki-highlight.mjs';

async function renderDiagrams(topic) {
  for (const v of Object.values(topic.views)) {
    // pane-level mermaid (e.g. the whiteboard diagram) -> inline SVG at build time
    if (v.mermaid !== undefined) { v.diagram = await renderMermaid(v.mermaid); delete v.mermaid; }
    // step-level mermaid (walk steps); guard paneless views -- rf/trade/... have no steps
    for (const step of v.steps || []) {
      if (step.mermaid !== undefined) { step.diagram = await renderMermaid(step.mermaid); delete step.mermaid; }
      // step-level non-JS code fence -> Shiki-highlighted inner HTML for the app's <pre class="code">
      if (step.shiki !== undefined) { step.code = await renderShiki(step.shiki.code, step.shiki.lang); delete step.shiki; }
    }
  }
}

export async function compileTopic(topicPath, { index = 1, total = 1, outDir, validate = true } = {}) {
  const src = fs.readFileSync(topicPath, 'utf8');
  const topic = topicPath.endsWith('.md')
    ? parseMarkdown(src, { index, total })
    : parseTopic(src, { index, total });
  if (validate) validateTopic(topic, topic.id);
  await renderDiagrams(topic);
  const files = emit(topic);
  const dir = outDir || path.join(path.dirname(topicPath), topic.id);
  fs.mkdirSync(dir, { recursive: true });
  for (const [name, body] of Object.entries(files)) fs.writeFileSync(path.join(dir, name), body);
  return { id: topic.id, dir, files: Object.keys(files) };
}

// Canonical bundle order: identity, each data slice, then register LAST. drill precedes bank
// (bank aliases the drill cards). Only slices emit actually produced are included, so a topic
// that omits an optional pane still yields a valid bundle.
const BUNDLE_SLICES = ['identity', 'walk', 'drill', 'wb', 'sys', 'trade', 'model', 'num', 'rf', 'open', 'bank', 'register'];

// All compiled output (per-topic slices + their include bundles) lives under topics/_generated/,
// so ONE .gitignore line covers it and it never sits beside the hand-authored topics (which are
// committed source). The registry partial stays at topics/_generated-registry.js -- app.js includes
// it by that name -- and only the include targets it lists move under _generated/. This is what
// makes adding a markdown topic require zero manual .gitignore edits.
const GEN = '_generated';

// Generate topics/_generated/<id>.js -- the include manifest that pulls a topic's slices in order.
function writeBundle(topicsDir, id) {
  const dir = path.join(topicsDir, GEN, id);
  const lines = ['/* GENERATED by compileTopicsPlugin from topics-md/' + id + ' -- do not edit. */'];
  for (const s of BUNDLE_SLICES) {
    if (fs.existsSync(path.join(dir, s + '.js'))) lines.push('<!--@build:include topics/' + GEN + '/' + id + '/' + s + '.js-->');
  }
  fs.writeFileSync(path.join(topicsDir, GEN, id + '.js'), lines.join('\n') + '\n');
}

// Generate the single registration partial app.js includes: every markdown topic's bundle, in
// index order. Written even when empty so the app.js include always resolves.
function writeRegistry(registryPath, topics) {
  const lines = ['/* GENERATED by compileTopicsPlugin -- markdown topics in index order. Do not edit. */'];
  for (const t of topics) lines.push('<!--@build:include topics/' + GEN + '/' + t.id + '.js-->');
  fs.writeFileSync(registryPath, lines.join('\n') + '\n');
}

export function compileTopicsPlugin({ srcDir, topicsDir, registryName = '_generated-registry.js' }) {
  return {
    name: 'ddr-compile-topics',
    async buildStart() {
      const files = fs.existsSync(srcDir)
        ? fs.readdirSync(srcDir).filter((x) => x.endsWith('.md') || x.endsWith('.topic'))
        : [];
      // Derive order + total from each source's own frontmatter index -- nothing hardcoded.
      const topics = files.map((f) => {
        const id = path.basename(f).replace(/\.(md|topic)$/, '');
        const { data: fm } = matter(fs.readFileSync(path.join(srcDir, f), 'utf8'));
        return { id, file: f, index: fm.index ?? 0 };
      }).sort((a, b) => a.index - b.index);
      const total = topics.length || 1;
      for (const t of topics) {
        await compileTopic(path.join(srcDir, t.file), {
          index: t.index || 1, total, outDir: path.join(topicsDir, GEN, t.id),
        });
        writeBundle(topicsDir, t.id);
      }
      writeRegistry(path.join(topicsDir, registryName), topics);
    },
    async buildEnd() { await closeMermaid(); await closeShiki(); },
  };
}
