/* ============ topics/authz/bank.js -- topic 3 cross-pane BANK ============
   The mock-run / mixed-fire / frame bank for topic 3. mockBeats + curveballs +
   frames are authz-specific; cards/speak alias the LOCAL AUTHZ_CARDS / AUTHZ_SPEAK
   (defined in drill.js, loaded before this in the bundle). publishBanks() seeds the
   registry-owned globals from this object on switch. Offline-safe; 7-bit ASCII. */
var TOPIC_AUTHZ_BANK = (function () {
  var mockBeats=[
   { tag:"FRAME", cue:"&ldquo;Design multi-tenant authorization &mdash; start wherever you like.&rdquo;",
     task:"Frame the scope in one line, then give your one-sentence version.",
     model:"<b>Frame:</b> multiple companies share the platform, and no tenant may ever see another&rsquo;s data; authorization is what enforces that boundary on every request. <b>One-liner:</b> the tenant comes from a verified, signed claim, the scope is a predicate the data layer injects into every query, it&rsquo;s deny-by-default, and a cross-tenant read returns 404 not 403.",
     int:{q:"Why isn&rsquo;t authentication enough &mdash; if I know who the user is, don&rsquo;t I know their tenant?",a:"Authentication proves <b>who</b> you are; authorization decides <b>what</b> you can touch &mdash; two different questions. Knowing a user is Alice from tenant A doesn&rsquo;t stop the <i>code</i> from fetching tenant B&rsquo;s order by id. The identity is the input; the enforcement &mdash; scoping every query, checking ownership on every object &mdash; is the work. Conflating them is how you get authenticated users reading each other&rsquo;s data."},int2:{q:"So where does the tenant actually come from &mdash; can&rsquo;t the client just tell me?",a:"Never from the client &mdash; that&rsquo;s the confused-deputy attack. The tenant comes from a <b>signed claim in the verified token</b>: the identity provider put it there, and forging it breaks the signature, so it&rsquo;s trustworthy. A header or body the client controls is not &mdash; an authenticated user of A just sends <code>tenant=B</code> and reads B. The whole model rests on deriving scope from verified identity, not accepting it from the request."} },
   { tag:"STRUCTURE", cue:"&ldquo;Walk me through it.&rdquo;",
     task:"Talk the whole flow, request to audit &mdash; no code, just the spine.",
     model:"Request arrives with a token &rarr; the <b>authorizer verifies the signature and extracts the tenant claim</b> &rarr; store it in <b>per-request context</b> &rarr; the shared data layer <b>injects <code>WHERE tenant_id = ctx.tenant</code></b> into every query, <b>deny-by-default</b> if there&rsquo;s no context &rarr; a fetch-by-id also gets an <b>object-level ownership check</b>, returning <b>404 not 403</b> across tenants &rarr; the <b>database backstops</b> it with RLS or LeadingKeys &rarr; every access is <b>audited</b> and id-scanning is flagged.",
     int:{q:"A developer three services deep needs the tenant. Do you thread it through every function call?",a:"No &mdash; that&rsquo;s brittle and easy to drop. The tenant lives in <b>per-request context</b> (AsyncLocalStorage, the Node equivalent of thread-local): middleware sets it once, and any code in that request &mdash; a repository three layers down &mdash; reads it without it being passed. It propagates through async calls automatically, so the data layer can always reach it, and there&rsquo;s no per-call plumbing to forget."} },
   { tag:"SCALE", cue:"&ldquo;One tenant is 90% of your traffic and the shared database is pegged. What breaks first?&rdquo;",
     task:"Name the first ceiling, then the fix &mdash; don&rsquo;t hand-wave &lsquo;it scales.&rsquo;",
     model:"The first thing to break is the <b>shared database</b> &mdash; the whale&rsquo;s load starves everyone else&rsquo;s queries (the noisy neighbor). Fixes, in order: <b>per-tenant rate limits and query timeouts</b> so one tenant can&rsquo;t consume the pool; <b>fair queuing</b> so work is scheduled proportionally; and for a true whale, <b>silo it</b> onto its own database. Underneath, <b>tenant_id must lead every index</b> so the scoped query is a seek, not a scan &mdash; or the whale&rsquo;s query alone scans the table.",
     int:{q:"Rate limits protect the API. Why isn&rsquo;t that enough for the database?",a:"Because a request that passes the rate limit can still issue an <b>expensive query</b> &mdash; one tenant running heavy scans exhausts connections and I/O the others need, even at a modest request rate. So you protect the database directly: <b>per-tenant connection caps</b> so one tenant can&rsquo;t drain the pool, <b>statement timeouts</b> per tier so a runaway query is killed, and <b>workload separation</b> routing analytics off the interactive path. The database is the scarcest shared resource, so it needs its own fairness controls, not just the API&rsquo;s."},int2:{q:"When do you stop tuning the pool and just silo the whale?",a:"When the whale&rsquo;s <b>normal</b> load, not a spike, is a meaningful fraction of the shared capacity &mdash; at that point per-tenant limits just throttle a legitimate customer, and you&rsquo;re optimizing a shared resource for a tenant that no longer fits in it. Siloing gives that tenant dedicated capacity, its own backup/restore, and removes it as a noisy neighbor for everyone else. The data layer already resolves tenant&rarr;datasource, so it&rsquo;s a routing change, not a rewrite. The tell is distinguishing &lsquo;bursty tenant&rsquo; (tune) from &lsquo;outgrew the pool&rsquo; (silo)."} },
   { tag:"FAILURE", cue:"&ldquo;A customer reports seeing another company&rsquo;s data. Now what?&rdquo;",
     task:"Walk the incident &mdash; contain, diagnose, close the class.",
     model:"<b>Contain, diagnose, prove.</b> First, scope the blast radius from <b>audit logs</b> &mdash; who saw what across which tenants &mdash; and disable the offending path if it&rsquo;s active. Diagnose: it&rsquo;s almost always a <b>query that escaped the scoped layer</b> &mdash; a raw query without the filter, or a <code>getById</code> that checked the primary key but not ownership. Fix the instance, then close the <b>class</b>: route it through the shared layer, add the object check, <code>FORCE</code> RLS so the database would&rsquo;ve caught it. Lock it with a <b>regression test that injects the foreign id</b>.",
     int:{q:"The logs show the query returned another tenant&rsquo;s rows but the code &lsquo;looks right.&rsquo; Where do you look?",a:"Three usual suspects. One: a <b>raw query</b> that bypassed the ORM and its injected scope. Two: a path that <b>lost the tenant context</b> &mdash; a background job, a queue consumer, an async boundary where context didn&rsquo;t propagate &mdash; so deny-by-default should have thrown but a fallback returned everything. Three: a <code>getById</code> that scoped the <i>list</i> query correctly but fetched the single object by primary key and forgot the ownership assertion. The audit log&rsquo;s query and code path tell you which; each has a different fix, which is why you diagnose before patching."},int2:{q:"How do you reassure the affected customers &mdash; and the ones who weren&rsquo;t affected?",a:"With the <b>audit trail</b>: because every access is logged per tenant, you can state <i>precisely</i> which records were exposed, to whom, and for how long &mdash; and prove which tenants were <i>not</i> touched. That specificity is the difference between &lsquo;we had a breach, scope unknown&rsquo; and &lsquo;these three records were visible to one other tenant for six minutes, here&rsquo;s the fix.&rsquo; The audit log isn&rsquo;t just detection; it&rsquo;s what lets you bound the incident honestly, which is exactly what regulators and customers demand."} },
   { tag:"CURVEBALL", theme:"Confused deputy", cue:"&ldquo;An authenticated user of tenant A changes the id in the URL to one belonging to tenant B and gets the record back. Your auth is &lsquo;working.&rsquo; Stop it.&rdquo;",
     task:"Reframe the premise out loud, then give the real mechanism.",
     model:"The premise to say aloud: authentication <b>is</b> working &mdash; the user is who they say. What failed is <b>object-level authorization</b>: the code fetched by id and never checked the object belongs to the caller&rsquo;s tenant. This is <b>BOLA / IDOR</b>, OWASP API #1. The fix: on every fetch-by-id, assert <code>resource.tenantId === ctx.tenant</code> (and ownership) server-side, and return <b>404 not 403</b> so you don&rsquo;t confirm B&rsquo;s record exists. The id is a <i>request</i>, never an authorization.",
     int:{q:"You added the ownership check to that endpoint. Why isn&rsquo;t that the end of it?",a:"Because BOLA is a <b>class</b>, not one endpoint &mdash; the same gap exists on every route that fetches by a client-supplied id. Patching one is whack-a-mole. The durable fix is <b>structural</b>: a shared authorize-resource helper that <i>every</i> by-id handler goes through, or the tenant predicate applied even to single-object fetches, plus a <b>test that injects a foreign id across every read path</b>. You close the class by making the check unavoidable, not by remembering it endpoint-by-endpoint &mdash; the same &lsquo;make the mistake unwritable&rsquo; principle as the tenant predicate."} },
   { tag:"CLOSE", cue:"&ldquo;Sum it up &mdash; and what would you watch in prod?&rdquo;",
     task:"Two-sentence close, then the one thing you&rsquo;d alarm on.",
     model:"It&rsquo;s an access boundary: identity comes from a verified claim, the tenant scope is a predicate injected into every query, it&rsquo;s deny-by-default, singleton fetches get an ownership check that returns 404 not 403, and the database backstops it. In prod I&rsquo;d watch for the <b>shape of an IDOR attack</b> &mdash; a user hitting many distinct object ids, or a spike of 404s from one account &mdash; because that&rsquo;s the earliest signal someone is probing the boundary, and every cross-tenant attempt is already in the audit log.",
     int:{q:"You&rsquo;ve got a week, not a month. Cut one thing you described to ship &mdash; what goes?",a:"The <b>sophistication</b> goes, never the boundary. I&rsquo;d ship <b>pooled</b> (skip silos and per-tenant keys), <b>RBAC only</b> (no ABAC or policy engine), and <b>no authz caching</b> (check every request) &mdash; all addable later without a rewrite because the data layer already resolves tenant&rarr;datasource. What I would <b>not</b> cut is the <b>verified-claim identity, the injected tenant predicate, deny-by-default, and the object-level check</b> &mdash; those are the contract, and a leaked-tenant MVP is an incident, not an MVP. And I&rsquo;d keep <code>FORCE</code> RLS on Postgres because it&rsquo;s nearly free insurance. Knowing which parts are the boundary and which are the hardening is the answer."} }
  ];
  var mockCurveIdx=0; for(var _ci=0;_ci<mockBeats.length;_ci++){ if(mockBeats[_ci].tag==="CURVEBALL") mockCurveIdx=_ci; }
  var curveballs=[ mockBeats[mockCurveIdx],
    { tag:"CURVEBALL", theme:"Stale token", cue:"&ldquo;You revoke an admin&rsquo;s access. Ten minutes later their token still works and they delete a tenant&rsquo;s data. How?&rdquo;",
      task:"Name the stateless-token trade-off, then the mitigations.",
      model:"The token is a <b>self-contained snapshot</b> &mdash; it carries the roles it was minted with and verifies <b>offline</b>, so it stays valid until it <b>expires</b>, regardless of a server-side revocation. That&rsquo;s the cost of stateless auth. Mitigations: <b>short lifetimes</b> so stale claims self-heal in minutes; <b>revocable refresh tokens</b> so the next refresh fails; a <b>denylist</b> of revoked token ids checked on sensitive operations; and for truly high-privilege actions, a <b>live check</b> against current state rather than trusting the token&rsquo;s cached role.",
      int:{q:"Why not just check the database on every request and drop stateless tokens entirely?",a:"Because that trades the whole benefit &mdash; a stateless token means <b>no lookup on the hot path</b>, which is what lets authorization scale. Checking live state on <i>every</i> request puts a read in front of every call and reintroduces the bottleneck tokens exist to avoid. The pragmatic answer is <b>tiered</b>: trust the short-lived token for ordinary reads, and pay for a live check only on the dangerous operations (delete, billing, privilege change). You buy immediate revocation exactly where it matters and keep statelessness everywhere else."} },
    { tag:"CURVEBALL", theme:"Pool leakage", cue:"&ldquo;Your RLS-protected app intermittently serves one tenant another&rsquo;s data under load. RLS is enabled and has a policy. What&rsquo;s happening?&rdquo;",
      task:"Find the leak that only appears under connection reuse.",
      model:"Almost certainly <b>SET vs SET LOCAL</b> on a pooled connection. A plain <code>SET app.tenant</code> <b>persists on that physical connection</b> &mdash; and under load, when the pool hands the same connection to the <i>next</i> request (a different tenant), that request inherits the previous tenant&rsquo;s context until it overwrites it, or reads with the stale one. The fix is <code>SET LOCAL</code>, which is <b>transaction-scoped</b> and reset on commit, so context can never bleed across a reused connection. It only shows &lsquo;under load&rsquo; because that&rsquo;s when connections get reused mid-flight.",
      int:{q:"Would a connection-per-tenant model have avoided this?",a:"Yes &mdash; a dedicated connection per tenant physically can&rsquo;t leak context, because it&rsquo;s never shared. But it doesn&rsquo;t <b>scale</b>: thousands of tenants means thousands of connections, which exhausts the database&rsquo;s connection limit. So connection-per-tenant is viable only for a handful of large tenants. For a pooled system &mdash; the norm at scale &mdash; the answer isn&rsquo;t to stop pooling, it&rsquo;s to set the context <b>transaction-scoped</b> so pooling is safe. The bug is the <i>session</i>-scoped SET, not pooling itself."} },
    { tag:"CURVEBALL", theme:"Escaped query", cue:"&ldquo;Your predicate-injection is airtight in the ORM. A new analytics service reads the same database with raw SQL and leaks across tenants. Whose fault, and how do you prevent the class?&rdquo;",
      task:"Name why the app-layer guarantee didn&rsquo;t transfer, then the durable fix.",
      model:"The app-layer predicate only protects <b>code that goes through the layer</b> &mdash; a service reading raw SQL, or a brand-new datastore, was never covered. The guarantee is real but <b>local to the enforcement path</b>. The durable fix is to push the boundary <b>below the app</b> where every reader hits it: <b>RLS <code>FORCE</code>d</b> so even raw SQL is filtered by the engine, or a policy at the datastore. And organizationally, a rule that <b>no service touches tenant data except through the shared layer or an RLS-enforced connection</b> &mdash; enforced in review, not hoped for.",
      int:{q:"The analytics service legitimately needs cross-tenant aggregates. How do you allow that safely?",a:"Through a <b>separate, explicit, audited path</b> &mdash; never by weakening the default. Analytics gets a <b>purpose-built accessor</b> allowed to aggregate across tenants but returning <i>only aggregates</i>, not row-level data, and logging its access; or it reads from a <b>pre-aggregated, de-identified</b> dataset built for reporting. Cross-tenant is a deliberate capability granted to one service with its own authorization, not a hole in the row-level boundary. The principle holds: crossing tenants is always explicit and audited, whether it&rsquo;s a support human or an analytics job."} },
    { tag:"CURVEBALL", theme:"Privilege abuse", cue:"&ldquo;Your break-glass support access is audited. A support engineer uses it to browse a high-profile customer&rsquo;s data out of curiosity. Audit caught it &mdash; after the fact. Is that good enough?&rdquo;",
      task:"Distinguish detective from preventive controls, then strengthen.",
      model:"Audit is a <b>detective</b> control &mdash; it caught the abuse, which is necessary but not sufficient. To <b>prevent</b> it, add friction and least privilege up front: break-glass should require a <b>stated reason tied to a ticket</b>, ideally a <b>second approver</b> for sensitive accounts, be <b>time-boxed</b> so access auto-expires, and <b>notify the customer</b> when their data is accessed. You can&rsquo;t make curiosity impossible, but you can make casual access <b>expensive, visible, and accountable</b> &mdash; so the audit trail is the backstop, not the only line.",
      int:{q:"Isn&rsquo;t requiring approval for every support access going to slow down legitimate work?",a:"Which is why you <b>tier it by sensitivity</b>, not blanket it. Routine support on an ordinary account might need only a logged reason; access to a <b>high-profile or flagged</b> account, or to especially sensitive fields, requires the second approver and the notification. Most access is low-risk and stays fast; the friction lands exactly where the blast radius is highest. Blanket approval trains people to rubber-stamp; targeted friction preserves both speed and control. The goal is least privilege that&rsquo;s <i>usable</i>, so people don&rsquo;t route around it."} },
    { tag:"CURVEBALL", theme:"Erasure", cue:"&ldquo;A tenant exercises right-to-erasure. You DELETE their rows and confirm zero remain. Legal asks you to prove it&rsquo;s <i>gone</i>, including backups. Now what?&rdquo;",
      task:"Name every copy the data lives in, then the mechanism for the immutable ones.",
      model:"The primary DELETE is the easy 20%. The data also lives in <b>backups, read replicas, caches, search indexes, logs, and warehouse copies</b> &mdash; erasure isn&rsquo;t done until each is addressed. Replicas and caches clear on their own or on invalidation; indexes need a targeted delete; logs age out on retention. <b>Backups are the hard one</b>: you usually can&rsquo;t surgically edit them, so you rely on <b>retention expiry</b> plus <b>crypto-shredding</b> &mdash; if the tenant&rsquo;s data is encrypted with a <b>per-tenant key</b>, destroying that key renders every copy, backups included, permanently unreadable.",
      int:{q:"So per-tenant encryption keys aren&rsquo;t just an isolation feature?",a:"Right &mdash; they&rsquo;re the <b>practical mechanism for erasure across copies you can&rsquo;t selectively edit</b>. Deleting rows handles the live database; destroying the key handles everything else at once, because ciphertext without the key is noise. It&rsquo;s why per-tenant keys show up as both an isolation control (a compromise blasts one tenant) and a compliance control (crypto-shred one tenant on request). The senior move is connecting &lsquo;right-to-erasure&rsquo; to &lsquo;per-tenant key&rsquo; instead of promising to scrub immutable backups you can&rsquo;t actually rewrite."} },
    { tag:"CURVEBALL", theme:"Cache invalidation", cue:"&ldquo;You cache authorization decisions for performance. A user is removed from a project but keeps editing it for five minutes. Fix it without killing the cache.&rdquo;",
      task:"Frame it as invalidation, then tier by blast radius.",
      model:"This is a <b>cache-invalidation</b> problem: a stale &lsquo;allow&rsquo; survived a permission change. You don&rsquo;t have to drop the cache &mdash; you <b>invalidate on the event</b>: when a role or membership changes, publish an event that <b>busts the cached decision</b> for that user (or user+resource), so the next request re-evaluates. For decisions you can&rsquo;t event-invalidate cheaply, keep a <b>short TTL</b> so staleness is bounded to seconds. And <b>tier by blast radius</b> &mdash; cache freely for low-risk reads, but for high-privilege actions check live rather than trust a cached allow.",
      int:{q:"Event-based invalidation adds a whole pub/sub dependency. When is a short TTL just good enough?",a:"When the <b>staleness window is acceptable for the action&rsquo;s risk</b>. For most reads and ordinary edits, a 30&#8209;to&#8209;60&#8209;second TTL means a revoked permission lingers under a minute &mdash; usually fine, and far simpler than wiring events for every permission change. You reserve immediate (event-based) invalidation for cases where even a minute is unacceptable: a fired employee, a revoked admin, a security incident. Match the invalidation strategy to the blast radius &mdash; TTL for the many, events for the dangerous few &mdash; rather than paying for immediate invalidation everywhere."} },
    { tag:"CURVEBALL", theme:"Over-broad grant", cue:"&ldquo;A partner integration you gave API access to gets breached. The attacker now has whatever you granted the partner. How bad is it, and what determined that?&rdquo;",
      task:"Tie the blast radius to how the grant was scoped, then the least-privilege fix.",
      model:"The blast radius is <b>exactly what you granted the partner &mdash; no more, no less</b>, which is why <i>how</i> you granted it decides how bad this is. A <b>coarse, long-lived API key</b> with broad access means the attacker has broad access to that tenant until you notice. A <b>scoped OAuth grant</b> &mdash; specific scopes, one tenant, an expiry, independently revocable &mdash; confines the attacker to those scopes, and you <b>revoke that grant</b> and cut them off without touching anyone else. Least privilege isn&rsquo;t bureaucracy; it&rsquo;s the variable that sets the blast radius of a partner breach.",
      int:{q:"The partner says they need broad access &lsquo;to be safe&rsquo; / for future features. How do you push back?",a:"Grant for <b>what they use now</b>, not what they might use later &mdash; you can always add a scope when a feature ships, but you can&rsquo;t un-leak data an over-broad grant exposed. &lsquo;Broad to be safe&rsquo; is backwards: broad access is the <i>opposite</i> of safe, because it maximizes the blast radius when &mdash; not if &mdash; the partner is compromised. I&rsquo;d give the minimum scopes for their current integration, make expanding it a lightweight request, and keep the grant expiring and revocable. Least privilege is a property you defend at grant time, because it&rsquo;s the only cheap moment to get it right."} }
  ];
  var mockFrameIdx=0; for(var _fi=0;_fi<mockBeats.length;_fi++){ if(mockBeats[_fi].tag==="FRAME") mockFrameIdx=_fi; }
  var frames=[ mockBeats[mockFrameIdx].cue,
    "&ldquo;Each customer&rsquo;s data must be invisible to every other customer. Design the authorization layer that guarantees it.&rdquo;",
    "&ldquo;Design multi-tenant access control for a SaaS platform &mdash; how do you keep tenants isolated in a shared database?&rdquo;",
    "&ldquo;A user makes a request. Walk me through every check between the token and the row that decides what they&rsquo;re allowed to see.&rdquo;"
  ];
  return { cards: AUTHZ_CARDS, speak: AUTHZ_SPEAK, curveballs: curveballs, mockBeats: mockBeats, frames: frames };
})();
