/* topics/authz/walk.js -- topic 3 WALKTHROUGH data. steps[] is the guided trace of
   the authorization flow (request -> authorizer verifies token -> tenant context ->
   data layer injects predicate -> deny-by-default -> object-level check -> 404 not
   403 -> DB backstop -> audit); modelScript[] is the spoken model answer (plain
   beats, the interviewer .mq line, then the .mbeat.ans -- which MUST be LAST, the
   last-child CSS depends on it). Offline-safe; 7-bit ASCII (entities + \uXXXX). */
var TOPIC_AUTHZ_WALK = {
  steps: [
    { k:"Step 1 / 9", t:"The authorizer runs first",
      flow:'<span class="fb n">request + token</span><span class="arr">&rarr;</span><span class="fb p">authorizer</span><span class="arr">&rarr;</span><span class="fb t">tenant context</span><span class="arr">/</span><span class="fb r">401 no token</span>',
      ins:'Before any handler runs, an <b>authorizer</b> intercepts &mdash; a Lambda authorizer, or middleware. It&rsquo;s the single choke point where identity is established, so authorization can&rsquo;t be forgotten per route.',
      deep:'Running the check <b>before</b> business logic is the whole point: authentication and tenant resolution happen in <b>one place</b>, not scattered across handlers. A request with no token or an invalid one is rejected at the door with 401 &mdash; it never reaches code that could leak. Centralizing the check is what makes &ldquo;every endpoint is protected&rdquo; a structural guarantee, not a discipline.' },
    { k:"Step 2 / 9", t:"Verify the token, extract the claim",
      flow:'<span class="fb n">token</span><span class="arr">&rarr;</span><span class="fb p">verify signature (JWKS)</span><span class="arr">&rarr;</span><span class="fb t">trusted claims</span><span class="arr">&middot;</span><span class="fb a">tenant from signed claim</span>',
      ins:'The authorizer verifies the token&rsquo;s signature against the issuer&rsquo;s public key (JWKS), then reads the tenant from a <b>signed claim</b> &mdash; never from a header or body the client controls. The claim is trustworthy precisely because forging it would break the signature.',
      code:'<span class="k">const</span> claims = <span class="k">await</span> verifyJwt(token, JWKS);  <span class="c">// throws on bad signature</span>\n<span class="k">const</span> tenantId = claims[<span class="s">\'custom:tenant_id\'</span>];  <span class="c">// a SIGNED claim</span>\n<span class="k">if</span> (!tenantId) <span class="k">throw</span> <span class="k">new</span> AuthError(<span class="hl">401</span>, <span class="s">\'no tenant in token\'</span>);\n<span class="c">// NEVER: const tenantId = req.headers[\'x-tenant-id\']  &lt;- client-controlled</span>',
      cap:'The line that matters is what you <i>don&rsquo;t</i> do &mdash; read the tenant from a header. It&rsquo;s trusted only because it rode inside a signed token; take it from client input and the confused-deputy attack is open.' },
    { k:"Step 3 / 9", t:"Establish tenant context",
      flow:'<span class="fb t">tenant_id</span><span class="arr">&rarr;</span><span class="fb p">AsyncLocalStorage.run({tenant})</span><span class="arr">&rarr;</span><span class="fb a">propagates through the request</span>',
      ins:'The verified tenant goes into per-request context &mdash; <b>AsyncLocalStorage</b> in Node, the equivalent of thread-local. It propagates through every async call in the request without being passed as a parameter, so the data layer can read it anywhere.',
      deep:'This is the plumbing that makes &ldquo;inject the scope everywhere&rdquo; practical. Middleware calls <code>tenantStore.run({tenant}, next)</code> once; any code downstream &mdash; a repository three calls deep &mdash; reads <code>getStore().tenant</code>. Each request gets its own isolated store, so there&rsquo;s no cross-contamination under concurrency. It&rsquo;s the same mechanism OpenTelemetry uses to propagate a trace context.' },
    { k:"Step 4 / 9", t:"The data layer injects the predicate",
      flow:'<span class="fb n">query</span><span class="arr">&rarr;</span><span class="fb p">layer reads context</span><span class="arr">&rarr;</span><span class="fb t">WHERE tenant_id = ctx.tenant</span><span class="arr">&middot;</span><span class="fb a">scoped result</span>',
      ins:'Here&rsquo;s the reframe: authorization isn&rsquo;t a check the handler performs, it&rsquo;s a <b>predicate the shared data layer injects into every query</b>. A developer writes <code>findOrders()</code>; the layer silently adds the tenant filter.',
      code:'<span class="c">// ORM extension / global scope -- runs on every read and write</span>\nprisma.<span class="hl">$extends</span>({ query: { $allModels: {\n  findMany({ args, query }) {\n    <span class="k">const</span> { tenant } = tenantStore.getStore();      <span class="c">// trusted context</span>\n    args.where = { ...args.where, tenantId: tenant };  <span class="c">// injected scope</span>\n    <span class="k">return</span> query(args);\n} } } });',
      cap:'The developer literally <i>cannot</i> forget the tenant filter, because they never write it. Moving the scope out of business logic and into the data layer turns isolation from a per-query discipline into a property of the system.' },
    { k:"Step 5 / 9", t:"Deny-by-default",
      flow:'<span class="fb r">no context</span><span class="arr">&rarr;</span><span class="fb r">throw</span><span class="arr">&middot;</span><span class="fb a">never runs unscoped</span><span class="arr">/</span><span class="fb t">has context &rarr; scoped</span>',
      ins:'The accessor <b>throws</b> if there&rsquo;s no tenant context &mdash; it never falls back to an unscoped query. A bug that loses the context becomes a loud failure, not a silent full-table leak.',
      code:'<span class="k">const</span> store = tenantStore.getStore();\n<span class="k">if</span> (!store?.tenant)\n  <span class="k">throw</span> <span class="k">new</span> Error(<span class="s">\'no tenant context -- called outside request scope\'</span>);\n<span class="c">// only reached WITH a tenant; an unscoped query is unreachable</span>',
      cap:'Deny-by-default is the difference between a missing filter that leaks everything and one that crashes the request. You engineer it so the unsafe path <i>doesn&rsquo;t exist</i>, rather than trusting every caller to remember.' },
    { k:"Step 6 / 9", t:"Object-level authorization",
      flow:'<span class="fb n">fetch by id</span><span class="arr">&rarr;</span><span class="fb t">resource.tenant === ctx.tenant?</span><span class="arr">&rarr;</span><span class="fb a">ownership?</span><span class="arr">/</span><span class="fb r">deny</span>',
      ins:'Even with the predicate, a direct <b>fetch-by-id</b> gets a second check: does this resource belong to the caller&rsquo;s tenant, and does the caller own it (or hold the role)? That&rsquo;s the object-level authorization the predicate alone doesn&rsquo;t cover for singleton lookups.',
      deep:'The predicate scopes list queries; a <code>getById(params.id)</code> still needs an explicit <code>resource.tenantId === ctx.tenant</code> assertion, because the id came from the client. This is exactly <b>BOLA</b> &mdash; Broken Object-Level Authorization, OWASP API&nbsp;#1 &mdash; the confused deputy where an authenticated user of tenant A requests tenant B&rsquo;s object by id. The rule: the id is a <i>request</i>, not an authorization; verify ownership server-side every time.' },
    { k:"Step 7 / 9", t:"404, not 403, on cross-tenant",
      flow:'<span class="fb r">cross-tenant access</span><span class="arr">&rarr;</span><span class="fb p">log the attempt</span><span class="arr">&rarr;</span><span class="fb t">respond 404</span><span class="arr">&middot;</span><span class="fb a">existence hidden</span>',
      ins:'When the object-level check fails across tenants, you return <b>404, not 403</b>. A 403 &ldquo;forbidden&rdquo; confirms the object exists; a 404 reveals nothing. The distinction is a real information-leak control.',
      deep:'A 403 tells an attacker &ldquo;this id is real, you just can&rsquo;t see it&rdquo; &mdash; which itself enumerates valid ids across tenants. A 404 makes a cross-tenant object indistinguishable from a nonexistent one. You <b>log the attempt</b> internally (it&rsquo;s a signal), but externally the response is the same as a miss. Same idea as &ldquo;invalid username or password&rdquo; instead of &ldquo;no such user.&rdquo;' },
    { k:"Step 8 / 9", t:"The database backstop",
      flow:'<span class="fb t">app-layer scope</span><span class="arr">+</span><span class="fb p">DB enforcement</span><span class="arr">&rarr;</span><span class="fb a">RLS FORCE (PG) / LeadingKeys (DDB)</span>',
      ins:'The app layer is the primary enforcement, but defense-in-depth pushes a copy into the database: Postgres <b>Row-Level Security</b>, or DynamoDB&rsquo;s <b>dynamodb:LeadingKeys</b> IAM condition. Even if application code has a bug, the database refuses cross-tenant rows.',
      code:'<span class="c">-- Postgres RLS: enforced by the engine, even on a forgotten WHERE</span>\n<span class="k">ALTER TABLE</span> orders <span class="k">ENABLE ROW LEVEL SECURITY</span>;\n<span class="k">ALTER TABLE</span> orders <span class="hl">FORCE ROW LEVEL SECURITY</span>;  <span class="c">-- owner too</span>\n<span class="k">CREATE POLICY</span> tenant_iso <span class="k">ON</span> orders\n  <span class="k">USING</span> (tenant_id = current_setting(<span class="s">\'app.tenant\'</span>)::uuid);\n<span class="c">-- per txn: SET LOCAL app.tenant = \'...\';  (not SET -- pool leakage)</span>',
      cap:'RLS only helps if you <b>FORCE</b> it (it skips owners by default), connect as a non-owner, and <code>SET LOCAL</code> per transaction so context doesn&rsquo;t leak across a pooled connection. On DynamoDB the parallel is <b>LeadingKeys</b> &mdash; but <code>Scan</code> bypasses it, so scan less.' },
    { k:"Step 9 / 9", t:"Audit + anomaly detection",
      flow:'<span class="fb n">every access</span><span class="arr">&rarr;</span><span class="fb p">structured log</span><span class="arr">&rarr;</span><span class="fb t">cross-tenant attempt flagged</span><span class="arr">&middot;</span><span class="fb a">id-scan detected</span>',
      ins:'Every cross-tenant attempt is <b>logged</b> (a detective control and compliance evidence), and a user hitting many different object ids rapidly is <b>flagged</b> &mdash; that pattern is automated IDOR scanning.',
      deep:'Authorization isn&rsquo;t just prevention; it&rsquo;s <b>detection</b>. You log who accessed what, segregate audit trails per tenant, and alarm on the signatures of an attack: a spike in 404s from one user, access to ids outside the caller&rsquo;s normal range, a burst of distinct-object lookups. The audit trail is what turns &ldquo;we think isolation held&rdquo; into &ldquo;here&rsquo;s the record&rdquo; &mdash; and it&rsquo;s the artifact regulators ask for.' }
  ],
  modelScript: [
    { ml: 'Frame it before diving', t: '"Before I design it &mdash; I&rsquo;ll assume identity comes from a verified token with a tenant claim, we&rsquo;re pooled into shared tables, and I own the data-access layer. Stop me if any of that&rsquo;s off."' },
    { ml: 'Headline in one breath', t: '"At a high level: authorization isn&rsquo;t a gate I check per handler &mdash; it&rsquo;s a <b>predicate the shared data layer injects into every query</b>. Identity comes from the <b>verified token</b>, the tenant scope is added automatically, and it&rsquo;s <b>deny-by-default</b> so a forgotten filter crashes rather than leaks."' },
    { ml: 'Walk the path', t: '"Concretely &mdash; the authorizer verifies the token and pulls the tenant from a <b>signed claim</b>, never a header. I put it in per-request context, and the repository layer injects <code>WHERE tenant_id = ctx.tenant</code> on every read and write. A developer writes <code>findOrders()</code> and the scope is already there &mdash; they can&rsquo;t forget it because they never write it."' },
    { ml: 'Name the risk yourself', t: '"The attack I&rsquo;d flag without being asked is the <b>confused deputy</b> &mdash; an authenticated user of tenant A asking for tenant B&rsquo;s object by id. The predicate covers list queries; a fetch-by-id still needs an explicit <b>ownership check</b>, and a cross-tenant miss returns <b>404, not 403</b> so I don&rsquo;t leak that the object exists. That&rsquo;s BOLA, OWASP&rsquo;s number one."' },
    { ml: 'Name the trade-off line', t: '"The isolation model isn&rsquo;t my preference &mdash; it&rsquo;s set by the tenant. I <b>pool</b> the long tail for cost and one-migration agility, and <b>silo</b> the biggest tenants and anyone with a hard compliance line. I&rsquo;d say that before they ask &lsquo;why not a database per tenant.&rsquo;"' },
    { ml: 'Be honest about the ceiling', t: '"This holds as long as the tenant scope is on the <b>leading edge of the index</b> &mdash; <code>WHERE tenant_id = ?</code> has to hit a contiguous range, or a big tenant&rsquo;s query scans the whole table. And the real operational hard part isn&rsquo;t the query &mdash; it&rsquo;s the <b>noisy neighbor</b>: one tenant&rsquo;s load starving the rest."' },
    { mq: 'Interviewer: "What stops a developer from writing a raw query that skips your layer?"' },
    { ml: 'Absorb the follow-up', t: '"Defense in depth. The primary answer is that raw queries don&rsquo;t reach the database directly &mdash; the data layer is the only path, and it&rsquo;s <b>deny-by-default</b>. But because code has bugs, I push a copy of the rule into the database: <b>Row-Level Security</b> in Postgres &mdash; <code>FORCE</code>d, so it applies even to the table owner &mdash; or <b>LeadingKeys</b> on DynamoDB, so a credential can only touch its own tenant&rsquo;s partition. Even a raw query that bypasses my layer hits the database&rsquo;s own refusal. The app layer prevents the mistake; the database catches the one that slips through &mdash; and I&rsquo;d name which backstop the datastore supports rather than pretend one fits all."', ans: true }
  ]
};
